### ISSUE TITLE
Problem with Mac OS 10.11 El Capitan

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#103]
Although matlab works on Mac OS 10.11 El Capitan on startup we get 
```
initialize MTEX 4.1.3  ..../bin/bash: line 1:   730 Trace/BPT trap: 5       /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf564.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf564.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log: Trace/breakpoint trap
********************************************************************************
  MTEX binary check failed!
 
  The original error message was:
  Error using call_extern (line 158)
Error running external program:

 /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf564.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log
 
  Check the following options:
  * Compile the binaries yourself.
  * Ask the maintainer for help!
********************************************************************************
/bin/bash: line 1:   733 Trace/BPT trap: 5       /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2fc /private/tmp/odf2fc646.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2fc /private/tmp/odf2fc646.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log: Trace/breakpoint trap
 done!
```
Some functions of MTEX still work, but as soon as plot pole figure that call odf2pf

you get an error message
```
/bin/bash: line 1:  1104 Trace/BPT trap: 5       /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf7399.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf7399.txt 2>> /private/tmp/output_DavidMacBookProlocal_davidmainprice.log: Trace/breakpoint trap
Error using call_extern (line 158)
Error running external program:

 /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf /private/tmp/odf2pf7399.txt 2>>
 /private/tmp/output_DavidMacBookProlocal_davidmainprice.log

Error in vector3d/kernelDensityEstimation (line 43)
kde = call_extern('odf2pf','EXTERN',gh,r,c,Al);

Error in vector3d/smooth (line 35)
    cdata = kernelDensityEstimation(v(:),S2G,'halfwidth',5*degree,varargin{:});

Error in vector3d/contourf (line 19)
h = v.smooth(data,'contours',10,'LineStyle','none',varargin{:});

Error in vector3d/plot (line 64)
    [varargout{1:nargout}] = v.contourf(varargin{:});
```
Has anyone found a fix for this problem ?

all the best David

**Comment by zmichels** [comment]
David,

I had this exact same problem trying to install the recent version, too. 

Scenario:
I had a folder sync'd with the github repo, and I couldn't install with a copy of those files (received identical errors to those you listed above). 

Work-around / Solution(?):
I tried instead downloading it through the MTEX github download page:
 http://mtex-toolbox.github.io/download.html

That install worked fine for me. I'm not savvy enough to understand why this is different. This may not be relevant for your install – I'm not sure how you did it.

best,
Z

**Comment by ralfHielscher** [comment]
Hi David, Hi zmichels,

first the simple answer. Only forking, syncing the github repo is not sufficient for a working installation as MTEX also relies on some binaries which are only included in the download. This binaries could be compiled from the repo but this requires extra work.

to David: according to you log file the reason for the error message is that the file 
```
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/libfftw3.3.dylib
```
was not found. Could you please check that this file exists and has the rights set to be executable.

Ralf

**Comment by DavidMainprice** [comment]
Dear Ralf,

Here are the permissions for /MatLab_Programs/mtex-4.1.3/c/bin/maci64/

-rwxr-xr-x@ 1 davidmainprice  staff    44924 30 sep 22:08 fc2odf
-rwxr-xr-x@ 1 davidmainprice  staff  3348076 30 sep 22:08 libfftw3.3.dylib
-rwxr-xr-x@ 1 davidmainprice  staff   471940 30 sep 22:08 libnfft3.1.dylib
-rwxr-xr-x@ 1 davidmainprice  staff    44924 30 sep 22:08 odf2fc
-rwxr-xr-x@ 1 davidmainprice  staff    45316 30 sep 22:08 odf2pf
-rwxr-xr-x@ 1 davidmainprice  staff    45316 30 sep 22:08 pdf2pf
-rwxr-xr-x@ 1 davidmainprice  staff    75164 30 sep 22:08 pf2odf

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

this error occurs after updating to a new OSX version?
Do you have a file
```
/opt/local/lib/libfftw3.3.dylib
```
If not could you try copying 
```
mtex-4.1.3/c/bin/maci64/libfftw3.3.dylib
```
to
```
/opt/local/lib/libfftw3.3.dylib
```

Ralf

**Comment by ralfHielscher** [comment]
Hi David,

This look quite complicated. I'm trying to find somebody with a Mac.
Maybe in the meanwhile you can give me the output of
```
$ otool -L /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf
```

Ralf.

**Comment by zmichels** [comment]
Ralf,

In case it helps...
I have a Mac that I recently updated (OS X and MTEX). My Matlab is 2014b, and all is working fine. Please let me know if there is anything I can try with my machine that will help you in troubleshooting David's issue.

Best,
Zach

**Comment by DavidMainprice** [comment]
Dear Ralf,

otool -L /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf:
	@loader_path/libnfft3.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@loader_path/libfftw3.3.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)

all the best David

**Comment by DavidMainprice** [comment]
Does it work with 2014b and MTEX 4.1.3 with not error message even for pole figure plots ?

all the best David

**Comment by ralfHielscher** [comment]
Hi Zach,

maybe you could also try
```
$ otool -L /some_path/mtex-4.1.3/c/bin/maci64/odf2pf
```
Thanks,
Ralf

**Comment by zmichels** [comment]
David and Ralf,

Yes, I am able to plot pole figures, and I am using 2014b and MTEX 4.1.3.
However, I realize now that I have not upgraded to OS X El Capitan. I have installed all recent updates, but I have not upgraded from Yosemite. 

I tried running the command mentioned above. I must be doing something wrong or I do not have that function installed because I get the errors:

Undefined function 'otool' for input arguments of type 'char'.
and
Undefined function or variable 'otool'.

best,
Zach

**Comment by DavidMainprice** [comment]
In terminal is would look like this after the $ and at the end odf2pf:

dhcp-143-51:bin davidmainprice$ otool -L /MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf
/MatLab_Programs/mtex-4.1.3/c/bin/maci64/odf2pf:
	@loader_path/libnfft3.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@loader_path/libfftw3.3.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)

all the best David

**Comment by zmichels** [comment]
Ah yes. That makes much more sense then. And as always, my ignorance know no bounds!

cheers,
Zach

here is output:

$ otool -L /Users/Z/Documents/MATLAB/MTEXmodules/mtex-4.1.3/c/bin/maci64/odf2pf
/Users/Z/Documents/MATLAB/MTEXmodules/mtex-4.1.3/c/bin/maci64/odf2pf:
	@loader_path/libnfft3.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@loader_path/libfftw3.3.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)



And proof of pole figures... in pink.
![screen shot 2015-10-05 at 4 27 27 am](https://cloud.githubusercontent.com/assets/8769619/10277109/6b8c9cd2-6b19-11e5-9b1f-c0dbe26655d9.png)

**Comment by DavidMainprice** [comment]
nice plot

all the best David
