### ISSUE TITLE
Small Edit in export_ctf - function

### ISSUE THREAD

**Issue by kootebruch** [mtex-toolbox/mtex#1047]
Dear developers,

I wanted to convert .ang-files to .ctf-files (from OIM Software to Channel 5 compatible files)

I used cleaned EBSD data from the OIM software in .ang format and tried to convert it with the export_ctf - function to .ctf format. When looking at the result file, the x-axis showed duplicate values and the map appeared square instead of its original size.

By debugging we found out that in line 204 the x-values are defined as:

`X = repmat(1:size(ebsdGrid,1),size(ebsdGrid,2),1);`

After changing the parameters to:

`X = repmat(1:size(ebsdGrid,2),size(ebsdGrid,1),1);`

the maps looked alike and the conversion was successful.

Also the orientation data were correctly assigned now correctly .

MTex 5.6.0

**Comment by ralfHielscher** [comment]
Is there a specific reason, why you use the outdated version 5.6? 
Are you able to check, whether the issue occurs in MTEX 5.7 as well?

Ralf.

**Comment by kootebruch** [comment]
> 
> 
> Is there a specific reason, why you use the outdated version 5.6?
> Are you able to check, whether the issue occurs in MTEX 5.7 as well?
> 
> Ralf.

Hi Ralf,

as far as I have checked, this error no longer occurs in the new version. Neither in the export_ctf nor in the ebsd.export function.

Greetings,
Mattis
