### ISSUE TITLE
'kernelDensityEstimation' is a very useful function

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#105]
The `kernelDensityEstimation` is a very useful function; A typical use would be

```
% define grid
r_plot = plotS2Grid;
% calculate kde for V vectors of the type vector3D
kde = kernelDensityEstimation(V,r_plot,'halfwidth',7.5*degree)
% find maximum density and corresponding vector
[max_density, max_index] = max(kde);
% and corresponding vector
Vmax = V(max_index);
```

It would be nice to have an antipodal option that works, currently it does not appear to work.

It would be great to have search function similar to [modes, values] = calcModes(odf,n) but calcModes(kde,n) to find the maxima in the distribution of kde.

all the best David

**Comment by zmichels** [comment]
Indeed! It is a great tool. I have sometimes tried to work around the antipodal issue by treating the combination of vectors and negated vectors... Essentially treating them as axial data... Then the returned maximum from the Kde can be negated, too, and you have that to deal with.
Also, I echo David's desire for something like calcModes for vectors.
Cheers,
Z
