### ISSUE TITLE
ODF/discreteSample from DirichletKernel errors

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#1065]
Hi Ralf,
here's a simple example
```
cs = crystalSymmetry('121')
psi = DirichletKernel(12)
odf = unimodalODF(orientation.rand(15,cs),'kernel',psi)
o = discreteSample(odf,1)
```
I tried adding a dummy value in https://github.com/mtex-toolbox/mtex/blob/ea94d454f2501ec95440acf0d8bc4d26887cce21/tools/kernelFunctions/DirichletKernel.m#L27 however, I guess that is not the right way to do it.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

these was first a bug. But it will not work anyway as you can not take a random sampling from a density function taking negative values.

**Comment by kilir** [comment]
Hi Ralf,
this of course makes totally sense! Switching to another kernel for sampling seems to work fine.
Cheers,
Rüdiger
