### ISSUE TITLE
Problem with Mac OS 10.11 El Capitan  and Solution

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#107]
Thanks to my colleague Benoit Ildefonse we have found a solution to running MTEX on Mac OS 10.11 El Capitan (see #103)

OS 10.11 El Capitan has new  “System Integrity Protection” (SIP) not present on 10.10

Some details can be found on MacWorld at
http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html

At present to run MTEX you have to disable SIP.

The method is as follows:

Follow these steps to disable SIP:

```
• Restart your Mac.
• Before OS X starts up, hold down Command-R and keep it held down until you see an Apple icon and a progress bar. Release. This boots you into Recovery this special mode to make repairs etc.
• From the Utilities menu top at the screen, select Terminal.
• At the prompt type exactly the following and then press Return: csrutil disable
• Terminal should display a message that SIP was disabled.
• From the (Apple) menu, select Restart.
```

I have done this on my Mac and it now works and there is not error message.

We hope there is way to use the MTEX with the need to disable SIP, this will depend on Apple.

all the best David

**Comment by creuzige** [comment]
My computer overlords have inflicted SIP on my computer as well.  Unfortunately, while I can disable it temporarily, it often gets re-enabled. 

Let me know if a better solution is found or what I can do to help find a long term solution for this.  

From the readings I've done to try and sort this out on my own, it seems that the DYLD_LIBRARY_PATH was commonly used to run external program, but is now disallowed.   I'm also trying to poke Mathworks to see if there are alternatives for running external code. I have to believe there are other options...

**Comment by creuzige** [comment]
I (with a lot of assistance from some other NIST colleagues), was able to sort out another solution that works with SIP enabled.  

It seems that the libfftw3.3.dylib and libnfft3.1.dylib files were trying to link to the /opt/local/lib folder and run the commands there.  Unfortunatlely, there were no similarly named dylib files in this directory.  

We made copies of the two .dylib files from the (mtex)/c/bin/maci64/ to /opt/local/lib/  

Mtex now works with SIP enabled.

**Comment by DavidMainprice** [comment]
Many thanks.  Now the problem has been identified maybe it would be better solution that names of files or their location in MTEX are changed ?

What do you think Ralf ?

all the best David

**Comment by creuzige** [comment]
I've also got a message back from Mathworks, they stated "that the dependency on DYLD_LIBRARY_PATH issue has been removed from MATLAB R2016a. Since disabling SIP may be inconvenient for the workflow, please consider upgrading to MATLAB R2016a. This should remove dependency with the DYLD_LIBRARY_PATH."
I currently have 2015a, so that may be another option.

**Comment by DavidMainprice** [comment]
Thanks for the info, I actually have version 2016a over our university network licence.

all the best David
