### ISSUE TITLE
INTER  vs  INTRA ?

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#110]
Hi Ralf,

In the help documentation for "Misorientation Analysis", it states that the INTERgranular misorientations are available in the ebsd.mis2mean, which provides the misorientation between an ebad measurement and the mean orientation from the grain to which it is assigned. In other words the misorientation INSIDE the grain, relative to the mean.

My question is:
Aren't the mis2mean orientations actually INTRAgranular data? That is... they are the misorientations *within* the grain (intra), rather than between or among the grains (inter). I may be missing something here, but I was confused by this point while perusing the documentation. I apologize if this seems like a trivial point to mention... I am perhaps sensitive to the idea because I have been working a lot lately on analyzing INTRAgranular orientation data, and the distinction is one I often need to make.

Am I incorrect about my understanding of the mis2mean data?

best,
Zach

**Comment by ralfHielscher** [comment]
Hi Zach,

good catch. I'm going to correct this. Your understanding is absolutely right.

Ralf.
