### ISSUE TITLE
plot(grains, grains.meanOrientation) shows error

### ISSUE THREAD

**Issue by LalitKaushik1991** [mtex-toolbox/mtex#1100]
Hi Ralf,

Recently I have downloaded the MTEX 5.7.0.  When I am trying to use plot(grains, grains.meanOrientation), the following error is shown. 

![image](https://user-images.githubusercontent.com/74644807/122383987-3f647100-cfa6-11eb-9683-f5c071e5ab0e.png)

For calculating grains, I am using the usual procedure.
[grains, ebsd.grainId]=calcGrains(ebsd('indexed'),'angle',5*degree);

Please look into the matter.

**Comment by ralfHielscher** [comment]
Hi Lalit,

could you please investigate under  which circumstances the error occurs. 
Maybe it is related with an already existing figure you are plotting in.

Ralf.

**Comment by LalitKaushik1991** [comment]
Thanks, Ralf

This was, in fact, happening because of plotting in an existing figure.
