### ISSUE TITLE
strange behaviour of calcAxisDistribution(mdf)

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#111]
Hi Ralf,
using  calcAxisDistribution and accordingly plotAxisDistribution on an mdf of a uniform odf results in a strange plot:

Edit: this is with `CS = crystalSymmetry('321')` while it looks fine with `CS = crystalSymmetry('-3m')` and others.
```matlab
mdf = calcMDF(uniformODF(CS));
axd = calcAxisDistribution(mdf,equispacedS2Grid);
plot(equispacedS2Grid,axd)
```
or

```matlab
plotAxisDistribution(mdf,'complete')
```
![mdf](https://cloud.githubusercontent.com/assets/11697557/10613091/0550f8c2-7754-11e5-9733-baf9e2586390.jpg)
![mdf3](https://cloud.githubusercontent.com/assets/11697557/10613096/0969775e-7754-11e5-9726-62b36208fe37.jpg)

Using a "regular" mdf obtained from a non-uniform odf, I see no problems.
Btw.,on the images you can also see a funny label placement error I also get with minmax when exproting images, but that's only of minor importance.

This is with mtex-4.1.4.

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this. It will be fixed in the next release.

Ralf.
