### ISSUE TITLE
plotSection

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#112]
Hi Ralf,
using plotSection I found three minor issues, I guess:
In brief: 
1) there are points plotted in the "forbidden" region, 
2) there's an error with 'contourf' 
3) contouring seems to be done against a zero boundary at the straight sides of the cake. 

With respect to 1:
```
plotSection(grains('q').boundary('q','q').misorientation,'axisAngle',(70:10:110)*degree,'volumeScaling',false)
```
![plotsection1](https://cloud.githubusercontent.com/assets/11697557/10613808/1cacb396-7757-11e5-806a-1f6337b8114a.jpg)

Some points lay in the "forbidden" region. Is that because this region is drawn for the upper angular bin limit while points come from within the bin?

Adding 'contourf'
```
plotSection(grains('q').boundary('q','q').misorientation,'axisAngle', (70:10:110)*degree,'volumeScaling',false,'contourf')
Matrix dimensions must agree.
Error in linspace (line 30)
    y = d1 + (0:n1).*(d2 - d1)/n1;
Error in plotS2Grid (line 36)
rho = linspace(rhoMin,rhoMax,round(1+(rhoMax-rhoMin)/res));
Error in vector3d/smooth (line 33)
    S2G = plotS2Grid(sR);
Error in vector3d/contourf (line 19)
h = v.smooth(data,'contours',10,'LineStyle','none',varargin{:});
Error in vector3d/plot (line 64)
    [varargout{1:nargout}] = v.contourf(varargin{:});
Error in axisAngleSections/plotSection (line 94)
      h = plot(v,data{:},'parent',ax,varargin{:},'doNotDraw');
Error in ODFSections/plot (line 59)
    plotSection(oS,mtexFig.gca,s,iv,secData,varargin{:});
Error in orientation/plotSection (line 24)
oS.plot(ori,varargin{:});
```
produces an error and this plot (actually all on top of each other):

![plotsection2](https://cloud.githubusercontent.com/assets/11697557/10614129/d622519a-7758-11e5-9ec3-00e4f87af388.jpg)

and 
`plotSection(grains('q').boundary('q','q').misorientation,'axisAngle','smooth','volumeScaling',false)`

gives
![plotsection3](https://cloud.githubusercontent.com/assets/11697557/10614229/660feb00-7759-11e5-9a5e-d28adc2c2a4a.jpg)

The smooth and the contoured plot look like they'd be contoured against zero-boundaries at the straight sides of the cake / fundamental region. I would have thought this shouldn't be like that, should it?

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

some quick answers:

1. points in the "forbidden area" may happen since the area is plotted for the exact rotational angle while the dots are within a certain tolerance around this angle. I could draw the area for the lower bound. May this makes more sense.
2. This I have to check in more detail. Can you give me the crystal symmetry?
3. I have to check this as well. However, for misorientation section I would very strongly recomment not to use contouring individual sections but to compute an MDF. The point that in your case each section is contoured for its own and the general symmetry of the misorientation space is not taken into account. From my experiences contouring the sections leads to  bad results.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
the crystal symmetry is -3m but happens as well for 321 in my case.

Thanks for the explanation for the contouring. When I plot individual misorientation axes for a certain angle range, contouring looks pretty good to me. So I was hoping that plotSection would be the lazy alternative instead of sorting axes by angles beforehand.

When I use
```
misor= grains('q').boundary('q','q').misorientation
mdf=calcODF(misor)
plotSection(mdf,'axisAngle','smooth','volumeScaling',false)
```
the following happens
```
misor = misorientation (show methods, plot)
  size: 229599 x 1
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  antipodal:         true
mdf = MDF (show methods, plot)
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  antipodal:         true
  Portion specified by Fourier coefficients:
    degree: 28
    weight: 1
>> plotSection(mdf,'axisAngle','smooth','volumeScaling',false)
Matrix dimensions must agree.
Error in linspace (line 30)
    y = d1 + (0:n1).*(d2 - d1)/n1;
Error in plotS2Grid (line 36)
rho = linspace(rhoMin,rhoMax,round(1+(rhoMax-rhoMin)/res));
Error in axisAngleSections/makeGrid (line 40)
        oS.plotGrid{s} = plotS2Grid(sR,varargin{:});
Error in ODF/plotSection (line 27)
S3G = oS.makeGrid('resolution',2.5*degree,varargin{:});
```
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I will release MTEX 4.2 today. Can you check whether this bug is still present there. I can not reproduce it.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I can confirm, `plotSection(mdf,'axisAngle','smooth','volumeScaling',false)`is fixed.
The error message with 'contourf' does not appear, but apparently using contourf / smooth on plotSection will be misleading at all - as it contours against a zero boundary and if people want a contoured plot, they should sort manually for angles and use plot where this problem does not exist.

With regard to (1), I still find points in the forbidden region.

Thanks and all the best,
Rüdiger
