### ISSUE TITLE
Mtex smooth ebsd and grains

### ISSUE THREAD

**Issue by bjoerneske** [mtex-toolbox/mtex#114]
Hi

I started working a bit with the filtering and smoothening of EBSD data in Mtex and I am looking for a bit more documentation here.

My main question is about smoothening and grains: 

grain calculations works quite well with the filtered data with missing points, however calculating grains after smothening an EBSD dataset gives different results. 

Is it somehow possible to limit the EBSD smoothening to allready calculated grains, I know it works for single grains but when I use a for loop I get an reshape error because the new grains has more values than the old?

``` matlab
   [grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'angle',10*degree);
   F = splineFilter;
   ebsd_smooth = ebsd;
   for i=1:length(grains)
   ebsd_smooth(grains(i)) = smooth(ebsd(grains(i)),F, 'fill');
   end
```

So far I used the trick in the documentation to avoid this and get the mis2mean and grainId og the smoothened EBSD data:

``` matlab
   F = splineFilter;
   ebsd_smooth = smooth(ebsd,F, 'fill');
   % compute mis2mean for the interpolated orientations
   [~,~,ebsd_smooth.mis2mean] = calcGrains(ebsd_smooth,'angle',10*degree);
```

if one asks a full grain calculation based on the smoothened data the grain results are quite different

``` matlab
[grains,ebsd_smooth.grainId,ebsd_smooth.mis2mean] = calcGrains(ebsd_smooth,'angle',10*degree);
```

**Comment by ralfHielscher** [comment]
Hi Björn,

I'm surprised you get different results. Actually, MTEX performs smoothing for each grain separately, whenever a ```grainId``` is stored in the ebsd variable. 

The only difference that I may think of are at the grain boundaries. Do you have an example?

Ralf

**Comment by bjoerneske** [comment]
​
 olivine8_oct2015.ang
<https://drive.google.com/file/d/0B86p4RNk_MzBbmdiMC02UGlMSWs/view?usp=drive_web>
​​
 olivine8_oct2015.ang
<https://drive.google.com/file/d/0B86p4RNk_MzBbmdiMC02UGlMSWs/view?usp=drive_web>
​Hi Ralf

Thanks for the fast response.

I cleaned up some of my code to give you and example. This dataset has poor
enstatite indexing, due to deformed lattice and poor patterns and the
problem is mainly for enstatite, especially clear in the lower left parts
of the plots. Fig 1-2 has preserved the data from the original grain
calculation, whereas fig 3 has changed grain-boundaries for enstatite.

i have atteched the dataset and script files.
​​​
 ralf_grains.m
<https://drive.google.com/file/d/0B86p4RNk_MzBcFZMZEZCLWp3ekk/view?usp=drive_web>
​​
 olivine8_oct2015.ang
<https://drive.google.com/file/d/0B86p4RNk_MzBbmdiMC02UGlMSWs/view?usp=drive_web>
​
[image: Innebygd bilde 1]
[image: Innebygd bilde 2]


2015-10-29 23:39 GMT+01:00 Ralf Hielscher <notifications@github.com>:
