### ISSUE TITLE
Misorientation Axes in Specimen reference frame

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#115]
Hello Ralf and others,

This is probably an ignorant question, and hopefully has a simple answer.
I am uncertain about how to plot the axes of misorientations relative to the principal directions of the specimen/acquisition reference frame.... rather than the crystal reference frame. I am probably missing something quite basic.

Here is an example:
```
>> mori = calcMisorientation(ebsd('Olivine'))
 
mori = misorientation (show methods, plot)
  size: 97907 x 1
  crystal symmetry : Olivine (mmm)
  crystal symmetry : Olivine (mmm)
```
The following plotting commands all seem to visualize the misorientation data relative to the crystallographic directions:
```
>> plotAxisDistribution(mori,'smooth')
```
![screen shot 2015-10-28 at 8 12 07 am](https://cloud.githubusercontent.com/assets/8769619/10789472/a0168b5e-7d4b-11e5-98ed-6b987775dfc0.png)
```
>> plot(axis(mori),'antipodal','lower','smooth')
```
![screen shot 2015-10-28 at 8 12 48 am](https://cloud.githubusercontent.com/assets/8769619/10789493/bdc46554-7d4b-11e5-8e1b-04570fbdc722.png)

How can I plot the axes of the misorientations relative to the specimen reference frame (i.e., a lower hemisphere plot of the misorientation axes that is orientated relative to the xvector, yvector, zvector specimen directions)?

Any help is greatly appreciated.

Thank you,
Zach

******************************************************************
For context... here are some other plots

plotPDF of mori data:
```
>> plotPDF(mori,ph,'antipodal','lower','complete','smooth')
```
![screen shot 2015-10-28 at 8 24 26 am](https://cloud.githubusercontent.com/assets/8769619/10789773/604b5188-7d4d-11e5-976c-cf700dccb276.png)

ODF for the sample (a mantle xenolith; sample surface cut randomly relative to any mesoscopic fabric):
![screen shot 2015-10-28 at 8 26 14 am](https://cloud.githubusercontent.com/assets/8769619/10789845/d3f44842-7d4d-11e5-8c70-467445b88fbf.png)

**Comment by ralfHielscher** [comment]
Hi Zach,

given a misorientation it is impossible to retrieve the misorientation axis in specimen coordinates. To compute this axis we need a pair of orientations. A list of such pairs of orientations can be computed by the command
```matlab
[ori1,ori2] = calcMisorientation(ebsd('Olivine'))
```
Not the misorientation axis in specimen coordinates is computed by
```matlab
a = axis(ori1,ori2)
```
You can plot the axes now by
```matlab
plot(a,'contourf')
```
In the next version of MTEX 4.2 you can do this directly with plotAxisDistribution.

Ralf.

**Comment by zmichels** [comment]
Ralf,

Thank you much! 

best,
Zach
