### ISSUE TITLE
Importing data in 4.x

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#118]
Hi Ralf,

I have a dataset that I cannot import into 4.x. The same file works fine in 3.5.
It is a Channel5 format .crc file, and in each case, I attempt to use the import_wizard

Works fine in 3.5.

I get the following error in 4.x:
![screen shot 2015-11-01 at 11 09 04 am](https://cloud.githubusercontent.com/assets/8769619/10871687/7e0af6ce-80b3-11e5-8fe1-7f4a44881d2a.png)

The .crc and .cpr files are available here temporarily:
https://www.dropbox.com/sh/g6w1e2d1puv6hho/AAAvWbuHnWnm0gpW3tEl5qeba?dl=0

Any idea what is wrong with my data file?

Thanks,
Zach

**Comment by ralfHielscher** [comment]
Hi Zach,

thank you for reporting this.

Ralf.
