### ISSUE TITLE
Wrong result with grains.perimeter

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#121]
Hi Ralf,
I wanted to compare the perimeters of grains with their convex hull.

So for some grains, grains.perimeter produces a realistic result, while for some it's most likely not correct as it is much smaller than the convex hull.

For example:
```
>> grains_merged(104)
 ans = grain2d (show methods, plot)
  Phase  Grains  Pixels  Mineral  Symmetry  Crystal reference frame
     1       1     114   Quartz      -3m1        X||a*, Y||b, Z||c
   Id   Phase   Pixels   phi1   Phi   phi2
 104       1      114    134   159    281

>> grains_merged(104).perimeter
ans =
   60.3387

>> hull_perimeter{grains_merged(104).id}
ans =
   48.8555
```
looks pretty fine to me.
![grains104](https://cloud.githubusercontent.com/assets/11697557/11040936/1b68f7a2-870f-11e5-8570-1bdce7c363a7.png)

However:
```
>> grains_merged(13361)
 ans = grain2d (show methods, plot)
  Phase  Grains  Pixels  Mineral  Symmetry  Crystal reference frame
     1       1     276   Quartz      -3m1        X||a*, Y||b, Z||c
     Id   Phase   Pixels   phi1   Phi   phi2
 13361       1      276     26    86    133

>> grains_merged(13361).perimeter
ans =
    5.9925
>> hull_perimeter{grains_merged(13361).id}
ans =
   77.5266

```
doesn't look too convincing.
![13361](https://cloud.githubusercontent.com/assets/11697557/11040988/6f7962e6-870f-11e5-8e49-29f56b124b17.png)

Please let me know if you need example data or anything else to help.
All the best,
Rüdiger

The way I calculate the convex hull is not a very intelligent solution and rather slow, but should be fine. For non-convex grains the perimeter of the convex hull gives me exactly the same as grains.perimeter.
```
for i = 1:length(grains_merged); 
   clear a;
   xy{i} = [grains_merged(i).x grains_merged(i).y];
   % sort by convex hull indexes and create hull
   b = boundary(xy{i}(:,1),xy{i}(:,2),0);
   hulls{i}  = xy{i}(b,:);
   %perimeter of hull
    for j=1:length(hulls{i})-1;
        a(j) = norm(hulls{i}(j,:) - hulls{i}(j+1,:));
    end
    hull_perimeter{i} = sum(a);
end        
```

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this. I believe the reason is the little circle on the right hand side of the grain. Can you send me the grain? Actually, ```grain.poly{:}``` would be sufficient.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I can confirm, results are fine now.
Thanks,
Rüdiger
