### ISSUE TITLE
Orientation : Only plot first pole figure out of 3 in the list PFs_olivine_hkl

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#122]
This script worked with previous versions of MTEX
```matlab
PFs_olivine_hkl = [ ...
    Miller(1,0,0,ebsd('Olivine').CS,'hkl'), ...
    Miller(0,1,0,ebsd('Olivine').CS,'hkl'), ...
    Miller(0,0,1,ebsd('Olivine').CS,'hkl'), ...
    ]
close all
setMTEXpref('FontSize',25)
figure
plotPDF(ori_Ol,PFs_olivine_hkl,'Marker','s',...
    'MarkerFaceColor','g','MarkerEdgeColor','g','MarkerSize',15)
drawNow(gcm,'figSize','large')
```
It plots only the (100) pole figure

where
```
ori_Ol = orientation (show methods, plot)
  size: 1 x 1
  crystal symmetry : Olivine (222)
  specimen symmetry: 1
 
  Bunge Euler angles in degree
  phi1  Phi phi2 Inv.
     0    0    0    0
```
is a single orientation, but I have same problem with 4 orientations

all the best David

**Comment by DavidMainprice** [comment]
I have found the cause of this problem
In my script I have put
%% Setup setMTEXpref
% you can uncomment the following line to disable the annotations
pfAnnotations = @(varargin) do_nothing;
setMTEXpref('pfAnnotations',pfAnnotations);
AFTER this command all plot figure plots only have the first pole figure in the list  PFs_olivine_hkl

SOLUTION

remove pfAnnotations = @(varargin) do_nothing;     from my script

Quit MATLAB
and re-run the script

all the best David

**Comment by DavidMainprice** [comment]
P.S.  mtex-4.1.4/mtex_settings.m

If you uncomment the following line to disable the annotations
pfAnnotations = @(varargin) do_nothing;
setMTEXpref('pfAnnotations',pfAnnotations);

In the file mtex_settings.m
at
mtex-4.1.4/mtex_settings.m

it works perfectly

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

if you want to disable annotations locally in your script you can do
```matlab
setMTEXpref('pfAnnotations',@(varargin) 1);
```

Ralf.
