### ISSUE TITLE
Plotting MDF as axis/angle sections will not plot near edge of MDF space

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#123]
```matlab
%% Yes plots from omega 0 to 105 degrees, but not above 105 to 120 degrees
plotSection(mdf,'axisAngle',(0:5:105)*degree,'volumeScaling',false,'contourf')
mtexColorbar
```
Above 105 degrees
```
Error using  .* 
Matrix dimensions must agree.

Error in linspace (line 31)
        y = d1 + (0:n1).*(d2 - d1)/n1;

Error in plotS2Grid (line 36)
rho = linspace(rhoMin,rhoMax,round(1+(rhoMax-rhoMin)/res));

Error in axisAngleSections/makeGrid (line 40)
        oS.plotGrid{s} = plotS2Grid(sR,varargin{:});

Error in ODF/plotSection (line 27)
S3G = oS.makeGrid('resolution',2.5*degree,varargin{:});
```
for mdf
``` 
mdf = MDF (show methods, plot)
  crystal symmetry : Olivine (222)
  crystal symmetry : Antigorite (121, X||a*, Y||b, Z||c)
 
  Portion specified by Fourier coefficients:
    degree: 38
    weight: 1
```
Personally I think the contours should cover the whole angle section and just overlay the boundary line of MDF space with minimum misorientation angles.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

I checked this with MTEX 4.1.4 and I got this

<img width="987" alt="sections" src="https://cloud.githubusercontent.com/assets/8619241/11227744/47a9149e-8d88-11e5-8817-786b347097fe.png">

I have no idea what went wrong in your case.

As for your second remark: This would mean that every misorientation counts for every of its symmetrically equivalent misorientation angles. I could compute this - actually this is more simple then selecting always the smallest misorientation angle. However, so far it is very unusual to consider this distribution. I'm a bit afraid to confuse the user.

Ralf.

**Comment by ralfHielscher** [comment]
Sorry, I misread your post.

Ralf.

**Comment by ralfHielscher** [comment]
Hi David,

I think I fixed your first issue. I will publish the fix as fast as possible.

Ralf

**Comment by DavidMainprice** [comment]
Many thanks

all the best David
