### ISSUE TITLE
 Using setColorRange after mtexColorbar

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#124]
Hi Ralf,
I get an error using `setColorRange` after `mtexColorbar`. Turning the colorbar off (if it's already there) before `setColorRange` and issuing `mtexColorbar` after `setColorRange`works perfectly.
```matlab
plotPDF(o,hs)
mtexColorbar
setColorRange([0 2],'zerowhite')
```
```
Error using get
There is no zscale property on the ColorBar class.

Error in setColorRange (line 63)
  if any(strcmp(get(mtexFig.cBarAxis,'zscale'),'log')), p = log10(p);end
```
I wasn't able to figure how the 'figure' option works, so maybe that's the problem. Do you have any hint how to use the option?

All the best,
Rüdiger

**Comment by zmichels** [comment]
Can you do what you need by separately setting the mtexColorMap and using:
caxis([0 2])
I may be misunderstanding…


I
On Nov 13, 2015, at 12:56 PM, kilir <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ralf,
I get an error using setColorRange after mtexColorbar. Turning the colorbar off (if it's already there) before setColorRange and issuing mtexColorbar after setColorRangeworks perfectly.

plotPDF(o,hs)
mtexColorbar
setColorRange([0 2],'zerowhite')

Error using get
There is no zscale property on the ColorBar class.

Error in setColorRange (line 63)
  if any(strcmp(get(mtexFig.cBarAxis,'zscale'),'log')), p = log10(p);end


I wasn't able to figure how the 'figure' option works, so maybe that's the problem. Do you have any hint how to use the option?

All the best,
Rüdiger

**Comment by kilir** [comment]
Hi,
an update on the  problem of setColorRange: It occurs on MatlabR2015b, I can't reproduce it with R2014a.

Zach, setting caxis only targets the last plot, so setColorRange is quite handy and also provides other option like 'equal' etc... So I would have ssumed it should work.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this issue. Its fixed in the next version.

Ralf.
