### ISSUE TITLE
144 symmetrically equivalent misoreintations - all angle/axis pairs are the same

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#126]
One can now calculated most things in MTEX at least two ways, this the case for symmetrically equivalent misoreintations
```matlab
%% route one 
delta_o_symm = symmetrise(delta_o,cs,cs)
delta_o_symm_axes = axis(delta_o_symm)
delta_o_symm_angles = angle(delta_o_symm) ./ degree;
%% route two
delta_o = o_host\o_twin
delta_o_symm = delta_o.symmetrise
delta_o_symm_axes = delta_o_symm.axis
delta_o_symm_angles = delta_o_symm.angle  ./ degree;
```
Both give the same results and for single misorientation delta_o
```
delta_o = misorientation (show methods, plot)
  size: 1 x 1
  crystal symmetry : -3m1, X||a*, Y||b, Z||c
  crystal symmetry : -3m1, X||a*, Y||b, Z||c
 
  Bunge Euler angles in degree
  phi1     Phi    phi2    Inv.
   150 52.5505      30       0
 ```
 You generated 144 equivalents
 ```
delta_o_symm = misorientation (show methods, plot)
  size: 144 x 1
  crystal symmetry : -3m1, X||a*, Y||b, Z||c
  crystal symmetry : -3m1, X||a*, Y||b, Z||c
 
delta_o_symm_axes = Miller (show methods, plot)
 size: 144 x 1
 symmetry: -3m1, X||a*, Y||b, Z||c
```
You can plot the 144 misorientations  using plot, so they exist.

The problem is for axes and angles of the 144 equivalents you can extract only smallest misorientation angle and axis pair, all 144 values are for this angle/axis pair. 

I suggest this is a bug or change in syntax that is not documented.

all the best David

**Comment by kilir** [comment]
Hi David,
do the lines below do what you want to do? I agree that it's some sort of workaround, but maybe it helps for now.
```
% misorientation between o1 and o2
mori = inv(o1).*o2 % or o1\o2

% all rotation angles - skip the unique and round if want them all
unique(round(100.*angle(rotation(symmetrise(mori)))))./100./degree

% all axes
unique(Miller(axis(rotation(symmetrise(mori))),cs))
```

All the best,
Rüdiger

**Comment by DavidMainprice** [comment]
Thanks Rüdiger I will take look at your suggestion. This a calcite e-twin before MTEX4 it was 6 x 6 = 36, now in MTEX4 its 12 x 12 =144 due to the additional mirror symmetry

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

this is consistent behavior throughout all of MTEX.
```matlab
angle(Miller(1,0,0,cs),Miller(0,1,0,cs)) % gives you the angle modulo symmetry
angle(ori1,ori2) % gives you the angle modulo symmetry
angle(ori) % gives you the angle modulo symmetry
``` 
apposed to that you get the angle ignorring symmetry by
```matlab
angle(vector3d(Miller(1,0,0,cs)),vector3d(Miller(0,1,0,cs)))
angle(rotation(ori1),rotation(ori2))
angle(rotation(ori))
``` 
I agree that syntax is a bit cumbersome. I can think about two alternatives:
Alternative 1: Introduce a flag, i.e.,
```matlab
angle(ori1,ori2,'symmetrised')       % if we make the not symmetrised version default
angle(ori1,ori2,'IgnoreSymmetry') % if we leave the symmetrised version default
```
Alternative 2: Introduce separate functions
```matlab
angleSym(ori1,ori2,'symmetrised')       % if we make the not symmetrised version default
angleIgnoreSym(ori1,ori2) % if we leave the symmetrised version default
```
Any suggestion is welcome,

Ralf.

**Comment by zmichels** [comment]
Hi Ralf,

As for the alternatives you mentioned, I like the flag option.

cheers,
Zach



On Nov 16, 2015, at 6:27 AM, Ralf Hielscher <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David,

this is consistent behavior throughout all of MTEX.

angle(Miller(1,0,0,cs),Miller(0,1,0,cs)) % gives you the angle modulo symmetry
angle(ori1,ori2) % gives you the angle modulo symmetry
angle(ori) % gives you the angle modulo symmetry

apposed to that you get the angle ignorring symmetry by

angle(vector3d(Miller(1,0,0,cs)),vector3d(Miller(0,1,0,cs)))
angle(rotation(ori1),rotation(ori2))
angle(rotation(ori))

I agree that syntax is a bit cumbersome. I can think about two alternatives:
Alternative 1: Introduce a flag, i.e.,

angle(ori1,ori2,'symmetrised')       % if we make the not symmetrised version default
angle(ori1,ori2,'IgnoreSymmetry') % if we leave the symmetrised version default

Alternative 2: Introduce separate functions

angleSym(ori1,ori2,'symmetrised')       % if we make the not symmetrised version default
angleIgnoreSym(ori1,ori2) % if we leave the symmetrised version default

Any suggestion is welcome,

Ralf.

**Comment by kilir** [comment]
With regard to the two possibilities: if it will be a flag, it should not break previous behavior, so nobody will have to fix their scripts. Might a separate function be easier to maintain?
Cheers,
Rüdiger

**Comment by DavidMainprice** [comment]
Dear all,

I would not call this coherent if you generated symmetrically equivalent 144 misorientations, but cannot access the range of angles and axes to show for example for twins there several equivalents that are plotted in MDF section at 180 degrees, which is the case for monoclinic crystal symmetry for example. To focus always on the minimum misorientation angles can be false direction when analysising grain boundary symmetry for example.

I can always use MTEX 3.5.0 to access the axes and angles, but that is not the point, there is functionally that is now missing.

all the best David

**Comment by DavidMainprice** [comment]
I would vote for angle(ori1,ori2,'IgnoreSymmetry') % if we leave the symmetrised version default, this leaves the current default in place and minimised the rewriting working scripts in MTEX4


’IgnoreSymmetry’ or ‘NoSymmetry’ would fine

all the best David
