### ISSUE TITLE
MTEX 4.1.4 Initialisation error (binary check failed)

### ISSUE THREAD

**Issue by GTerHaar** [mtex-toolbox/mtex#127]
Hi,

I am having a problem initialising MTEX 4.1.4 (missing binary pf2odf.exe). Any help on this would be much appriciated. See error message generated below:

run('C:\Users\16434978\Documents\GitHub\mtex\install_mtex.m')

```
initialize MTEX 4.1.4  ....Warning: missing binary pf2odf.exe 
In check_installation>fast_check_binaries at 101
  In check_installation>check_binaries at 37
  In check_installation at 18
  In startup_mtex at 74
  In install_mtex at 13
  In run at 63 
********************************************************************************
  MTEX binary check failed!
 
  The original error message was:
  Error using call_extern (line 30)
Can not find C:\Users\16434978\Documents\GitHub\mtex\c\bin\win64\odf2pf.exe!
 
  Check the following options:
  * Compile the binaries yourself.
  * Ask the maintainer for help!
********************************************************************************
```
 done!

**Comment by ralfHielscher** [comment]
Dear GTerHaar,

are you sure that you have downloaded the binary
https://github.com/mtex-toolbox/mtex/releases/download/mtex-4.1.4/mtex-4.1.4.zip

Ralf

**Comment by GTerHaar** [comment]
Hi,

Yes, downloading the zip solved the problem. The original files were cloned from the website though, strange that I did not work.

Thanks!

**Comment by ralfHielscher** [comment]
Hi,
this is not so surprising as cloning gives you only the source files. You could compile the binaries by yourself but downloading the binaries is more comfortable.

Ralf.
