### ISSUE TITLE
Problem of order of phases in phase transformation

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#131]
Dear Ralf,

I have TSL *.ang import with 1st olivine and  2nd antigorite in an import script.

When modifying my script developed on another *.ang file that had 1st olivine and  2nd antigorite I had a problem.

The  Olivine to Antigorite misorientation that I calculated with “map" etc is of course as before
```
Ol2Atg_No1 = misorientation (show methods, plot)
  size: 1 x 1
  crystal symmetry : Olivine (222)
  crystal symmetry : Antigorite (121, X||a*, Y||b, Z||c)
 
  Bunge Euler angles in degree
  phi1   Phi  phi2  Inv.
   180    90 91.16     0
```
BUT when I define my gB misorientation as before 
```
% using selected_grains.boundary select boundary by phase
gB_Ol_Atg = selected_grains.boundary('Olivine','Antigorite’)
```
now
```
gB_Ol_Atg = grainBoundary (show methods, plot)
 
 Segments   mineral 1  mineral 2
    88455  Antigorite    Olivine
```
The order of the minerals is now to the order in the import sequence, not the order in the command selected_grains.boundary('Olivine','Antigorite’)

and a get error message from
```
% restrict misorientation to within 5 dgrees
isMisorientation_No1 = angle(gB_Ol_Atg.misorientation,Ol2Atg_No1) < 5*degree;

Error using orientation/dot (line 34)
Symmetry missmatch

Error in orientation/angle (line 17)
  omega = real(2*acos(dot(o1,varargin{:})));
```
The order of symmetry in gB_Ol_Atg.misorientation is Antigorite and Olivine, 
where as Ol2Atg_No1 it is Olivine and Antigorite

clearly resulting in a Symmetry  mismatch !

Can I impose the order of symmetry in gB_Ol_Atg = selected_grains.boundary('Olivine','Antigorite’) ?

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

it is not possible to change this order. You can however change the order in the misorientations by taking the inverse of the misorientations.

Ralf
