### ISSUE TITLE
MTEX-4.2.1: minmax values: min always 0

### ISSUE THREAD

**Issue by semicarbazid** [mtex-toolbox/mtex#132]
Dear Ralf,

as far as I can see, since MTEX 4 the minmax values in all plots (checked PFs, tensor plots and ODF sections) are wrong: min value is always 0, max value is correct however (valid on latest MTEX-4.2.1). Can you confirm this?

All the best,
Bernd

**Comment by ralfHielscher** [comment]
Thank you for reporting this bug. It should be fixed in the next release of MTEX.
