### ISSUE TITLE
MTEX-4.2.1: 3D ODF plot does not work

### ISSUE THREAD

**Issue by semicarbazid** [mtex-toolbox/mtex#133]
Dear Ralf,

the following commands:
```matlab
odf = SantaFe;
plot(odf,'3d')
```
results in
```
Error using polar
Too many output arguments.

Error in ODF/plot3d (line 13)
[xlim, ylim] = polar(S2G);

Error in ODF/plot (line 9)
  plot3d(odf,varargin{:});
```
I digged a little bit into this error and found out, that the MATLAB internal polar function is called instead of the appropriate MTEX polar function.

All the best,
Bernd

**Comment by ralfHielscher** [comment]
ODF 3d plots are not supported any more. If there is a lot of interest in it I might reintroduce them.

Ralf

**Comment by ralfHielscher** [comment]
```plot3d(odf)```

should work in MTEX 4.4.alpha5 
not with all options but in a basic version.

Ralf.
