### ISSUE TITLE
parent grain reconstructer bug in clusterVariantGraph, likely due to other (not used) phase

### ISSUE THREAD

**Issue by Tijmenvermeij** [mtex-toolbox/mtex#1335]
**What do you want to do?**
PAG reconstruction with Mtex 5.8 on ferrite-martensite steel. When I run clusterVariantGraph, I get an error that I suspect is due to the fact that I also have ferrite in the dataset as an alternative phase.

**Error Message**
Error using repelem
In repelem(v, N), N must be a scalar or a vector of length equal to v.

Error in parentGrainReconstructor/clusterVariantGraph (line 51)
h2ind = repelem(h2ind, numV * job.isChild + job.isParent);

**Working solution**

I changed the code:
```matlab
% h2ind 
h2ind = 1:length(job.grains);
h2ind = h2ind(job.isChild | job.isParent);
h2ind = repelem(h2ind, numV * job.isChild + job.isParent);

isChild = job.isChild;
isChild = isChild(job.isChild | job.isParent);
isChild = repelem(isChild, numV * job.isChild + job.isParent);
```
into the following, to try to avoid the issue with the extra phase. It seems to run on my data:
```matlab
% h2ind 
h2ind = 1:length(job.grains);
h2ind = h2ind(job.isChild | job.isParent);
h2ind = repelem(h2ind, numV * job.isChild(job.isChild | job.isParent) + job.isParent(job.isChild | job.isParent));

isChild = job.isChild;
isChild = isChild(job.isChild | job.isParent);
isChild = repelem(isChild, numV * job.isChild(job.isChild | job.isParent) + job.isParent(job.isChild | job.isParent));
```

Not sure if this is a good solution that can be implemented in the code... It works for me (for now).

**Comment by nyyssont** [comment]
This fix works very well for me. Thanks. I will keep testing it.

**Comment by ralfHielscher** [comment]
Hi Tijmen,

thank you very much for pointing this out and providing a solution. I have included it into the official code.

All the best,

Ralf.
