### ISSUE TITLE
triple junctions on merged grains

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#136]
Hi Ralf,
triple junction on grains work fine, however, when I merge these grains to get rid of twin boundaries, triple junctions on merged grains still returns  junctions that include twin boundaries.
```matlab
% calcgrains
[grainsl ebsdc.grainId] = calcGrains(ebsdc,'angle',10*degree);

% get tp points
tp = grainsl('q').triplePoints('q','q','q');

figure
plot(grainsl('q'))
hold on
plot(tp,'MarkerSize',8,'MarkerFaceColor','k')
hold off
% looks good 
```
![tp_non_merged](https://cloud.githubusercontent.com/assets/11697557/11441946/4350c334-9511-11e5-93c1-6561620bb086.png)

```matlab
% but we don't want to include twin boundaries  - merge dauphine
gb_qtz = grainsl.boundary('Quartz','Quartz');
rot1 = rotation('axis',Miller(0,0,0,1,CS{2}),'angle',60*degree);
ind1 = angle(gb_qtz('Quartz','Quartz').misorientation,rot1)<6*degree; 
twinBoundary = gb_qtz(ind1);
[grains_mergedc,parentID_grains]= merge(grainsl,twinBoundary);
ebsd_mergedc = ebsdc;
ebsd_mergedc.grainId  = parentID_grains(ebsdc.grainId);

% get tp points
clear tp
tp = grains_mergedc('q').triplePoints('q','q','q');

% there are triple junction along boundaries
figure
plot(grains_mergedc('q'))
hold on
plot(tp,'MarkerSize',8,'MarkerFaceColor','k')
hold off

% seems that triple junctions still relay on the original grain boundary?
figure
plot(grains_mergedc('q'))
hold on
plot(twinBoundary,'lineColor','r','linewidth',2)
hold on
plot(tp,'MarkerSize',8,'MarkerFaceColor','k')
hold off
```
There are triple junctions indicated where none should be.
![tp_merged](https://cloud.githubusercontent.com/assets/11697557/11441956/559cd6f4-9511-11e5-822d-4555e51345fc.png)

It looks like the old twin boundaries are still considered, despite grains are merged.
![tp_merged_dau](https://cloud.githubusercontent.com/assets/11697557/11441955/5599e14c-9511-11e5-8171-bd78c37e4900.png)

Did I miss something or do I have an error in the script above? Or do I have to implicitly exclude/delete triple junctions that belong to a twin boundary?

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this. It will be fixed in the next minor release.

Ralf.
