### ISSUE TITLE
Taylor factor code issues

### ISSUE THREAD

**Issue by ArulUQ** [mtex-toolbox/mtex#1364]
**I have generated Schmid factor map but i could not able to get a taylor factor map using the below code**

eps = strainTensor(diag([-1,-1,-1]))

epsCrystal = inv(grains.meanOrientation) * eps

[M, b, W] = calcTaylor(epsCrystal, sS);

plot(grains,M,'micronbar','off')
mtexColorbar southoutside

**Error Message**

Error using optimoptions (line 124)
Invalid solver specified. Provide a solver name or handle
(such as 'fmincon' or @fminunc).
Type DOC OPTIMOPTIONS for a list of solvers.

Error in strainTensor/calcTaylor (line 65)
  options =
  optimoptions('linprog','Algorithm','interior-point-legacy','Display','none');

Error in TRIAL_CASA_10 (line 197)
[M, b, W] = calcTaylor(epsCrystal, sS);```
put the error message here
```
**5.6.0**

Can you please help me to fix this?

**Comment by ArulUQ** [comment]
Hi, I am using 2021b
BR
Arul

**Comment by kilir** [comment]
And you have the Optimization Toolbox installed?
Cheers,
Rüdiger

**Comment by ArulUQ** [comment]
Thank you, Rudiger. It worked well after the Optimization toolbox installation !
BR
Arul
