### ISSUE TITLE
Pole figures at high point counts

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#138]
I've noticed an issue with plotPDF at high point numbers.  My EBSD data includes a total of 333468 points, and is of the magnesium symmetry  
```
>> CS = grains.CS
 CS = crystalSymmetry (show methods, plot)
 
  mineral        : Magnesium        
  color          : light blue       
  symmetry       : 6/mmm            
  a, b, c        : 3.2, 3.2, 5.2    
  reference frame: X||a*, Y||b, Z||c)
```
First I enter my data using the import wizard, and it looks good when I plot it.

Then I define the pole figures I want using
```matlab
h=[Miller(0,0,1,ebsd('Magnesium').CS), Miller(1,0,0,ebsd('Magnesium').CS)];
```
and finally I plot the pole figures using 
```matlab
plotPDF(ebsd('Magnesium').orientations,h,'points',10000,'antipodal')
```

If I plot 8300 points
![pastedimage1](https://cloud.githubusercontent.com/assets/16214025/11667900/6a70bab4-9dc2-11e5-8f05-e1e479d0d485.png)

if I plot 8400 points
![pastedimage2](https://cloud.githubusercontent.com/assets/16214025/11667916/78b391e6-9dc2-11e5-937e-c49d581d0dd4.png)

if I plot 30 000 points
![pastedimage3](https://cloud.githubusercontent.com/assets/16214025/11667918/82569496-9dc2-11e5-8732-8eb482a9ede9.png)

So it looks like this is something to do with very large point quantities, which is probably only an issue when working with EBSD data.

**Comment by ralfHielscher** [comment]
I guess you are asking about the markerSize. You can set it explicitly by
```matlab
plotPDF(ebsd('Magnesium').orientations,h,'points',10000,'MarkerSize',10)
```

Change the number to adjust the marker size to your needs.

Ralf

**Comment by jhiscocks** [comment]
That's interesting, if you don't specify a marker size, then with a few points you get small markers, and with many points you get larger markers.  Thank you for showing me how to fix this.

Jessica
