### ISSUE TITLE
EBSD maps flipping when zoomed

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#139]
Hello, I am using Matlab R2015b and Mtex 4.2.1 with  EBSD maps that are very long and thin (~100 points in x by 1500 points in y).  When I import this data (in .ctf format) and view the map either in the import wizard or upon entering the command plot(ebsd('Magnesium'),ebsd('Magnesium').orientations)  the zoom in option in the figure GUI causes it to flip in Y orientation frequently, or sometimes to get smaller.

This may be due to the import options I use (Y down, x left or right), and "use CTF interface flag ```convertEuler2SpatialReferenceFrame```

**Comment by ralfHielscher** [comment]
Hi jhiscocks,

I have never experienced this problem. I'm very sorry about this but I do not know how to fix it.

Ralf

**Comment by jhiscocks** [comment]
Hello Ralf, to give greater detail on the issue;
I am using Matlab R2015b student edition, and MTEX 4.2.1.

My files are exported from the bruker esprit 2.0 system as .ctf (channel text files) and imported with specimen reference frame 'use CTF interface flag 'convertEuler2SpatialReferenceFrame'' and x positive to the west, y positive south.  Data is imported as a workspace variable.

When I plot as plot(ebsd('Magnesium'),ebsd('Magnesium').orientations) the behaviour on zooming is not useful, it seems to do things like flip the data in some cases.  When I try to zoom to a region, the region doesn't expand to fit the window, and when I try to pan the region using the hand tool, the surrounding window moves rather than the data.

Conversely, everything works properly when moving around a scatter plot generated from the data.

I have attached a copy of one of my small datasets, so you can maybe try to reproduce it.  If it doesn't attache properly it can also be found at the link below.  This isn't a huge problem or anything, but the occasional flipping of data is a bit disturbing if you aren't expecting it.

I appreciate the huge workload involved in continuing to keep this code updated and appreciate any future improvements you can offer in this area.


Jessica



https://www.dropbox.com/s/wgbghf62asbgtih/W31-LT-run3-box3.ctf?dl=0

[https://cf.dropboxstatic.com/static/images/icons128/page_white.png]<https://www.dropbox.com/s/wgbghf62asbgtih/W31-LT-run3-box3.ctf?dl=0>

W31-LT-run3-box3.ctf<https://www.dropbox.com/s/wgbghf62asbgtih/W31-LT-run3-box3.ctf?dl=0>
www.dropbox.com
Shared with Dropbox



_____________________________________________________________________
Jessica Hiscocks
j.hiscocks@queensu.ca

PhD Candidate, Materials Engineering
312 Nicol Hall, Queen's University, Kingston Ont.


________________________________

**Comment by ralfHielscher** [comment]
Hi Jessica,

this is most likely a problem between Matlab and your graphics driver. You might try switching the renderer by
```matlab
set(gcf,'renderer','zBuffer')
```
You may also try a different computer or a different Matlab version. I'm sorry about these problems, but there is nothing I can do.

Ralf.
