### ISSUE TITLE
plotPDF results for equal angle, equal distance, equal area all identical

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#140]
Hello, I have used the following code to plot pole figures, and substituted the 'earea' argument for 'eangle' 'edist' 'schmidt' and 'stereo' and in all cases the pole figures were identical, except for 'stereo' where the result is slightly larger but not fundamentally different.  I am using matlab 2015b and Mtex 4.2.1
```matlab
h=[Miller(0,0,1,ebsd('Magnesium').CS), Miller(1,0,0,ebsd('Magnesium').CS)];
plotPDF(ebsd_V1('Magnesium').orientations,h,'upper','earea','points','all', 'MarkerSize',1)
```
Regards, Jessica

**Comment by kilir** [comment]
Hi,
does adding `'projection'` before the `'edist'`,`eangle'`,`'earea'` work for you?
Cheers,
Rüdiger

**Comment by jhiscocks** [comment]
Thank you, that fixes it.
