### ISSUE TITLE
reduced symmetry of misorientations sampled from mdf

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#144]
Using 
```
CS = crystalSymmetry('321')
plotAxisDistribution(CS,'antipodal')
```
![axis_cs](https://cloud.githubusercontent.com/assets/11697557/12429538/1b7e3964-beeb-11e5-865d-5a6be8a6bfb0.png)

gives the axis distribution of misorientation axes to be expected for the CS.

Similarly, one can calculate an mdf from an uniform odf and use calcAxisDistribution
```
unio= uniformODF(CS)
mdf= calcMDF(unio)
grid = equispacedS2Grid('Resolution',1*degree,'antipodal');
grid = Miller(grid,CS)
axs = mdf.calcAxisDistribution(grid);
plot(grid,axs,'antipodal','MarkerSize',4)
```
![axis_mdf](https://cloud.githubusercontent.com/assets/11697557/12429822/b02f2e0a-beec-11e5-9d08-ad595c940782.png)

It looks like this can be approximated by

```
os = discreteSample(unio,2000000)
mori = inv(os(1:end/2)).*os(end/2+1:end);
plot(mori.axis,'smooth','antipodal')
```
![axis_mori](https://cloud.githubusercontent.com/assets/11697557/12429540/25f23c74-beeb-11e5-89f1-79ecde21396d.png)

However, sampling from the mdf, the resulting symmetry of the axis distribution is reduced. So I am wondering what I might be missing.
```
mdf= calcMDF(unio)
moriS = discreteSample(mdf,1000000)
plot(moriS.axis,'smooth','antipodal')
```
![axis_moris](https://cloud.githubusercontent.com/assets/11697557/12429573/5fe9377a-beeb-11e5-8a6b-400fe911c742.png)

The reasoning behind it is, that at the end I want to calculate the axis distribution for axes with just a specific range of angles and I don't know how I can use any continuous function to do so.
Any hint on what might be going wrong when sampling from the mdf or how I could calculate the axis distribution for axes with a specific angle is welcome.
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this was a bug. Thank you for reporting this.

Ralf.
