### ISSUE TITLE
import_wizard  has trouble reading .osc

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#145]
Reading an .osc file with just one phase with import wizard, the first phase queried is phase -1 (notIndexed) and phase 0 is the indexed phase. The summary is:

phase -1 (not Indexed): notIndexed, 0 orientations
phase 0 (Quartz): symmetry 321, 283490 orientations

and the script will contain:

```matlab
CS = {... 
  'notIndexed',...
  crystalSymmetry('321', [4.91 4.91 5.41], 'X||a', 'Y||b*', 'Z||c', 'mineral', 'Quartz', 'color', 'light blue')};
ebsd = loadEBSD(fname,CS,'interface','osc',...
  'convertEuler2SpatialReferenceFrame');
```
However, the ebsd does not contain the indexed data, no orientations.
```
ebsd = EBSD (show methods, plot)
 Phase   Orientations     Mineral  Color  Symmetry  Crystal reference frame
     0  283490 (100%)  notIndexed                                          
 Properties: confidenceindex, fit, imagequality, semsignal, x, y
 Scan unit : um
```
This can be easily fixed by deleting the 'notIndexed' entry in CS, but I thought this might not be too obvious for everyone and could be a bug.

[OIM systems (at least some versions - but this behavior has changed with a certain software version - maybe someone with such a system knows better) with just one phase selected for indexing seem to produce files with 100% of this phase (no matter how bad the indexing is). If some filtering is done and the data is exported, the files (.ang or .osc) may actually lack non-indexed entries (no x,y for non-indexed pixels) at all and will still only consist of one phase]

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

could you please send me a corresponding data file?

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I'll send you a download link.
Cheers,
Rüdiger
