### ISSUE TITLE
odf2fc may break during calcMDF() 

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#147]
While I was trying to figure if the behavior reported in #146 is related to calcMDF returning a Fourier mdf, I tried running calcMDF on a fairly uniform odf.
```matlab
odf=unimodalODF(orientation('Euler',[0 0 0]*degree,cs),'halfwidth',90*degree)
mdf=calcMDF(odf)
```
Most of the times odf2fc crashes with the following in the logfile:
```
odf2fc(85213,0x7fff79853310) malloc: *** error for object 0x100807600: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```
Sometimes it works, but I did not find a ways to reproduce the  behavior.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,
there are two issues here. The first one is when specifying the halfwidth only MTEX uses by default the de la Vallee Poussin kernel which is not suitable for modelling very weak textures. In particular halfwidth 90 degree gives you a constant ODF. The second issue is that calcMDF fails on constant ODFs. The second issue will be fixed. For the first issue simply use a different kernel, i.e., de Abel Poisson kernel.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
thanks for the explanation, that is good to know. By defining this such a constant odf (instead of uniformODF), I was just trying to see if I can work around #146.
All the best,
Rüdiger
