### ISSUE TITLE
issue plotIPDF labels

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#153]
Hi Ralf,
using mtex4.3.beta1
```
plotIPDF(ebsd('q').orientations,xvector)
```
results in a plot with 3 digit annotations, while crystal symmetry is 321 which seems to have some rounding issue, displaying 470 instead of 10-10. 
 `annotate(Miller(1,0,-1,0,ebsd('q').CS),'symmetrised','labeled')` works fine.

![ipdf](https://cloud.githubusercontent.com/assets/11697557/13088687/8b8e812e-d4ed-11e5-9d8d-985f6c1ca6c0.jpeg)

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Thank you for reporting. Fix is here 9a14c50
