### ISSUE TITLE
feature request/enhancement: saveFigure

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#155]
Hi Ralf,
is there any way to easily tell whether mtexFigure displays a map (e.g.grains) or something else?
The reasoning behind it, is that I don't want anti-aliasing and Matlabs GraphicsSmoothing in those plots. Hence I modified saveFigure to contain `set(gcf,'GraphicsSmoothing','off');` and the `'-a1'` option in export_fig and called it maybe saveFigure_map, using either one or the other, depending what should be saved. If there would be a way to tell what is actually in mtexFigure, one could have a switch in saveFigure.
If this isn't trivial, no need to put any effort in it as I can also live with two saveFigure commands.
(File format is of course a raster file as the vector files for maps are quite unusable for me.)

Cheers,
Rüdiger

Closeup produced by saveFigure
![savefigure_default](https://cloud.githubusercontent.com/assets/11697557/13431518/132704c6-dfca-11e5-87eb-47b19c5f4e1a.jpg)

Closeup produced by saveFigure_map
![savefigure_map](https://cloud.githubusercontent.com/assets/11697557/13431539/26eb186c-dfca-11e5-968a-fc19e930c5f9.jpg)

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

graind, EBSD, etc. plots are a mapPlot. In particular you can get a handle to it by
```matlab
mP = getappdata(gca,'mapPlot')
```
If this appdata is not set the plot is not a mapPlot.

Ralf.

**Comment by kilir** [comment]
Hi Ralf, that's for that info. I'll put a saveFigure version which switches smoothing off on gistbox. Maybe someone will find it useful.
Cheers,Rüdiger
