### ISSUE TITLE
Error in running external program

### ISSUE THREAD

**Issue by KKrishna1** [mtex-toolbox/mtex#156]
Hi there, 
While running Mtex for ODF calculation, following error is popping up. 
How to fix it, Thanks in advance. Best,

---

Error using call_extern (line 158)
Error running external program:

 C:\Users\mbessrk2\mtex-4.3.beta2\mtex-4.3.beta2\c\bin\win64\pf2odf.exe
 C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484.txt

Error in PoleFigure/calcODF (line 145)
[c,alpha] = call_extern('pf2odf',...

**Comment by kilir** [comment]
Posting the content of the log file (pf2odf3484.txt) might be helpful.
Cheers,
Rüdiger

**Comment by KKrishna1** [comment]
function [odf,alpha] = calcODF(pf,varargin)
% PDF to ODF inversion
%
% *calcODF* is one of the main function of the MTEX toolbox.
% It estimates an ODF from given Polefigure intensities by
% <PoleFigure2odf.html fitting an ODF that consists of a large number of unimodal ODFs to the data>.
% It does so by minimizing a least squares functional. The command
% *calcODF* supports <ghost_demo.html automatic ghost correction> and
% <dubna_demo.html the zero range method>.
% The function *calcODF* has several options to control convergence,
% resolution, smoothing, etc. See below for a complete description.
%
% Syntax
%
%   odf = calcODF(pf)
%   odf = calcODF(pf,'halfwidth',5*degree)
%   odf = calcODF(pf,'ZERO_RANGE')
%   odf = calcODF(pf,'resolution',2.5*degree)
% 
% Input
%  pf - @PoleFigure
%
% Options
%  KERNEL            - the ansatz functions (default = de la Vallee Poussin)
%  KERNELWIDTH | HALFWIDTH - halfwidth of the ansatz functions (default = 2/3 * resolution)
%  RESOLUTION        - localization grid for the ansatz fucntions (default = 3/2 resolution(pf))
%  BANDWIDTH         - bandwidth of the ansatz functions (default = max)
%  ITER_MAX          - maximum number of iterations (default = 11)
%  ITER_MIN          - minimum number of iterations (default = 5)
%  REGULARIZATION    - weighting coefficient lambda (default = 0)
%  ODF_SAVE          - save ODF simultanously
%  C0                - initial guess (default = [1 1 1 1 ... 1])
%
% Flags
%  ZERO_RANGE        - apply zero range method (default = )
%  NOGHOSTCORRECTION - omit ghost correction
%  ENSURE_DESCENT - stop iteration whenever no procress if observed
%  FORCE_ITER_MAX - allway go until ITER_MAX
%  RP_VALUES      - calculate RP values during iteration
%  ODF_TEST       - for testing only
%  SILENT         - no output
%
% Output
%  odf    - reconstructed @ODF
%  alpha  - scaling factors, calculated during reconstruction
%
% See also
% PoleFigure2odf ODF_demo PoleFigureSimulation_demo
% loadPoleFigure ImportPoleFigureData examples_index

tic

vdisp('------ MTEX -- PDF to ODF inversion ------------------',varargin{:})

% ------------------- get input--------------------------------------------

% take the mean over duplicated pole figure values
pf = unique(pf);

CS = pf.CS;
SS = pf.SS;
if pf.r.antipodal
  CS = CS.properGroup;
  SS = SS.properGroup;
end

% generate discretization of orientation space
if pf.allR{1}.isOption('resolution')
  res = pf.allR{1}.resolution;
else
  res = 5*degree;
end
res = get_option(varargin,'resolution',res);
S3G = equispacedSO3Grid(CS,SS,'resolution',res);

% zero range method
if check_option(varargin,{'ZR','zero_range'}), S3G = zeroRange(pf,S3G,varargin{:});end

% get kernel
kw = get_option(varargin,{'HALFWIDTH','KERNELWIDTH'},S3G.resolution,'double');
psi = get_option(varargin,'kernel',...
  deLaValeePoussinKernel('halfwidth',kw),'kernel');

% get other options
iter_max = int32(get_option(varargin,'ITER_MAX',...
  getMTEXpref('ITER_MAX',15),'double'));
iter_min = int32(get_option(varargin,'ITER_MIN',10,'double'));

c0 = get_option(varargin,'C0',...
	1/sum(length(S3G))*ones(sum(length(S3G)),1));


% ----------------- prepare for calling calcODF.c -------------------------

% calculate gh
gh = symmetrise(S3G).' * pf.h; % S3G x SS x CS x h
gh = [gh.rho(:),gh.theta(:)].' /2 /pi;

% extract kernel Fourier coefficents
A = psi.A;
if pf.allR{1}.antipodal
  A(2:2:end) = 0;
else
  warning('MTEX:missingFlag','Flag HEMISPHERE not set in PoleFigure data!');
end;
bw = min(get_option(varargin,'bandwidth',length(A)),length(A));
A = A(1:bw);

% detect superposed pole figures
lh = int32(cellfun('length',pf.c)*length(CS)*length(SS));
refl = cell2mat(pf.c);

% arrange Pole figure data
P  = max(0,pf.intensities); % ensure non negativity
lP = int32(cellfun('prodofsize',pf.allI));
r = [pf.r.rho(:),pf.r.theta(:)].' /2/pi;

% normalize very different polefigures
mm = max(pf.intensities(:));

for i = 1:pf.numPF
  if mm > 5*max(pf.allI{i}(:))
    pf.allI{i} = pf.allI{i} * mm/5/max(pf.allI{i}(:));
  end
end

% compute quadrature weights
w = [];
if ~check_option(varargin,'b')
  for i = 1:pf.numPF
    ww = calcQuadratureWeights(pf.allR{i});
    w = [w;ww(:)]; %#ok<AGROW>
  end
  varargin = set_option(varargin,'WEIGHTS');
end

% calculate flags
CW_flags = {{'WEIGHTS',0},{'REGULARISATION',1},...
  {'SAVE_ODF',5},{'RP_VALUES',6},{'FORCE_ITER_MAX',7},{'ODF_TEST',8}};
flags = calc_flags(varargin,CW_flags);

% call c-routine
vdisp('Call c-routine',varargin{:});

[c,alpha] = call_extern('pf2odf',...
  'INTERN',lP,lh,refl,iter_max,iter_min,flags,...
  'EXTERN',P,r,gh,A,c0,w,...
  char(extract_option(varargin,'silent')));
vdisp(['required time: ',int2str(toc),'s'],varargin{:});

% return ODF
odf = unimodalODF(S3G,psi,'weights',c./sum(c));

if check_option(varargin,'noGhostCorrection'), return;end

% ------------------ ghost correction -----------------------------------

% determine phon
phon = 1;
for ip = 1:pf.numPF
  phon = min(phon,...
    quantile(max(0,pf.allI{ip}(:)),0.01)./alpha(ip));
end

if phon > 0.99
  odf = uniformODF(CS,SS);
  return
elseif phon > 0.1
  vdisp('ghost correction',varargin{:});
  vdisp(['calculate with fixed background ',xnum2str(phon)],varargin{:});
else
  return
end

% subtract uniform portion from intensities
for ip = 1:pf.numPF
  pf.allI{ip} = pf.allI{ip} - alpha(ip) * phon;
end
P = max(0,pf.intensities(:)); %no negative values !

c0 = (1-phon)/length(S3G)*ones(length(S3G),1);

% calculate new ODF
[c,alpha] = call_extern('pf2odf',...
  'INTERN',lP,lh,refl,phon,iter_max,iter_min,flags,...
  'EXTERN',P,r,gh,A,c0,w,char(extract_option(varargin,'silent')));

% return ODF
odf = phon * uniformODF(CS,SS) + ... 
  (1-phon) * unimodalODF(S3G,psi,'weights',c./sum(c));

end

**Comment by KKrishna1** [comment]
Hi Rüdiger, 

Are you asking for the above file? 

Thanks

**Comment by zmichels** [comment]
Did you install from the repository? ...  or instead from the downloads page here:
http://mtex-toolbox.github.io/download.html

The problem you have shared is similar to ones people have had when they did *not* install from the downloads page. The downloads on the download page have some necessary compiled portions of the toolbox that are not pre-compiled in the repository folder.

Perhaps you have already tried to install from the files on the downloads page... But if not, I would give that a go first to see if it helps.

Best,
Zach

On Mar 1, 2016, at 12:59 PM, KKrishna1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi R?diger,

Are you asking for the above file?

Thanks

-

**Comment by kilir** [comment]
Hi,
actually I meant the C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484.txt
cheers,
Rüdiger

**Comment by KKrishna1** [comment]
lP: 69 69 69 
lh: 144 144 432 
refl: 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 
iter_max: 11 
iter_min: 10 
flags: 1 
P: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_P.dat
r: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_r.dat
gh: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_gh.dat
A: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_A.dat
c0: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_c0.dat
w: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_w.dat
res1: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_res1.dat
res2: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3484_res2.dat



Program was downloaded from the repository


Thanks ALL.

**Comment by ralfHielscher** [comment]
Does it work now after you have downloaded it from the download page?

**Comment by KKrishna1** [comment]
Hi RH, 
The issue is only for one sample condition (i didn't know why), but for the other sample it is working fine. Thanks.

**Comment by wlepage** [comment]
Hi all. First, thank you to Ralf and all of the developers for making MTEX a really impressive package. I have been using it with success for creating pole figure plots. Next, I need to compute ODFs, but I'm running into this same error:
```
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
Error using call_extern (line 158)
Error running external program:

 C:\Users\wlepage\Documents\MATLAB\mtex-4.3.1\c\bin\win64\pf2odf.exe
 C:\Users\wlepage\AppData\Local\Temp\pf2odf34896.txt

Error in PoleFigure/calcODF (line 145)
[c,alpha] = call_extern('pf2odf',...

Error in plot20160322_mtex (line 49)
odf = calcODF(pf);
```

I've reinstalled MTEX from the downloads page instead of the repository, and I've also tried changing the permissions on pf2odf.exe to "Run as administrator" (I'm on win64) but I still get the same error. What else could I try? Thank you in advance for all of the expertise.

Here is the log file, pf2odf34896.txt
```
lP: 3541 3541 3541 
lh: 48 48 48 
refl: 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 
iter_max: 11 
iter_min: 10 
flags: 1 
P: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_P.dat
r: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_r.dat
gh: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_gh.dat
A: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_A.dat
c0: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_c0.dat
w: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_w.dat
res1: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_res1.dat
res2: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_res2.dat
```

**Comment by zmichels** [comment]
Have you put the mtex folder in your Matlab folder? If not, you might try that, too. I think on some computers or systems it needs to be located there.


On Apr 5, 2016, at 7:10 AM, wlepage <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all. First, thank you to Ralf and all of the developers for making MTEX a really impressive package. I have been using it with success for creating pole figure plots. Next, I need to compute ODFs, but I'm running into this same error:

------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
Error using call_extern (line 158)
Error running external program:

 C:\Users\wlepage\Documents\MATLAB\mtex-4.3.1\c\bin\win64\pf2odf.exe
 C:\Users\wlepage\AppData\Local\Temp\pf2odf34896.txt

Error in PoleFigure/calcODF (line 145)
[c,alpha] = call_extern('pf2odf',...

Error in plot20160322_mtex (line 49)
odf = calcODF(pf);


I've reinstalled MTEX from the downloads page instead of the repository, and I've also tried changing the permissions on pf2odf.exe to "Run as administrator" (I'm on win64) but I still get the same error. What else could I try? Thank you in advance for all of the expertise.

Here is the log file, pf2odf34896.txt

lP: 3541 3541 3541
lh: 48 48 48
refl: 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00
iter_max: 11
iter_min: 10
flags: 1
P: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_P.dat
r: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_r.dat
gh: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_gh.dat
A: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_A.dat
c0: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_c0.dat
w: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_w.dat
res1: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_res1.dat
res2: C:\Users\wlepage\AppData\Local\Temp\pf2odf32674_res2.dat


-

**Comment by wlepage** [comment]
Thank you for the suggestion. I get the same error with MTEX installed in matlabroot (C:\Program Files\MATLAB\R2014b\mtex-4.3.1), as well as in my MATLAB user folder (C:\Users\wlepage\Documents\MATLAB\mtex-4.3.1). Any other ideas?

**Comment by ralfHielscher** [comment]
To everybody with problems running the precompiled binaries. Could you please post the log file? You get the name of the log file from
```matlab
getMTEXpref('logfile')
```
Please do also indicate, which version of Windows, Matlab and MTEX you are using.

I'm very sorry for your inconvenience and hope we can fix the issue soon.

Ralf.

**Comment by wlepage** [comment]
I'm running: 
Windows 7, 64 bit
MTEX 4.3.1
Matlab R2014b

Unfortunately there is no log file at the location given by `getMTEXpref('logfile')`, only the log file from the error (pf2odf34896.txt that I included previously).

**Comment by wlepage** [comment]
Also, I tried `check_mtex`, but that seems to show no problems. I would eagerly welcome any further ideas on this. 
```
>> check_mtex
checking MTEX installation
this might take some time
 
simulating pole figures
 
pf = PoleFigure  
  crystal symmetry : m-3m
  specimen symmetry: 222
 
  h = (100), r = 1 x 206 points
  h = (110), r = 1 x 206 points
  h = (111), r = 1 x 206 points
  h = (211), r = 1 x 206 points
 
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
initialize solver 
start iteration 
error: 7.6789E-002 2.5115E-002 1.2679E-002 8.3856E-003 6.6842E-003 5.6454E-003 4.9630E-003 4.3781E-003 3.9393E-003 3.5268E-003 3.2031E-003  
Finished PDF-ODF inversion. 
error: 3.2031E-003 
alpha: 9.9506E-001 9.9918E-001 1.0003E+000 9.9753E-001  
required time: 2s
ghost correction
calculate with fixed background 0.73
initialize solver 
start iteration 
error: 4.6922E-001 3.2059E-001 2.2928E-001 1.7337E-001 1.3383E-001 1.0465E-001 7.8193E-002 5.6640E-002 3.9186E-002 2.6812E-002 1.9339E-002 1.5173E-002  
Finished PDF-ODF inversion. 
error: 1.5173E-002 
alpha: 9.9186E-001 9.9595E-001 9.9731E-001 1.0020E+000  
 
rec = ODF  
  crystal symmetry : 432
  specimen symmetry: 222
 
  Uniform portion:
    weight: 0.73223
 
  Radially symmetric portion:
    kernel: de la Vallee Poussin, halfwidth 10°
    center: 150 orientations, resolution: 10°
    weight: 0.26777
 
 
check reconstruction error: 
everythink seems to be ok!
Elapsed time is 3.703923 seconds.
```

**Comment by KKrishna1** [comment]
Hi there,


Issue with: pf2odf.exe could be solved if you change this on *.m file


% create a Pole Figure variable containing the data
pdf **= loadPoleFigure(fname,h,CS,SS,'interface','uxd');

% defocussing
pf_def = loadPoleFigure(fname_def,h,CS,SS,'interface','uxd');

% correct data
pf = correct(pdf,'def',pf_def);

Thanks,

**Comment by ralfHielscher** [comment]
Hi wlepage,

I'm very surprised that ```check_mtex``` works but odf reconstruction of your sample does not work.

Could you please run (section be section) the demo
``` matlab
edit PF2ODFAmbiguity.m
```
and tell me weather the odf reconstruction works there.

If its only you example that does not work, please try to send your data and your script.

I'm very sorry about your inconvenience.

Ralf.

**Comment by 0309akash** [comment]
Hi, 
I went through  the above thread and still unable to resolve this issue. I am also facing same problem for ODF calculation. Does anyone has solution yet? I tried with both mtex 4.2.1 and 4.0.23. Here are error files.

![image](https://cloud.githubusercontent.com/assets/8506418/15208763/03117968-184b-11e6-8da8-5aaf564eb828.png)

![image](https://cloud.githubusercontent.com/assets/8506418/15208779/26de927c-184b-11e6-9e79-a5abdabf9337.png)

![image](https://cloud.githubusercontent.com/assets/8506418/15208791/3da90064-184b-11e6-964c-b36eae1a04c7.png)

Akash

**Comment by ralfHielscher** [comment]
Akash, could you please run in a terminal
```bash
ldd --version
```

**Comment by 0309akash** [comment]
![image](https://cloud.githubusercontent.com/assets/8506418/15239625/b7c7a9e8-1901-11e6-8c5f-d56a3d432ef1.png)

**Comment by ralfHielscher** [comment]
It seems that you are running MTEX on a very old Linux system. libc 2.5 is depreciated since 2006. Current version is libc 2.23. Basically you have two options:

* compile MTEX binaries yourself
* update your system or use a different system

Ralf.

**Comment by KKrishna1** [comment]
Hi Ralf, 

How to compile MTEX binaries? 

Many thanks, 
k

**Comment by kilir** [comment]
H k,
have a look here: https://mtex-toolbox.github.io/files/doc/compilation.html
Cheers,
Rüdiger

**Comment by KKrishna1** [comment]
I am having a similar issue which I had earlier. 
 
>> odf = calcODF(pf)
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
initialize solver 
Error using call_extern (line 158)
Error running external program:

 \\nask.man.ac.uk\home$\MATLAB\mtex-4.4.alpha.2\mtex-4.4.alpha.2\c\bin\win64\pf2odf.exe C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3374.txt

Error in PoleFigure/calcODF (line 145)
[c,alpha] = call_extern('pf2odf',...

here, is the log file:


initialize solver
start iteration
error: 6.6487E-002 1.1279E-002 6.4692E-003 4.7628E-003 3.8317E-003 3.2339E-003 2.8152E-003 2.5023E-003 2.2611E-003 2.0696E-003 1.9120E-003 
Finished PDF-ODF inversion.
error: 1.9120E-003
alpha: 2.3094E-001 
initialize solver
initialize solver

Thanks,

**Comment by KKrishna1** [comment]
further looking in the text file - it shows that call_extern has not used enough input arguments.

C:\Users\mbessrk2\AppData\Local\Temp\pf2odf3374.txt file:

lP: 1225 1225 1225 
lh: 12 12 36 
refl: 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 1.0000E+00 
iter_max: 11 
iter_min: 10 
flags: 1 
P: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_P.dat
r: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_r.dat
gh: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_gh.dat
A: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_A.dat
c0: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_c0.dat
w: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_w.dat
res1: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_res1.dat
res2: C:\Users\mbessrk2\AppData\Local\Temp\pf2odf2744_res2.dat


---

Hiw to fix this issue, thanks in advance, Krishn

**Comment by qzmdtc** [comment]
Hi guys! I'm running into the same problem.
I'm using matlab_2014b
               OS X EI Capitan Version 10.11.5
               mtex_4.4.alpha.2
Thanks in advance!!
>> check_mtex
checking MTEX installation
this might take some time
 
simulating pole figures
 
pf = PoleFigure (show methods, plot)
  crystal symmetry : m-3m
  specimen symmetry: 222
 
  h = (100), r = 1 x 206 points
  h = (110), r = 1 x 206 points
  h = (111), r = 1 x 206 points
  h = (211), r = 1 x 206 points
 
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
/bin/bash: line 1:  5788 Trace/BPT trap: 5       /Users/RichardQ/Documents/MATLAB/mtex-4.0.23/c/bin/maci64/pf2odf /private/tmp/pf2odf42832.txt 2>> /private/tmp/output_ZhiminsMacBookProlocal_RichardQ.log
/Users/RichardQ/Documents/MATLAB/mtex-4.0.23/c/bin/maci64/pf2odf /private/tmp/pf2odf42832.txt 2>> /private/tmp/output_ZhiminsMacBookProlocal_RichardQ.log: Trace/breakpoint trap
Error using call_extern (line 158)
Error running external program:

 /Users/RichardQ/Documents/MATLAB/mtex-4.0.23/c/bin/maci64/pf2odf /private/tmp/pf2odf42832.txt 2>>
 /private/tmp/output_ZhiminsMacBookProlocal_RichardQ.log

Error in PoleFigure/calcODF (line 139)
[c,alpha] = call_extern('pf2odf',...

Error in check_mtex (line 25)
rec = calcODF(pf) %#ok<NOPRT>
 
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to
avoid a potential name conflict. 

Besides, I got denied when I'm trying to get the log file.
Also, when I was trying to use sudo!! to give myself the permission, it asks for the password and with a key icon behind preventing me from entering the password.

**Comment by kilir** [comment]
Hi Richard,
not sure if it helps with your problem, but are you sure you are using mtex 4.4, your log says 4.023.
Not sure what you mean with a key icon, but if you use sudo in a terminal, it will most often not give you any hint on what you are typing and if you are not in the sudoers file, you should also be getting a notification about that.
Cheers,
Rüdiger

**Comment by qzmdtc** [comment]
@kilir Thank you for your reply. The things is I was trying both version and it all doesn't work and now I kinda mixed them up. Though I'm thinking maybe the problem is due to the unsuccessful compiling METX binaries, I don't have enough basic coding knowledge to support me finishing the compiling myself. Btw, is there any command that can be used to check if the binaries is successfully compiled? Thanks

**Comment by qzmdtc** [comment]
More updates,
I get this message when I'm trying to execute the libfftw3.3.dylib manually.


Last login: Mon Jun  6 10:15:46 on ttys002
Zhimins-MacBook-Pro-2:~ RichardQ$ /Users/RichardQ/Documents/MATLAB/mtex-4.4.alpha.2/c/bin/maci64/libfftw3.3.dylib ; exit;
-bash: /Users/RichardQ/Documents/MATLAB/mtex-4.4.alpha.2/c/bin/maci64/libfftw3.3.dylib: cannot execute binary file
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


Besides, I get this output when I'm trying to open the pf2odf (because I have trouble when trying to simulate ODF).

/Users/RichardQ/Documents/MATLAB/mtex-4.4.alpha.2/c/bin/maci64/pf2odf ; exit;
Zhimins-MacBook-Pro-2:~ RichardQ$ /Users/RichardQ/Documents/MATLAB/mtex-4.4.alpha.2/c/bin/maci64/pf2odf ; exit;
dyld: Library not loaded: /opt/local/lib/libfftw3.3.dylib
  Referenced from: /Users/RichardQ/Documents/MATLAB/mtex-4.4.alpha.2/c/bin/maci64/libnfft3.1.dylib
  Reason: image not found
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

So I create a path  /opt/local/lib and copied libfftw3.3.dylib into it, but it still won't work.

**Comment by zmichels** [comment]
Did you:
Disable SIP?
And install from the mtex page downloads where the binaries are already compiled?

**Comment by qzmdtc** [comment]
@zmichels 
I didn't disable SIP, wouldn't that cause some safety issue?
The toolkit is directly downloaded from the downloads page. Thanks

**Comment by zmichels** [comment]
It will inhibit the install, so you should disable for that.
My understanding is you can re-enable it afterwards (not sure if that's correct tho?), in case you are worried about some security issue. However, you'd likely need to disable every time you install a new version.

**Comment by KKrishna1** [comment]
Hey, 

It didn't work for me, even after disabling SIP.
Any other suggestions?
Thanks

**Comment by qzmdtc** [comment]
@zmichels @KKrishna1 Thx! Solved! 

@KKrishna1 Did you actually install the toolkit? The install_mtex.m file in the folder. Though it is my guessing, I originally only used startup_mtex.m because the download page said so.

**Comment by zmichels** [comment]
Hey there,
I have helped install it on some lab computers and laptops of colleagues in our lab. When I (or my colleagues) get this error, I take a step back and do three things:
1. Disable SIP
2. Make sure the download they retrieved was from this page link (rather than from the repo directly): http://mtex-toolbox.github.io/download.html
3. Make sure they're running the appropriate version of matlab.

100% of the time, these things have fixed our problems on a variety of macs. I do not mean to suggest that there aren't other troubles to be had... But that is all I know for any advice.

Best of luck and please keep us posted.
Z

**Comment by KKrishna1** [comment]
@qzmdtc
Just wondering where is the toolkit, I did not install it. Thanks

**Comment by qzmdtc** [comment]
@KKrishna1 
Download it under the download page
 http://mtex-toolbox.github.io/download.html
Unzip it and then move it to the Matlab folder. 
Run the matlab and then type install_mtex in the command window. 
Then type check_tex in the command window, you should be all set if no error message pops up.

**Comment by KKrishna1** [comment]
@qzmdtc @zmichels and ALL.Thanks, Guys. Working perfectly. Cheers!

**Comment by zmichels** [comment]
Excellent! Enjoy!
cheers,
Z
