### ISSUE TITLE
should rand(Miller) and project2FundamentalRegion(Miller) return a vector3d

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#159]
Hi Ralf,
despite the help for Miller/rand clearly says that it returns a vector3d, it also states that Miller/project2FundamentalRegion will returns a Miller again. However in both cases the result is a vector3d. 
1) Wouldn't it be more consistent for both to return a Miller? 
2) Using Miller/rand on a set of Millers located in the fundamentalRegion, the resulting vector3d will have to be projected again into that area.Is that intentional?
3) Of course discreteSample works on Miller and returns a Miller. So what is then the intention of Miller/rand?
Example:
```matlab
% generate some sample data
cs=crystalSymmetry('321')
odf=unimodalODF(orientation('Euler',[0,0,0]*degree,cs),cs)
o=discreteSample(odf,1000) 
m =o.\xvector

m = m.project2FundamentalRegion % returns a vector3d
m=Miller(m,cs) % make it a Miller again
plot(m)
m=m.rand(10) % select a subset returns vector3d
m= Miller(m,cs) % make it a Miller again
m = m.project2FundamentalRegion % returns a vector3d
m=Miller(m,cs) % make it a Miller again 
plot(m) %

m =o.\xvector % re-generate some sample data
m = m.project2FundamentalRegion % returns a vector3d
m=Miller(m,cs) % make it a Miller again
plot(discreteSample(m,10)) % that's fine
```
All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

1a) m.project2FundametalRegion should definitly return Miller

1b) Miller.rand is actually only defined for vector3d. I agree that I have to implement this for Miller as well. 

2 and 3) Miller.rand and m.discreteSample have completely different meaning.

className.rand(10,1) returns a 10x1 list of random className analogously as rand(10,1) returns a 10x1 list of random numbers.

discretSample(someList,n) takes out of someList n random entries.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
thanks for the clarification of 2/3, that makes a lot of more sense then, actually the help says so. If 1a) is something like a bug and 1b) would be a shorter version (despite it's sort of short) of  `Miller(Miller.rand(10),cs)` as a feature, I leave the issue open for now, ok?
Cheers,
Rüdiger
