### ISSUE TITLE
Problem with calcGND

### ISSUE THREAD

**Issue by ajcross89** [mtex-toolbox/mtex#164]
Dear Ralf,

Thank you for including the code to calculate GND in MTEX 4.3 - this is a very useful tool. I have a problem when I try to calculate it though.:

```matlab
ebsd = ebsd.gridify;
ebsd = ebsd('Quartz-new');
gnd = calcGND(ebsd);
```

The code above gives the following error:

```
Undefined function 'calcGND' for input arguments of type 'EBSD'.

Error in TestGND (line 45)
gnd = calcGND(ebsd);
```

This may be related to the fact that gradientX and gradientY are unknown. Trying `ebsd.gradientX `gives the following error:

```
Error using subsref
No appropriate method, property, or field 'gradientX' for class 'EBSD'.

Error in EBSD/subsref (line 32)
  [varargout{1:nargout}] = builtin('subsref',ebsd,s);
```

Kind regards,
Andrew

**Comment by ralfHielscher** [comment]
Hi Andrew,

this might appear a bit strange in MTEX right now. The point is that after
```matlab
ebsd = ebsd.gridify;
ebsd = ebsd('Quartz-new');
```
the variabe ```ebsd``` is not in a gridded form anymore - because we considered only the quartz phase. You just have to interchange the commands:
```matlab
ebsd = ebsd('Quartz-new');
ebsd = ebsd.gridify;
gnd = calcGND(ebsd)
```
I hope this helps,
Ralf

**Comment by tabassum2014** [comment]
Hi Ralf,

I am getting the error of "the above 2 symmetries doesnot match" for the previously working GND code for titanium - not sure why ?
Could I please be helped?

Thanks 
Regards 
Tabassum
