### ISSUE TITLE
memory considerations using grain2d/merge

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#167]
Hi Ralf,
if it comes to merging grains in maps with many grains (e.g. 100000+), it happens that Matlab announces that I'll be running out of memory trying to do the A=full(A + A.') (line 36 in merge.m).

Is it really necessary to convert to a full matrix? Replacing the line with A = A + A.' actually worked for me and I could not see any difference, comparing the merges of a sufficiently small map.
Could there anything else be going wrong? If not, maybe it's an option to skip the conversion to full.

All the best,
Rüdiger

**Comment by kilir** [comment]
Hi Ralf,
with the fix, the function still needs the varargin, otherwise I'll get:

>> [grains_merged,parentID_grains]= merge(grains,twinb);
Attempt to execute SCRIPT varargin as a function:
/Applications/MATLAB_R2015b.app/toolbox/matlab/lang/varargin.m

Error in grain2d/merge (line 95)
if check_option(varargin,'calcMeanOrientation')



Cheers,
 Rüdiger

**Comment by ralfHielscher** [comment]
You are right. That was a stupid mistake.

Ralf.

**Comment by kilir** [comment]
Anyhow, now it works and that's great and merging a large number of grains works without needing 20+ gigs of ram. Maybe it's worth mentioning the 'calcMeanOrientation' in the help of merge, in the case someone wonders why by default meanOrientation will not be calculated anymore.
All the best,
Rüdiger
