### ISSUE TITLE
bug: saveFigure and placement of 'minmax'

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#168]
Hi Ralf,
I get a frequently misplaced 'max' value in pdf or ipf plots when saved with saveFigure in a raster format.
Turns out that when changing the scaling in export_fig [(https://github.com/mtex-toolbox/mtex/blob/master/plotting/saveFigure.m#L75)] from -m1.5 to -m2, the offset increases, while with -m1 (or without the option), the figure is saved correctly.
This is the -m1.5 setting:
![test_original1 5](https://cloud.githubusercontent.com/assets/11697557/13987520/3a6b3558-f108-11e5-8ea6-8b04f76d7863.jpg)

This is figure saved with -m2 :
![test_m2](https://cloud.githubusercontent.com/assets/11697557/13987539/4f32b056-f108-11e5-9cb5-5d655058367b.jpg)

and it look correct after setting -m1 / or deleting the option :-1
![test_m1](https://cloud.githubusercontent.com/assets/11697557/13987565/75011f34-f108-11e5-8730-68937d6c020e.jpg)

This happen on OSX 10.9 with Matlab 2013a, 2015b but the problem does not appear under Debian Jessie, Matlab 2015b, nor Arch, Matlab 2014b. On OSX running a high dpi display, the value needs to roughly 2.2 to find the max value at all in the saved figure.

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
So many strange things. I'm afraid there is nothing I can do.

**Comment by kilir** [comment]
Indeed it's strange and I know that export_fig is not your playground. It also seems to depend on the display resolution and the display resolution that Matlab thinks it's running on. 
Apparently not so many people complained about it, so it doesn't seem to affect too many users. However, it might be worth keeping in mind that the export_fig -m option has an influence on the placement of the Max:  in the final rater image; just in case somebody else complaining..
All the best,
Rüdiger
