### ISSUE TITLE
MTEX 4.3.1 and 4.4.alpha.2 is not working : Function with same name

### ISSUE THREAD

**Issue by ThomasChauve** [mtex-toolbox/mtex#171]
Dear Ralf

I've got an issue using both MTEX 4.3.1 and 4.4.alpha.2. Hence I cannot use it. I saw that Dave Mainprice has the same issue (https://groups.google.com/forum/?fromgroups=#!topic/mtexmail/XrzzLODAc8k).

I have no probleme with MTEX 4.2.1 but I am interesting to look at GND calculation.

I using Matlab2014b on Debian 8.

I put error message for both MTEX 4.3.1 and 4.4.alpha.2 and the result of plot(ebsd) which give me an error. For both test, I used a clean setpath with just MTEX inside.

All the best
Thomas Chauve

**MTEX 4.3.1**
`
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup at 4
  In matlabrc at 225 
initialize MTEX 4.3.1  .Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup_mtex>addpath_recurse at 321
  In startup_mtex>setMTEXPath at 134
  In startup_mtex at 58
  In startup at 7
  In matlabrc at 225 
...Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In check_installation>check_mex at 118
  In check_installation at 21
  In startup_mtex at 74
  In startup at 7
  In MTEX 4.3.1 (shomentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX`

`
>> plot(ebsd)
Error using isgraphics (line 3)
Not enough input arguments.

Error in labelcheck>local_validlabelobj (line 31)
if isscalar(obj) && ...

Error in labelcheck (line 10)
if (nargs > 0) && (numel(args{1}) == 1) &&
local_validlabelobj(args{1},propname)

Error in xlabel (line 20)
[ax,args,nargs] = labelcheck('XLabel',varargin);

Error in mapPlot (line 65)
        xlabel(ax,'x','visible','off')

Error in newMapPlot (line 18)
    mP = mapPlot(ax,varargin{:});

Error in EBSD/plot (line 30)
mP = newMapPlot('scanUnit',ebsd.scanUnit,'parent',mtexFig.gca,varargin{:});
 `

**MTEX 4.4.alpha2**
`
   Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
   Warning: Function disp has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
   Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
   Warning: Function disp has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
   Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup at 4
  In matlabrc at 225 
Warning: Function disp has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup at 4
  In matlabrc at 225 
initialize  MTEX 4.4.alpha.2  .Warning: Function disp has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup_mtex>addpath_recurse at 321
  In startup_mtex>setMTEXPath at 134
  In startup_mtex at 58
  In startup at 7
  In matlabrc at 225 
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In startup_mtex>addpath_recurse at 321
  In startup_mtex>setMTEXPath at 134
  In startup_mtex at 58
  In startup at 7
  In matlabrc at 225 
...Warning: Function disp has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In check_installation>check_mex at 118
  In check_installation at 21
  In startup_mtex at 74
  In startup at 7
  In matlabrc at 225 
Warning: Function isgraphics has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
> In path at 109
  In addpath at 86
  In check_installation>check_mex at 118
  In check_installation at 21
  In startup_mtex at 74
  In startup at 7
  In pmat(A,M) or re,M,N) where M or N is an empty array will return an error in a future release. Replace empty array inputs with 1 instead.
> In disp at 10
  In MTEXmenu at 4
  In startup_mtex at 85
  In startup at 7
  In matlabrc at 225  
   MTEX 4.4.alpha.2 (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
`

`
>> plot(ebsd)
Error using isgraphics (line 3)
Not enough input arguments.

Error in labelcheck>local_validlabelobj (line 31)
if isscalar(obj) && ...

Error in labelcheck (line 10)
if (nargs > 0) && (numel(args{1}) == 1) &&
local_validlabelobj(args{1},propname)

Error in xlabel (line 20)
[ax,args,nargs] = labelcheck('XLabel',varargin);

Error in mapPlot (line 65)
        xlabel(ax,'x','visible','off')

Error in newMapPlot (line 18)
    mP = mapPlot(ax,varargin{:});

Error in EBSD/plot (line 30)
mP =
newMapPlot('scanUnit',ebsd.scanUnit,'parent',mtexFig.gca,varargin{:});
 `

**Comment by ralfHielscher** [comment]
Could you please check line 130 of the file ```mtex/startup_mtex```

According to your matlab version the condition should be true and line 131 should be executed. 

You could also replace ```MATLABverLessThan('8.1')``` by 
```verLessThan('matlab','8.1')``` and please post the result of the last command.

Ralf.

**Comment by ThomasChauve** [comment]
I replaced `MATLABverLessThan('8.1')` by `verLessThan('matlab','8.1')`

Line 131 seem to be run, but I still have the same error (see screenshot, red line)
This is for both 3.3.1 and 4.4.alpha2.

Thomas
![mtexerror](https://cloud.githubusercontent.com/assets/9338747/14310158/c71ca1a2-fbe0-11e5-991d-b6050a02d30f.png)

**Comment by ralfHielscher** [comment]
Maybe the problem was, that you added the mtex path with all subdirectories to the search path. This you should not do. startup_mtex takes care that the correct subdirectories are added to the matlab search path.

Ralf.

**Comment by ThomasChauve** [comment]
Yes it was this. I create new path with only mtex directory.
It works fine for MTEX 4.3.1
![mtex4 3 1](https://cloud.githubusercontent.com/assets/9338747/14375992/0f2ed39e-fd66-11e5-94bd-36ecbf89ce46.png)

But I still have warning for MTEX 4.4.alpha2
![mtex4 4 alpha2](https://cloud.githubusercontent.com/assets/9338747/14376021/3154fb60-fd66-11e5-96ad-10e09a629cc2.png)

Thanks
Thomas

**Comment by ralfHielscher** [comment]
I know about these warnings. You should be fine ignoring them.

Ralf.

**Comment by ThomasChauve** [comment]
OK thanks a lot

Thomas
