### ISSUE TITLE
code to get integral values

### ISSUE THREAD

**Issue by KKrishna1** [mtex-toolbox/mtex#174]
Hi all, 

Please help me if any code exists which can be used to get information on the followings,  

How to get the value of Intergrals of  I(phi)_sin^3(phi)_d(phi) and I(phi)_cos^2(phi)_sin(phi)*d(phi), between the limits of 0 and pi/2, using pole figure.

Thanks in advance.

**Comment by ralfHielscher** [comment]
Could you please explain more in detail, what are your input data and what do you want to compute?

**Comment by KKrishna1** [comment]
Hi RH, 

I need to calculate anisotropy factor. 

Using the ratio of two integrals,

Numerator: Intergarl of [I(phi) sin^3(phi)d(phi)] (limits 0 to pi/2)
denominator: integral of [I(phi)cos^2(phi) sin(phi) d(phi)] (limits 0 to pi/2)

I = Intenity and phi = azumulthal angle

Using the pole figure (0002) these data can be calculated, pole figure for (0002) intensity and phi as an azumuthal angle will be input to calculate the above ratio. 

Thanks
