### ISSUE TITLE
how to remove error message 

### ISSUE THREAD

**Issue by KKrishna1** [mtex-toolbox/mtex#175]
Hi there, 

How to remove this error message:

```matlab
if nargin<2,
    error(message('stats:pdf:TooFewInputs'));
end

if ischar(name)
    name = internal.stats.getDistributionName(name);
else
    error(message('stats:pdf:BadDistribution'));
end

function value = getMTEXpref(pref,default)

group = getappdata(0,'mtex');

if nargin == 0

  value = group;
  
elseif isfield(group,pref)
  
  value = group.(pref);
  
else
  
  value = default;
  
end

end
```

Many thanks

**Comment by ralfHielscher** [comment]
When does this error occur? After which command. What is the error message?

**Comment by KKrishna1** [comment]
HI RH, 

Using Matlab2015a and Mtex 4.3.1
That happens after plot(pdf) command:
>> plot(pdf)
Error using pdf (line 51)
Requires at least two input arguments.

-------- error message:
if nargin<2,
    error(message('stats:pdf:TooFewInputs')); (line 51)
end

if ischar(name)
    name = internal.stats.getDistributionName(name);
else
    error(message('stats:pdf:BadDistribution'));
end

**Comment by ralfHielscher** [comment]
Hi Krishna,

```pdf``` is not an MTEX command.

Ralf.

**Comment by KKrishna1** [comment]
ok, Thanks Ralf, it was a great help.
