### ISSUE TITLE
reconstructed pole figure data

### ISSUE THREAD

**Issue by KKrishna1** [mtex-toolbox/mtex#176]
HI RH, 

I need reconstructed pole figure data (Intensity versus tilt angle) from ODF (not the raw data which used to produce ODF). can you please help me how to get this?

Many thanks

**Comment by ralfHielscher** [comment]
Hi Krishna,

you can compute the pole density function from an ODF ```odf``` by
```matlab
h = Miller(1,0,0,odf.CS)
r = vector3d('polar',20*degree,30*degree);
odf.calcPDF(h,r)
```
where ```h``` is the crystal direction and ```r``` is the specimen direction. The specimen direction has been specified in polar coordinates, where the first angle (20*degree) is the polar angle (maybe your tilde angle) and the second angle (30*degree) is the azimuth.

I hope this helps,
Ralf.
