### ISSUE TITLE
Possible BUG in Fundamental Region (oR orientationRegion)

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#177]
This is simple example below
```matlab
%% Specify Crystal and Specimen Symmetries
% crystal symmetry (proper rotations with point groups 121 and 222)
CS_Enstatite = crystalSymmetry('222', [18.2406 8.8302 5.1852], 'mineral', 'Enstatite')
CS_Clinoenstatite =  crystalSymmetry('121', [9.62 8.825 5.188], [90,71.67,90]*degree, 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Clinoenstatite')
%% Fundamental Region
oR = fundamentalRegion(CS_Enstatite,CS_Clinoenstatite);
FR_max_angle = oR.maxAngle/degree
FR_min_angle = oR.minAngle/degree

FR_max_angle = 120.0000
FR_min_angle = 90
```
I think the minimum angle should always be zero ? May be there are exceptions ?

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

```minAngle``` is *not* the minimum angle orientation in the fundamental region - this is of course 0. It is the angle until which all axes are still possible, i.e., the first special point in the angle distribution or smallest angle such the axisdistribution in not constant. Maybe this should be better documented.

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

Thanks for the additional information. So the present example orthorhombic - monoclinic crystal symmetry the minAngle = 90 and maxAngle =120 the minAngle of 90 is also the peak in misorientation angle histogram fro uniform distribution and the ‘highest' angle for a complete coverage of fundamental region by the misorientation axes , above 90 the the fundamental region shrinks to eventually to single point at an angle of 120 degrees. I guess we need some graphics to show these points.

all the best David

**Comment by ralfHielscher** [comment]
exactly.
