### ISSUE TITLE
calc

### ISSUE THREAD

**Issue by jerabekp** [mtex-toolbox/mtex#1771]
**What code do you use?**
```
MSodf=calcDensity(ebsdcor('Muscovite').orientations,'halfwidth',10*degree);

figure, plotPDF(MSodf,Miller(0,0,1,CS{3}),'antipodal','minmax')%'grid','grid_res',10*degree,)
hold all
plotPDF(ebsdcor('Muscovite').orientations,Miller(0,0,1,CS{3}),'antipodal',...
    'MarkerSize',2,'MarkerColor','black')
hold off  
```
**What result do you get**
see attached picture
**What result do you expect**
odf maximum is perpendicular to distribution of the points, it worked with the previous versions

**What MTEX version do you use?**
5.9
![wrong_odf](https://user-images.githubusercontent.com/128160916/225934451-89aa2662-4283-44fd-a54c-829277a0c9c1.png)

**Comment by kilir** [comment]
Hi Petr,
any chance that in the center of your plot, this single black point is actually many many points at the same position?
You cou check by inspecting the orientations?
Cheers,
Rüdiger

**Comment by jerabekp** [comment]
Hi Rudiger,
Sorry, I have done a stupid mistake by assigning the nonindexed data to the 'Muscovite' phase. This created the strange and very intense maximum of ODF in the center of the pole figure. I will now close the issue. Apologies!
Cheers
Petr
