### ISSUE TITLE
Issue with discreteSample in MTEX 5.9

### ISSUE THREAD

**Issue by MarcoWitte1** [mtex-toolbox/mtex#1779]
**What do you want to do?**
Calculate discrete orientation sample from ODF

**What data do you have?**
odf = SO3FunRBF (m-3m → xyz (-1))
 
  uniform component
  weight: 0.11
 
  multimodal components
  kernel: de la Vallee Poussin, halfwidth 3.5°
  center: 14323 orientations, resolution: 3.5°
  weight: 0.89

**What code do you use?**
dis = odf.discreteSample(1000);

**What result do you get**
Error message

**What result do you expect**
No error

**Error Message**
If you get an error message copy and paste it below
```
Arrays have incompatible sizes for this operation.

Error in  .*  (line 33)
  q.a = a1 .* a2 - b1 .* b2 - c1 .* c2 - d1 .* d2;

Error in  .*  (line 23)
  r = times@quaternion(a,b,varargin{:});

Error in  .*  (line 37)
r = times@rotation(a,b,isa(b,'orientation'));

Error in SO3FunRBF/discreteSample (line 40)
ori = ori .* SO3F.CS.rot(randi(SO3F.CS.numSym,npoints,1));

Related documentation
```
**What MTEX version do you use?**
5.9
[odf.zip](https://github.com/mtex-toolbox/mtex/files/11061032/odf.zip)

Cheers,
Marco

**Comment by ralfHielscher** [comment]
Hi Marco,

thank you for pointing out this bug. I have fixed it in the developer version.

Ralf.
