### ISSUE TITLE
Gaps in plots of gridified data imported from .ctf

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#178]
Using MTEX 4.3.1 with Matlab R2016a, and importing data from .ctf, if the data is gridified and then plotted inevitably there are gaps in the plot which seem to get worse as the aspect ratio between X and Y increases.  So a long thin map looks like the attached. Plots from the non-gridified data look fine.

![w30anl5bgnd](https://cloud.githubusercontent.com/assets/16214025/14944455/4c330d42-0fc1-11e6-8316-d52575db307e.jpg)

**Comment by ralfHielscher** [comment]
May it be the case that you had ebsd data with a hexagonal grid? For those data ```gridify``` is not yet supported.

Ralf.

**Comment by jhiscocks** [comment]
I think I've found the source;  It's not hexagonal grid data for sure (our system can't do that).  The issue is something to do with how bruker exports ebsd maps to .ctf format- the x and y grid spacing in the file header have 10 significant digits but the coordinates associated with each measurement only have 4.  I expect there's some sort of rounding error/rollover of digits resulting in little gaps in the 'grid' on which data is acquired.

When I re-numbered the coordinates of the data and made it identical to a multiple of the header x and y grid interval the gaps went away.

So I guess the problem is solved; it's an issue with the Bruker software, and I have to fix all the coordinates.  I'm just surprised that this isn't an issue with the raw ebsd data. and only in one dimension.

Thank you for your help, Jessica
