### ISSUE TITLE
setting parent axes with plotPDF and orientations

### ISSUE THREAD

**Issue by cthissen** [mtex-toolbox/mtex#180]
Hi Ralf, 

I'm having trouble using the parent property when plotting pole figures of orientation classes. When I try to plot the pole figures, the axes remain empty. Everything works fine when I plot odf classes this way. Here's my minimum working example:

```
cs = crystalSymmetry('mmm');
odf = uniformODF(cs);
nPoints = 500;
ori = discreteSample(odf,nPoints);
h(1) = Miller(1,0,0,cs);

hFig(1) = figure(1);
hAx(1) = axes;
plotPDF(ori,h(1),'parent',hAx(1))
```

**Comment by ralfHielscher** [comment]
Hi,

thank you for reporting this bug. I will fix this soon.

Ralf.

**Comment by ralfHielscher** [comment]
Would you mind checking the fix?

Ralf

**Comment by cthissen** [comment]
Hi Ralf, 

Yes - that seems to have fixed the bug. The latest branch under ralfHielscher/mtex has the updated code, but the fix hasn't been pulled to the mtex-toolbox/mtex branch yet. 

Thanks!
Chris
