### ISSUE TITLE
Possible bug with combining ODFs

### ISSUE THREAD

**Issue by breedlun** [mtex-toolbox/mtex#181]
I am trying to combine several similar ODFs into a single average ODF.  The trouble is the pole figures from the `avg_odf` (average ODF) are identical to the pole figures from `odfs{1}` (the first ODF I combined).  Somehow the average operation is not working as expected.  Here is my code:
```matlab
% crystal symmetry
CS = crystalSymmetry('m-3m', [3.592 3.592 3.592], 'mineral', 'Iron', 'color', 'light blue');
    
% Specify Miller Indices
h = { ...
Miller(1,1,1,CS),...
Miller(2,0,0,CS),...
Miller(2,2,0,CS)};
    
% Load individual sample odfs
ID_list = {'sample_02', 'sample_03'};
I = length(ID_list);
odfs = cell(I,1);
for i = 1:I
    sID = ID_list{1};
    saved_data = load([sID, '-austenite-mtex_odf']);
    odfs{i} = saved_data.odf;
end

% Average them into a single average odf
avg_odf = odfs{1}/2.0 + odfs{2}/2.0;
    
%Plot the results
figure;
plotPDF(odfs{1}, h, 'colorrange', [0,12]);
mtexColorbar;
figure;
plotPDF(odfs{2}, h, 'colorrange', [0,12]);
mtexColorbar;
figure;
plotPDF(avg_odf, h, 'colorrange', [0,12]);
mtexColorbar;
```
I have had success combining ODFs when I generate the ODFs using `unimodalODF` and `fiberODF`, which makes me think I am doing something right.  I only run into trouble when I use my experimental data, which should be attached to this post.

I have just started using mtex, so I apologize if this is just user error, and not a bug.  

[experimental_data.zip](https://github.com/mtex-toolbox/mtex/files/287560/experimental_data.zip)

**Comment by ralfHielscher** [comment]
Hi Bredlun,

I just tested this with your data and the result looked fine to me. See below: odf1, odf2, odf1 + odf2

Ralf.

![odf1](https://cloud.githubusercontent.com/assets/8619241/15625403/e845e99a-24a5-11e6-9af7-8fbd95f15d3d.png)
![odf2](https://cloud.githubusercontent.com/assets/8619241/15625402/e84563e4-24a5-11e6-8b7e-4f414fa9211b.png)
![odf3](https://cloud.githubusercontent.com/assets/8619241/15625404/e84840fa-24a5-11e6-9a1e-c44a3fb77b70.png)

**Comment by breedlun** [comment]
Strange!  I will retest as soon as I get a chance.

**Comment by breedlun** [comment]
First, I updated the code I posted above to include the crystal symmetry.  

Second, I reran the code I posted above, and got the same result.  The pole figures for odf1, odf2, and 0.5*odf1 + 0.5*odf2 are identical.  

I will keep playing around with this.  In case it matters, I am on MATLAB R2014b.

**Comment by breedlun** [comment]
I just found the error in my code.  I had

    for i = 1:I
        sID = ID_list{1};
        saved_data = load([sID, '-austenite-mtex_odf']);
        odfs{i} = saved_data.odf;
    end

when I should have had

    for i = 1:I
        sID = ID_list{i};
        saved_data = load([sID, '-austenite-mtex_odf']);
        odfs{i} = saved_data.odf;
    end

Everything works as expected now.  I apologize for wasting your time.
