### ISSUE TITLE
Using on-line MTEX help - how search the help ?

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#182]
It has been suggested that we use the on-line help when we have problems installing help in the MATLAB environment. I think this is a good idea, but I wonder if we can search the on-line help, so far I did not find a search window.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

this is true. I'm not an expert in this field and have no idea how to make an online help searchable. Maybe somebody else can help here?

Ralf.
