### ISSUE TITLE
plotAngleDistribution on non uniform ODF

### ISSUE THREAD

**Issue by ThomasChauve** [mtex-toolbox/mtex#1822]
**What do you want to do?**
I want to compute `plotAngleDistribution` on an non uniform ODF but it seems that the result is false.

**What data do you have?**
I build ODF using custom function buildODF

**What code do you use?**

```matlab
CS = crystalSymmetry('6/mmm', [4.51 4.51 7.34], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Ice-Ih', 'color', 'light blue');

odf = fibreODF(Miller(0,0,0,1,CS),yvector,'halfwidth',5*degree);

figure;
plotAngleDistribution(odf)

ori=odf.discreteSample(20000);

for i=1:9999
    i
    clc
    mk(i)=angle(ori(i*2),ori(i*2+1));
end

figure;
[counts,centers]=hist(mk);
plot(centers*180/pi,counts,LineWidth=2)
xlim([0,100])
```

**What result do you get**
 I compare a list of angle computed using `angle` function on 2 orientations obtained using  `odf.discreteSample`  to `plotAngleDistribution(odf)` The results does not match.

![image](https://github.com/mtex-toolbox/mtex/assets/9338747/7e71585c-2aff-486a-96cf-b01050a0d658)

**What result do you expect**
That both figures are similar.

**Error Message**
none

**Comment**

- I have the good behavior when I use an uniform ODF : `odf=uniformODF(CS)`
- I have other more complex ODF where it does not work either.

**What MTEX version do you use?**
MTEX 5.9.0
Matlab R2021a

I also tried with MTEX 5.8.2 : same result.

**Comment by kilir** [comment]
Hi Thomas,
you are comparing the angle distribution of an odf to the misorientation angle distribution, that's two different things. You probaly should use an mdf.
```
CS = crystalSymmetry('6/mmm', [4.51 4.51 7.34], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Ice-Ih', 'color', 'light blue');
odf = fibreODF(Miller(0,0,0,1,CS),yvector,'halfwidth',5*degree);
mdf = calcMDF(odf)

plotAngleDistribution(mdf)

ori=odf.discreteSample(1000);
mk = angle_outer(ori);

% mori=mdf.discreteSample(100000);
% mk = mori.angle;

figure;
[counts,centers]=hist(mk(:),72);
plot(centers*180/pi,counts,LineWidth=2)
xlim([0,100])
```
Cheers,
Rüdiger

**Comment by ThomasChauve** [comment]
Hi Rüdiger

Thanks for the quick fix. I haven't use MTEX for a while and I didn't recall `mdf` the last time used it.
Therfore I don't  really understand what does `plotAngleDistribution(odf)` . It is just out of curiosity.

Anyway thanks for fix.
Best
Thomas

**Comment by kilir** [comment]
Hi Thomas,
the angle of an orientation would correspond to the axis-angle representation, the same applies to an odf, which is what 
`plotAngleDistribution(odf)` does. Often this makes sense for misorientations but in many cases not really for orientations.
Cheers,
Rüdiger
