### ISSUE TITLE
calcParent2Child gives an error in develop

### ISSUE THREAD

**Issue by nyyssont** [mtex-toolbox/mtex#1835]
The latest develop seems to have an issue with calcParent2Child.

When I run the help file "maParentGrainReconstruction.m", I get the following error message:

![image](https://github.com/mtex-toolbox/mtex/assets/10060198/5335cbf9-17bb-4587-a646-25f0c1f6f706)

**Comment by nyyssont** [comment]
Replacing "project2FRCS2_ref.m" with the version from MTEX 5.9.0 resolves the issue.

**Comment by ralfHielscher** [comment]
Hi Tuomo, I think its resolved right now.

Ralf.

**Comment by nyyssont** [comment]
Yep. This can be closed.
