### ISSUE TITLE
b-axis points towards east introduced in MTEX 4.3

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#184]
Can we have ```setMTEXpref('a-axis to east',true)``` or ```setMTEXpref('b-axis to east',false)``` as many of us have large number of scripts with old convention. If we run them with MTEX 4.3 or latter all the plots have labelling problems and we have re-write the scripts.  

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

I understand this issue and I will try to implement this.

Ralf.
