### ISSUE TITLE
Misorientation angles above 180° in triclinic minerals

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#186]
I have run a series of test with plagioclase feldspar using MTEX 4.4.alpha.2 and Matlab R2016a, the latest versions of both softwares.

However the bug for triclinic minerals with misorientation angles greater than 180° is still present, such as 296 degrees in one example, suggesting the scale is 0 to 360 degrees. Matlab R2016a corrects certain plotting errors. So the bug is rather in MTEX.

This bug causes the following problems;
a) Causes errors in EBSD map plot of boundaries colored by value of misorientation angle with angles on the colour bar greater than 180 degrees.
b) Misorientation angle histograms plotted the Matlab 'hist' command are in error. However using the MTEX 'plotAngleDistribution' command wraps the angles between 0 and 180 degrees, but is really correct ?
c) twin detection or identification specific boundaries using misorientation axis and angle are likely to be in error.

I have reported these errors before, but as I noticed the MTEX 'plotAngleDistribution'  apparently gives the angles between 0 and 180 degrees the MTEX users may have not noticed this problem for triclinic minerals.

Alternatively this is new definition of misorientation angle !

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

do you have a simple example on that?

Ralf.

**Comment by ralfHielscher** [comment]
I think I found the bug.

Ralf.
