### ISSUE TITLE
halfQuadraticFilter not smoothing?

### ISSUE THREAD

**Issue by vedadb** [mtex-toolbox/mtex#1869]
-	Having applied the filter on the same EBSD maps several times, sometimes it filters and sometimes not: 
o	Can not reproduce conditions for either case
o	The success of the smoothing is here quantified by the mean KAM over the EBSD map

-	In the following I show:
o	Comparison between KAM maps of the largest grain of two EBSD samples (no. 1 and 11, see below) with no filtering, hQF and spline filter on.
o	This effect was first noticed on full maps but is here illustrated on single grains
o	A summary over 11 EBSD maps comparing no, hQF, and spline filtering; all other filters (mean, median, Kuwahara, etc.) have been checked that they also smooth the data but are not included here.

-	Attached with the document is a .zip file containing the @EBSD map of the single largest grain, without filtering, from two samples (No.1 and No.11) and a script file to reproduce the figures:
o	no1_largest_grain.mat & no11_largest_grain
o	first cell in issues_script.m
[hQF_issues.zip](https://github.com/mtex-toolbox/mtex/files/11745942/hQF_issues.zip)

1a. Summary

Figure 1. Mean KAM plotted for 11 samples without filtering, with hQF (F.alpha=1) or with spline filtering. Samples 1 to 5 and 10 show no effect of smoothing by hQF, while all KAM-values are lowered upon spline filtering (smoothed orientation maps)
 
![image](https://github.com/mtex-toolbox/mtex/assets/8612076/7e0695df-f368-460a-b91d-a4c6a34c1637)

1b. Specific KAM maps

 
![image](https://github.com/mtex-toolbox/mtex/assets/8612076/e31f91f4-8d0a-4dbf-9cbe-3fc4bc3b6879)

Figure 2. Comparison between filtering methods on the KAM maps for Sample 1 and 11. Sample 1 hQF is obviously not being smoothed properly.

**Comment by kilir** [comment]
Hi,
what alpha parameter do you use? The default doesn't do a lot. in the current version, values are NOT normalized to be in the range [0 ,1] and maybe something around 100-300 should give reasonable results.
Cheers,
Rüdiger

**Comment by kilir** [comment]
Hi,
this was an issue for some input data, fixed here fb40dea, so e.g. using 
 `ebsd.quality = ebsd.quality ./ max(ebsd.quality(:))`
should correct the input and reasonably small alpha values should work again. 
Cheers,
Rüdiger

**Comment by vedadb** [comment]
Hi,
thank you, that fixed it. For one of the grains I needed an alpha of 10000 to reach similar smoothing result as alpha = 1 for the other, now they are normalized. 

Vedad
