### ISSUE TITLE
Error in PoleFigure/union in 4.3.1

### ISSUE THREAD

**Issue by cochranec** [mtex-toolbox/mtex#187]
There is an error in mtex/PoleFigureAnalysis/@PoleFigure/union.m in 4.3.1.

Attempting to use the function results in the following error:

```
Undefined function or variable 'u'.

Error in PoleFigure/union (line 40)
u
```

Simply removing/commenting out this line of code will fix this error.

**Comment by ralfHielscher** [comment]
thank you for reporting this.

Ralf.
