### ISSUE TITLE
Is there way to have annotation for specific pole figure in plot with 3 poles figures ?

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#190]
I think we used to have this feature, and the documentation you find IPFs under title 
"One can also mark specific orientations in pole figures or in inverse pole figures"
but I cannot see any specific commands to chose which IPF is annotated with mod1 and mod2
except order of execution

``` matlab
plotIPDF(...
mtexColorMap(...
annotate( mod1...)
annotate( mod2...)
drawNow
```

with pole figures it does not seem to work.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

by default all are annotated.

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

If you use modes calculated from the ODF, in this case using 3 modes of highest peaks in the ODF, MTEX manages to plot only on the peaks of each pole figure using 

annotate(modes,'Marker','s','MarkerFaceColor','r','MarkerEdgeColor','w','MarkerSize',15)




Clear MTEX adjusts the annotation to fit each pole figure.

If I calculate the vectors in the pole figures for the 3 crystal directions using 3 orientations of modes, I can reproduce the results, but I cannot avoid putting the same information on the all pole figures.






The maxima are red in the first pole figure , green in the second and blue in third pole figure.

all the best David
