### ISSUE TITLE
Bug in SO3FunHarmonic/max 

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#1967]
I have a set of misorientations, computing an mdf works fine, however, if computed below a certain halfwith, max() returns something non-sensical.
Since I cannot reproduce it with synthetic data, real data is attached below.

```matlab
load('badmoris.mat')

%% getting the max of an mdf
mdf = calcDensity(bad_moris,'halfwidth',8*degree) % that works fine

plot(mdf,'contourf','axisAngle')

[~,mmori]=max(mdf)

hold on
plot(mmori,'MarkerFaceColor','r','axisAngle','MarkerSize',20 )
hold off


%% same for smaller halfwidth
mdf = calcDensity(bad_moris,'halfwidth',5*degree) % that is not fine

plot(mdf,'contourf','axisAngle')

[~,mmori]=max(mdf)

hold on
plot(mmori,'MarkerFaceColor','r','axisAngle','MarkerSize',20 )
hold off
```

Ok
<img width="330" alt="ok" src="https://github.com/mtex-toolbox/mtex/assets/11697557/3a9380f2-82ca-4725-8646-4273ad55d8d0">

not OK
<img width="332" alt="not_ok" src="https://github.com/mtex-toolbox/mtex/assets/11697557/4f2c6d40-8806-453d-a245-490572dbe2c3">

[badmoris.mat.zip](https://github.com/mtex-toolbox/mtex/files/12750992/badmoris.mat.zip)

**Comment by ralfHielscher** [comment]
This is a problem in geometry/@symmetry/fundamentalRegionEuler.m which return a far to small region for angle phi2.
@num3RIK can you have a look at this.

Ralf.

**Comment by num3RIK** [comment]
There occurred a problem by computation of the fundamental sector of equispacedSO3Grid.
Now it should work.

**Comment by kilir** [comment]
Works perfectly!
