### ISSUE TITLE
calculating schmid factor

### ISSUE THREAD

**Issue by mmarteleur** [mtex-toolbox/mtex#197]
Hi everyone, 

I tried to calculate the Schmid factor of the following system in cubic symmetry (233)[-311] and I get values of SF higher than 0.5. I followed the toturial for each step (and even redo it entirely to be sure that my installation was correct) but it doesn't work... 

Can anybody help me ??
Thanks

**Comment by ralfHielscher** [comment]
Maybe you can post the code you have used?

Thanks,

Ralf.

**Comment by mmarteleur** [comment]
Ok so here it comes :

CS = crystalSymmetry('cubic',[3.265,3.265,3.265],'mineral','Ti12Mo')
m = Miller(2,3,3,CS)
n = Miller(-3,1,1,CS)
r = vector3d(3,-6,4)
tau = dot(m,r) * dot(n,r)

it gives me the following :

tau =

    9.484293637375451e-001

**Comment by mmarteleur** [comment]
whatever the r vector I am using, I get weird values of schmid factor...

**Comment by ralfHielscher** [comment]
The reason is that you have to use normalized vectors, i.e.,
```matlab
tau = dot(m.normalize,r.normalize) * dot(n.normalize,r.normalize)
```
alternatively, you can use
```matlab
tau = cos(angle(m,r) * cos(angle(n,r))
```
The best solution would probably to use MTEX funftionality
```matlab
sS = slipSystem(Miller(2,3,3,CS),Miller(-3,1,1,CS))
tau = sS.SchmidFactor(r)
```
Ralf.

**Comment by mmarteleur** [comment]
Thank you very much ! I am quite a newbie in MatLab...

**Comment by mmarteleur** [comment]
I still get the same tau value as before with the 2 first possibilities, and for the third one I get the following error : 
sS = slipSystem(Miller(2,3,3,CS),Miller(-3,1,1,CS))
??? Undefined function or method 'slipSystem' for input arguments of type 'Miller'.

Is there something wrong with the installation ? I am using MatLab 7.10.0 (R2010a)

**Comment by ralfHielscher** [comment]
Sorry,

the last line works only for MTEX 4.4.
the above you have to modify to
```matlab
tau = cos(angle(m,r,'noSymmetry') * cos(angle(n,r,'noSymmetry'))
```
