### ISSUE TITLE
MTEX error message: Error running NFFT with openMP in MTEX 5.10.2

### ISSUE THREAD

**Issue by Phoenix21-root** [mtex-toolbox/mtex#1970]
**What do you want to do?**
Installing MTEX 5.10.2 in MATLAB_R2023b (M1 Silicon Chips MacOS 14.0)

**Error Message**
If you get an error message copy and paste it below
```
********************************************************************************
 
  MTEX: Error running NFFT with openMP - I'm going to try it without openmp!
 
  MTEX: Error running NFFT without openMP!
   
 I did not get NFFT working. This restricts the functionality of MTEX.
 To overcome this restriction you may need to compile the NFFT your own.
 Please have a look at https://mtex-toolbox.github.io/installation for possible workarounds
 or ask in the forum https://github.com/mtex-toolbox/mtex/discussions for help.
 
  The original error message was:
 
Undefined function 'nfsftmex' for input arguments of type 'char'.

Error in S2FunHarmonic.quadrature (line 77)
  nfsftmex('precompute', bw, 1000, 1, 0);

Error in check_installation>check_NFSFT (line 83)
  sF = S2FunHarmonic.quadrature(f,'bandwidth',12);

Error in check_installation (line 53)
  check_NFSFT

Error in startup_mtex (line 69)
check_installation;

Error in install_mtex (line 13)
  startup_mtex('noMenu')
********************************************************************************
```
**What MTEX version do you use?**
MTEX 5.10.2

**Comment by kilir** [comment]
Hi,
do you use the MATLAB native arm version (Native Apple silicon MATLAB) ? 

If not, you can try what is recommended e.g. here https://github.com/mtex-toolbox/mtex/issues/1778#issuecomment-1625435566

If yes, as far as I know, there are not native arm-binaries available for nfft, so you might have to build them yourself.
See here https://www-user.tu-chemnitz.de/~potts/nfft/installation.php

Hope this helps.

Cheers,
Rüdiger

**Comment by eheikkenen** [comment]
Well, that was a pain. Could someone give it a try?

[mexmaca64.zip](https://github.com/mtex-toolbox/mtex/files/12835815/mexmaca64.zip)

**Comment by Phoenix21-root** [comment]
> Well, that was a pain. Could someone give it a try?
> 
> [mexmaca64.zip](https://github.com/mtex-toolbox/mtex/files/12835815/mexmaca64.zip)

Thank you, using the attached files, the MTEX 5.10.2 runs smoothly in native Apple silicon MATLAB.

Regards,
Dyuti
