### ISSUE TITLE
Euler angles in the fundamental region

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#198]
I noticed that most of the time when MTEX prints out Euler angles they are not necessarily in the the fundamental region, sometimes also called asymmetric region.

Where as if you want to compare two Euler angle triplets it see if they are the same or different you should transform them into the fundamental region.

```
O1 = orientation (show methods, plot)
  size: 1 x 1
  crystal symmetry : Ice-Ih (6/mmm, X||a*, Y||b, Z||c)
  specimen symmetry: 1

  Bunge Euler angles in degree
     phi1     Phi    phi2    Inv.
  73.8084 68.0646 237.164       0
```

To get O1 into the fundamental region

```
O1.niceEuler

  Bunge Euler angles in degree
     phi1     Phi    phi2    Inv.
  73.8084 68.0646 57.1644       0
```

So these two sets of Euler angles are equivalent.

I am just wondering why the "default display" does not use .niceEuler ?

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

the reason is that it would be very irritating for the normal user to enter an orientation by Euler angles and get displayed an orientation with completely different Euler angles.

Ralf.
