### ISSUE TITLE
import_wizard and .ang files 

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#199]
Hi Ralf,
I have an .ang file with multiple (4+1) phases which loads nicely with older versions of mtex, for example 4.2.1 but fails with  4.3.2 and  4.4.alpha.7. It's the "Could not detect file format" error. In case you'd need it, I can send you the input.
Cheer,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüder,

yes it would be nice if you could send me the file.

Ralf.

**Comment by kilir** [comment]
I've sent you a download link.
Rüdiger
