### ISSUE TITLE
Bug: TSLOrientationMapping(crystalSymmetry('321')) is broken

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#200]
Hi Ralf,
```
oM=TSLOrientationMapping(crystalSymmetry('321')) 
plot(oM)
```
results in the following:
![brokentsl](https://cloud.githubusercontent.com/assets/11697557/18783356/9f80d92a-818b-11e6-913a-77d8e0bc6454.jpg)
This is for -3m and 321 but it works fine for other crystal symmetries.
Happens in mtex4.3.2 and 4.4.alpha.7.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this works ok for me? Which settings do you use?

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I just tested it with the default mtex_settings as they come off 4.4.alpha.7 from git various Matlab versions and operation systems. No change. All show the funny colored piece of cake. The error also happens fro me on mtex4.3.2.

There's some variation with the aAxis - bAxisDirection: The original from above was `setMTEXpref('bAxisDirection','east');`
Switching to 
```
setMTEXpref('bAxisDirection','north');
setMTEXpref('aAxisDirection','');
```
comes up with:
![b_north](https://cloud.githubusercontent.com/assets/11697557/19198081/6660cafa-8cbd-11e6-80c1-f9bee04d6276.jpg)


next
```
setMTEXpref('bAxisDirection','');
setMTEXpref('aAxisDirection','west');
```
![a_west](https://cloud.githubusercontent.com/assets/11697557/19197813/31ca6d88-8cbc-11e6-8774-9be65d4c3fa3.jpg)

or
```
setMTEXpref('bAxisDirection','');
setMTEXpref('aAxisDirection','south');
```
![a_south](https://cloud.githubusercontent.com/assets/11697557/19197867/703fcae0-8cbc-11e6-967e-10340149c449.jpg)
or
```
setMTEXpref('bAxisDirection','west');
setMTEXpref('aAxisDirection','south');
```
![b_west_a_south](https://cloud.githubusercontent.com/assets/11697557/19197909/af2be8a6-8cbc-11e6-819f-8cc2091d7a39.jpg)

Anything I could do for testing?

Maybe unrelated, `plot(TSLOrientationMapping(crystalSymmetry('6')))`shows a little glitch as well at the lower corner. Should I open another issue for this one?
![6](https://cloud.githubusercontent.com/assets/11697557/19197460/43b0731e-8cba-11e6-8919-ee2e0f68264f.jpg)

Cheers,
Rüdiger

**Comment by kilir** [comment]
Hi Ralf,
I found that it breaks '321' at https://github.com/mtex-toolbox/mtex/commit/648c2e52f3f4402f3a2a3b88bb14520173cf5d0b ,before it works fine.
However the glitch for '6' is much older and unrelated, removed from above.
Cheers,
Rüdiger

**Comment by kilir** [comment]
It seem also to be a problem for orientations in the fundamentalRegion.
E.g. using mtex prior to https://github.com/mtex-toolbox/mtex/commit/648c2e52f3f4402f3a2a3b88bb14520173cf5d0b
```
%arbitrary orientations
o=orientation('Euler',...
 [ 21.4628 101.624 108.524; ...
  245.51 86.9188 252.396; ...
  15.2752 99.5786 239.882; ...
  25.7204 71.7165 194.086 ; ...
  187.794 75.1703 251.318]*degree,crystalSymmetry('321'))
plotIPDF(o,xvector,'antipodal')
```
gives the following plot:
![pre_648c2](https://cloud.githubusercontent.com/assets/11697557/19378632/f8903a3e-91ed-11e6-8d70-1a71f57ab4be.jpg)

While afterwards, it looks like this:
![post_648c2](https://cloud.githubusercontent.com/assets/11697557/19378648/07ad2734-91ee-11e6-8713-0a4d73a0a2e5.jpg)
Cheers,
Rüdiger

**Comment by kilir** [comment]
Reverting the change in  geometry/@symmetry/fundamentalSector.m 
at https://github.com/mtex-toolbox/mtex/commit/648c2e52f3f4402f3a2a3b88bb14520173cf5d0b#diff-dcac0aa0b3325283c7f62df9a01eb8c4R92
back to 
 `N = rotate(N,-30*degree);`
"fixes" the problem.

**Comment by kilir** [comment]
An additional observation without above mentioned changes:
```
om=TSLOrientationMapping(crystalSymmetry('321', 'X||a*', 'Y||b', 'Z||c'))
plot(om)
```
gives the iffy color map.
![tsl_astar](https://cloud.githubusercontent.com/assets/11697557/19383159/5db34dba-9203-11e6-9685-0c686a66e5be.jpg)

Using:
```
om=TSLOrientationMapping(crystalSymmetry('321', 'X||a', 'Y||b*', 'Z||c'))
plot(om)
```
results in the right color map.

![tsl_bstar](https://cloud.githubusercontent.com/assets/11697557/19383191/798236f0-9203-11e6-8304-52aba562a3e7.jpg)

However, it might be the wrong definition for Euler angles.

**Comment by kilir** [comment]
Could this be a workaround in (https://github.com/ralfHielscher/mtex/blob/feature/slipSystem/geometry/%40symmetry/fundamentalSector.m#L93)
```
  case {19,20,21} % 321, 3m1, -3m1    
    if strcmp(cs.alignment{1},'X||a*') == 0;
    N = rotate(N,-mod(30+round(rho/degree),60)*degree);
    else
    N = rotate(N,-mod(round(rho/degree),60)*degree);
    end
```

**Comment by kilir** [comment]
Hi Ralf,
I can confirm, that both, color coding and plotIPDF with antipodal symmetry work again.
Thanks a lot & cheers
Rüdiger
