### ISSUE TITLE
small glitch in TSLOrientationMapping(crystalSymmetry('6'))

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#205]
Hi Ralf,
I moved this from https://github.com/mtex-toolbox/mtex/issues/200 because it seems unrelated.
Two things I noticed:
After https://github.com/mtex-toolbox/mtex/commit/b51602c the orientation mapping looks like below
![post_b51602c](https://cloud.githubusercontent.com/assets/11697557/19377747/e76b073e-91e8-11e6-9a84-f1a6c44047c4.jpg)
However, prior to that, there's already a glitch for '6'. See below:
![pre_b51602c](https://cloud.githubusercontent.com/assets/11697557/19377809/4e8295f4-91e9-11e6-9e55-19e0f951a3fb.jpg)

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this is a good illustration why this colormap is not topologically correct, -12-10 and 2-1-10 are symmetrically equivalent thus needs to be assigned to the same color. Hence, the color jump.

Ralf.

**Comment by kilir** [comment]
Certainly you are right. I was just thinking that green and blue each would end up at  -12-10 and 2-1-10; however, there's indeed no reason for that. Closing.
