### ISSUE TITLE
scatter gives empty plot with mtex4.4.alpha.7

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#207]
Hi Ralf,
using mtex4.4.alpha.7 on matlab 2015b
`scatter(orientation.rand(100,crystalSymmetry('432'))) `
gives an empty plot window. Works on mtex4.3.2.
Cheers,
Rüdiger
Edit:
Seems to be related to this one: ae99a9f2987b385acc8c3a909c939ffdd74ebba8 ,leaving out the `if isNew ... end` makes the plot appear again for me.

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this. It appears for me as well. I can fix it with some pause command in option_plot. But I want to investigate it a bit more in detail.

Ralf.

**Comment by kilir** [comment]
Yes, that fixed it. So I close this as well, I guess.
Cheers,
Rüdiger
