### ISSUE TITLE
reduce() command does not work correctly for hexagonal grid following 90 degree rotation

### ISSUE THREAD

**Issue by Tom-G-Uni-Vienna** [mtex-toolbox/mtex#2074]
Hello,
I have discovered that reduce() does not work on hexagonal grids after a 90 degree rotation, at least for OIM data. After a 90 degree rotation of the dataset about the map normal (zvector), the reduce command gives either a dataset with no points, or reduces by far too many points.

Why this is a problem: in order to align the map coordinates and sample reference axes for my OIM maps, I need to carry out a 90 degree rotation, which puts them in the orientation where reduce() does not work. As a workaround, I can just rotate my map by 90 degrees, reduce, and flip back when I am done, but this is obviously not the most elegant solution.

At first, I thought it had to do with the orientation of hexagons ("vertical" or "horizontal"), but it turns out that importing the same map with x oriented to north or east has no impact on whether it is in the "correct" orientation for reduce() to work or not. 

Please find attached some code to illustrate the issue, I also attached a .ang file. In the case of my (OIM) data, the error shows up after carrying out the 90 degree rotation.

The issue is clearly being caused by the second part of line 43 in the reduce command (the last part in the following code block, where ix is added to iy) - in some cases the result of summing ix and iy is entirely odd numbers, which leads to no data being extracted into the reduced variable, in some cases only a small number of points fulfil this criteria (as occurs in the attached example).

```
    % generate regular grid
    ext = ebsd.extent;
    dx = max(ebsd.unitCell(:,1))-min(ebsd.unitCell(:,1));
    dy = max(ebsd.unitCell(:,2))-min(ebsd.unitCell(:,2));
      
    % detect position within grid
    iy = round((ebsd.prop.y - ext(3))/dy*4/3);
    ix = round((ebsd.prop.x - ext(1))/dx*2);
     
    ebsd = ebsd.subSet(~mod(iy,fak) & ~mod(ix+iy,2*fak));
```

(fak is a variable telling is to take every nth pixel, default fak=2)

best regards,
Tom Griffiths
[hex_error.zip](https://github.com/mtex-toolbox/mtex/files/14298049/hex_error.zip)

**Comment by ralfHielscher** [comment]
Hi Thomas,
thank you for reporting this issue. I hope I could fix it.
Ralf.
