### ISSUE TITLE
error in calcODF (mtex4.4.alpha.7)

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#208]
Hi Ralf,
I have an ebsd
```
>> ebsd('q')
 
ans = EBSD (show methods, plot)
 
 Phase   Orientations  Mineral       Color  Symmetry  Crystal reference frame
     1  432525 (100%)   Quartz  light blue       321        X||a*, Y||b, Z||c
 
 Properties: bands, bc, bs, error, mad, x, y, grainId, mis2mean
 Scan unit : um
```
and trying to calculate an odf (either using `calcODF` or `calcFourierODF`) results in the following error
```
>> odf=calcODF(ebsd('q').orientations)
Error using  * 
Inner matrix dimensions must agree.

Error in deg2dim (line 4)
d = l*(2*l-1)*(2*l+1)/3;

Error in FourierComponent/set.bandwidth (line 44)
      newLength = deg2dim(L);

Error in FourierComponent (line 35)
      component.bandwidth = find(component.power>1e-10,1,'last');

Error in ODF/FourierODF (line 18)
odf.components = {FourierComponent(f_hat,odf.CS,odf.SS)};

Error in orientation/calcFourierODF (line 54)
odf = FourierODF(odf,get_option(varargin,{'L','bandwidth','fourier'},L,'double'));

Error in orientation/calcODF (line 64)
  odf = calcFourierODF(ori,varargin{:},'kernel',psi);
```
Using just 1000 orientations or sometimes a few more, or randomly sampled orientations seems to work as well, however, quite unpredictably (or results in the same error as above):
```
o=ebsd('q').orientations
odf=calcODF(o(500:1500)) 
 
o = orientation (show methods, plot)
  size: 432525 x 1
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  specimen symmetry: 1
 
 
odf = ODF (show methods, plot)
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  specimen symmetry: 1
 
  Harmonic portion:
    degree: 28
    weight: 1
```
Simulating data is not a problem and using `odf=calcODF(o,'exact')` works as well.
Trying to use `calcKernelODF` comes up with:
```
>> odf=calcKernelODF(o)
Error using sparse
Index into matrix must be positive.

Error in orientation/calcKernelODF (line 69)
  M = sparse(1:length(ori),find(S3G,ori),weights,length(ori),length(S3G));
```
Cheers,
Rüdiger

Edit: this is on osx 10.9. Matlab 2016a and 2016b. However, on a different machine running debian, matlab0216a it works without flaw(sometimes, but not always giving out a weight that is just very close to 1). Not sure if this makes any sense.
```
>> odf=calcODF(ebsd('q').orientations)
 
odf = ODF (show methods, plot)
  crystal symmetry : Quartz (321, X||a*, Y||b, Z||c)
  specimen symmetry: 1
 
  Harmonic portion:
    degree: 28
    weight: 0.99989
```

**Comment by ralfHielscher** [comment]
Very strange,

I can not reproduce any of these errors. First error is probably because f_hat is computed to zero or nan. But I have no idea how this can happen.

Maybe you can debug this a bit?

Ralf.

**Comment by kilir** [comment]
Ok, indeed strange.
I load the ebsd from a .mat file (saved from Matlab2016a on linux) and I get the error with calcODF on a Mac, with Matlab 2015b and 2016a/b.

Loading the same .mat on linux, Matlab 2015a, no error occurs with calcODF.
Also, loading the ebsd on a Mac from the .ctf file, calcODF, also no error with calcODF.

When saving the the .mat on linux with Matlab2015a, I do not get the error when loading the file and running clacODF on a Mac with Matlab2015b.
I'll try it tomorrow with a Mac and Malb2016a/b.

The reason I saved and load the ebsd in a .mat is that I did several things, especially using the halfQuadraticFilter with the ebsd which takes quite some time (on a fast machine about 0.5 to 1+ hour), and of course I didn´t want to repeat that every time I want to do something with the data.

**Comment by kilir** [comment]
Hi Ralf,
I think I found something:
During a certain step in a clean-up procedure, after running the halfQuadraticFilter, there are orientations of an indexed phase with NaN Euler angles.
I was able to crop the region and it seems reproducible. I can send you the cropped area an the relevant part of the script.
Cheers,
Rüdiger

**Comment by kilir** [comment]
Hi Ralf,
thanks a lot, that fixed the error of calcODF when there are indexed orientations with NaN Euler angles. I'm still wondering how they got in there at the first place, and why it actually didn't fail on linux but on a Mac, but who knows.
Cheers,
Rüdiger
