### ISSUE TITLE
max(SO3FunComposition) does not work

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#2085]
Hello MTEX-Team,

using MTEX 5.10.2 we face a problem. For composit ODFs the max function does not work, try code below:

CS = crystalSymmetry('cubic');
SS = specimenSymmetry('1');
odf = 0.4*uniformODF(CS,SS) + 0.6*fibreODF(Miller(1,1,1,CS),zvector,'halfwidth',5*degree)
[value, ori] = max(odf)

Is there any work arround?

Great thanks.

Arne

**Comment by kilir** [comment]
Hi Arne,
for me both the current develop version as well as the recent 6.0beta3 does not throw an error. However, what would you expect as a result for the given example of a fibre odf?
Cheers,

Rüdiger

**Comment by ralfHielscher** [comment]
Hi Arne,
thank you for reporting. As it seems to work in MTEX 6.0.beta3 as well as in the current development branch which will become 5.11. I close this issue.
Ralf.
