### ISSUE TITLE
axis() command giving error in 5.11.2 (and not in 5.10.2)

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#2132]
**What do you want to do?**

compute misorientation axes

**What data do you have?**

I have a set of orientations (3ct in this example, but happens with larger sets as well). 

I want to compute the misorientation of each orientation to the mean-orientation of the set.

**What code do you use?**

axis(o, mean(o))

Please provide minimalist code with code in the following form
```matlab

a = axis(o, mean(o));

```

**What result do you get**
I get an error (see below)

**What result do you expect**

I expect axes returned as with previous versions (i.e., 5.10.2)

**Error Message**
If you get an error message copy and paste it below
```
Error in project2FR_ref (line 84)
q.a(changeSign) = -q.a(changeSign);

Error in quaternion/project2FundamentalRegion (line 44)
  q = project2FR_ref(q,CS1,q_ref);

Error in orientation/project2FundamentalRegion (line 17)
  ori = project2FundamentalRegion@quaternion(ori,ori.CS,varargin{:});

Error in orientation/axis (line 52)
    po2 = project2FundamentalRegion(o2, o1);
```
**What MTEX version do you use?**
This is occurring in MTEX v5.11.2

The following link is to an example set of orientations for which this error occurs:
https://drive.google.com/file/d/11ykkBK0zWsMcrYPxR25JeVNzxO4utFep/view?usp=sharing

**Comment by ralfHielscher** [comment]
Hi Zach,
thank you for reporting this issue. I hope I have fixed it.
Ralf.
