### ISSUE TITLE
After adding custom property to grainSet, Matlab gives an error when attempting to display the variable in command line

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#2137]
**What do you want to do?**
append a grainSet with properties containing computed results

**Error Message**
If you get an error message copy and paste it below
```
Dot indexing is not supported for variables of this type.

Error in vector3d/cat (line 26)
    vx{i} = vs.x;

Error in vector3d/horzcat (line 4)
v = cat(2,varargin{:});

Error in dynProp/char (line 177)
          d = [d,value]; %#ok<AGROW>

Error in grain2d/display (line 71)
disp(char(dynProp(grains.prop),...
```
**What MTEX version do you use?**
5.11.2

**Comment by ralfHielscher** [comment]
Could you please add the code you are using?

Ralf.

**Comment by ralfHielscher** [comment]
Hi Zach, I assume the issue occurred because your additional property was of type vector3d. I think I have fixed this issue now.

Ralf.
