### ISSUE TITLE
grainMean function isn't working properly

### ISSUE THREAD

**Issue by PedroPinh** [mtex-toolbox/mtex#2165]
**What do you want to do?**
Calculate GAM  function
**What data do you have?**
EBSD
**What code do you use?**

```matlab
% Index grains and remove smaller ones, index subgrain and grain boundaries
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd, 'alpha', 2.2);
ebsd(grains(grains.grainSize<5)) = [];
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'alpha', 2.2, 'threshold',[5*degree, 15*degree]);

%Denoise
F = halfQuadraticFilter;
F.alpha = 0.25;
ebsd = smooth(ebsd,F,'fill');
EBSD = ebsd('indexed');
% calculate KAM
kam = EBSD.KAM(EBSD,'threshold',5*degree,'order',5)./degree;
% Calculate GAM
gam = EBSD.grainMean(EBSD,kam, grains);
```
**What result do you get**
KAM and GAM

**What result do you expect**
KAM and GAM

**Error Message**
```
Error using max
Invalid data type. First argument must be numeric or logical.

Error in EBSD/grainMean (line 42)
ulim = get_option(varargin,'ulim', max(prop));

Error in EBSD/subsref (line 57)
  [varargout{1:nargout}] = builtin('subsref',ebsd,s);
```
**What MTEX version do you use?**
5.11.1
Matlab R2018a

**Comment by PedroPinh** [comment]
Hello everyone.

I'm trying to obtain GAM with MTEX, but I keep getting this error; 
I'm trying other combinations of this code, like:
gam = grainMean(EBSD,kam, grains); 
and get:
Error using sum
Invalid option. Option must be 'double', 'native', 'default', 'omitnan' or 'includenan'.

Error in mean (line 116)
        y = sum(x, dim, flag) ./ size(x,dim);

Error in EBSD/grainMean>@(x)mean(x,1,"omitmissing") (line 50)
method = getClass(varargin,'function_handle',@(x) mean(x,1,"omitmissing"));

Error in EBSD/grainMean (line 53)
mP = accumarray(ebsd.grainId(hasGrain),prop(hasGrain),[],method);

I've tried a combination with GOS calculation too, and didn't work either:
GOS = EBSD.grainMean(mis2mean.angle, grains);
didn't work either.

Glad from your help and attention.

Cheers,
Pedro

**Comment by ralfHielscher** [comment]
Your code is syntactically not correct. You should almost never use `EBSD` as this is the class name. 

```matlab
% Index grains and remove smaller ones, index subgrain and grain boundaries
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd, 'alpha', 2.2);
ebsd(grains(grains.grainSize<5)) = [];
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'alpha', 2.2, 'threshold',[5*degree, 15*degree]);

%Denoise
F = halfQuadraticFilter;
F.alpha = 0.25;
ebsd = smooth(ebsd,F,'fill');

% calculate KAM
kam = ebsd.KAM('threshold',5*degree,'order',5)./degree;
% Calculate GAM
gam = ebsd.grainMean(kam, grains);
```
Ralf.
