### ISSUE TITLE
Trouble with Schmid Factor and Slip Systems in MTEX  Unrecognized method, property, or field 'symmetrise' for class 'slipSystem'.  Error in Basic_Import_Grain_KAM (line 82) sSBasalSym = sSBasal.symmetrise('antipodal')

### ISSUE THREAD

**Issue by ute23** [mtex-toolbox/mtex#2193]
**What do you want to do?**

**What data do you have?**

**What code do you use?**
Please provide minimalist code with code in the following form
```matlab
% load the data
ebsd = EBSD.load('myFile.txt')

% plot a pole figure
plotPDF(ebsd,Miller(1,0,0,ebsd.CS)
```

**What result do you get**

**What result do you expect**

**Error Message**
If you get an error message copy and paste it below
```
put the error message here
```
**What MTEX version do you use?**

**Comment by ralfHielscher** [comment]
Could you please provide some more detail?
If
```matlab
sSBasalSym = sSBasal.symmetrise('antipodal') 
```
gives the error specified in the header, I would assume that your MTEX installation is not complete. Please consider downloading and extracting it again.
Ralf.
