### ISSUE TITLE
Orientation equality check fails

### ISSUE THREAD

**Issue by frankNiessen** [mtex-toolbox/mtex#2194]
Hi, 

I found a bug I think: 

```matlab
ori = orientation.rand
ori == ori
%ans =
%
%  logical
%
%   1
ori = rotation.inversion * ori
ori == ori
%ans =
%
%  logical
%
%   0
```

Best wishes
Frank

**Comment by frankNiessen** [comment]
To give a bit more context: If I do the same using a `rotation` there is no issue. Following the call stack, the rotation equality is evaluated by taking the `quaternion` dot product, which is 1. For the orientation the `itimes` method is selected. Here the resulting dot product is 0.

**Comment by ralfHielscher** [comment]
Hi Frank,
thank you for pointing this out. This obviously needs to be fixed.

Ralf.
