### ISSUE TITLE
Internal grain boundaries

### ISSUE THREAD

**Issue by ThomasChauve** [mtex-toolbox/mtex#22]
Hey

Does the internal grain boundaies are include in MTEX or not yet.

Because in the doc, it write :  

Subboundaries
Another special type of boundaries, are boundaries that are located within a grain, nevertheless this happens, if two adjacent measurements are somehow conneted by a lattice rotation within a grain. 
```matlab
plot(grains.boundary,'external')
hold on
plot(grains.boundary,'internal','linecolor','r','linewidth',2)
```

because for me it doesn't seem to work. I using matlab2013a and MTEX4.0.9

Thanks for all
and merry christmas and happy new year

Thomas

**Comment by ralfHielscher** [comment]
Hi Thomas,

the internal grain boundaries are included but it seems the documentation is wrong. The correct syntax beginning with MTEX 4.0 is
```matlab
plot(grains.boundary)
hold on
plot(grain.innerBoundary,'linecolor','r','linewidth',2)
hold off
```
Thank you for pointing out this error in the documentation.

Ralf.

**Comment by SergioElizalde** [comment]
Hi ralfHielscher.

I was wondering if it's posible to set the inner boundary  from 2 to 15°? What is the default angle?

Thx

**Comment by zmichels** [comment]
I am pretty sure the boundary is set when computing grains... such that the inner boundary and outer boundaries are defined by the same threshold angle. You could try defining a grainset using 15° segmentation angle and see if it changes the inner boundary angles.

Z
