### ISSUE TITLE
converting EBSD with rectangular grid to hexagonal or hexagonal to rectangular grid

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#221]
In MTEX 4.4 beta1 we have

xy = [ebsd.x,ebsd.y]' % this transposed
% rectangular to hexagonal
unitCell = calcUnitCell(xy,'GridType','hexagonal','GridRotation',0*degree)
% update unitCell 
ebsd_hex = updateUnitCell(ebsd)
this does not seem to work

It is quite possible I do not have syntax right.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

conversion from square to hex grid is not supported in MTEX. you can do the other way round with 
```matlab
ebsd.gridify
```
So far I did not have this on my todo list as in MTEX there are more functions that work for rectangular grids then for hex grids. Why do you want to have hex grid?

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,
What is utility  of calcUnitCell(xy,'GridType','hexagonal','GridRotation',0*degree)
as I clearly missed the point !
all the best David

**Comment by ralfHielscher** [comment]
Its more an internal function which I use to determine the unit cell from given data.

Ralf.
