### ISSUE TITLE
Error in fill function

### ISSUE THREAD

**Issue by vedadb** [mtex-toolbox/mtex#2217]
After updating the mtex version today (from 5.10.2 to dev) I get errors when using the fill command. This could be traced to @EBSD/fill.m line 65 where trying to access the property grains.meanRotation gives error. Changing this line to grains.prop.meanRotation works. 

I do not know what changed in the code otherwise for this error to occur. Maybe it can be fixed

![image](https://github.com/user-attachments/assets/0a48263e-b857-4678-a5f7-0c45c5238089)

Vedad

**Comment by ralfHielscher** [comment]
Hi Vedad,

I think I have fixed this.

Ralf.
