### ISSUE TITLE
Issue in opening*.uxd files

### ISSUE THREAD

**Issue by KKrishna1** [mtex-toolbox/mtex#223]
Hi All, 

the attached uxd file is not opening in mtex 4.4. It also looks something has been changed in the file, but not
[160603 6M05 peak.uxd.txt](https://github.com/mtex-toolbox/mtex/files/590043/160603.6M05.peak.uxd.txt)

 very sure where. Anyone, please help me in identifying the issue? Many thanks

**Comment by ralfHielscher** [comment]
MTEX is missing in the header the value for KHI which is usually provided in uxd files

**Comment by KKrishna1** [comment]
Solve, Thank you Ralf. 

Cheers,
