### ISSUE TITLE
Documentation error on generating fibre textures

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#224]
On:
https://mtex-toolbox.github.io/files/doc/fibre_index.html

Lists:
>>>beta = fibre.beta(cs,'full');
>>>odf = fibreODF(beta,'halfwidth',10*degree)

When I run this command I get the following error:

Error using argin_check (line 29)
Input argument "" should be of type "Miller"
See syntax definition above!

Error in fibreODF (line 31)
h = argin_check(varargin{1},'Miller');

The correct syntax is 

>>>odf = fibreODF(beta.h, beta.r,'halfwidth',10*degree)

**Comment by ralfHielscher** [comment]
Hi Adam,

this is a version problem. Unfortunately, our online documentation system has now support for different versions of MTEX. The syntax in the documentation is valid for MTEX 4.4.

All the best,

Ralf.
