### ISSUE TITLE
error in mean(odf) and mean(orientation)

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#225]
Hi Ralf,
using `[m, kappa, v] = mean(odf)` does not work as expected since the kappa returned are not the Bingham parameters but the quaternions (second output argument of orientation/mean) and v are not the eigenvectors but the eigenvalues (third output argument of orientation/mean).
Kappa is not returned from orientation/mean at all.

I guess odf/mean could rather read like this:
```
function [m, lambda, v] = mean(odf,varargin)
% returns mean, kappas
%
% Input
%  odf       - @ODF
%
% Output
%  mean      - @orientation
%  lambda     - principle moments of inertia
%  v         - eigenvectors
%
S3G = extract_SO3grid(odf,varargin);
[m, ~, lambda, v] = mean(S3G,'weights',eval(odf,S3G)); %#ok<EVLC>
m = orientation(m);
```

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

yes I have to update the documentation. computation of kappas is now inside calcBinghamODF

Ralf.

**Comment by kilir** [comment]
Hi Ralf, yes, it's not really an error, it just do what it says. I'll keep this up here in case someone wonders or I'll forget about what I changed.
Cheers,
Rüdiger
