### ISSUE TITLE
vetor3d/plot with 'contourf' forgets to plot circle around projection

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#230]
Hi Ralf,
using current master doing `plot(evctor3d.rand(10),'contourf')` results in a plot without a circle around
 the projection. Does not happen for `contour` or `smooth`.

![bla](https://cloud.githubusercontent.com/assets/11697557/22622764/85731e80-eb44-11e6-9902-f73cdff3eba6.jpg)

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

can you check that this fixes the bug?

**Comment by kilir** [comment]
Hi Ralf,
yes, it's fixed. Thanks a lot. Closing.
Cheers,
Rüdiger
