### ISSUE TITLE
grain2d/checkInside fails for banana (or simlar) shaped grains

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#232]
Hi Ralf,
using checkInside to find inclusions in grains might be very handy. However, using grains as an input to check for inclusions, I get a lot false positives (and checking for ebsd to be inside a grain is very very very slow).
Could that be due to the fact that some grains have their centroid outside of their own area?
Adding an additional check for just an inclusion to just  have one neighbor still might fail in certain situations but sort of helps already.

```
        ngrains=grains('n');
        isinside=logical(sum(checkInside(grains('q'),ngrains),2));
        plot(grains)
        hold on
        plot(ngrains(isinside),'FaceColor',[1 0 0])
        hold on
        n0=ngrains.neighbors ==1;
        plot(ngrains(isinside&n0),'FaceColor',[0 1 0])
        hold off
```
![nei](https://cloud.githubusercontent.com/assets/11697557/23437392/4435bf90-fe0e-11e6-9da2-73dbe9375edc.png)

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I have worked on this and hopefully fixed it. Though I did not find an example with concave grains so quickly could you check it works now?

As a bonus the new version allows the inclusiongrains to be withing the list of hostgrains, i.e., 
```checkInside(grains,grains('quartz'))``` should check for all inclusions that are of type Quartz.

By the way
```
grains.inclusionId
```
gives you for every grain whether it is included in another grain. In this case it gives the id of the host grain.

Ralf.

**Comment by ralfHielscher** [comment]
For some reason I habe set this property to hidden. Do not remember why.
