### ISSUE TITLE
Does anyone know the syntax for ori = discreteSample(odf,npoints,varargin) with weights

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#234]
Is is possible use discreteSample(odf,npoints,varargin)
to get a list orientations with associated weights ?

Also is possible to use a uniform ODF to generate a list of orientations ?

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

there are two alternatives:

1. compute orientations according to the ODF with weight one
```maltab
ori = odf.calcOrientations(10000)
```
2. take a uniform grid of orientations and compute the weights as the value of the ODF
```matlab
ori = equispacedSO3Grid(odf.CS,odf.SS)
weights = odf.eval(ori)
```

Ralf.
