### ISSUE TITLE
Using calcTensor geometric Mean

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#236]
Using calcTensor option 'geometricMean'
```matlab
C_GeoMean_ol = calcTensor(ebsd('olivine').orientations,C_olivine,'geometricMean')
```
This option is restricted to 'ebsd' which makes it very slow with 500 000 orientations

Computation time could be reduced either allowing  orientations with weights or mean_grain orientations with weights such as grain area.

Related question about extracting random weighted orientations  from ODFs posted recently

all the best David

**Comment by ralfHielscher** [comment]
I have to check, whether this can be computed using the harmonic route. Is there any paper about the geometricMean approach?

Ralf.
