### ISSUE TITLE
Changing font size in pole figure axes labels

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#239]
Is there a way to make the axis labels (X, Y), the pole label (hkl), and/or colorbar label bigger?  Or remove them entirely?  I've tried 'silent', but that does not change them.  

Thanks!

**Comment by ralfHielscher** [comment]
Have you checked changing the option
```matlab
setMTEXpref('FontSize',13);
```
in ```mtex_settings.m```

Ralf.

**Comment by creuzige** [comment]
I had not.  I figured it would be something trivial like that, but couldn't find it in the documentation nor on the issues list.  

Using the setMTEXpref command changes the axis labels and pole lables in pole figures, but does not change the colorbar label.  I found that you can change the colorbar label with:

figure;
h=colorbar;
set(h,'fontsize',14);

( see https://www.mathworks.com/matlabcentral/newsreader/view_thread/240012.html? ).  As a note, the number ticks seems to be a function of the font size.  

Is there something similar for the ODF sections? 
On ODF plots, setting the font size with setMTEXpref only affects the Max, Min and section (Phi2 in my case) labels, but does not change the phi1 and PHI axis labels, nor the phi1 and PHI tick labels.  (See below for example).  There used to be a work around for vector graphics, ie saving at a smaller size, but with those being problem in recent matlab releases, is there another way?

Export vector graphics issues:
https://www.mathworks.com/matlabcentral/answers/222479-bug-eps-pdf-matlab-2014b-surface-plot-contourf
https://github.com/altmany/export_fig/issues/44


![image](https://cloud.githubusercontent.com/assets/10198749/24044841/550641a4-0af3-11e7-905f-d1c2779dab2b.png)
