### ISSUE TITLE
scaling issue in principalComponents (bug?)

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#240]
Hi Ralf,
looking at principalComponents, I was expecting that ew (length of axis) should be roughly within the scale of the grain.
It's related to https://groups.google.com/d/msg/mtexmail/NR-WmKFysqk/UMrWXqtFEQAJ 
However, I think it's not an issue of this particular map and I also get strange results with any other grain, e.g. the following:

![sillygrain](https://cloud.githubusercontent.com/assets/11697557/24045034/0534f47e-0b1e-11e7-85dd-aaadd167b102.png)

the axis direction is roughly vertical, but the length seems to be quite small (just looking at several best fit alternatives, the major axis should be ranging about 3).
```
>> [ev,ew]= principalComponents(grains)

ev =

   -0.0071    1.0000
    1.0000    0.0071


ew =

    0.9620         0
         0    0.4811
```

I think it should be this line https://github.com/mtex-toolbox/mtex/blob/master/EBSDAnalysis/%40grain2d/principalComponents.m#L42 but couldn't get it to work properly.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

could you please check what I did. I also changed the syntax a bit to return angle + axes length. I also readded the function plotEllipse to check the result.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
it looks like it works ('hull' option as well)! Thanks a lot.
![image](https://cloud.githubusercontent.com/assets/11697557/24458940/a1159724-149a-11e7-97ff-86066dda2aac.png)

The new syntax might require some people to adopt their scripts (and grain2d/aspectRatio needs to be updated as well) but it is actually more user friendly. Could you also add the help text to the option 'hull' from plotEllipse to principalComponents?

With respect to the scale option in plotEllipse: It's a factor with respect to a,b which itself is scaled length of the boundary, somehow? So what would be the easiest way to scale the ellipse to be areaequivalent to the grain? Making plotEllipse report the area using polyarea I guess?

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I changed things a bit. principalComponents can now normalize according to area and boundary length. plotEllipse is a pure plotting function that requires center points, a, b and orientation of the ellipse. Scaling needs to be done by hand. I think this is more direct.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
that seems more straightforward and works nicely. I added 3 comments.
With respect to the option 'boundary', one might get funny results, especially if one forget excluding non-indexed area, however being aware of very lobate grains is probably a good thing.

Cheers and thanks a lot,
Rüdiger
