### ISSUE TITLE
Issue calculating ODF's

### ISSUE THREAD

**Issue by ibanezmejia** [mtex-toolbox/mtex#247]
Hi Ralf,
I'm having an issue when trying to calculate ODF's; my particular data is a .ctf EBSD data input, and the command I'm using an error produced are pasted below.

Just to double check that there isn't something wrong with my data or the way I'm doing it, I uploaded the forsterite data of the tutorial and when I tried to calculate the ODF using your command (odf = calcODF(ebsd('fo').orientations)) it returned exactly the same error.

Any ideas on how to solve this? I guess I'm missing a library, but I don't know where to find it.
Thanks!
Mauricio

PS: I tried running in three computers with separate installations of MTEX 4.5.0 and it produced the same error each time.

**This is my command:**
odf = calcODF(ebsd('Zr02 monoclinic').orientations,'halfwidth',10*degree)

**Which results in this error:**
Error using call_extern (line 160)
  Error running external program: odf2fc show logfile

Error in unimodalComponent/calcFourier>gcA2fourier (line 68)
f = call_extern('odf2fc','EXTERN',g,c,A);

Error in unimodalComponent/calcFourier (line 29)
f_hat = gcA2fourier(abg,c,A);

Error in ODF/calcFourier (line 32)
  hat = calcFourier(odf.components{i},L,varargin{:});

Error in ODF/FourierODF (line 8)
f_hat = calcFourier(odf,varargin{:});

Error in orientation/calcFourierODF (line 54)
odf = FourierODF(odf,get_option(varargin,{'L','bandwidth','fourier'},L,'double'));

Error in orientation/calcODF (line 64)
  odf = calcFourierODF(ori,varargin{:},'kernel',psi);

Error in test_Kov7 (line 76)
odf = calcODF(ebsd('Zr02 monoclinic').orientations,'halfwidth',10*degree)

**And this is the logfile:**
dyld: Library not loaded: /opt/local/lib/libfftw3.3.dylib
  Referenced from: /Users/Ibanez-Mejia/Documents/MATLAB/mtex-4.5.0/c/bin/maci64/libnfft3.1.dylib
  Reason: image not found

**Comment by ralfHielscher** [comment]
Have you looked at #238

**Comment by ibanezmejia** [comment]
I have. Zach was having issues with the maci64 files under the mex folder; he shared those with me and they seem to be working. That thread did not mention anything about the maci64 files under the bin folder, though. Could you suggest a test to make sure those are working properly?

Thanks,
Mauricio

**Comment by ralfHielscher** [comment]
All this should now work without problems in MTEX 5.0.

Ralf.
