### ISSUE TITLE
MTEX & Permissions

### ISSUE THREAD

**Issue by benjaminbritton** [mtex-toolbox/mtex#250]
Hi - when you install MTEX on a multi user machine and matlab is installed as a shared install, the path change upsets the user permissions of "\toolbox\local\pathdef" - which then requires an administrator to reset permissions to all users.

**Comment by benjaminbritton** [comment]
There are subsequent issues if the single user installs the software on a director for which other users do not have access.

**Comment by ralfHielscher** [comment]
Hi Benjamin,
sorry for the delay. Could you please explain more in detail what is happening? The function `install_mtex` only calls the matlab function `savepath` which should save the matlab search path locally. For a global installation the best way is to add the following line to the file `matlab_dir/toolbox/local/startup.m`
```matlab
run('mtex_path/startup_mtex')
```

I hope this helps,

Ralf.

**Comment by benjaminbritton** [comment]
Hi Ralf,

We often run MTEX on a computer matlab is installed for access by multiple users.
Selecting the ‘install MTEX’ for all users command from the run MTEX window changes the start-up path file.
In doing so, it also changes permissions on this starting path file to the user who selected to install it.
All other users of the machine are subsequently not able to open matlab successfully, as they do not have permission for matlab to initialise the paths when it starts up.
The way we have fixed this on our computers is to manually go and revert the permissions for the path file to make it viewable by all users of the computer.

Regards,
Ben

--
Dr T Ben Britton, CEng, CSci, FIMMM
Lecturer/RAEng Research Fellow,
Director of MSc in Advanced Nuclear Engineering
Deputy Director, Centre for Nuclear Engineering

Department of Materials, Imperial College London,
Exhibition Road, London, SW7 2AZ
T: +44 (0) 207 594 2634
Email: b.britton@imperial.ac.uk<mailto:b.britton@imperial.ac.uk>
Twitter: @bmatb

Research Group: http://expmicromech.com/
IC Profile: http://www.imperial.ac.uk/people/b.britton
Academia.edu: http://imperial.academia.edu/TBenBritton
Eng Alloys: http://www.imperial.ac.uk/engineeringalloys
Centre for Nuclear Engineering: http://www.imperial.ac.uk/nuclear-engineering/

**Comment by ralfHielscher** [comment]
Hi Ben,

may I ask which version of MTEX and Matlab you are using. So far I was not able to reproduce this behavior.

Ralf.

**Comment by benjaminbritton** [comment]
This issue happens if you have a multiuser machine. If a user without administration rights installed mtex, it changes the owner of \toolbox\local\pathdef to the user who made the install. Any other user on the computer will no longer be able to get matlab to run, unless the users account is used again to install mtex. I think that the issue is fixed if you load matlab in administrator mode within windows prior to installing it.

**Comment by benjaminbritton** [comment]
As a note - you also may want to advise that users copy MTEX into a folder which other users have access to (e.g. I put it in 'C:\Program Files\MATLAB\R2017a\toolbox') - otherwise there will be issues when other users try to use the toolbox, and they will install it themselves & cause the permissions issue.
