### ISSUE TITLE
phase Id of EBSD with one phase - a bug ?

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#255]
Here is the output

>> ebsd
 
ebsd = EBSD (show methods, plot)
 
 Phase  Orientations  Mineral       Color  Symmetry  Crystal reference frame
     1  13358 (100%)   Ice-Ih  light blue       622        X||a*, Y||b, Z||c
 
 Properties: bands, bc, bs, error, mad, x, y, grainId, mis2mean
 Scan unit : um
 
>> ebsd_phaseId = unique(ebsd('Ice-Ih').phaseId)

ebsd_phaseId = 2

The phaseId of Ice-Ih should be 1 !!!!

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

MTEX always introduces a not indexed phase with id=1, e.g. the user might want to set some pixels do not indexed afterwards.

On the other hand phases that are not present are not displayed in the output. Therefore, there is no guaranty that if only one phase is shown this has id 1.

Ralf.

**Comment by DavidMainprice** [comment]
so I have to test for non-index being absent ?

all the best David

**Comment by ralfHielscher** [comment]
No I don't think you have to test this. What do you want to do? Can't you use
```matlab
ebsd.phase
```

**Comment by zmichels** [comment]
When I import a dataset, the not-indexed fraction is always automatically set with phase id = 0. And then all of the indexed phases are integers. What David shows...

Phase Orientations Mineral Color Symmetry Crystal reference frame
1 13358 (100%) Ice-Ih light blue 622 X||a*, Y||b, Z||c

… indicates that the phase id of Ice-lh *should* be 1, not 2. And also, I’ve never had mtex import a not-indexed phase with id = 1.


On Jun 20, 2017, at 8:44 AM, DavidMainprice <notifications@github.com<mailto:notifications@github.com>> wrote:

so I have to test for non-index being absent ?

all the best David

**Comment by zmichels** [comment]
Ahhh… I see… ebsd.phaseId is different from ebsd.phase.

sorry for my confusion


On Jun 20, 2017, at 8:30 AM, DavidMainprice <notifications@github.com<mailto:notifications@github.com>> wrote:

Phase Orientations Mineral Color Symmetry Crystal reference frame
1 13358 (100%) Ice-Ih light blue 622 X||a*, Y||b, Z||c

**Comment by DavidMainprice** [comment]
I went back to the original data set with notIndexed

rebsd12 = EBSD (show methods, plot)
 
 Phase  Orientations     Mineral       Color  Symmetry  Crystal reference frame
     0    187 (1.4%)  notIndexed                                               
     1   13358 (99%)      Ice-Ih  light blue     6/mmm        X||a*, Y||b, Z||c

this works fine with 

% Selected phase Id number
selected_phaseId = unique(rebsd12('Ice-Ih').phaseId)

selected_phaseId =  2

all the best David
