### ISSUE TITLE
Calculation of grains, grain areas, and grain lengths

### ISSUE THREAD

**Issue by samanmon** [mtex-toolbox/mtex#256]
Hello,

I have been using MTEX to process EBSD data (in .ang format) of binary and ternary alloys. I would like to get clarification on some fronts:

1. After gridifying the EBSD data files, the command size(ebsd) gives the size of the image in units of grids (this is the same as just typing the variable name 'ebsd', with an output containing 'Grid Size: X Y', although the ebsd.scanUnit is indeed um. It appears that, for this data set, there are two grids per pixels, found from the command 2*abs(ebsd.unitCell(1,1)). So the question is, what about the outputs that I get for total grain area and segment lengths (i.e., sum(grains.area) and sum(grains.boundary.segLength)); are they also in grid units, in which case I should divide by 2 and 4, respectively, to convert to pixels, or are they already in pixels? My suspecion is that they are in grid units (but see item 3 below). 

2. In the EBSD data sets that I am analyzing, I purposefully indexed only one of the phases. I still remove the low confidence index pixels from ebsd. But, surprisingly, I find different total number of grains for the following three methods:
size(grains) = 31,768       % 'grains' was calculated from 'ebsd' with 2 degree threshold and the 'unitcell' parameter
size(grains) = 28,883       % in this case, 'grains' was calculated from ebsd('indexed'), but again only one phase was indexed anyway
size(grains) = 36,971       % here, 'grains' was calculated from ebsd('phase'), where 'phase' is the name of the phase that was indexed in taking the EBSD data. 
I should note that all three methods give the same number of pixels for the grains (565,725). Based on these, if you could please confirm the rigorous way of getting the segment lengths, that would be much appreciated. 

3. The total grain area that I get -- from sum(grains.area) with 'grains' calculated using the first method listed in item 2 above -- is different from just counting the white pixels of the ebsd.ci image in MATLAB, and the ratio is not 1:4, as I would expect from item 1 above. Could you please clarify?

4. The first command that I execute on variable 'ebsd' is gridify. I then remove the low ci pixels, but I notice that after this removal step I would need to gridify the ebsd variable again (for example, to see the ebsd.ci image). Could you please explain why the grids disappear after removing the low ci pixels?
Thank you!

Saman

**Comment by samanmon** [comment]
Just to clarify, I am mostly interested in learning about a robust way of obtaining the total grain length as well as area of an EBSD data file. I obtain noticeably different area measurements when using 'sum(grains.area)' vs. adding up the number of white pixels of a binarized image of the confidence index of an ebsd, i.e., 'sum(imbinarize(ebsd.ci(:)))'. I would also appreciate any clarification as to whether the units of length or area would be in pixels, grid steps, or scanUnit for an ebsd variable that is gridified.

Thanks in advance.

**Comment by ralfHielscher** [comment]
Sorry for the late response.

1. both ```area``` and ```segLength``` are **not** in terms of pixels but have the same unit as ```x``` and ```y```.
