### ISSUE TITLE
mtexColormap does not accept change of colorcoding for multiple axes

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#257]
Colorcoding does not change when  using more than one figure axis.
The following code reproduces the issue:
```
% create data
cdata=rand(50,1);
rands2=rand(50,1);
theta=2*pi*cdata;
rho=2*pi*rands2;
vec=vector3d('polar',theta,rho);
equiGrid=equispacedS2Grid('resolution',10*degree);
idwVec= interp(vec,cdata,equiGrid,'inverseDistance'); % 
%
colornames={'hot', 'cool', 'parula',}
sz=size(colornames,2)

% plot single figure axis - works ok
figure
plot(equiGrid,idwVec,'upper','smooth','edist','grid','grid_res',90*degree);
mtexColorMap(colornames{1})
mtexTitle(colornames{1})
mtexColorbar

% plot three figure axes - does not change colorcode
figure
for i=1:sz
axesPos=subplot(1,sz,i); 
plot(equiGrid,idwVec,'upper','smooth','edist','grid','grid_res',90*degree,'parent',axesPos);
mtexColorMap(axesPos,colornames{i})
 mtexTitle(colornames{i})
 mtexColorbar
end

% expected result using matlab's colormap - works fine too
figure
for i=1:sz
axesPos=subplot(1,sz,i); 
plot(equiGrid,idwVec,'upper','smooth','edist','grid','grid_res',90*degree,'parent',axesPos);
colormap(axesPos,colornames{i})
 mtexTitle(colornames{i})
 mtexColorbar
end

```
Regards,
Filippe

**Comment by ralfHielscher** [comment]
Hi Filippe,

thank you for reporting this. I think this is quite a recent Matlab feature to have different colormaps in one figure. I have adopted the mtexColorMaps accordingly. Are you able to check this?

You may produce even nicer multiplots by using the following syntax
```matlab
% initialize an MTEXFigure
mtexFig = newMtexFigure;

% for three different colormaps 
for cm = {'hot', 'cool', 'parula'}
  
  % plot some random data in different axis
  plot(vector3d.rand(100),'smooth','parent',mtexFig.nextAxis,'grid','grid_res',90*degree);
  
  % and apply an individual colormap
  mtexColorMap(gca,char(cm))
  
  % set the title to be the name of the colormap
  mtexTitle(char(cm))
end

% plot a color for each plot
mtexColorbar('multiple')
```
Ralf.

**Comment by filippeof** [comment]
Hello Ralph, 
Many thanks! It works greatly assigning a colorbar for the current axes but, if gca is not passed as argument, it is not applying the colorcode for gcf, as it was before.  For instance, using the following code:
```
cs = crystalSymmetry('-3m');
odf = fibreODF(Miller(1,1,0,cs),zvector)
m_main = Miller({1,0,0},{0,0,1},{0,1,0},cs);
plotPDF(odf,m_main,'contourf')
mtexColorMap LaboTeX
```
produces:
Before changes
![image](https://user-images.githubusercontent.com/11142094/29402599-da983d4e-8335-11e7-8ecf-fb89f9c4a4b9.png)
After changes:
![image](https://user-images.githubusercontent.com/11142094/29402632-f70b79c8-8335-11e7-8c0c-a027de198e85.png)

Changing line 14 of the new mtexColorMap.m from
`if isa(ax,'Figure')`
to
`if isappdata(ax,'mtexFig')`
worked for me but I am not sure if it has implications elsewhere.
Regards, 
Filippe

**Comment by ralfHielscher** [comment]
Better now?

**Comment by filippeof** [comment]
Yes. Perfect.
Thank you!
