### ISSUE TITLE
Error in loadEBSD_ang (BUG)

### ISSUE THREAD

**Issue by davisonajr** [mtex-toolbox/mtex#258]
There is one error on the code of function loadEBSD_ang that avoid the data of FIT to be loaded.

The error is in line 79:  if isempty(sscanf(hl{nh+1},'%*f %*f %*f %*f %*f %*f %*f %*f %*f %*f\n'))

it shoud be corrected by: if isempty(sscanf(hl{nh+1},'%*f %*f %*f %*f %*f %*f %*f %*f %*f %s\n'))

With this correction, the fit numbers that are usually in the 10 colum will be loaded by the condition elseif or by the else... I would suggest to correct the else condition as well in line 96 and 97:

96      'ColumnNames',{'Euler 1' 'Euler 2' 'Euler 3' 'X' 'Y' 'IQ' 'CI' 'Phase' 'SEM_signal' 'Fit' 'unknown1' 'unknown2' 'unknown3'},...
97     'Columns',1:13,varargin{:},'header',nh,'ReplaceExpr',replaceExpr);

. Usually in my ang the data is organized like this...

I hope it will helps in future versions....

**Comment by ralfHielscher** [comment]
Could you please attach your ang file?

**Comment by davisonajr** [comment]
​
 crop_1.ang
<https://drive.google.com/file/d/0B14y1h47CaChMEdyRXNWSkluX2s/view?usp=drive_web>
​

2017-08-16 9:45 GMT+02:00 Ralf Hielscher <notifications@github.com>:

**Comment by davisonajr** [comment]
This file was created by the export data of the OIM TSL 7

2017-08-16 16:28 GMT+02:00 davisola . <davison.ajr@gmail.com>:

**Comment by ralfHielscher** [comment]
I have rewritten the ang interface to work with more conventions. 
Ralf.

**Comment by davisonajr** [comment]
Nice... I hope I helped in something...

So, basicly I am in germany until November (I'm a guest in the Max-Planck
Institut für Eisenforschung) Is there any chance to me visit the team who
develop the MTEX? I think I saw that most of you are in Berlin right?

2017-08-17 8:42 GMT+02:00 Ralf Hielscher <notifications@github.com>:

**Comment by ralfHielscher** [comment]
I would be happy to welcome you in Chemnitz at any time. Though the way is a bit longer then to Berlin.

Ralf.

**Comment by davisonajr** [comment]
I pass through Chemnitz when I went to Prague... Yeah it is a bit far
but... lets see... maybe one day during the week I can plan to visit you...
thank you for the open invitation...

2017-08-17 9:49 GMT+02:00 Ralf Hielscher <notifications@github.com>:
