### ISSUE TITLE
Restrict data to phase 

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#26]
Dear Mtex users/developers,

I am currently starting to translate my codes from mtex 3.5 for 4.x syntax,working with ebsd(cpr,crc)files, and i am facing a problem to restrict my data  for a specific phase in Mtex 4.0.10 , such as  grains('phase') or ebsd('phase'), although gB = grains.boundary('phase','phase')  works fine.

The number informed by grains of 'phase' grains exceeds 500 (nevertheless when i try to get the number of grains by numel(grains)  the answer is always 1.).
I already tried to reinstall Mtex but the following msgerror persists:

Subscript indices must either be real positive integers or logicals.
Error in subsind (line 40)
    ind = ind & phases(ebsd.phaseId);
Error in EBSD/subsref (line 12)
  ind = subsind(ebsd,s(1).subs);

Thanks,
Filippe.

**Comment by ralfHielscher** [comment]
Hi Filippe,

due to Matlab related reasons `numel(grains)` as well as `numel` applied to any other MTEX variable will always return 1. Please use `length(grains)` instead.

However, `grains('phaseName')` should we working. Could you post the output when you type `grains` to the command window. It would also be very helpfull if you could attache your data and you script resulting in the error.

Ralf

**Comment by filippeof** [comment]
Hi! Thanks for your reply.

I think i found what is wrong. In the earliest versions of Mtex(e.g. v3.5) the only phases that were imported were the ones that really existed in the set. In Mtex 4.0.1x, however, crystal symmetries from all available phases  for indexing are now imported. If i manually delete phases that are not in use the restriction of ebsd or grains data works fine.
 I had to send the requested data via e mail since github only supports image files. Please find attached the scripts generated by import_wizard, for the same cpr file, in versions 3.5 and 4.12, as well as the requested output for grains and the original data.

Thanks,

Filippe.

**Comment by ralfHielscher** [comment]
Hi Filippe,

thank you for sending me the data and reporting the issue. For now you can work around the issue by adding the not indexed phase to the list of symmetries, i.e.
```matlab
CS = {'notIndexed',...
  crystalSymmetry('-3m1', [5.038 5.038 13.772], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Hematite', 'color', 'light blue'),...
  crystalSymmetry('m-3m', [8.3958 8.3958 8.3958], 'mineral', 'Magnetite', 'color', 'light green'),...
  crystalSymmetry('321', [4.913 4.913 5.504], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Quartz-new', 'color', 'light red'),...
  crystalSymmetry('12/m1', [8.56 13 7.17], [90,116,90]*degree, 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Orthoclase', 'color', 'cyan'),...
  crystalSymmetry('-1', [8.153 12.8694 7.107], [93.52,116.46,90.26]*degree, 'X||a*', 'Z||c', 'mineral', 'Albite High', 'color', 'magenta'),...
  crystalSymmetry('12/m1', [8.274 12.991 7.144], [90,116.13,90]*degree, 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Albite - mon', 'color', 'yellow'),...
  crystalSymmetry('-1', [8.194 12.897 14.19], [92.98,115.82,91.15]*degree, 'X||a*', 'Z||c', 'mineral', 'Anorthite', 'color', 'blue'),...
```
In MTEX 4.0.13 this issue will be fixed in the import wizard.

Thank you,

Ralf.
