### ISSUE TITLE
ODF exported (ASCII file) is totally different than the original one

### ISSUE THREAD

**Issue by wanghm02** [mtex-toolbox/mtex#260]
I tried to export the ODF as an ASCii file. The material is magnesium alloy. I used the command export(odf,'odf.txt','Bunge'). A file ('odf.txt') with four columns (three euler angles and 1 weight) was obtained. However the exported odf.txt is totally different than the origin. I re-imported this odf.txt and plot the corresponding pole figures. See attached the pole figures before and after the exporting. There are obviously something missing during the exporting.

The ODF file 'odf.mat' is not supported to upload. Please let me know if you need it. my email address is huamiaow@hotmail.com.

Before the exporting:
![beforeexport](https://user-images.githubusercontent.com/24977664/28319513-1b119138-6b9c-11e7-9803-fde467fd9e99.jpg)
After the exporting:
![afterexport](https://user-images.githubusercontent.com/24977664/28319512-1ae094de-6b9c-11e7-8206-a4c89a787ddd.jpg)

**Comment by ralfHielscher** [comment]
Hi,

you are right there is something wrong. Multiple remarks:

1. Try the command 
```matlab
odf = loadODF('odf.txt',cs,ss,'columnNames',{'Euler 1','Euler 2','Euler 3','weights'})
```
to import your data

2. Have you computed you ODF from pole figure data. If yes, they are most likely not correct. Defocusing correction?

3. Why do you want to export the data and reimport them this way?

Ralf.

**Comment by wanghm02** [comment]
Dear Ralf,

Thanks for the message. I want to use the ODF for my simulation. However I found very strange resulst by using ODF generated. I trusted MTEX so much, that I never suspect the ODF.  It took me a lot of time and eventually find that the ODF is not correct.

I re-import the ODF is to show you that the ODF generated is not correct (I used calcODF(pf)), and hope you can fix this problem.

Best Regards,
Huamiao Wang

发件人: Ralf Hielscher<mailto:notifications@github.com>
发送时间: 2017年8月7日 22:00
收件人: mtex-toolbox/mtex<mailto:mtex@noreply.github.com>
抄送: wanghm02<mailto:huamiaow@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [mtex-toolbox/mtex] ODF exported (ASCII file) is totally different than the original one (#260)


Hi,

you are right there is something wrong. Multiple remarks:

  1.  Try the command

odf = loadODF('odf.txt',cs,ss,'columnNames',{'Euler 1','Euler 2','Euler 3','weights'})

to import your data

  1.  Have you computed you ODF from pole figure data. If yes, they are most likely not correct. Defocusing correction?
  2.  Why do you want to export the data and reimport them this way?

Ralf.

―

**Comment by ralfHielscher** [comment]
Hi Huamiao Wang,

1) have you tried the command I gave you in the last answer?
2) The ODF computed from you pole figure data is probably wrong. Can you send your pole figure data?
3) For simulations it might be better to computet orientations from your ODF and export them, i,e,

```matlab
ori = calcOrientations(odf,100000)
export(ori, fileName)
```

Ralf.

**Comment by wanghm02** [comment]
Dear Ralf,

Yes, I tried. It did not make any difference.
See attached the pole figure data.

The weights of the orientations are all the same when exported in the way you provied. Can we export the orientations with their own weights? It can reduce (significantly) the number of orientations to represent a texture, and therefore save the computational cost.

Best Regards,
Huamiao Wang

发件人: Ralf Hielscher<mailto:notifications@github.com>
发送时间: 2017年8月10日 20:26
收件人: mtex-toolbox/mtex<mailto:mtex@noreply.github.com>
抄送: wanghm02<mailto:huamiaow@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [mtex-toolbox/mtex] ODF exported (ASCII file) is totally different than the original one (#260)


Hi Huamiao Wang,

  1.  have you tried the command I gave you in the last answer?
  2.  The ODF computed from you pole figure data is probably wrong. Can you send your pole figure data?
  3.  For simulations it might be better to computet orientations from your ODF and export them, i,e,

ori = calcOrientations(odf,100000)

export(ori, fileName)

Ralf.

―

**Comment by ralfHielscher** [comment]
In order to work on this issue we require some more information:

1. your script file
2. your data

Ralf.
