### ISSUE TITLE
Possible bug in ODF calculation from *.uxd input format

### ISSUE THREAD

**Issue by nimasant** [mtex-toolbox/mtex#261]
Hello dear Dr. Hielscher;
We use x-ray data provided by BRUKER device to calculate ODF. The data is processed in Multex and the output files (input for Mtex) have *.uxd extension. To process these files calcODF calls loadPoleFigure_uxd.m under interfaces folder. We noticed that this function reads intensities and divides them into two matrices named data{1} and data{2} which later on are assigned to rho and intensity matrices respectively. 

![data](https://user-images.githubusercontent.com/30318794/28419138-ccadf654-6d66-11e7-833d-6e761f4f5347.png)
![theta and rho](https://user-images.githubusercontent.com/30318794/28419147-d5c45e18-6d66-11e7-922a-d266c8ec35fd.png)

This means the half of intensity values are assigned to rho!!! causing irregular distribution of measurement grid points and the other half are used as intensity matrix. 
![pf](https://user-images.githubusercontent.com/30318794/28419392-7a8afa88-6d67-11e7-81f5-ce71c4a58fe4.png)

We tried to fix the issue by reading the whole intensity values into a single variable "data", then simply produced "rho" using the size of variable "data" and "linspace" command. 

A part of an input file is shown below;

![input file](https://user-images.githubusercontent.com/30318794/28421697-9795b986-6d6e-11e7-95d6-dad04b1210ed.png)

Could you please confirm the bug and the correctness of the solution.

**Comment by ralfHielscher** [comment]
Hi,

it looks like the uxd format has changed over the time. Your fix is correct. Could you please send me such a data file and you modifications such that it can be incorporated into MTEX.

Ralf.

**Comment by nimasant** [comment]
Hello, 
Attached you may find a pole figure data file and the modified Matlab file which should be placed under Interfaces folder.

[xud_bug_fix .zip](https://github.com/mtex-toolbox/mtex/files/1207308/xud_bug_fix.zip)

Regards,
Nima.

**Comment by ralfHielscher** [comment]
Thank you very much. I altered your approach a bit such that the interface remains working for the old format as well. It will be included into the next release.

Ralf.
