### ISSUE TITLE
Grain boundary misorientations in specimen reference

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#263]
Hi Ralf,

I am trying to calculate grain boundary misorientations relative to the specimen reference frame using the approach shown on this webpage:
https://mtex-toolbox.github.io/files/doc/BoundaryMisorientations.html

I am doing the following:
```matlab
% set the phase
phase = 'fo';

% compute grains 
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd('indexed'),'angle',10*degree);

% and boundaries
gB = grains.boundary;

% boundaries for a given phase
gB_fo = gB(phase,phase);

% Get ebsd orientations of boundaries
ori= ebsd(gB_fo.ebsdId).orientations
```
The last line gives an error, stating that:
This operatorion is only permitted for a single phase!

When I do the following:
```matlab
e_Gb = ebsd(gB_fo.ebsdId)
```
I see this:
```
e_Gb = EBSD (show methods, plot)
 
 Phase  Orientations     Mineral        Color  Symmetry  Crystal reference frame
     0    4259 (33%)  notIndexed                                                
     1  13338 (102%)  Forsterite  light green       mmm                         
     2    5326 (41%)    Diopside    light red     12/m1        X||a*, Y||b, Z||c
     3    2248 (17%)  Enstatite        yellow       mmm                         
     4    928 (7.1%)    Chromite         cyan      m-3m                         
     5   1 (0.0077%)   Anorthite      magenta        -1              X||a*, Z||c
     6    18 (0.14%)  Hornblende   dark green     12/m1        X||a*, Y||b, Z||c
```
... which seems to indicate that this operation is not properly isolating the ebsd orientations for the 'Forsterite','Forsterite' boundaries. If I subsequently isolate the "Forsterite" orientations by:
e_gB('fo').orientations

the result is:
```
ans = orientation (show methods, plot)
  size: 13338 x 1
  crystal symmetry : Forsterite (mmm)
  specimen symmetry: 1
```
The trouble with that result is it is *not* an Nx2 matrix of orientations as the webpage tutorial suggests, and which I would need to calculate the misorientations relative to the specimen reference frame.

If I try to isolate the Forsterite orientations using the different columns of gB_fo.ebsdId separately (by the following), I get a list of orientations that are slightly different lengths, and I am not sure how to know which are the correct pairings to use.
```matlab
e_gB_ind = gB_fo.ebsdId;
e_gB1 = ebsd(e_gB_ind(:,1));
e_gB2 = ebsd(e_gB_ind(:,2));
e_fo1 = e_gB1('fo')
e_fo2 = e_gB2('fo')
``` 
```
e_fo1 = EBSD (show methods, plot)
 
 Phase  Orientations     Mineral        Color  Symmetry  Crystal reference frame
     1   6666 (100%)  Forsterite  light green       mmm                         
 
e_fo2 = EBSD (show methods, plot)
 
 Phase  Orientations     Mineral        Color  Symmetry  Crystal reference frame
     1   6672 (100%)  Forsterite  light green       mmm                         
 ```

And... of course I cannot calculate the misorientations if the sets of orientations have different number of orientations:

gB_axes_FoFo = axis(e_fo1.orientations,e_fo2.orientations)
Matrix dimensions must agree.

Error in  .*  (line 21)
     a = a1 .* a2 - b1 .* b2 - c1 .* c2 - d1 .* d2;

Error in orientation/axis (line 51)
  q21 = inv(q2).*q1; %#ok<*MINV>

Any help to identify what I am doing incorrectly would be great. 

Thank you much for your time.

Cheers,
Zach

**Comment by ralfHielscher** [comment]
Hi Zach,

your problem is probably, that you did
```matlab
grains = calcGrains(ebsd('indexed'))
gB_Fo = grains.boundary('fo','fo')
```
now ```gB_Fo.ebsdId``` refers to the position in ```ebsd('indexed')```. Hence,
```matlab
ebsdI = ebsd('indexed')
ebsdI(gB_Fo.ebsdId).orienations
```
should give you the desired result.

Ralf.

**Comment by ralfHielscher** [comment]
From the conceptual point of I could introduce

```gB.ebsdInd``` which is the index in an EBSD data set and may change while operating with it and
```gB.ebsdId``` which is the id stored for every measurement and remains the same all the time

actually we have already a function ```ebsd.id2ind``` to convert from id to index. The problem is, if I replace ```gB.ebsdId``` to be the Id and not the index at it is at the moment it will break many existing code.

Ralf.

**Comment by zmichels** [comment]
Dear Ralf,

Thank you very much for the explanation – this makes perfect sense. Also, I am glad to now understand the difference between the id and the index. 

Cheers,
Zach
