### ISSUE TITLE
c_hat

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#267]
Hi Ralf,
is it possible that  https://github.com/mtex-toolbox/mtex/blob/master/tools/statistic_tools/c_hat.m#L22
should be 
` n = length(varargin{1});` instead of ` n = numel(varargin{1});` 
and https://github.com/mtex-toolbox/mtex/blob/master/tools/statistic_tools/c_hat.m#L23
should be 
`[~,q, T, Tv] = mean(varargin{:},'approximated');` instead of `[qm, T, Tv, kappa, q] = mean(varargin{:},'approximated');`
to work as expected?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
You are absolutely right.

Ralf.
