### ISSUE TITLE
How to fill nonindexed holes in orientations?

### ISSUE THREAD

**Issue by TatVai** [mtex-toolbox/mtex#268]
Hi Ralf,

I am new in using Mtex. When I follow the guideline of 
[http://mtex-toolbox.github.io/files/doc/GrainReconstruction.html](url) 'fill nonindexed holes', I found that the phase diagram (grain.) is filled but the colored IPF (ebsd.orientation) is still left holes.
May I ask how to reconstruction the ebsd.orientations after remove all nonindexed part?

Thanks!
Best regards,
TV

**Comment by kilir** [comment]
Hi TV,
if you'd like to generate new orientations for holes (of type 2 as iven in the docu - points that are not in your dataset) you can use ebsd/fill or ebsd/smooth with the 'fill' option.
Cheers, Rüdiger

**Comment by TatVai** [comment]
Thank you Rüdiger!

May I know how to select some grains by grain ID?
For example grain 723 645 650.

Thank you!

**Comment by kilir** [comment]
Hi, the mailing list would be a good place to ask, since it is actually not an issue with mtex and then consider closing this issue as well.
Cheers,
Rüdiger
(grains([723 645 650]) would do what you want)

**Comment by TatVai** [comment]
Hi Rüdiger，
 Got it !  Thank you!
TV
