### ISSUE TITLE
display for 1-by-n sphFunTri

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#269]
Hi Ralf,
I am able to create a 1-by-n sphFunTri (which, for example I'd like to average), however, everythi involving sphFunTri/display errors:
``` matlab
ans = spherical function (show methods, plot)
Error using size2str
Too many input arguments.
Error in sphFunTri/display (line 17)
disp([' ' varlink([inputname(1),'.vertices'],'vertices') ': ',size2str(sF.vertices)])
 ```
My idea was to use somethin (sph1+sph2+...sphn)/sum(mean(sph1)+mean(sph2) ...mean(sphn)) and for convenience storing sph1,...sphn in one sphFunTri object. But maybe that's not hte right way to do it?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this is certainly a good idea. Currently, nothing in this direction is supported. One difficulty is to decide how the functions mean, sum, max, min work in this case. If only one function in in the list they would provide the mean, min, max of the function over the whole sphere. Maybe you have a good syntax idea.

I will think about this and hopefully implement in until our workshop.

Ralf.

**Comment by kilir** [comment]
I guess this is now what SFun is for.

**Comment by ralfHielscher** [comment]
yes :)

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************
