### ISSUE TITLE
about high angle grain boundary and low angle grain boundary

### ISSUE THREAD

**Issue by TatVai** [mtex-toolbox/mtex#271]
Hi

May I know is there any method to list the HAGB and LAGB like the figure below?

Thank you!

![image](https://user-images.githubusercontent.com/31933703/30573492-c7f00522-9d26-11e7-8581-3a5e3184464b.png)

**Comment by zmichels** [comment]
Hi,

One approach: You can calculate grains using a segmentation angle of the "lowest" angle for which you are interested – the result will be a set of grains that include LAGB and HAGB. Then calculate grain boundary misorientations and make a histogram of the corresponding misorientation angles.

Cheers,
Zach

On Sep 18, 2017, at 9:39 PM, TatVai <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

May I know is there any method to list the HAGB and LAGB like the figure below?

Thank you!

[image]<https://user-images.githubusercontent.com/31933703/30573492-c7f00522-9d26-11e7-8581-3a5e3184464b.png>

**Comment by ralfHielscher** [comment]
Have you tried
```matlab
hist(grains.boundary('phaseName','phaseName').misorientation.angle./degree)
```
Ralf.
