### ISSUE TITLE
Incorrect slip plane trace

### ISSUE THREAD

**Issue by plehto** [mtex-toolbox/mtex#272]
https://github.com/mtex-toolbox/mtex/blob/ed9abd9922c1d5ca85cdc9540829e3ecbbcde4b2/doc/TensorAnalysis/TaylorModel.m#L112

This example is plotting the slip plane normal, and not the slip plane trace as it suggests. For consistency with other examples (e.g. https://mtex-toolbox.github.io/files/doc/PlasticDeformation.html), the following should be used:
` quiver(grains,sSGrains.trace,'autoScaleFactor',0.5,'displayName','slip plane trace') `

**Comment by ralfHielscher** [comment]
This is certainly correct. Thank you very much.

Ralf.
