### ISSUE TITLE
mtexColorbar label cut off when logarithmic 

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#274]
Hello,

I am plotting grain maps where the grains are colored by a vector with a large range, such that when I call 'mtexColorbar', the result is a colorbar on a scale of # x 10^n. The top of the colorbar label is cut off, such that the "10^n" value cannot be read. Resizing the figure does not change this. I also tried: 
set(gca, 'ActivePositionProperty', 'OuterPosition')
but this did not fix the problem.

Attached is a simple example to illustrate the issue. Any help on how to circumvent the problem is greatly appreciated.

I am using MATLAB R2017a on a MacBook Air.

Thanks,
Zach

![colorbar_example_cut_off](https://user-images.githubusercontent.com/8769619/30980473-ce4bc6be-a446-11e7-9ae1-9c72ea4d1086.png)

**Comment by kilir** [comment]
Hi Zach,
in mtex_settings_settings.m, setting `setMTEXpref('outerPlotSpacing',10);` to a larger value e.g. 40 should do it.

If for some reason you don't want this, you can shrink the colorbar:
```
cb = mtexColorbar
cbP = cb.Position;
cbP(4)=cbP(4)*0.9;
cb.Position= cbP;
```
Cheers,
Rüdiger

**Comment by zmichels** [comment]
Thanks Rüdiger!

cheers.




On Sep 29, 2017, at 4:13 AM, kilir <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Zach,
in mtex_settings_settings.m, setting setMTEXpref('outerPlotSpacing',10); to a larger value e.g. 40 should do it.

If for some reason you don't want this, you can shrink the colorbar:

cb = mtexColorbar
cbP = cb.Position;
cbP(4)=cbP(4)*0.9;
cb.Position= cbP;


Cheers,
Rüdiger
