### ISSUE TITLE
Old bug in documentation for calcODF use 'weight' not 'weights'

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#275]
I seem to remember this bug has already been reported by me !
Using latest version of MTEX MTEX 4.5.1

This does not work
odf_by_area = calcODF(o_mean_grains,'kernel',psi,'Fourier','weights',g_area)

However in the doc
function odf = calcODF(ori,varargin)
% computes an ODF from individuel orientations
%
% The function *calcODF* applies one of the following algorithms to compute
% an ODF from a list of orientations.
%
% # direct kernel density estimation 
% # kernel density estimation via Fourier series
% # Bingham estimation
%
% Syntax
%
%   % use kernel density estimation with a 10 degree kernel
%   odf = calcODF(ori,'halfwidth',10*degree) 
%
%   % use grain area as weights for the orientations
%   odf = calcODF(grains.meanOrientation,'weights',grains.area)

This does not work
odf_by_area = calcODF(o_mean_grains,'kernel',psi,'Fourier','weight',g_area)

all the best David

**Comment by ralfHielscher** [comment]
I think I fixed this
