### ISSUE TITLE
Plotting a fiber

### ISSUE THREAD

**Issue by ClaesO** [mtex-toolbox/mtex#277]
Hi,
I'm running mtex 4.5.1 and try to plot fibers in some steel data. I am importing XRD data from an intensity matrix "poleInts". The new feature looks great, however, when I run something like:
```
cs = crystalSymmetry('Fm-3m');
ss = specimenSymmetry('orthorhombic');

for i = matNdcs
    pints = poleInts(:, i);
    pf({j}) = PoleFigure(hkls{j}, r, pints(:), 'CS', cs, 'SS', ss);
    j = j+1;
end

odf1 = calcODF(pf);
volume(odf1, alpha, 15*degree);
```
I get the error message:
```
Error using ODF/fibreVolume (line 30)
Only triclinic specimen symmetry is supported for fibreVolume

Error in ODF/volume (line 24)
  v = fibreVolume(odf,center.h,center.r,radius,varargin{:});
```
It appears strange that the fiber function should be limited to triclinic symmetries, or am I doing something wrong?

Best regards,

Claes O.

**Comment by ralfHielscher** [comment]
The volume computation of fibres is indeed restricted to triclinic specimen symmetry. Isn't it possible for you to work with triclinic specimen symmetry?

Ralf.

**Comment by ClaesO** [comment]
Ralf,

Thanks for getting back. I put the specimen symmetry to triclinic, and now it’s working fine.

The reason I want to use an orthorhombic sample symmetry, apart from the fact that I’m looking at steel sheet, is that we are  recording pole figures using full th-th XRD diffractograms in each node point. Extracting the intensities with curve fitting then gives an improved background estimation, resolves overlaps, and also helps in taking care of defocusing effects. If I could limit the data acquisition to the first quadrant and then reconstruct the ODF assuming orthorhombic symmetry, it would save me a couple of hours of measurement per sample, equivalent to some 400 th-th scans / sample.

Thanks for providing a great toolbox,

Claes O.

**Comment by ralfHielscher** [comment]
Hi Claes O.

the restriction to triclinic specimen symmetry has been removed in MTEX 5.0. Would you mind testing it?

Ralf

**Comment by ClaesO** [comment]
Hi Ralf / Sehr geehrter Herr Prof. Dr. Hielscher

Thanx, looks like it’s working fine. This is useful for us.

MfG,

Claes O.
