### ISSUE TITLE
HKLOrientationMapping is broken

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#279]
Hi Ralf,
not that it would be used a lot, but I realized that HKLOrientationMapping does not work due to various lines:
https://github.com/mtex-toolbox/mtex/blob/master/tools/orientationMappings/HKLOrientationMapping.m#L44
should be 
`if any(strcmp(oM.CS1.LaueName,{'m-3m','m-3'}))` instead of `if any(strcmp(cs.LaueName,{'m-3m','m-3'}))`.

https://github.com/mtex-toolbox/mtex/blob/master/tools/orientationMappings/HKLOrientationMapping.m#L20
 `rho = rho - rho_min;` where `rho_min`is not defined
 and similarly `maxTheta` further down seems not to be defined somewhere.
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this seems to be broken for a while already. I think I fixed it for all but triclinic.

Ralf.

**Comment by kilir** [comment]
Hi Ralf, now it works. However there is a slight problem somewhere, running `plot(om,'3d')` (don't do it unless you might have lots or RAM or swap space or can afford to lock up your machine), consumes about 40 GB of memory, a behaviour that luckily color codings do not show.
Cheers, Rüdiger
