### ISSUE TITLE
Blank window when plotting EBSD

### ISSUE THREAD

**Issue by colorblindy** [mtex-toolbox/mtex#28]
Dear MTEX developers:

I get a blank window when trying to plot EBSD data. 
File formats are .osc and .ang. 
I am having this problem in MTEX 4.0.12 and 4.0.10, while MTEX 3.5.0 works fine for the same data. 

Thanks,
Marat.

**Comment by ralfHielscher** [comment]
Hi Marat,

maybe you have a single phase data set. In this case the phase plot
```matlab
plot(ebsd)
```
displays a uniformly colored map. If you want to plot the orientation data you might want to do
```matlab
plot(ebsd,ebsd.orientations)
```
You might also want to look at
http://mtex-toolbox.github.io/files/doc/EBSDSpatialPlots.html

I hope this helps. If not please attache your data and your import script.

Ralf.

**Comment by colorblindy** [comment]
Hi Ralf, 

Thank you for your reply. I have tried plotting for both single-phase and two-phase data sets but still get blank figure windows in some cases. 

I attach an image showing the results of plot command in MTEX 3.5.0 and 4.0.12 for the same data set (single phase, osc format). The data set is available here: https://dl.dropboxusercontent.com/u/19156272/Cu_x500-test.osc

Thank you, 
Marat. 

![plotebsd](https://cloud.githubusercontent.com/assets/11174975/6391283/09774dc2-bdf8-11e4-8332-955416765631.png)

**Comment by ralfHielscher** [comment]
Hi Marat,

maybe this is a Matlab related bug. You might want to try 
``` matlab
plot(ebsd,ebsd.orientations)
set(gcf,'renderer','zBuffer')
```
I get this one
![ebsd](https://cloud.githubusercontent.com/assets/8619241/6392711/d7c057b2-bdc3-11e4-9eb0-41569fe60bc9.png)

**Comment by colorblindy** [comment]
Thank you, Ralf, that command solved the problem.
