### ISSUE TITLE
axisAngleOrientationMapping lost symmetry

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#280]
Hi Ralf, somewhere starting with Mtex 4.4 up to now Mtex 4.5.2 the axisAngleOrientationMapping seems to have lost symmetry.
`plot(axisAngleOrientationMapping(crystalSymmetry('321')),'axisAngle')`
just has 2  magneta-blue regions but I guess it should have 3.
![axang](https://user-images.githubusercontent.com/11697557/32417496-0356973a-c25b-11e7-96b6-f600a28b75f1.jpg)
Similar things happen for other crystal symmetries.
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you very much for pointing this out.

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by kilir** [comment]
Hi Ralf,
works for me, thank you!
Cheers,
Rüdiger
