### ISSUE TITLE
figure of linearCompressibility

### ISSUE THREAD

**Issue by sagetu** [mtex-toolbox/mtex#286]
I have plotted the figure of linearCompressibility,but it just like a reel of string,it is so strange andI didnot find mistake in my code.

**Comment by ralfHielscher** [comment]
Maybe sharing your code would increase our chances of understanding your issue :)

**Comment by sagetu** [comment]
![default](https://user-images.githubusercontent.com/33057699/33226102-853f4656-d1c0-11e7-8cc1-e8aa5920e877.PNG)

**Comment by zmichels** [comment]
Hi,

What is the specific code you are using to arrive at this figure? If you can share that, it may help the rest of us understand how best to help you do what you want to do.

Best,
Zach


On Nov 24, 2017, at 7:12 PM, sagetu <notifications@github.com<mailto:notifications@github.com>> wrote:


[default]<https://user-images.githubusercontent.com/33057699/33226102-853f4656-d1c0-11e7-8cc1-e8aa5920e877.PNG>
