### ISSUE TITLE
issue for the shape preferred orientation ploting

### ISSUE THREAD

**Issue by lwlgeo** [mtex-toolbox/mtex#287]
i am trying to plot the long axis distribution of the grain related to the lineation. it seems like the something wrong with the maxtix: Theta = atan2(ev(1,2,:),ev(1,1,:))/degree
below is the problematic script
```matlab
%% Angle of grain long axis from EBSD map X-axis
    % Principle components using SVD analysis
    % Eigen-vectors (ev) Eigen-values (ew)
[ev,ew]= principalComponents(grains_selected('Forsterite'),'Hull');
    %% Angle from X-axis using Eigen-vectors (ev)
Theta = atan2(ev(1,2,:),ev(1,1,:))/degree;
   %% Remove unwanted singleton dimensions
Theta=squeeze(Theta);
    %% keep angles in the range 0-180 degrees from X-axis
for i=1:length(Theta)
    if(Theta(i)<0)
       Theta(i) = 180 + Theta(i);
    end
end
    % Mean, Standard deviation and median
mean_Theta_ol = mean(Theta);
StD_Theta_ol = std(Theta);
median_Theta_ol = median(Theta);
```

**Comment by kilir** [comment]
Hi,
it seems you're using a snippled from a script from some years ago. The syntax of principalComponents has changed and the output contains [angle, long axis, short axis] by now. Have a look at help principalComponents.
Cheers,
Rüdiger

**Comment by lwlgeo** [comment]
thanks, yes, i nail it down  with the new function.
