### ISSUE TITLE
Calculation of Schmid factor

### ISSUE THREAD

**Issue by Kevineta** [mtex-toolbox/mtex#288]
Hi,
I'm trying to calculate schmid factors for the slip direction in slip planes as the shear direction is changed.
I googled the code from Ralf Hielscher in this forum and attached that code.
My question is in the end of the code

========================================================================
``` matlab
% crystal symmetry
CS = crystalSymmetry('6/mmm', [2.95,2.95,4.686], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Ti-Hex', 'color', 'light blue');

% Grain orientation Euler angles
ori = orientation('Euler', 0*degree, 0*degree, 0*degree, CS);

%%
% Obtain loading directions in terms of the crystal orientation
% [1 0 -1 0], [-1 2 -1 0] and [0 0 0 1] in three index array to multiply
% with g matrix

xcs = round(inv(ori) * xvector);
ycs = round(inv(ori) * yvector);
zcs = round(inv(ori) * zvector);

%%
% {0001} Slip Shear direction

mx = Miller(1,1,-2,0,CS,'uvw');


% Plane

k = Miller(0,0,0,1,CS,'hkl')

% there is not so much a difference between k and nx
nx = k; nx.dispStyle = 'uvw';

% Find symmetrically equivalent slip and plane normal directions
[m,l] = symmetrise(mx,CS)
[n,l] = symmetrise(nx,CS)

 
plot(m,'antipodal')
hold all
plot(n)
hold off

%%

rx = xcs, ry = ycs, rz = zcs

% Find planes and directions that are normal

[r,c] = find(isnull(dot_outer(vector3d(m),vector3d(n))));
m = m(r); n = n(c);
 
plot(m,'antipodal')
hold all
plot(n)
plot(rx)
hold off

%%
% Calculate individual Schmid factors by calculating the angles

% you wrote here "degree - angle_outer(m(i),rx)" which makes no sense
anglem = angle_outer(m,rx);
anglen = angle_outer(n,rx);
   
tau = cos(anglem).*cos(anglen);
  
if length(m)>1

  [tauMaxx,ind] = max(abs(tau));
  m = m(ind);
  n = n(ind);
else
  tauMaxx = tau;
  ind = ones(size(tauMaxx));
end
```
Maybe, the following lines of code do a better job and are more understandable
```matlab
% stress Tensor
loadingDirection = xvector;

sigma = EinsteinSum(tensor(loadingDirection),1,tensor(loadingDirection),2,'name','stress')

% {0001} Slip Shear direction

k = Miller(0,0,0,1,CS,'hkl')
m = Miller(1,1,-2,0,CS,'uvw')

%// the maximum Schmid factor this slip system
[tauMax,mActive,nActive] = calcShearStress(sigma,m,k,'symmetrise')
```
========================================================================

Finally I want to calculate schmid factor in terms of other loading direction (like [11-21] and [10-11]) as well as [10-10], [-12-10], [0001]. Which values can I put as loadingDirection?
``` matlab
% [1 0 -1 0], [-1 2 -1 0] and [0 0 0 1] in three index array to multiply
% with g matrix
xcs = round(inv(ori) * xvector);
ycs = round(inv(ori) * yvector);
zcs = round(inv(ori) * zvector);
% stress Tensor
loadingDirection = xvector;
```
In the case, loadingDirection is xvector which means the direction [10-10].
But he did put the xvector  as loading direction, not xcs.
How can I do If I calculate schmid factor for the slips system <11-20>{0001} plane when loading direction is [11-21]?

I put the "Miller(1,1,-2,1,CS,'uvw')" into loadingDirection, but I got the wrong values.

**Comment by ralfHielscher** [comment]
Dear Kevineta,

the syntax for computing Schmid factors has been significantly improved with MTEX 4.5. You can proceed now as follows

```matlab
CS = crystalSymmetry('6/mmm', [2.95,2.95,4.686], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Ti-Hex', 'color', 'light blue');

% define a slip system
sS = slipSystem.basal(CS)

% define a loading direction
loadingDirection = Miller(1,1,-2,1,CS)

% compute the Schmid factor for the slip system sS
SF = SchmidFactor(sS,loadingDirection)

% compute the Schmid factor for all slip systems symmetrically equivalent  to sS
SF = SchmidFactor(sS.symmetrise,loadingDirection)
```
I hope this helps,
Ralf.

**Comment by MGRashed** [comment]
Hi Ralf,

There are several approaches to calculate Schmid factor in the MTEX documentation -
- https://mtex-toolbox.github.io/files/doc/PlasticDeformation.html
- https://mtex-toolbox.github.io/files/doc/SlipTransmition.html
- https://mtex-toolbox.github.io/files/doc/StrainAnalysis.html

Your snippet above is another one, which approach is best from a general point of view?

**Comment by Kevineta** [comment]
Hi Ralf,
The syntax you inform me is very simple. I have one more question.

When we define a slip system, the syntax "sS = slipSystem.basal(CS)" is only considered for <11-20>{0001} slip systems.

I want to check various slip direction on various planes (basal, pyramidal, prismatic, comp. twin plane and tension twin plane, ...).

For example, I want to find the schmid factor <-12-10> slip direction on {10-10} plane, not on basal plane when loading direction is <11-21>.

CS = crystalSymmetry('6/mmm', [2.95,2.95,4.686], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Ti-Hex', 'color', 'light blue');

% define a slip system
b=Miller(-1,2,-1,0, CS)
n=Miller(1,0,-1,0,CS)
sS = slipSystem(b, n)

% define a loading direction
loadingDirection = Miller(1,1,-2,1,CS)

% compute the Schmid factor for the slip system sS
SF = SchmidFactor(sS,loadingDirection)

% compute the Schmid factor for all slip systems symmetrically equivalent  to sS
SF = SchmidFactor(sS.symmetrise,loadingDirection)

Is it no problem? I think there's another method to replace .basal to another one.

**Comment by ralfHielscher** [comment]
Q1. This is ok. There is a list of predefined slip systems. Try ```slipSystem.``` and then press the tabulator key to see which else are defined. You can also look up the file slipSystem with
``` matlab
edit slipSystem
```

Q2.
``` matlab
[maxSF,id] = max(SF,[],2)
```
gives the maximum of all Schmid factors with respect to all slip systems and the id of the active slip system. This works also with many loading directions.

Ralf.

**Comment by Kevineta** [comment]
Hi Ralf,

Oh I forgot to press the Tab key because I'm using Matlab for a long interval.

All I want exists inside of the func. of slipSystem.
So if the material I treat was something special for slip system, I could modify the slipSystem func.

Really thank you so much for your reply.
