### ISSUE TITLE
remove not indexed area

### ISSUE THREAD

**Issue by lwlgeo** [mtex-toolbox/mtex#289]
Hi, everyone
there is large notindexed area in my data, and i want to remove it first and then compute the grains, or else the computed grains will be overestimated. here is the script;
```matlab
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd);
notIndexed = grains('notIndexed')
toRemove = notIndexed(notIndexed.grainSize ./ notIndexed.boundarySize<1)
ebsd(toRemove) = []
```
I want to put all the data after the removing step into a new ebsd matrix (create a new name like ebsd_indexed), and keep the origin ebsd as it is. how can i do that?

**Comment by ralfHielscher** [comment]
Most easiest solution
```matlab
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd);
notIndexed = grains('notIndexed')
toRemove = notIndexed(notIndexed.grainSize ./ notIndexed.boundarySize<1)
ebsd_indexed = ebsd
ebsd_indexed(toRemove) = []
```

**Comment by lwlgeo** [comment]
it works! and thank you very much.
