### ISSUE TITLE
generic ASCII ODF export on a regular grid produces malformed files

### ISSUE THREAD

**Issue by jgawad** [mtex-toolbox/mtex#290]
# Synopsis

export_generic produces ASCII files with redundant (repeated) grid points on a supposedly regular grid. Due to the repetitions some other grid points are omitted, given that the number of grid points is correct. 

# Details 
## Reproducer
See the code below:
```
CS = crystalSymmetry('m-3m');
SS=specimenSymmetry('triclinic');
odf = uniformODF(CS, SS);
% Case 1: regular grid
S3G_regular = regularSO3Grid(CS,SS,'resolution', 5.0*degree);
export_generic(odf, 'uniform_regular.txt', S3G_regular,'BUNGE');
% Case 2: regular grid by slices
S3G_slices = regularSO3Grid(CS,SS, 'phi2', 'sections', 19);
export_generic(odf, 'uniform_slices.txt', S3G_slices,'BUNGE');
```
It produces two files, each should contain a generic ASCII representation of the uniform ODF on a regular grid (see the attached output files  [uniform_regular.txt](https://github.com/mtex-toolbox/mtex/files/1517084/uniform_regular.txt) and [uniform_slices.txt](https://github.com/mtex-toolbox/mtex/files/1517085/uniform_slices.txt)).

## Issue

The two output files are identical and contain ODF intensities a grid. However, the grid departs from regularity on many places, includes redundant blocks and omits data points. See the lines: 
1444, 2811, 4178, 5545, 6912, 8279, 9646, 11013, 12380, 13747, 15114, 16481, 17848, 19215, 20582, 21949, 23316.

For instance, line 1444 contains repeated value at phi1=0, Phi=0, phi2=0.

For instance, lines 23316 - 23332 contain:
```
0.00000 0.00000 0.00000 1.00000
5.00000 0.00000 0.00000 1.00000
10.00000 0.00000 0.00000 1.00000
15.00000 0.00000 0.00000 1.00000
20.00000 0.00000 0.00000 1.00000
25.00000 0.00000 0.00000 1.00000
30.00000 0.00000 0.00000 1.00000
35.00000 0.00000 0.00000 1.00000
40.00000 0.00000 0.00000 1.00000
45.00000 0.00000 0.00000 1.00000
50.00000 0.00000 0.00000 1.00000
55.00000 0.00000 0.00000 1.00000
60.00000 0.00000 0.00000 1.00000
65.00000 0.00000 0.00000 1.00000
70.00000 0.00000 0.00000 1.00000
75.00000 0.00000 0.00000 1.00000
80.00000 0.00000 0.00000 1.00000
```
which is a part of the ODF already covered by lines 5 - 21. 

## Testing environment 
MTEX 4.5.2, Matlab 2017b, Ubuntu, x64

# Remarks

The issue might have a connection to #260 and [issue reported here](https://groups.google.com/forum/#!topic/mtexmail/uHE4BELEaGs).

**Comment by ralfHielscher** [comment]
Dear jgawad,
your observation is correct. The point is, that the Eulerian angles (0 0 10) defines the same orientation as (10 0 0) or (5 0 5). I understand that this is confusing especially if one expects a regular grid. Though the function values are correct and the grid is a regular one, only the displayed Euler angles are not what you expect.

If have fixed this in the developer branch. It would be nice if you could check this.

Ralf.

**Comment by jgawad** [comment]
Dear Ralf,

Thanks for your response and implementing a fix.

I cannot help but comment that the reason for exporting an ODF is usually to pick up the data in some downstream software. It would be nice that the downstream software does not have to be aware of all the intricacies related to the Euler angles. So, if MTEX promises a _regular grid_, let it be a regular grid and keep it as simple as possible.

best regards,
Jerzy
