### ISSUE TITLE
Misorientation between phase  mononclinic and orthorhombic

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#291]
Version MTEX 4.5.2

Plotting  misorientations 3D space for mononclinic - orthorhombic space it is clear the c-axis(blue) in plot has upper hemisphere and lower hemisphere  projections.

The uniform misorientation 2D plot for mononclinic - orthorhombic has only upper hemisphere

The axis/angle plots also has only upper hemisphere
[3D_Misoreintation_TiClinohumiteP21b_Forsterite_misorientation_axes_correlated.tif.pdf](https://github.com/mtex-toolbox/mtex/files/1522028/3D_Misoreintation_TiClinohumiteP21b_Forsterite_misorientation_axes_correlated.tif.pdf)
[Al95_15d_corr_Large_map_TiClinohumiteP21b_Forsterite_Boundary_Misorientation_contours2.tif.pdf](https://github.com/mtex-toolbox/mtex/files/1522030/Al95_15d_corr_Large_map_TiClinohumiteP21b_Forsterite_Boundary_Misorientation_contours2.tif.pdf)
[Al95_15d_corr_TiChu_small_mapTiClinohumiteP21b_Forsterite_misorientation_axes_correlated.tif.pdf](https://github.com/mtex-toolbox/mtex/files/1522033/Al95_15d_corr_TiChu_small_mapTiClinohumiteP21b_Forsterite_misorientation_axes_correlated.tif.pdf)

It appears to me that only 3D plot is consisentent with the data for mononclinic - orthorhombic space

There is no antipodal option for mononclinic - orthorhombic space
as exchange symmetry where O1 and O2 can swap does not operate as they are difference symmetries.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

your observations are completely correct. This is mostly a plotting issue and not that simple to resolve. Do you heavily rely on it?

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

I understand it is rather complex to have upper and lower hemisphere section plots with serial axis/angle sections, but for phase transformation or reactions involving chemical alteration (hydration or dehydration, oxidation etc) we typically have difference symmetry for the two phases.

May be the simplest solution is to have the possibility to do serial sections in axis/angle plot where can specify the hemisphere, upper or lower.

Then for the users who want to make two axis/angle section plots for upper and lower, then they have the complete representation. In terms of programming this would be rather like what you have given us for pole figures.

If this plot option (hemisphere; upper or lower) I would certainly use it, yes. The 3D plot is very nice for lectures and presentations, but to present the data in paper we need contoured axis/angle section plots. 

For axis/angle with points plot you could have different symbol for upper and lower hemisphere data.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

I did a quick check. For me
``` matlab
ori = orientation.rand(10,Clinohumite_CS_unique_c_axis,Forsterite_CS)
figure(1)
plotSection(ori,'upper')
figure(2)
plotSection(ori,'lower')
```
gives a complete representation of the orientation space. Maybe this is sufficient for the moment? I could give a warning if both hemispheres are required but `upper` or `lower` are not specified.

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

Many thanks I try out. 

all the best David
