### ISSUE TITLE
.ang EBSD: Assign EBSD 'no data' to not indexed

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#293]
In reference to https://groups.google.com/forum/#!topic/mtexmail/XkihnlCkano.

TSL .ang files contains no data for positions where there's no indexing.
Example: EBSD data of the same area with and without holes(clean):

[ang_empty2notIndexed.zip](https://github.com/mtex-toolbox/mtex/files/1532854/ang_empty2notIndexed.zip)

I wrote a function to compare the x and y values of the ang file with those that should be present if the 'noData' values were assigned as 'notIndexed'. It can be merged into loadEBSD_ang with small modifications and maybe some better coding than mine (should come before possibly rotating spatial data in case 'convertSpatial2EulerReferenceFrame' is chosen).

``` matlab
function ebsd_new = empty2notIndexed(ebsd, fname)
% assign empty values in .ang file as 'notIndexed'

hl = file2cell(fname,500); % read header (first 500 lines)

gridType = validatestring('# GRID: ',hl);
gridType = erase (gridType,'# GRID: ');

if strcmp(gridType,'HexGrid')
    Xstep = validatestring('# XSTEP: ',hl); %find position of X step
    Xstep = str2double(erase (Xstep,'# XSTEP: ')); %get the number of xtep, erasing text

    % Ystep = validatestring('# YSTEP: ',hl);
    % Ystep = str2double(erase (Ystep,'# YSTEP: '));
    Ystep = Xstep*sin(pi/3);

    nColsOdd = validatestring('# NCOLS_ODD: ',hl);
    nColsOdd = str2double(erase (nColsOdd,'# NCOLS_ODD: '));

    nColsEven = validatestring('# NCOLS_EVEN: ',hl);
    nColsEven = str2double(erase (nColsEven,'# NCOLS_EVEN: '));

    nRows = validatestring('# NROWS: ',hl);
    nRows = str2double(erase (nRows,'# NROWS: '));

    %x_base=[0,1,2...maxX, 0.5,1.5...maxX-0.5]; X values repeat in this order
    x_base=[0: Xstep: (nColsOdd-1)*Xstep, (Xstep/2):Xstep: nColsEven*Xstep];
    x = repmat(x_base',floor(nRows/2),1);
    if rem(nRows,2)~=0 % odd number of X
        x=[x;(0: Xstep: (nColsOdd-1)*Xstep)'];
    end
    
    %y_base=[0,0...0, stepSize*sind(60).....maxY]; Y values repeat in this order
    y_base=(0:Ystep:Ystep*nRows-Ystep)'; %
    
    % y2=repelem(y_base',nRows/2); % Doesn't work when nColsEven ~= nColsOdd
    % if there's no better solution, loop:
    y=[];
    for i=1:nRows
        if mod(i,2) %odd column
            y_array = repmat(y_base(i),nColsOdd,1);
        else % even column
            y_array = repmat(y_base(i),nColsEven,1);
        end
        y = [y;y_array];
    end
    
    %concatenate x,y:
    xy=[x,y];

    %Find the coordinates of empty points
    tol=1.E-4; % tolerance
    xy_ang=[ebsd.prop.x,ebsd.prop.y];
    idEmpty=find(~ismembertol(xy,xy_ang,tol,'ByRows',true));
    
    if isempty(idEmpty)
        ebsd_new=ebsd;
    else
        % create ebsd data for notIndexed phase
        oris= repmat(orientation(nanquaternion), length(idEmpty), 1);
        phase = -ones(length(idEmpty), 1); 
        cs = {'notIndexed'};     
        
        %Get the same EBSD properties , assign all as 0
        existingProps=fieldnames(ebsd.prop);
        for i=1:length(existingProps)
            eval(['opt.',existingProps{i},'=zeros(length(idEmpty),1);']);
        end
        opt.x = xy(idEmpty,1); 
        opt.y = xy(idEmpty,2); 
        
        %Create EBSD data
        ebsd_empty = EBSD(oris,phase,cs,'options',opt); 

        %concatenate ebsd
        ebsd_new=[ebsd,ebsd_empty];       
    end
% else
    %it is square grid ('SqrGrid'), or no grid ('NoGrid'). Should do something?
%     ebsd_square=ebsd.gridify;
%     ebsd_empty=ebsd_square(isnan(ebsd_square.prop.sem_signal)); 

end
%% Tests
%     length(idEmpty)==length(xy)-length(xy_ang) % this must be true
    % check if find by location is working properly (otherwise delta tolerance must be reduced):
%     isempty( ebsd(xy(idEmpty,1),xy(idEmpty,2)))% % this must be true
end

```
Filippe

**Comment by kilir** [comment]
Hi Filippe,
one way to do that is the following
```
ebsd('notIndexed')=[]; % create some input to mimick an .ang file
% usually gridify and reassembling should also do the trick
ebsd=ebsd.gridify;
ebsd=EBSD(ebsd.rotations,ebsd.phase, ebsd.CSList,'options',ebsd.prop)
```
The result will not be a gridified EBSd but contain again notIndexed pixels
Cheers,
Rüdiger

**Comment by filippeof** [comment]
Hi Rüdiger,
Many thanks for your answer. 
I think I might be missing something:  By using ebsd.prop in the last line I am getting the coordinates of the gridified EBSD, changing ebsd to a square grid:
``` matlab
fname = 'small_hexTSL_2.ang'

CS = {'notIndexed',...
  crystalSymmetry('mmm', [4.762 10.225 5.994], 'mineral', 'olivine', 'color', 'green')};

setMTEXpref('xAxisDirection','east');setMTEXpref('zAxisDirection','intoPlane');

ebsd = loadEBSD(fname,CS,'interface','ang',...
      'convertSpatial2EulerReferenceFrame');
figure;plot(ebsd('ol'),ebsd('ol').orientations)
```
![image](https://user-images.githubusercontent.com/11142094/33690211-e96cd44c-dae2-11e7-986e-a2ca0fbf532a.png)
``` matlab
ebsd=ebsd.gridify;
ebsd(isnan(ebsd.prop.ci)).phaseId=-1;
ebsd(isnan(ebsd.prop.ci)).phase=-1; 
ebsd=EBSD(ebsd.rotations,ebsd.phase, ebsd.CSList,'options',ebsd.prop);
figure;plot(ebsd('ol'),ebsd('ol').orientations);
```
![image](https://user-images.githubusercontent.com/11142094/33690221-efa0e89e-dae2-11e7-8143-d575add8c61b.png)

Is there something I should include to recognize it as hexGrid?
Cheers,
Filippe

**Comment by kilir** [comment]
Hi Filippe,
I see, I didn't think of a hexgrid at all but in that case it makes sense to stay away from ebsdSquare and my answer won't work.
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Filippe,

thank you very much for your code. I do completely understand the need of such a function. The initial idea was to implement ebsd.gridify also for hex grids which should then return a variable of type EBSDhex instead of EBSDsquare. I think this is a nice student project. In the meantime your solution is very good. There are two things I would like to be improved:

1. maybe we can do this conservation without reimporting the ang file? E.g., ebsd.unitCell should tell you whether the grid is hex and also the grid parameters.

2. The commands used for string manipulation are rather new, i.e., from 2016b. I would like to have MTEX a bit more backward compatible.

Thank you again for your function.

Ralf.

**Comment by filippeof** [comment]
Dear Ralf,
Thanks for the suggestions. I  include this function inside loadEBSD_ang.m and modified it in order to:
- Read the headerLines from 'hl' instead of reimporting the ebsd file
- Replace functions that were not implemented before R2015a.
But I am not really sure how to use unitCell to check the spatial parameters so I am still reading it from the headerLines. Please check commit: 
https://github.com/filippeof/mtex/commit/99888311d96e8eda3787e65f87601368e070ba18

Regards,
Filippe

**Comment by ralfHielscher** [comment]
I think with gridify now working for hex grids I can close this.

Ralf.
