### ISSUE TITLE
Predefined ORs

### ISSUE THREAD

**Issue by ks-or** [mtex-toolbox/mtex#296]
Hi,

I am wondering why the GT-OR is not defined like in the literature [1-3]:
``
{111}_y || {110}_a  and <5 12 17>_y || <17 17 7>_a
``
instead of the definition in orientation.m:

``
mori = inv(orientation('Euler',2.7*degree,46.6*degree,7.5*degree,csAlpha,csGamma));
``

The definition of the Pitsch-OR is also wrong. It was postulated by Wolfgang Pit**S**ch in 1962 [4]:  

``
function mori = Pitch(csGamma,csAlpha)
``
The "s" is missing in orientation.m.

Regards,
Michael

----

[1] Greninger, Alden B., and Alexander R. Troiano. "The mechanism of martensite formation." JOM 1.9 (1949): 590-598.
[2] Barcelo, F., Bechade, J.-L., & Fournier, B. (2010). Orientation relationship in various 9%Cr ferritic/martensitic steels–EBSD comparison between Nishiyama–Wassermann, Kurdjumov–Sachs and Greninger–Troiano. Phase Transitions, 83(8), 601–614. https://doi.org/10.1080/01411594.2010.502054
[3] He, Y., Godet, S. & Jonas, J. J. (2006). J. Appl. Cryst. 39, 72-81.
[4] Pitsch, W. (1962). Acta Metall. 10, 897–900.

**Comment by ralfHielscher** [comment]
Dear Michael,

thank you for pointing this out. Could you please verify that
```matlab
GT2 = orientation('map',Miller(1,1,1,csGamma),Miller(1,1,0,csAlpha), 
... Miller(5,12,17,csGamma,'uvw'),Miller(17,17,7,csAlpha,'uvw'));
```
would be the correct definition. 

And beside the missing "s" the Pitsch-OR is ok?

Ralf.

**Comment by ralfHielscher** [comment]
Dear Michael,

I checked this once again and realized that the misorientation you think is correct is almost Kurdjumov Sachs, whereas Greninger Trojano should be approximately in the middle between Kurdjumov Sachs and Nishiyama Wassermann. This was satisfied by the old definition. For that reason I went back to the old definition.

Ralf.

**Comment by ArianeNeves** [comment]
Dear Ralf,
The Euler angles for G-T OR are phi1 = 2.7°, PHI = 46.6° and phi2 = 7.5°. According to MTEX, the Euler angles corresponds to (110)d || (111)p (2 -2 -3)d || (2 1 -3)p. However, I usually see the parallelism {110}d ||| {111}p <113>d || <123>p in the papers that citing the Greninger’s paper listed below:

Greninger, A.B., Troiano, A.R. The mechanism of Martensite formation. JOM 1, 590–598 (1949). https://doi.org/10.1007/BF03398900

Why is there such a difference?
