### ISSUE TITLE
S2FunHarmonic/sum bug?

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#303]
Hi Ralf,
if, according to the changelog `sum(sF.^2)`should return the pole figure index (
https://github.com/mtex-toolbox/mtex/blob/develop/doc/ReleaseNotes/changelog.m#L54)
then I'd expect `sum(calcDensity(vector3d.rand(100000),'halfwidth',30*degree).^2)`to return something close to 1. However the result is close to 4*pi.
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
you are right. This is a question of normalization, which I have not yet finally decided. In the meantime 
```
mean(calcDensity(vector3d.rand(100000),'halfwidth',30*degree).^2)
```
should give the expected result.

**Comment by kilir** [comment]
Ok, I just thought in this context the note in the changelog might be a litttle misleading. So I might leave this up till you decided which way to go.
