### ISSUE TITLE
Different results of kde for equispaced and regularS2Grid

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#307]
Dear all,
I was trying to estimate the vector3d which has the maximum density with the kernelDensityEstimation function (MTEX 4.5.2):
```matlab
ax=gb.misorientation.axis;

% S2G = regularS2Grid('resolution', [0.5*degree, 0.5*degree],'antipodal');
S2G = equispacedS2Grid('RESOLUTION',0.5*degree,'antipodal');

kde = kernelDensityEstimation(ax,S2G,'antipodal');
[~,id]=max(kde);
plot(S2G,kde,'antipodal');hold on
plot(S2G(id),'antipodal','MarkerSize',10);hold off
```
The output for 'regular' shows a repetition of the values in the outer rim,  while  for 'equispaced' looks ok:

regular            |  equispaced
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11142094/35965465-30c9e186-0cbb-11e8-9a16-03a98d22b7f0.png)  |  ![](https://user-images.githubusercontent.com/11142094/35965486-44d0df22-0cbb-11e8-976d-9385b040eadc.png)

plotAxisDistribution also shows the maximum value away from the correct maximum:

Axis distribution            |  -zoomed in
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11142094/35965815-57925ffe-0cbc-11e8-9517-5522b26fdb71.png)  |  ![](https://user-images.githubusercontent.com/11142094/35965802-4f8a8d54-0cbc-11e8-8684-29c2c24d88f3.png)

**Comment by ralfHielscher** [comment]
This is indeed a bit strange. Can you attach the list of misorientations.

Ralf.

**Comment by filippeof** [comment]
Attached the gb misorientations:
[gb_mis.mat.zip](https://github.com/mtex-toolbox/mtex/files/1707141/gb_mis.mat.zip)

**Comment by ralfHielscher** [comment]
Hi Filippe,

this seems to be a plotting issue. Your are not supposed to produce smooth plots like you did it in the posting. To this end we have
```matlab
S2G = plotS2Grid('resolution', 0.5*degree,'antipodal'); % this is the correct grid type
pcolor(S2G,kde,'antipodal');                            % this is the correct plotting command
```
Maybe you would like to give MTEX 5.0 a try. There grids are not needed at all and the determination of the maximum is much more accurate.
```matlab
kde = calcDensity(ax,'antipodal'); % this is now a spherical function
pcolor(kde) % which we can plot
[~,ax_max]=max(kde); % or seach for a maximum
annotate(ax_max,'MarkerSize',10);
```

**Comment by filippeof** [comment]
Hi Ralf,
Thank you for clarifying. I didn't find 'kernelDensityEstimation' in MTEX 5 but good to know that there's a replacement. Both approaches gave the expected result now.
Regards,
Filippe

**Comment by ralfHielscher** [comment]
you can call ```calcDensity``` also with a grid for evaluation, i.e.,
```matlab
kde = calcDensity(ax,S2G,'antipodal')
```
