### ISSUE TITLE
Antipodal in S2Fun

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#309]
Hi Ralf,
how would one define a very simple antipodal spherical function. My attemps below seem to be either wrong or there's a bug somewhere?

![antipodal](https://user-images.githubusercontent.com/11697557/35979804-8cbeef62-0ce9-11e8-9bce-65a19dfe3979.jpg)
```
f = @(v) [v.x];
sF1 = S2FunHarmonic.quadrature(f, 'bandwidth', 30)
sF2 = S2FunHarmonic.quadrature(f, 'bandwidth', 30,'antipodal')

plot(sF1,'antipdoal')
f=gcm; 
plot(sF2,'parent',f.nextAxis)
```
I also tried `S2FunHarmonicSym`with `-1`as a summetry with no success.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

your syntax is correct and so is the result. Just have a look at the Fourier coefficients
```matlab
plotSpektra([sF1,sF2])
```
and you will see that you started with an entirely odd function the even part of which is zero.
Ralf

**Comment by kilir** [comment]
Ok,
I guess I need to learn about this a bit. In the mean time I figured what I actually tried to do: define an antipodally symmetric bump on the sphere and this works:

```
mu=xvector;
k=15
c=k/(4*pi*sinh(k));
f = @(v) c*exp(k*dot(mu,v))
sF = S2FunHarmonic.quadrature(f, 'bandwidth', 50)
sF.antipodal=1
plot(sF)
```

Cheers,
Rüdiger
