### ISSUE TITLE
plotPDF and new plotting system: issue with superposing plots 

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#313]
Hi Ralf,
is there any way to tell `plotPDF` to superose plots/axes? This used to work very nicely with the old plotting system, however, now when I do: 
```
h = [Miller(0,0,0,1,odf.CS) Miller(1,1,-2,0,odf.CS)]
plotPDF(odf,h,'smooth')
hold on
plotPDF(odf,h,'contour','contours',[1,2,3], ...
    'lineColor','k','linewidth',2)
hold off
f=gcm
f.drawNow
```
I get this result.

![1_plot](https://user-images.githubusercontent.com/11697557/36344965-abecc360-1422-11e8-9c5e-baae92cc5fbb.jpg)

And when I try to call the axes directly for every pole figure, it sort of works, but the the figure ends up with some empty, but labeled axes:
``` 
f=newMtexFigure;
for i=1:length(h)
plotPDF(odf,h(i),'smooth','parent',f.gca)
hold on
plotPDF(odf,h(i),'contour','contours',[1,2,3], ...
    'lineColor','k','linewidth',2,'parent',f.gca)
hold off
if i~=length(h); f.nextAxis; end
end
f.drawNow
```
![2_plot](https://user-images.githubusercontent.com/11697557/36344976-03c8fdce-1423-11e8-88fc-5a4628f7bc32.jpg)

The reason why I want to do this is to have a smooth plot but with one or more contourlines at specific levels.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
with the newest commit you can at least do
```matlab
h = [Miller(0,0,0,1,odf.CS) Miller(1,1,-2,0,odf.CS)]
plotPDF(odf,h,'smooth')
hold on
f=gcm
f.currentId = 1
plotPDF(odf,h,'contour','contours',[1,2,3], ...
    'lineColor','k','linewidth',2)
hold off
f.drawNow
```

**Comment by kilir** [comment]
May there's still somethign missing? Doing exactly this, it just gives the last plot:
![3_plot](https://user-images.githubusercontent.com/11697557/36345426-3f762a16-142a-11e8-99d3-f2859103541d.jpg)

**Comment by ralfHielscher** [comment]
```hold on``` should be after ```f.currentId = 1```

**Comment by kilir** [comment]
Juhuu, excellent, it works! Thanks.
I'm not sure if anybody else would do something like that, but maybe  I could put a note how to do that somewhere?
Closing.
