### ISSUE TITLE
Set mtexFigure nrows and ncols

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#315]
I am not sure if it's either not implemented yet or my syntax is wrong but would be nice to change the mtexFigure grid, e.g.
```matlab
S2G = plotS2Grid();
mtexFig=newMtexFigure;
for i=1:6
  plot(S2G,'parent',mtexFig.nextAxis)
end
mtexFig.nrows=3; %for now it has no effect
mtexFig.ncols=2; %for now it has no effect
mtexFig.drawNow;
```
mtex5.beta5
Regards,
Filippe

**Comment by ralfHielscher** [comment]
Its not yet implemented. You need to change the figure position.

**Comment by ralfHielscher** [comment]
It should be working now. Could you please check?

Ralf.

**Comment by kilir** [comment]
I just tried it and it only partially works for me. It seems to only consider nrows or ncols but I could not make it switch to "portrait". Following example should be have 3 columns and 8 rows, but really likes to stick to the 3 rows. 
```
cs=crystalSymmetry('mmm',[4.8 10 6]);
h=Miller([1 0 0 ],[0 1 0],[0 0 1],cs,'uvw');
n=8;
hw=40*degree;
f=newMtexFigure;
for i=1:n
    o=orientation.rand(n,cs)
    plotPDF(o,h,'smooth','halfwidth',hw)
    if i<n; nextAxis; end
end
f.ncols=length(h);
f.nrows=n;
f.drawNow;
CLim(f,'equal')
mtexColorbar

% in case somone reads that wonders what this above is good for:
% looking at random "textures" with too few datapoints?
% nice to compare against Jung & Karato 2001 and  Katayama et al. 2004
```
![randolivine](https://user-images.githubusercontent.com/11697557/38882485-87131924-426a-11e8-8b6c-9879fbb1e947.jpg)


Cheers,
Rüdiger

**Comment by filippeof** [comment]
I confirm that it's working very nicely. Also with 
`newMtexFigure('nrows',2,'ncols',4);`
Thanks for this nice feature! Would be nice if the colorbar (if clim is 'equal') rescaled to occupy the whole vertical extension of the axes (or horizontal, if mtexcolorbar is horizontal) e.g.:

```matlab
% after check if mtexFig.CLim=='equal' (how?):

if mtexFig.cBarAxis.Position(4)>mtexFig.cBarAxis.Position(3) %Vertical bar
    
    vbar_height=mtexFig.nrows*(mtexFig.axisHeight+mtexFig.innerPlotSpacing)+mtexFig.outerPlotSpacing;
    vbar_left=mtexFig.ncols*(mtexFig.axisWidth+mtexFig.innerPlotSpacing)+mtexFig.outerPlotSpacing;

    mtexFig.cBarAxis.Position(1)=vbar_left; %c_bar left
    %mtexFig.cBarAxis.Position(2)=mtexFig.cBarAxis.Position(2); %c_bar bottom
    %mtexFig.cBarAxis.Position(3)=mtexFig.cBarAxis.Position(3) %c_bar width
    mtexFig.cBarAxis.Position(4)=vbar_height; %c_bar height

else %mtexFig.cBarAxis.Position(4)>mtexFig.cBarAxis.Position(3) %Horizontal bar
    
    hbar_width=mtexFig.ncols*(mtexFig.axisWidth)+mtexFig.innerPlotSpacing;
   
    mtexFig.cBarAxis.Position(1)=mtexFig.outerPlotSpacing+mtexFig.innerPlotSpacing; %c_bar left
    %mtexFig.cBarAxis.Position(2)=mtexFig.cBarAxis.Position(2); %c_bar bottom
    mtexFig.cBarAxis.Position(3)=hbar_width; %c_bar width
    %mtexFig.cBarAxis.Position(4)=mtexFig.cBarAxis.Position(4) %c_bar height
end
```
vertical bar             |  horizontal bar
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11142094/38932655-2766d508-4317-11e8-955d-5951b77d7d60.jpg)  |  ![](https://user-images.githubusercontent.com/11142094/38932656-2780eefc-4317-11e8-938b-fe425a92381a.jpg)

cheers,
Filippe

**Comment by ralfHielscher** [comment]
I have included your code. Thank you for the suggestion. Could you check it.

Ralf.

**Comment by filippeof** [comment]
Dear Ralf,
I think I forgot to consider the title size when adjusting the colorbar.
I included some code in updatelayout.m for this effect. Please check the commit:
a839b7042b4cd00711c4434e68dc3ddd8c81f756

Maybe is also necessary to consider a fallback in case there are less axis than (nrows-1)*ncols, such as in this example:  

```matlab
setMTEXpref('figSize','huge');
cs=crystalSymmetry('mmm',[4.8 10 6]);
h=Miller({1,0,0},cs,'uvw');
o=orientation.rand(cs);
v=vector3d.rand(5,cs);

f=newMtexFigure('nrows',4,'ncols',4);
n=10;% nAxis
for i=1:10
    %plot(v,'antipodal') % without title
    plotPDF(o,h) %with title
    if i<n; nextAxis; end
end
% f.ncols=2; % change later
% f.nrows=4;
f.drawNow;
CLim(f,'equal')
% mtexColorbar('southOutside') % horizontal
mtexColorbar % vertical bar

```

Filippe
