### ISSUE TITLE
orientation/plotPDF issue with superposition of plots

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#317]
Hi Ralf,
after it was solved for odf/plotPDF I tried to adopt the changes to orientation/plotPDF but can't get it to work.

When superposing point plots using `plotPDF` I only get points into the first axis.

![somefile](https://user-images.githubusercontent.com/11697557/36615765-afeb265a-18e1-11e8-9b94-0b619be1f482.jpg)
```matlab
mtexdata mylonite
o=ebsd('q').orientations; cs=o.CS; h = [Miller(0,0,0,1,cs) Miller(1,1,-2,0,cs)]
plotPDF(o,h)
f=gcm;
f.currentId = 1;
hold on
plotPDF(o,h)
hold off
```
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

currently only the following works
```matlab
mtexdata mylonite
o=ebsd('q').orientations; cs=o.CS; h = [Miller(0,0,0,1,cs) Miller(1,1,-2,0,cs)]
plotPDF(o,h)
plot(o,'add2all')
```
Ralf.

**Comment by kilir** [comment]
Yes, this works. Still forgot about this possibility.
Cheers,
Rüdiger
