### ISSUE TITLE
Issue with repelem Matlab function...

### ISSUE THREAD

**Issue by DavidMercier** [mtex-toolbox/mtex#319]
[repelem](https://nl.mathworks.com/help/matlab/ref/repelem.html) has been introduced in Matlab 2015a, and thus it could be great to have an alternative function for people working with previous Matlab version.
https://nl.mathworks.com/matlabcentral/answers/346102-repelem-substitute-for-older-matlab-version
Thanks for your help.
David

**Comment by ralfHielscher** [comment]
Hi David,

this issue has been considered in b04f77ceeb11d8a946738eae64b05b93808699b0

Could you check this

Ralf

**Comment by DavidMercier** [comment]
Hi Ralf, thanks for the patch.

Works fine for me.

David
