### ISSUE TITLE
velocity in MTEX 5.0.1 gives an error

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#324]
%% Compute WaveFront as spherical functions : vp,vs1,vs2 and polarizations
%  select harmonic method by using []
[vp,vs1,vs2,pp,ps1,ps2] = velocity(C,[]);

Error using  - 
Matrix dimensions must agree.

Error in eig3 (line 42)
  v = vector3d(a12 .* a23 - a13 .* (a22 - lambda),...

Error in complianceTensor/velocity (line 54)
[V,D] = eig3(E.M(1,1,:),E.M(1,2,:),E.M(1,3,:),E.M(2,2,:),E.M(2,3,:),E.M(3,3,:));

Error in stiffnessTensor/velocity (line 20)
[varargout{1:nargout}] = velocity(inv(C),varargin{:});

Even when running example ElasticityTensor.m

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

for me ElasticityTensor.m does not give an error. 

What is the output of ```size(C.M)``` in your case?

Ralf.

**Comment by DavidMainprice** [comment]
> Le 6 mars 2018 à 17:28, Ralf Hielscher <notifications@github.com> a écrit :
> 
> Hi David,
> 
> for me ElasticityTensor.m does not give an error.
> 
> What is the output of size(C.M) in your case? I do not know this parameter 
> 
all the best David

**Comment by DavidMainprice** [comment]
Dear Ralf,

I was using R2015B I get this 

%% Compute WaveFront as spherical functions : vp,vs1,vs2 and polarizations
%  select harmonic method by using []
[vp,vs1,vs2,pp,ps1,ps2] = velocity(C,[]);

Error using  - 
Matrix dimensions must agree.

Error in eig3 (line 42)
  v = vector3d(a12 .* a23 - a13 .* (a22 - lambda),...

Error in complianceTensor/velocity (line 54)
[V,D] = eig3(E.M(1,1,:),E.M(1,2,:),E.M(1,3,:),E.M(2,2,:),E.M(2,3,:),E.M(3,3,:));


Error in stiffnessTensor/velocity (line 20)
[varargout{1:nargout}] = velocity(inv(C),varargin{:});

I switched R2016b now it works fine, so it something to do with R2015b. I can use R2016b for now.

all the best David
