### ISSUE TITLE
MTEX 5.0.1 Bug(s) in function velocity - not present in MTEX 5.0.0 

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#329]
There is a real problem in MTEX5.0.1, which is NOT present in MTEX 5.0.0 when using velocity in MTEX5.0.1 the Vp,Vs1 and Vs2 are not correct, they too low.

The correct velocities from MTEX5.0.0 are Vp=  9.7737 Vs1 = 5.4590 Vs2 = 4.8322  Vp/Vs1 = 9.7737/5.4590=1.7904     Vp/Vs2 = 9.7737/4.8322=2.0226

The too low velocities from MTEX5.0.1 are Vp=  5.3360 Vs1 = 2.9803 Vs2 = 2.6382  Vp/Vs1 = 5.3360/2.9803=1.7904     Vp/Vs2 = 5.3360/2.6382=2.0226

The Vp/Vs1 and Vp/Vs2 are the same, this may help to identify the problem. The problem is the same for classical and harmonic values in MTEX 5.0.1

MTEX5.0.0 you compute the velocities as
% compute wavespeeds
 D = sqrt(diag(D)/rho);

MTEX5.0.1 you compute the velocities as
% compute wavespeeds
D = sqrt(D)/rho;

So I put this D = sqrt(diag(D)/rho); in velocity in MTEX5.0.1

Classical S2 grid 1 degrees
Vp =  8.3423
Vs1 = 4.7917
Vs2 = 4.3676
Sphere defined by harmonic method
Vp = 8.3420
Vs1 = 4.7929
Vs2 = 4.3676

this is still not correct I double checked with my FORTAN code for maximum Vp=9.7739  in 100 direction with MTEX5.0.0 Vp=9.7737,  (9.7739 - 9.7737)=2.0000e-04 OK , but (9.7737 - 8.3423) = 1.4314 there  must be something else ?

By the way the density of olivine in should be 3.355, I corrected in SeismicsMultiplot.m attached to avoid future velocity issues !

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

thank you for pointing this out. 

Ralf.
