### ISSUE TITLE
Angles (phi and lambda) of Schmid Factor

### ISSUE THREAD

**Issue by Kevineta** [mtex-toolbox/mtex#339]
Hi,
I posted some question for calculation of Schmid factors 6 months ago.
I would like to thank you for helping me at that time.
I need more calculation for the angles in the Schmid factor.

My question is that I want to know 2 angles which are phi(Angle between loading direction and slip plane normal) and Lambda(Angle between loading direction and slip direction) respectively.

The code  for calculating Schmid factor is below.

Codes for calculating Schmid factor
========================================================================
``` matlab
clc;
clear all;
% Define a crystal system
CS = crystalSymmetry('6/mmm',[3.23,3.23,5.15],'Matrix','Zirconium');

% Define a slip system
sS1 = slipSystem.basal(CS);

sS2 = slipSystem.prismatic2A(CS);
sS3 = slipSystem.prismaticA(CS);

sS4 = slipSystem.s4(CS);
sS5 = slipSystem.s5(CS);

sS6 = slipSystem.pyramidal2CA(CS);
sS7 = slipSystem.pyramidalA(CS);
sS8 = slipSystem.pyramidalCA(CS);

sS9 = slipSystem.twinC1(CS);
sS10 = slipSystem.twinC2(CS);

sS11 = slipSystem.twinT1(CS);
sS12 = slipSystem.twinT2(CS);

% Define a loading direction
loadingDirection = Miller(7, -13, 6, 2, CS);

% Compute the Schmid factor for all slip systems symmetrically equivalent to slip system
SF1 = SchmidFactor(sS1.symmetrise,loadingDirection);
SF2 = SchmidFactor(sS2.symmetrise,loadingDirection);
SF3 = SchmidFactor(sS3.symmetrise,loadingDirection);
SF4 = SchmidFactor(sS4.symmetrise,loadingDirection);
SF5 = SchmidFactor(sS5.symmetrise,loadingDirection);
SF6 = SchmidFactor(sS6.symmetrise,loadingDirection);
SF7 = SchmidFactor(sS7.symmetrise,loadingDirection);
SF8 = SchmidFactor(sS8.symmetrise,loadingDirection);
SF9 = SchmidFactor(sS9.symmetrise,loadingDirection);
SF10 = SchmidFactor(sS10.symmetrise,loadingDirection);
SF11 = SchmidFactor(sS11.symmetrise,loadingDirection);
SF12 = SchmidFactor(sS12.symmetrise,loadingDirection);

% Calculate the maximum Schmid factor 
[maxSF1,id1] = max(SF1,[],2);
[maxSF2,id2] = max(SF2,[],2);
[maxSF3,id3] = max(SF3,[],2);
[maxSF4,id4] = max(SF4,[],2);
[maxSF5,id5] = max(SF5,[],2);
[maxSF6,id6] = max(SF6,[],2);
[maxSF7,id7] = max(SF7,[],2);
[maxSF8,id8] = max(SF8,[],2);
[maxSF9,id9] = max(SF9,[],2);
[maxSF10,id10] = max(SF10,[],2);
[maxSF11,id11] = max(SF11,[],2);
[maxSF12,id12] = max(SF12,[],2);

% Corresponding real slip system and at which Schmid factor is maximum
a_sS10 = sS10.symmetrise;
b_sS10=a_sS10(id10);

% List the maximum Schmid factor at each slip systems.
maxSF1;
maxSF2;
maxSF3;
maxSF4;
maxSF5;
maxSF6;
maxSF7;
maxSF8;
maxSF9;
maxSF10;
maxSF11;
maxSF12;
```

The results was that
========================================================================
``` matlab
When the loading direction is [7, -13, 6, 2], 
Among a lot of slip systems, the slip system which has the maximum Schmid factor was slip system 10(twinC2).
So I can guess that the slip system 10 would be activated.

b_sS10 was real slip System at which Schmid factor is maximum.

So,

b_sS10 = slipSystem (show methods, plot)
 symmetry: 6/mmm, X||a*, Y||b, Z||c
 CRSS: 1
 size: 1 x 1
  U   V   T   W | H   K   I   L
  1  -2   1   3   1  -2   1  -2

and maxSF10=0.4825;
```

I wanted to calculate "angles" as well as Schmid factor using real direction data from EBSD.
The loadingDirection is [7, -13, 6, 2] from EDAX EBSD data and it corresponds ideal direction [2, -1,- 1, 0].
So I put the direction [7, -13, 6, 2] in above code. Maximum Schmid Factor (maxSF) is SF10.

In other words, I want to calculate the angles (phi and lambda) using the loading direction [7, -13, 6, 2] and the slip system "b_sS10".

So I added some codes below to calculate the angles.

Codes for calculating angles
========================================================================
``` matlab
phi=angle(loadingDirection, b_sS10.n)/degree
lambda=angle(loadingDirection, b_sS10.b)/degree
m=cos(phi*degree)*cos(lambda*degree);
```

But I have some problem in this situation.

m was not 0.4825 but 0.5447 while maxSF10 was 0.4825.
The m value doesn't make sense.

However, when I tried to replace the ideal loading direction [2, -1, -1, 0] instead of  the real loading direction [7, -13, 6, 2], the m value was same as maxSF10.
When I applied the loading direction [2,-1-1,0], maxSF10 was 0.4501 and m was also 0.4501

But I want to get that the value m is 0.4825 using the real loading direction [7, -13, 6, 2].
What is missing part?

**Comment by kilir** [comment]
Hi,
as you are in crystal coordinates, you need to either add `'noSymmetry'` to your manual calculation of angles and the Schmid factor to get the same result as using `SchmidFactor` or convert to `vector3d`. Otherwise angles are calculated obeying crystal symmetry which not give what you want:

```
phi=angle(loadingDirection, b_sS10.n,'noSymmetry')/degree;
lambda=angle(loadingDirection, b_sS10.b,'noSymmetry')/degree;
m=cos(phi*degree)*cos(lambda*degree)

% or

phi=angle(vector3d(loadingDirection), vector3d(b_sS10.n))/degree;
lambda=angle(vector3d(loadingDirection), vector3d(b_sS10.b))/degree;
m=cos(phi*degree)*cos(lambda*degree)

```

Cheers,
Rüdiger
