### ISSUE TITLE
Define black using R G B coding?

### ISSUE THREAD

**Issue by aramoanav** [mtex-toolbox/mtex#340]
Hi
I am trying to define a colour coding for EBSD maps that assigns white, a colour, and black to three different crystallographic directions for the mineral of interest. I have done this using the following code (for quartz):

oMq = ipdfCenterOrientationMapping(csQtz);
oMq.inversePoleFigureDirection = fQtz.r;
oMq.center = [Miller(1,1,-2,0,csQtz),Miller(0,0,0,1,csQtz),Miller(-1,1,0,0,csQtz)];
oMq.color = [[1 1 1];[0 0 1];[1 1 1]];
oMq.psi = deLaValeePoussinKernel('halfwidth',45*degree);

However, I can't actually set one of the three orientations to be black ([0 0 0]?)- if I do so all colours become black and 
>>plot(oMq);
yields a totally black IPF.

Any suggestions?
Thanks
Virginia

**Comment by kilir** [comment]
Did 08f9bdf101989f961835e5d4fca014d07aabeb98 take care of this?
Cheers,
Rüdiger

**Comment by aramoanav** [comment]
Yes, thanks Rü!
