### ISSUE TITLE
Error when computing grains whith 'tight' option

### ISSUE THREAD

**Issue by DorianDepriester** [mtex-toolbox/mtex#343]
Hello there,
When trying to compute the grains using the `'boundary','tight'`, it leads to the following error:

```matlab
Undefined function 'boundary' for input arguments of type 'double'.

Error in spatialDecomposition>calcBoundary (line 73)
      k = boundary(x,y,1);

Error in spatialDecomposition (line 26)
  dummyCoordinates = calcBoundary(X,unitCell,varargin{:});

Error in EBSD/calcGrains (line 26)
[V,F,I_FD] = spatialDecomposition([ebsd.prop.x(:),
ebsd.prop.y(:)],ebsd.unitCell,varargin{:});
```

MWE: MTEX documentation/Grain/Grain Reconstruction/Non convex data sets

Cheers,
Dorian

**Comment by ralfHielscher** [comment]
Hi Dorian,

```boundary``` is a matlab function introduced in Matlab 2014b. Most likely you are using an earlier version.

Ralf.

**Comment by DorianDepriester** [comment]
Hi Ralf,
Indeed, I am using the R2013b version. I will try to update it.
Thanks!
