### ISSUE TITLE
bug:   ipfTSLKey and ipfHKLKey broken for '2/m'

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#344]
Hi Ralf, I guess there's a glitch with those tho color keys:
```
cs=crystalSymmetry('2/m')
om1=TSLDirectionKey(cs) % or ipfTSLKey
plot(om1)
om2=HKLDirectionKey(cs) % or ipfHKLKey
plot(om2)
```
![hkl](https://user-images.githubusercontent.com/11697557/40722946-f70d725e-641d-11e8-81fd-80a802f8a267.png)
![tsl](https://user-images.githubusercontent.com/11697557/40722947-f729ebf0-641d-11e8-98f8-c1be29b7cfa8.png)

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger, 

thank you for pointing this out.

Ralf.

**Comment by kilir** [comment]
Thanks,
works for me, so I close this.
Cheers,
Rüdiger
