### ISSUE TITLE
Problem with physical properties  MTEX 5.1.0

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#348]
E=YoungsModulus(C_Voigt,xvector) gives 198.5774 GPa fine

Uses compliance so inv(C_Voigt)
G=shearModulus(inv(C_Voigt),xvector,zvector)
**Undefined function 'matrix' for input arguments of type 'double'.
Error in complianceTensor/shearModulus (line 36)
  E = 0.25./matrix(EinsteinSum(S,[-1 -2 -3 -4],h,-1,u,-2,h,-3,u,-4));** 

Uses compliance so inv(C_Voigt)
v=PoissonRatio(inv(C_Voigt),xvector,zvector) gives v = 0.2483

[Vp,Vs]=velocity(C_Voigt,xvector,rho) this is a request for only direction xvector
Vp = S2FunTri (show methods, plot)
 vertices: 1 x 18338
 values:   1 x 18338
Vs = S2FunTri (show methods, plot)
 vertices: 1 x 18338
 values:   1 x 18338

Several different problems here.

all the best David

**Comment by DavidMainprice** [comment]
Comment with MTEX 5.0.3

E =
  198.5774 (good)
G =
   79.5367 (good)

v =  0.2483 (good)

[Vp,Vs]=velocity(C_Voigt,xvector,rho) same problem as  MTEX 5.1.0
Vp = S2FunTri  
 
 vertices: 1 x 18338
 values:   1 x 18338
 
Vs = S2FunTri  
 
 vertices: 1 x 18338
 values:   1 x 18338
Undefined operator '/' for input arguments of type 'S2FunTri'.
Error in Isotropic_elastic_parameters (line 40)
VpVs=Vp/Vs 

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

thank you for reporting this. I think I have found the source of the error.

Ralf.
