### ISSUE TITLE
Bug in subsref/crystalShape

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#349]
Hi Ralf,
I think this change https://github.com/mtex-toolbox/mtex/commit/0896471d67ca98362f1e6de8e2150d081c171fb5#diff-bcc94f5c5fd96b0277e39742f8d6c46bR53
results in subsref not working properly anymore. Example:
```
cs = crystalSymmetry('-1',[8,13,7],[94,117,87]*degree,'X||a*','Z||c')
m = [Miller(1,0,0,cs),Miller(0,1,0,cs),Miller(0,0,1,cs)]
 cS= crystalShape(m)
hold on
plot(cS(symmetrise(m(1))),'FaceColor','r')
hold on
plot(cS(symmetrise(m(2))),'FaceColor','b')
hold on
plot(cS(symmetrise(m(3))),'FaceColor','g')
hold off
```

![wrong_faces](https://user-images.githubusercontent.com/11697557/42174700-87599f80-7e23-11e8-83fd-f6500b0b187f.png)

Getting rid of 'stable' resolves the issue, however, it might have had areason why it was introduced there?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this.

Ralf.
