### ISSUE TITLE
Mtex ODF calculation

### ISSUE THREAD

**Issue by Chaithanya123456** [mtex-toolbox/mtex#350]
In Mtex, when ever I run the plot ODF function, some times I do get a plot of ODF sections. SOmetimes, It opens separate window to show ODF, but just one empty box will be there (I attached the figure here).
  Can you tell me how to overcome that problem?
  Thannks..
<img width="957" alt="capture" src="https://user-images.githubusercontent.com/40796258/42258985-0c61c140-7f7c-11e8-9c8d-6055e8c10bf1.PNG">

**Comment by kilir** [comment]
Hi,
I think you have to provide a little more information. Any error message? Example code and which version of mtex/Matlab you use etc. will be helpful.
Cheers,
Rüdiger

**Comment by Chaithanya123456** [comment]
Its is MATLAB 2013a and Mtex 4.5.2.......and there won't be any error message....just that image appears instead of ODF sections....
 Thank you for the replay..

**Comment by kilir** [comment]
I can't recall if Matlab 2013a was still supported with 4.5.2, but as of now, the current version of Mtex is 5.1.1. To use the current version, you need might need to upgrade Matlab as well.
Cheers,
Rüdiger

**Comment by Chaithanya123456** [comment]
Thanks a lot for your suggestions.. It is the incompatibility which lead to that error...It is working fine with matlab2015a.
