### ISSUE TITLE
Feature request: Personal preference file

### ISSUE THREAD

**Issue by ks-or** [mtex-toolbox/mtex#351]
A single file where the default behavior of MTEX commands can be edited. This would improve usability as a lot of commands are repeatedly used with certain arguments. It would also be easier to check what the default settings for certain commands are.

**Comment by ralfHielscher** [comment]
Can you give some examples. Some things can already be set in [mtex_settings.m](https://github.com/mtex-toolbox/mtex/blob/develop/mtex_settings.m). Obviously, we can not provide this functionality for all functions - so which one are the most important.

On the other hand I would rather like to improve tab completion to make it more easy to add options. The point is that I believe that keeping the options within the script files makes the code more reproducible.

Ralf.
