### ISSUE TITLE
Problem installing 5.1.1

### ISSUE THREAD

**Issue by seylerc** [mtex-toolbox/mtex#353]
New to MTEX and having trouble starting it up.
Mac 10.12.6 and MATLAB R2017a (9.2.0.556344) trying to install mtex 5.1.1

Running startup_mtex, the command window reads out "initialize MTEX 5.1.1  . . . ." and then never completes or fails. No error messages. From reading the startup script it seems like it gets stalled when it calls check_installation.m

**Comment by jbrussell** [comment]
I am having the same issue... Did you ever figure it out?
