### ISSUE TITLE
Not able to reproduce the results following the GND tutorial with MTEX 5.1.1

### ISSUE THREAD

**Issue by marcoalopez** [mtex-toolbox/mtex#354]
Hello,

I am working with MTEX version 5.1.1 (Matlab R2016a) and I am not able to reproduce the results following the GND tutorial (https://mtex-toolbox.github.io/files/doc/GND_demo.html) despite doing it step by step. Specifically, when I calculate the curvature using:

```matlab
kappa = ebsd.curvature
```

I get a curvature tensor of size 5151 x 1 instead of 101 x 51. Due to this, when try ``kappa(2,3)`` I get the following error:

```matlab
>> kappa(2,3)
Index exceeds matrix dimensions.

Error in tensor/subsref (line 40)
  T.M = subsref(T.M,s(1));
  
  
% also if I try
>> kappa12 = kappa{1,2};
>> size(kappa12)

ans =

        5151           1
```

I am able to visualize and reproduce all the steps below (including visualizing the different components of the curvature tensor) until I try to fit the dislocation tensors to the dislocation density tensor: 

```matlab
[rho,factor] = fitDislocationSystems(kappa,dSRot);
```

Since all I got is a ``rho`` variable full of ``NaN`` instead of numbers. Is anyone else having these behaviours with the latest version of MTEX?

***UPDATE**: I can confirm that everything works perfectly in version 5.1.0*

Thanks

**Comment by huihuizhi** [comment]
Hi, marcoalopez
The same problem as you.  I got is a rho variable full of NaN instead of numbers. did you solve the problem?

huihui

**Comment by marcoalopez** [comment]
> Hi, marcoalopez
> The same problem as you. I got is a rho variable full of NaN instead of numbers. did you solve the problem?
> 
> huihui

Just use the previous version (5.1.0) in the meantime

**Comment by huihuizhi** [comment]
It works. Thank you so much!

**Comment by huihuizhi** [comment]
@marcoalopez 
Thank you for your kind attention. Another question: do you know how to plot the histogram maps of gnd density
