### ISSUE TITLE
Small documentation bug

### ISSUE THREAD

**Issue by benjaminbritton** [mtex-toolbox/mtex#356]
https://mtex-toolbox.github.io/files/doc/CrystalOrientations.html

I think Bunge should be ZXZ:

"o = orientation('Euler',30*degree,50*degree,10*degree,'ZYZ',cs,ss)"

**Comment by ralfHielscher** [comment]
Hi Ben,

I think the problem is the heading stands not out correctly. Actually, this section is about the Matthies Euler angles.

Ralf.
