### ISSUE TITLE
installation problem (MTEX: Couldn't get the mex files working!)

### ISSUE THREAD

**Issue by mingminwang** [mtex-toolbox/mtex#359]
Dear MTEX developers,

I am a new user of METX.  I followed the installation instruction and typed startup_mtex, and got errors as shown in the attached image.  Could you please help me?

"The original error message was:
  Invalid MEX-file '/Users/mingmin/Documents/Work/mtex-5.1.1/mex/SO3Grid_dist_region.mexmaci64': dlopen(/Users/mingmin/Documents/Work/mtex-5.1.1/mex/SO3Grid_dist_region.mexmaci64, 6): Library not loaded: @loader_path/libmex.dylib
  Referenced from: /Users/mingmin/Documents/Work/mtex-5.1.1/mex/SO3Grid_dist_region.mexmaci64
  Reason: image not found."

Thanks,
Mingmin
<img width="1186" alt="screen shot 2018-08-19 at 10 15 24 am" src="https://user-images.githubusercontent.com/25515587/44309757-9c282300-a399-11e8-9d1b-4218d14c86a7.png">
<img width="1792" alt="screen shot 2018-08-19 at 10 15 38 am" src="https://user-images.githubusercontent.com/25515587/44309761-a0544080-a399-11e8-9f99-c4d3a4b427fd.png">

**Comment by ralfHielscher** [comment]
Have you read the warning:

XCode is installed but its license has not been accepted ....

Maybe you should try running XCode and accepting its licence agreement.

Ralf.
