### ISSUE TITLE
wrong angle distribution for monoclinic and trigonal symmetry

### ISSUE THREAD

**Issue by ralfHielscher** [mtex-toolbox/mtex#36]

**Comment by Aslan25253** [comment]
Dear Dr. Ralph,
I am trying to plot thermal expansion matrix of a monoclinic structure. However, when I define the crystal symmetry using the following command:

CS=crystalSymmetry ('2/m',[2.885 4.120 4.622], [90*degree,96.8*degree,90*degree], 'X||a')
The following appears:

CS = crystalSymmetry (show methods, plot)

  symmetry          : 12/m1             
  a, b, c           : 2.9, 4.1, 4.6     
  alpha, beta, gamma: 90Â°, 96.8Â°, 90Â°
  reference frame   : X||a, Y||b*, Z||c*

According to your paper, for monoclinic it should be either:
X||a*  Y||b  Z||c   or    X||a Y||b  Z||c*
Do you have any idea why in my case reference from is defined like that? I think the angles are not defined correctly somewhere.
Can you please help?
Regards,
Aslan
