### ISSUE TITLE
Explicitly setting the number of points in an ODF

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#365]
I am running into some issues explicitly setting the number of points in an ODF.  

### Code snippet
Running the following code:

    cs = crystalSymmetry('m-3m');
    ss = specimenSymmetry('1');

    HW=5*degree;
    res=1.5*HW;
    pts=1459; 

    s3grid1= equispacedSO3Grid(cs,ss,'points',pts); % does not = pts
    length(s3grid1) % returns 1453, NOT equal 1459
    s3grid2= equispacedSO3Grid(cs,ss,'resolution',res); 

I get the same length of the grid, despite asking for a slightly different number of points. 

-------------
### equispacedSO3Grid 
I read over "equispacedSO3Grid.m", it seems that the number of points is converted back to a resolution (lines 60 - 62):

  % calculate number of subdivisions for the angles alpha,beta,gamma
  res = 2/(points/( maxBeta*maxGamma))^(1/3);
  
So it doesn't seem like the equispacedSO3Grid will allow me to explicitly set the number of points.

-------------
### SO3Grid 
The class SO3Grid would seem to suffice, but I run into errors:

    S3G = SO3Grid(1000,cs,ss)

Error using double
Too many output arguments.

Error in rotation (line 124)
      [rot.a,rot.b,rot.c,rot.d] = double(quat);

Error in orientation (line 60)
    o = o@rotation(varargin{:});

Error in SO3Grid (line 35)
      S3G = S3G@orientation(ori);

I believe I am following the syntax correctly, but may have missed something.
  Syntax
   S3G = SO3Grid(nodes,CS,SS)
   S3G = SO3Grid(points,CS,SS)
   S3G = SO3Grid(resolution,CS,SS)

--------
### Why I'm digging around this far
I'm trying to update the Monte Carlo texture analysis code I wrote in mtex version 3.x for version 5.x (and hope to share).  I'm trying to work with the ODF weights directly (and the ODF calculation in MLSSolver class uses the equispacedSO3Grid.m function, see issues above). I had hoped that the orientations (odf.components{2}.center) were fixed in space and I could then operate directly on the weights. However, the number of unimodal components varies slightly. I usually get a size( (odf.components{2}.weights)') = 1450.  But occasionally I get 1451, 1448, or 1451 (approximately 1 out of 20 times).  I have set the halfwidth and resolution directly, as we found previously (https://code.google.com/archive/p/mtex/issues/117).  So I'm not quite sure what else to try beyond working with the points from a plot.  Suggestions are welcome!

Running mtex version 5.0.3, matlab R2105a, Mac OS 10.13.6

**Comment by ralfHielscher** [comment]
Hi Adam,

the quick answers:

1. '''equispacedSO3Grid''' is not supposed to return the exact number of orientations requested
