### ISSUE TITLE
Problem with accessing the  grains First Steps and Function Overview in Editor in MTEX 5.1.0 and 5.1.1

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#372]
This is with Mac OS, may not be the same for other computer systems.

However I used MTEX 5.1.0 and 5.1.1 on Mac I cannot open the examples in the Editor, may be is what you wanted ? I just checked again and it appears only the First Steps and Function Overview of grains, following examples do open in the Editor.

all the best David

**Comment by ralfHielscher** [comment]
I can confirm that there is a problem on my computer as well
