### ISSUE TITLE
Enhancement: calcAxisDistribution could return S2FunHarmonic

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#373]
Hi Ralf,
just a note: Wouldn't it be good if crystalSymmetry/calcAxisDistribution and odf/calcAxisDistribution would optionally return a spherical function, or is there something that 's at odds with it?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger, I somehow overlooked this. Thank you for adding this. When returning a spherical function a function name like axisDistribution seem more appropriate. Right?

plot(cs.axisDistribution)

looks reasonable.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
yes that totally makes sense. I just added a little so that it should hopefully work correctly in the case of two symmetries.

The reason behind this is, that now one can nicely normalize an axis distribution by the one coming from crystalSymmetry, and there are some cases where this makes quite a difference.
Cheers,
Rüdiger

**Comment by kilir** [comment]
Related to that, I found a little issue in symmetrise:
A few lines to reproduce:
```
% does not work
cs1  =crystalSymmetry('321')
cs2 = crystalSymmetry('1')

mdf = unimodalODF(orientation.rand(1,cs1,cs2))
ax = calcAxisDistribution(mdf)

% other symmetries work
cs1  =crystalSymmetry('321')
cs2 = crystalSymmetry('222')

mdf = unimodalODF(orientation.rand(1,cs1,cs2))
ax = calcAxisDistribution(mdf)
```


Having a disjoint cs of:
```
dcs = crystalSymmetry  
   symmetry          : 1                 
  a, b, c           : 1, 1, 1           
  alpha, beta, gamma: 90°, 90°, 90°     
  reference frame   : X||a, Y||b*, Z||c*
 ```
from
```
K>> odf.CS
ans = crystalSymmetry (show methods, plot)
  mineral        : Quartz-new       
  color          : light blue       
  symmetry       : -3m1             
  a, b, c        : 4.9, 4.9, 5.5    
  reference frame: X||a*, Y||b, Z||c
 
K>> odf.SS
ans = crystalSymmetry (show methods, plot)
  mineral           : An01 Ab                
  color             : light green            
  symmetry          : -1                     
  a, b, c           : 8.1, 13, 7.2           
  alpha, beta, gamma: 94.23°, 116.64°, 87.72°
  reference frame   : X||a*, Z||c
```
now symmetrise errors

```
K>>  x = symmetrise(x,dcs,varargin{:});
Error using S2FunHarmonicSym
Too many input arguments.

Error in S2FunHarmonic/symmetrise (line 68)
  sFs = S2FunHarmonicSym(sF.fhat, sym, varargin{:});
```
as `varargin{:}` in  S2FunHarmonic/symmetrise also contains a symmetry. Stripping the symmetry out of `varargin{:}` works, but I'm not sure if this is the way to do it.

Cheers,
Rüdiger

**Comment by kilir** [comment]
And another one:
only using
```
   f = @(h) (oR.maxAngle(h) - sin(oR.maxAngle(h))) ./ pi * nSym ;
   x = S2FunHarmonicSym.quadrature(f,dcs,'bandwidth',128,varargin{:});
```
instead of 

 https://github.com/mtex-toolbox/mtex/blob/0b842af6568c865d03986279befb7e728c68cae1/geometry/%40symmetry/calcAxisDistribution.m#L26

Produces what I think one might expect for two different crystal symmetries.

Here's a test case:
```
cs1  =crystalSymmetry('432')
cs2 = crystalSymmetry('622')

o1 = orientation.rand(10000,cs1);
o2 = orientation.rand(10000,cs2);
mori = o2.\o1

plot(mori.axis,'MarkerSize',4,'FundamentalRegion')
mtexTitle('axes input from random misorientations')
nextAxis

mdf = calcMDF(mori)
ax1 = calcAxisDistribution(mdf)
plot(ax1)
mtexTitle('axes distribution from mdf from input')
nextAxis

ax2 = calcAxisDistribution(cs1,cs2)
plot(ax2)
mtexTitle('axes distribution from cs1,cs2')
```
and here is what I would say the result should be:
<img width="1521" alt="fine" src="https://user-images.githubusercontent.com/11697557/46775145-3ce5ef80-cd06-11e8-81a7-036ab33f9ac8.png">

Unfortunately, neither 0b842af6568c865d03986279befb7e728c68cae1 nor b0d71ff6a8a1a542aa9ad1e89557eba13f6b3c90 produce this.

Am I missing something here?

**Comment by kilir** [comment]
Hi Ralf,
great, I think it's all fixed as far as I can see. Closing this one.
Cheers,
Rüdiger
