### ISSUE TITLE
sign of Schmidfactor

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#374]
Hi Ralf,
brought up here https://groups.google.com/forum/?fromgroups=#!topic/mtexmail/TbFORMYtI1A,
shouldn't the sign of the Schmidfactor be ideally be the same for different methods?

```matlab
cs = crystalSymmetry('622');
o  =orientation('Euler',[20 170 30]*degree,cs);
sS = symmetrise(slipSystem.pyramidalA(cs));
v= xvector;

%1)
SF1 = sS.SchmidFactor(o\v);
% which is 
sr = o\v; bn=normalize(sS.b);nn=normalize(sS.n);
SF1 =  dot_outer(sr,sS.b.normalize,'noSymmetry') .* dot_outer(sr,sS.n.normalize,'noSymmetry');

%2)
SF2 = sS.SchmidFactor(o\stressTensor.uniaxial(v));

%3)
SF3=(sr.xyz*(bn.xyz)').*(sr.xyz*(nn.xyz)');

% switchign to a "sense" of the slip plane:
sS.n.antipodal=0;
SF4 =  dot_outer(sr,sS.b.normalize,'noSymmetry') .* dot_outer(sr,sS.n.normalize,'noSymmetry');

[SF1; SF2'; SF3; SF4]
```

Since sS.n is antipodal, `vector3d/dot`takes the absolute, so wouldn't adding `n.antipodal=0` in the vector3d section in `slipSystem/Schmidfactor` be appropriate? Or was there any reason why signs returned by vector3d and stressTensor and the 'matrix' form input might be different?

Cheers,
Rüdiger

**Comment by MGRashed** [comment]
Hi Ralf,

I would also request to look into this issue, the sign of Schmid factor calculated using different methods should be the same.

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

you are right the normal direction should not have the antipodal attribute. After all the deformationTensor that is associated to the slip system does depend on the sign of the normal direction. In fact, it remains unchanged if both slip direction and normal direction change sign. So it is more appropriate to set sS1 == sS2 when -sS1.b = sS2.b and -sS1.n = sS2.n.

Ralf.

**Comment by MGRashed** [comment]
Hi Ralf,
Thanks for the correction.
The trace of the slip plane is now seen as an arrow, previously it was just a line (which is the convention).

![untitled](https://user-images.githubusercontent.com/1528712/53326417-a70bd380-3939-11e9-8bad-7988c92f9aa3.jpg)
