### ISSUE TITLE
flipped plot symmetry comparing ebsd.orientations vs grains.meanOrientation

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#380]
The following code results in plots with "flipped" appearance which seems incorrect. I recognize that the patterns will look somewhat different because they are not the exact same set of orientations, however, that does not explain the "flip" observed. Is this a bug? 

%% Load example data
mtexdata mylonite;

%% Isolate quartz orientations and plot
o = ebsd('qu').orientations;
cs = o.CS;
h = [Miller(0,0,0,1,'direction',cs), Miller(1,0,-1,0,'direction',cs)];

% plot of the ebsd.orientations
figure, 
plotPDF(o,h,'antipodal','lower','contourf','halfwidth',10*degree)

%% Isolate the mean orientations from quartz grains and plot

% construct grainset
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'angle',10*degree,'boundary','tight');

% isolate the set of mean orientation from grains
go = grains('qu').meanOrientation;

% plot of the grains.meanOrientations
figure,
plotPDF(go,h,'antipodal','lower','contourf','halfwidth',10*degree)

all quartz orientations:
![orientations](https://user-images.githubusercontent.com/8769619/48016652-c31d0800-e0f1-11e8-9f27-eed29e1c3fbb.png)

all mean orientations from quartz grains:
![meanorientations](https://user-images.githubusercontent.com/8769619/48016672-cd3f0680-e0f1-11e8-9c70-91919c6d158c.png)

**Comment by kilir** [comment]
Hi Zach,
the difference is that when plotting the grain mean orientation, there is simply no weighting be the area of the grain,i .e small grains, 1 px grains have the same contribution as large grains - which I think is the case you observe here. Have a look at the following:
```
mtexdata mylonite
h = Miller(0,0,0,1,ebsd('q').CS)
o = ebsd('q').orientations;
plotPDF(o,h,'contourf','halfwidth',10*degree)
mtexTitle('ebsd orientations')
nextAxis
grains = ebsd.calcGrains;
plotPDF(grains('q').meanOrientation,h,'contourf','halfwidth',10*degree)
mtexTitle('grain mean orientations')
nextAxis
odf = calcODF(grains('q').meanOrientation,'weights',grains('q').area)
plotPDF(odf,h,'contourf')
mtexTitle('grain mean orientations - weighted by area')
```
Does that make sense?

Cheers,
Rüdiger

**Comment by zmichels** [comment]
Makes fine sense but did you look at how the plots are flipped? That doesn’t explain the difference in mirroring observed to me

**Comment by zmichels** [comment]
Ok.... I tried it and I agree that the weighted approach achieves something more expected, and I understand the difference.  It just seems odd that the result is so well mirrored... it seems conspicuous.
