### ISSUE TITLE
In MTEX5 this demo no longer works - produces nice colour polefigures

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#381]
Example script as *.txt

[PF_with_color_BackGround_and_white_contours.txt](https://github.com/mtex-toolbox/mtex/files/2555056/PF_with_color_BackGround_and_white_contours.txt)

plotPDF(ODF_Fo,PFs_Fo_uvw,'lower','antipodal','resolution',1*degree);
hold on
% plot white contours
plot(ODF_Fo,PFs_Fo_uvw,'contour','lower','antipodal','resolution',1*degree,'linecolor','w','linewidth',1,'add2all’);
I get error message below
%plotPDF(ODF_Fo,PFs_Fo_uvw,'contour','lower','antipodal','resolution',1*degree,'linecolor','w','linewidth',1,'add2all');
With plotPDF(ODF_Fo,PFs_Fo_uvw,'contour','lower','antipodal','resolution',1*degree,'linecolor','w','linewidth',1,'add2all’);
no error message

With plotPDF(ODF….….,’add2all’
No error message, but the plot is not correct. It seems to plot the contours of all 3 pole figures on each polefigure !
![pole_figure](https://user-images.githubusercontent.com/10712356/48094306-1ab29500-e212-11e8-81c2-2b375688f869.png)

all the best David

**Comment by kilir** [comment]
Hi David,
using 
```
figure
plotPDF(ODF_Fo,PFs_Fo_uvw,'lower','antipodal','resolution',1*degree);
hold on
plot(ODF_Fo,PFs_Fo_uvw,'contour','lower','antipodal','resolution',1*degree,'linecolor','w','linewidth',1,'add2all');
hold off
```
produces the following result for me:
![result_](https://user-images.githubusercontent.com/11697557/48096485-8fd49900-e217-11e8-8daa-564d234d025b.png)

Using the recent mtex develop version. What error message did you get?
Cheers,
Rüdiger

**Comment by DavidMainprice** [comment]
Dear Rüdiger,

I get 

Warning: Plot properties not compatible to previous plot! I'going to create a new figure. 
> In newMtexFigure (line 45)
  In newODFSectionPlot (line 4)
  In ODF/plotSection (line 25)
  In ODF/plot (line 21) 

Then it tries to plot ODF sections !

MATLAB R2016b    MTEX 5.1.1     Mac OS

So I guess either you consider to be too old or your development version has some fix for this problem.

Thanks for your efforts on this problem. Your plot is what we get with MTEX4, but not MTEX5

all the best David

**Comment by kilir** [comment]
Hi David,
this commit fixes it  https://github.com/mtex-toolbox/mtex/commit/c6dea0c3585af044e763c3c0d05d4650765cad7f, was brough up here https://github.com/mtex-toolbox/mtex/issues/366 
Cheers,
Rüdiger
