### ISSUE TITLE
Plot IPF from Miller in 5.1.1

### ISSUE THREAD

**Issue by FlorianCastioni** [mtex-toolbox/mtex#383]
Hi,

I am using MTex 5.1.1 since few weeks, and my goal is to plot orientations map from ebsd data. Rather than plotting IPF considering (0,0,1) direction, I would like to plot it considering the direction of my choice, for example (1,0,0).

Here is an exemple of my code : 

```
%% Import Script for EBSD Data
%
% This script was automatically created by the import wizard. You should
% run the whoole script or parts of it in order to import your data. There
% is no problem in making any changes to this script.

%% Specify Crystal and Specimen Symmetries

% crystal symmetry
CS = {... 
  'notIndexed',...
  crystalSymmetry('m-3m', [2.866 2.866 2.866], 'mineral', 'Iron bcc (old)', 'color', 'red'),...
  crystalSymmetry('m-3m', [3.6599 3.6599 3.6599], 'mineral', 'Iron fcc', 'color', 'blue')};

% plotting convention
setMTEXpref('xAxisDirection','east');
setMTEXpref('zAxisDirection','intoPlane');

%% Specify File Names

% path to files
pname = 'C:\Users\Florian\Desktop\Florian\5A\Cours\PFE\MTex\Tests_Mtex\Map_data\EBSD 690C 15min';

% which files to be imported
fname = [pname '\690 C 15min 090513 400N.crc'];

%% Import the Data

% create an EBSD variable containing the data
ebsd = loadEBSD(fname,CS,'interface','crc',...
  'convertEuler2SpatialReferenceFrame');

MyPhase='Iron fcc';
ebsd_selected=ebsd(MyPhase);
h = Miller(1,0,0,ebsd_selected.CS);
oM = ipfColorKey(ebsd_selected.orientations);
oM.inversePoleFigureDirection = h;
color = oM.orientation2color(ebsd_selected.orientations);
plot(ebsd_selected,color);
```

Here is the error message I received : 

```
Undefined function 'transformationMatrix' for input arguments of type 'specimenSymmetry'.

Error in orientation/transformReferenceFrame (line 28)
M = transformationMatrix(ori.CS,cs1);

Error in  .*  (line 30)
    a = a.transformReferenceFrame(inner2);

Error in ipfColorKey/orientation2color (line 56)
      h = inv(ori) .* oM.inversePoleFigureDirection;

Error in Duplex_400N (line 38)
color = oM.orientation2color(ebsd_selected.orientations);
```

The code works when I use xvector instead of a Miller object. How could I fix this problem ? 
Thank you !

**Comment by kilir** [comment]
Hi,
an inverse pole figure shows crystal directions (@Miller) which are parallel to a single specimen direction (@vector3d). This specimen reference direction is specified by the inversePoleFigureDirection property in the colorcoding for example.

From that point of view it is ok for Mtex to error if you want to colorcode/plot an orientation in an inverse polefigure while using crystal direction as reference direction since this would not make a lot of sense.

Cheers,
Rüdiger

**Comment by FlorianCastioni** [comment]
> Hi,
> an inverse pole figure shows crystal directions (@miller) which are parallel to a single specimen direction (@vector3d). This specimen reference direction is specified by the inversePoleFigureDirection property in the colorcoding for example.
> 
> From that point of view it is ok for Mtex to error if you want to colorcode/plot an orientation in an inverse polefigure while using crystal direction as reference direction since this would not make a lot of sense.
> 
> Cheers,
> Rüdiger

Thanks for your answer Rüdiger, now it seems obvious!

Florian.
