### ISSUE TITLE
Misorientation axis of two different phases

### ISSUE THREAD

**Issue by yourghurt** [mtex-toolbox/mtex#384]
Dear Ralf, 
I am using MTEX 5.1.1 and Matlab 2014b to calculate the misorientation axis between two orientations from different phases, somehow the misorientation axis with wrong crystal symmetry is obtained. For example: 

```
cs1= crystalSymmetry('4/mmm', [6, 6, 11]);
cs2 = crystalSymmetry('m-3m', [3 3 3]);
ori1 = orientation('Euler',110*degree,70*degree,30*degree,cs1);
ori2 = orientation('Euler',170*degree,13*degree,40*degree,cs2);
mori1 = inv(ori1) * ori2;
mori2 = inv(ori2) * ori1;
```

However, the misorientation axis in cs1 and cs2 are: 
```
>> mori1.axis
ans = Miller (show methods, plot)
 size: 1 x 1
 symmetry: 422
  h -3.6939
  k  0.5365
  l  8.6123

>> mori2.axis
ans = Miller (show methods, plot)
 size: 1 x 1
 symmetry: 422
  h -0.5365
  k  3.6939
  l  8.6123
```

Obviously, the mori1.axis and mori2.axis should have different crystal symmetries. 

Would you please check this problem?
Thanks very much for your help. 

Best regards, 
Yao Li

**Comment by kilir** [comment]
Hi Yao,
what symmetries would you expect for the axis of the misorientation between two different crystalSymmetries? In that case 422 is the disjoint symmetry between 4/mm and m-3m. If you want it in one of either symmetries, you can probably convert it using `Miller(vector3d(axis),cs)`.
Does that help?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
maybe this helps:

http://mtex-toolbox.github.io/files/doc/orientation.axis.html

Ralf.

**Comment by yourghurt** [comment]
> Hi Yao,
> what symmetries would you expect for the axis of the misorientation between two different crystalSymmetries? In that case 422 is the disjoint symmetry between 4/mm and m-3m. If you want it in one of either symmetries, you can probably convert it using `Miller(vector3d(axis),cs)`.
> Does that help?
> Cheers,
> Rüdiger

Hi Rüdiger, 
I just want to know the Miller indices of the misorientation axis denoted in the two phases. 
Thanks very much for your help. I got it. 

Best regards, 
Yao

**Comment by yourghurt** [comment]
> maybe this helps:
> 
> http://mtex-toolbox.github.io/files/doc/orientation.axis.html
> 
> Ralf.

Hi Ralf, 
I got it. Thank you very much. 

Best regards, 
Yao
