### ISSUE TITLE
spatialProfile bug depending on starting/end points

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#386]
Depending on starting/ end points of a line defining an ebsd spatial profile, wrong pixels are retrieved.
Following the example available at [GrainSingleAnalysis](https://mtex-toolbox.github.io/files/doc/GrainSingleAnalysis.html ) but flipping the points results in the following plot:

```matlab
% example data 
mtexdata forsterite
ebsd = ebsd('indexed');
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd);

% select and plot grain
[~,id] = max(grains.GOS)
grain_selected = grains(id)
plot(grain_selected.boundary,'linewidth',2)
hold on, plot(ebsd(grain_selected),ebsd(grain_selected).orientations)
 
% line segment
lineSec =  [18826   6438; 18089 10599];%x2<x1 && y2>y1
%lineSec =  [18826 10599;  18089 6438];%x2<x1 && y2<y1
%lineSec =  [18089 10599; 18826   6438];%x2>x1 && y2<y1
%lineSec =  [18089 6438;    18826   10599];%x2>x1 && y2>y1


line(lineSec(:,1),lineSec(:,2),'linewidth',2)

% change starting/ end points (the line is the same)
lineSec=flipud(lineSec);
ebsd_line = spatialProfile(ebsd,lineSec);

% Plot the retrieved data
hold on
scatter(ebsd_line.prop.x,ebsd_line.prop.y)
hold off
```
![image](https://user-images.githubusercontent.com/11142094/48574218-e3796d80-e90e-11e8-9788-4483be02c09f.png)

Replacing  in @EBSD/spatialProfile.m
```matlab
        dX = lineX(k+1,:)-lineX(k,:);
```
by
```matlab
    if lineX(k+1,1)>lineX(k,1) %x2>x1 && y2<y1 || x2>x1 && y2>y1
         dX = [lineX(k+1,1)-lineX(k,1), - (lineX(k+1,2)-lineX(k,2))];
    else %x2<x1 && y2>y1 || x2<x1 && y2<y1
        dX = lineX(k+1,:)-lineX(k,:);
    end
```
worked for me but maybe there's a more elegant solution.
Best,
Filippe

**Comment by ralfHielscher** [comment]
Hi Filippe,

thank you very much for reporting this. The fix will be included into the next release.

Ralf.

**Comment by plehto** [comment]
Hi Ralf,

I came across this bugfix when figuring out why some of my ebsd line traces were yielding incorrect points in version 5.0.3.

The bug fix resolved the issues, with the exception of line segments having equal X_start and X_end coordinates.

Using the example above:

```
[~,id] = max(grains.GOS)
grain_selected = grains(id)
figure
plot(grain_selected.boundary,'linewidth',2)
hold on, plot(ebsd(grain_selected),ebsd(grain_selected).orientations)
 
% Vertical line segment
lineSec =  [18826   6438; 18826 10599];%x2=x1 && y2>y1
line(lineSec(:,1),lineSec(:,2),'linewidth',2)

%Plot ebsd line segment
ebsd_line = spatialProfile(ebsd,lineSec);
hold on
scatter(ebsd_line.prop.x,ebsd_line.prop.y)
hold off

% change starting/ end points (the line is the same)
lineSec_1=flipud(lineSec);
ebsd_line_1 = spatialProfile(ebsd,lineSec_1);
hold on
scatter(ebsd_line_1.prop.x,ebsd_line_1.prop.y)
hold off
```

This yields an EBSD line where y-coordinates always face away from the end point, shown here:
![spatialprofile_equalX](https://user-images.githubusercontent.com/32155769/55502823-16ba6000-5656-11e9-985e-61f584c0dd96.png)

By changing in @EBSD/spatialProfile.m
`if lineXY(k+1,1)>lineXY(k,1) %x2>x1 && y2<y1 || x2>x1 && y2>y1`
with
`if lineXY(k+1,1)>=lineXY(k,1) %x2>=x1 && y2<y1 || x2>=x1 && y2>y1`

The output is:
![spatialprofile_equalX_1](https://user-images.githubusercontent.com/32155769/55502912-41a4b400-5656-11e9-9d22-755a13ee5802.png)

Probably not the right way to do it, but fixes the spatial profile.

**Comment by zmichels** [comment]
I’m having this issue again with latest MTEX 5.2.

**Comment by ralfHielscher** [comment]
Which issue are you referring to? The issue raised by Pauli Letho was never included into MTEX. Changed this now. Ich check with the very first script and everything was fine.

Ralf.
