### ISSUE TITLE
Use of hold on hold off with 3D surf Vp plot with propagation vectors and polarization vector

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#387]
Matlab 2016b  with MTEX 5.1.1. Mac OSX
%**************************************************************************
%% 3d surface with radius vector with vp values
%**************************************************************************
[vp,vs1,vs2,pp,ps1,ps2] = C.velocity('harmonic');
% propagation vectors
prop = S2AxisFieldHarmonic.normal;
close all
figure
hold all
surf(vp)
% propagation vectors
plot(prop,'3D','color','k','LineWidth',3,'add2all')
% P-wave polarization vectors
plot(pp,'3D','color','m','LineWidth',5,'add2all')
hold off
% set colour map to seismic color map : red2blueColorMap
% Red = slow to Blue = fast in Seismology
colormap(red2blueColorMap)

The surf Vp plot works well, but I cannot get the vectors to plot on the velocity Vp surface

all the best David

**Comment by ralfHielscher** [comment]
use 
```
quiver3(vp,pp)
```
to plot on top of surface plots. See 72ba9737a76a0ac4eb3a08271cf7856ba990d8ea
