### ISSUE TITLE
About GND density calculation

### ISSUE THREAD

**Issue by yourghurt** [mtex-toolbox/mtex#388]
Dear Ralf, 
I am so sorry to bother you. Attached please find two sets of EBSD data from a nickel sample, that is, the the original data Ni.cpr/crc and the denoised data Ni_smooth.cpr/crc by channel 5 software. Then I use MTEX to analyze GND density with the following commands: 
```
cs = ebsd('Ni').CS;
ebsdg = ebsd('Ni').gridify;
kappa = ebsdg.curvature;
```
It works fine for the original data while something goes wrong with the denoised data (Ni_smooth.cpr/crc) and shows the following error messages:
```
Error using Miller (line 110)
(0,0,0) is not a valid Miller index

Error in orientation/log (line 53)
v = Miller(log@quaternion(ori),ori.CS);

Error in EBSDsquare/get.gradientX (line 60)
      gX = log(ori_right,ori,'left') ./ ebsd.dx;

Error in EBSDsquare/curvature (line 16)
kappa = dyad(ebsd.gradientX,tensor([1;0;0])) + ...

Error in EBSD/subsref (line 40)
  [varargout{1:nargout}] = builtin('subsref',ebsd,s);

Error in PlotGND (line 4)
kappa = ebsdg.curvature;
```
I am confused with this problem. Would you please check it when it is convenient for you? 
Thanks very much for your help!

Best, 
Yao

[Ni.zip](https://github.com/mtex-toolbox/mtex/files/2592535/Ni.zip)

**Comment by kilir** [comment]
Hi Yao,
I can't reproduce the error with the most recent mtex version (5.2beta1). What version are you using?
Cheers,
Rüdiger

**Comment by yourghurt** [comment]
Hi Rüdiger, 
Thanks for your message. 
I used MTEX 5.1.1 the most recent version downloaded from MTEX homepage, but I can't find the access to the version 5.2beta1. Could it be related to different Matlab versions? I used an old version (Matlab 2014b).  

BTW, after smoothing the Ni_smooth.cpr/crc data by using splineFilter, the above commands work successfully. 

Cheers, 
Yao

**Comment by ralfHielscher** [comment]
Hi Yao,

this is indeed a bug. MTEX should not complain about Miller indices (000). To fix this remove the lines

```matlab
if any(norm(varargin{1}) == 0)
    error('(0,0,0) is not a valid Miller index');
end
```
in geometry/@Miller/Miller.m

Thank you for reporting.

Ralf.
