### ISSUE TITLE
Incorrect resizing behaviour of ODF plots when using mtexColorbar

### ISSUE THREAD

**Issue by dsconnol** [mtex-toolbox/mtex#389]
Using version 5.1.1 as released in June 2018 with r2017a MATLAB on OSX the ODF plots do not correctly resize when adding mtexColorbar and when more than one section is plotted. Minimal working example is: 
`CS = {crystalSymmetry('m-3m')};`
`odf=uniformODF(CS);`
`plot(odf,'sections',2);`
`mtexColorbar;`

which on my system gives:
![bugreport_2](https://user-images.githubusercontent.com/38664195/48788644-3eb5b200-ecb9-11e8-9172-b97797fe0102.png)

With 1 ODF section this gives correct plotting:
![bugreport_1](https://user-images.githubusercontent.com/38664195/48789526-45ddbf80-ecbb-11e8-83b3-74b3204e88fb.png)

**Comment by dsconnol** [comment]
In v4.5.1 the same code gives correct plotting behaviour on the same system:
![bugreport_2_v4_5_1](https://user-images.githubusercontent.com/38664195/48790045-75d99280-ecbc-11e8-8ead-3ea4eb8841e8.png)

**Comment by kilir** [comment]
Hi,
actually it s reproducible with `crystalSymmetry('1')` or `crystalSymmetry('-1')` and the current 5.2beta1.

Wth respect to your working example, the `{}` actually prohibit the odf to have the given point group 'm-3m' and if you check the symmetry of the ODF, you see that it'll have '1' - but that is obviously unrelated.
Cheers,
Rüdiger

**Comment by dsconnol** [comment]
Hi, 
I hadn't noticed that. Thanks for the advice!
Cheers,
Dan
