### ISSUE TITLE
some new versions of osc file format are not readable

### ISSUE THREAD

**Issue by ralfHielscher** [mtex-toolbox/mtex#39]

**Comment by djm87** [comment]
Hi Ralf,

The attached modifications that fixed all of the problems I've observed with my datasets. I added if statements to handle some changes in bitstream position, there appeared to be a type change for the number of phases, and a small modification was added to handle osc with various number of columns (e.g. EDS, Prius data, custom data, etc...). 

[loadEBSD_osc.m.txt](https://github.com/mtex-toolbox/mtex/files/2793633/loadEBSD_osc.m.txt)

**Comment by ralfHielscher** [comment]
Hi Daniel,

that is great work. How have you done this? Do you have some internal information about the data format?

I tested it with some osc files I got from other users and sometimes it struggled.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Daniel,

I just recognized. That you did some very interesting work on twin analysis. Would it be possible for you to send me your email address so I can ask you about

1. send you some other osc data file which do not yet work
2. ask you about possible participation in the MTEX workshop

Ralf.
