### ISSUE TITLE
calcAxisDistribution: Why normalized to 2 instead of 1?

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#392]
Hi Ralf,
just occured to me that adf.mean  produced either by `symmetry/calcAixsDistribution` or ` odf/calcAxisDistribution` is 2 (or close to two) instead of 1.

I assume this is a bug, right?

```matlab
cs = crystalSymmetry('-3m');
% adf from millers
ax = Miller.rand(1000,cs);
adfax = calcDensity(ax);
adf.mean % ==1
% case 1: adf from symmetry
adfcs = calcAxisDistribution(cs,cs);
adfcs.mean %==2
% case 2: adf from mdf
adfmdf = calcAxisDistribution(uniformODF(cs,cs));
adfmdf.mean %==2
```
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I confirm this is a bug. I will have a look at this.

Ralf.
