### ISSUE TITLE
calcFourierODF - ODF reconstruction problem

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#393]
Hi Ralf,
is it normal that `calcFourierODF` produces an odf with lower symmetry then the list of input orientations?
Example:
```
cs = crystalSymmetry('-3m');
f = fibreODF(Miller(1,1,-2,0,cs),xvector,cs)
h = [Miller(0,0,0,1,cs) Miller(1,1,-2,0,cs)];
plotPDF(f,h)
nextAxis
o = discreteSample(f,10000);
plotPDF(o,h,'smooth') % that's fine
nextAxis
odf = calcFourierODF(o); % all <a> seem to be pointing towards one direction
plotPDF(odf,h)
```

![example](https://user-images.githubusercontent.com/11697557/51627699-3f7df500-1f43-11e9-9167-deeda2be2186.jpg)

It does NOT happen when using `calcKernelODF`.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this.

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by kilir** [comment]
Hi Ralf, that fixes it. I guess one would have to revisit some results in certain cases, right?
Cheers,
Rüdiger
