### ISSUE TITLE
"mtexColorbar WhiteJet" command is not working

### ISSUE THREAD

**Issue by MGRashed** [mtex-toolbox/mtex#395]
MTEX is using the default colorbar even if the command "mtexColorbar WhiteJet" is used:

%% Plot misOrientation map
% extract from the grains its boundary and save it to a separate variable,
% restrict the grain boundaries to a specific phase transistion
gB_FeFe = grains.boundary('Iron fcc','Iron fcc');

% plot the grain boundaries colorized by the misorientation angle
plot(gB_FeFe,gB_FeFe.misorientation.angle./degree,'linewidth',1,'micronbar','off');
mtexColorbar WhiteJet
axis off

**Comment by kilir** [comment]
Hi,
it's mtexColorMap, not mtexColorbar. I don't see any issues using the right command, so closing. However, you keep running into a problem, please feel free to reopen.

Cheers,
Rüdiger
