### ISSUE TITLE
Best place to escape () in phase names

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#396]
@grainBoundary/subsref https://github.com/mtex-toolbox/mtex/blob/a5f44b75322ba25b96b29eb628fe4a03eed86e8d/EBSDAnalysis/%40grainBoundary/subsref.m#L25 and possible others may run into trouble when phase names contain brackets. See e.g. https://groups.google.com/forum/?fromgroups=#!topic/mtexmail/j3vXlp5AbfA

Escaping the brackets in the phasae name works, so I was wondering if it would be worth using something like regexprep to escape all sorts of funny characters centrally in the phase name, probably already in https://github.com/mtex-toolbox/mtex/blob/a5f44b75322ba25b96b29eb628fe4a03eed86e8d/geometry/%40crystalSymmetry/crystalSymmetry.m#L118 ? 

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
I think we have addressed this somewhere ...
