### ISSUE TITLE
Error message while installing MTEX 5.2.beta2

### ISSUE THREAD

**Issue by MGRashed** [mtex-toolbox/mtex#397]
Thanks for the latest release, an error pops up while installing (it is not a major issue though).

![matlab_2019-02-05_20-55-50](https://user-images.githubusercontent.com/1528712/52265561-78c55480-2988-11e9-9bd0-05013eea2d6e.jpg)

There are 2 .mat files in the data folder that are not present in the release - https://github.com/mtex-toolbox/mtex/tree/develop/data

**Comment by ralfHielscher** [comment]
Hi Rashed,

thank you for pointing this out. I have updated the release accordingly.

Ralf.
