### ISSUE TITLE
MTEX 5.1.1 plot Section (vp,pN,'linewidth','color','black')

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#399]
This command is very useful for plotting 2D section of seismic velocity 
like this figure below, but you cannot plot dashed lines so when two velocities are equal.
Would it possible to add dashed option.

all the best David

![phase_velocites](https://user-images.githubusercontent.com/10712356/52332673-a7304780-29fb-11e9-8dfa-8445b0ac8618.png)

**Comment by DavidMainprice** [comment]
The plot above shows uncontrolled overlap, with controlled dash you could see the velocities are equally distributed

**Comment by ralfHielscher** [comment]
Hi David,

have you some more code? This would allow me to check this more easily.

Ralf.
