### ISSUE TITLE
How to set Specimen Symmetry in EBSD?

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#401]
I have a sample that should have orthotropic (orthorhombic) specimen symmetry that I would like to impose in the EBSD data set.  But I can't seem to find a way to apply specimen symmetry to EBSD data.

Following the documentation:
https://mtex-toolbox.github.io/files/doc/ebsd_demo.html

The header for the first box mentions specimen symmetry, but none of the following commands are made to enforce any specimen symmetry, only the crystal symmetry.  

Looking at the class definition in EBSD.m, crystal symmetry and specimen symmetry seem to have a single listing, in comparison to the ODF class definition in ODF.m.

Is there a different way I should be applying specimen symmetry for EBSD data?  

I'm currently using mtex 5.0.3, Matlab 2015a, MacOS 10.13.6.

**Comment by ralfHielscher** [comment]
Hi Adam,

just to close this issue. No specimen symmetry can not be set for EBSD data. You can extract orientations and set for those specimen symmetry.

Ralf.
