### ISSUE TITLE
System Incompatibility

### ISSUE THREAD

**Issue by 2dkcani** [mtex-toolbox/mtex#402]
> Invalid MEX-file '/zhome/e5/0/94864/Documents/MATLAB/mtex-5.2.beta2/extern/nfft/nfsoftmex.mexa64': libmvec.so.1: cannot open
shared object file: No such file or directory.
Error in unimodalComponent/calcFourier>gcA2fourier (line 64)
plan = nfsoftmex('init',length(A)-1,length(g),nfsoft_flags,0,4,1000,2*ceil(1.5*(length(A)+1)));
Error in unimodalComponent/calcFourier (line 26)
f_hat = gcA2fourier(g,c,A);
Error in ODF/calcFourier (line 32)
  hat = calcFourier(odf.components{i},L,varargin{:});
Error in ODF/FourierODF (line 8)
f_hat = calcFourier(odf,varargin{:});
Error in orientation/calcFourierODF (line 54)
odf = FourierODF(odf,get_option(varargin,{'L','bandwidth','fourier'},L,'double'));
Error in orientation/calcODF (line 64)
  odf = calcFourierODF(ori,varargin{:},'kernel',psi);
Error in EvaluateTexture (line 24)
odf_rot = calcODF(ori_rot,'halfwidth',precision);
Error in W80_master (line 93)
EvaluateTexture;

I am trying to run an unistalled beta2 version of MTEX 5.2 on a remotely controlled High Performance computing node. Intel Xeon based. And I get this error whch I don't get on my Windows 10 based laptop which unfortunately is way slow. Anyone could help me figure out what's going nuts?!

I am evaluating ODFs from a huge 4M pixel map and then I will be running many "findByOrientation" commands after evaluating ODFs.

Thanks in advance,
Umberto,
Ph.D student at the Technical University of Denmark.

**Comment by 2dkcani** [comment]
I am using an hpc node to have more RAM available than 16GB.

**Comment by kilir** [comment]
Hi, you are probably using an old glibc (should be >= 2.22, http://sourceware.org/glibc/wiki/libmvec).

See here:  https://groups.google.com/d/msg/mtexmail/0LkUv2XiPJI/76N4CydxAwAJ
If you can't change to a newer glibc, you might have to compile nfft for this setup without vectorization/openMP support, which will most likely be slower in some tasks.

Cheers,
Rüdiger

**Comment by 2dkcani** [comment]
Dear Rüdiger,
one can always count on you! thank you very much!

Best Regards,
Umberto.
