### ISSUE TITLE
Rotation of EBSD Orientations only, in axes other than the Zaxis

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#403]
The Euler angles in an EBSD dataset often are measured relative to the acquisition coordinate system (I'll call this the EBSD coordinate system).  I would like to rotate the measured orientations from the EBSD coordinate system to a different coordinate system so that it's consistent between several data sets. In some EBSD software (I'm most familiar with Oxford - Channel 5) this is accomplished with a 'virtual chamber' where you can set different coordinate conventions.

In my example, I would like to rotate about the Y axis of the EBSD coordinate system by 90° to switch the X and Z axes. For the IPF maps, I agree I could just switch which one I am plotting against, but if I try to calculate ODFs or Pole Figures to compare, I'd like them to be consistent.  This seems permitted via the example rotate command in the EBSD class:

%   % rotate about the x-axis
%   ebsd = rotate(ebsd,rotation('axis',xvector,'angle',180*degree))

However, when I try to apply this rotation, I get an error message:

'Spatial rotation of EBSD data is only supported for rotations about the z-axis. I'm going to rotate only the orientation data!'

Looking over the code, it's not clear to me that any rotation is applied as the 'end' on line 66 precedes the affine transformation on line 67. Is a rotation applied when you get this warning message?

I recall from the ICOTOM-18 (2017) workshop that one needs to be careful to distinguish between rotating the view, rotating spatial coordinates, and rotating orientations.  The rotate command with 'keepEuler' seems to preserve the second of these, but how to only rotate the Euler angles is not clear to me.  Is there a way to do this?

Thanks!

**Comment by ralfHielscher** [comment]
The rotation takes place in line 37.
To only rotate the orientations use the option 'keepXY'

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by creuzige** [comment]
Ok.  I'll give 'keepXY' a try.  Thanks!

I see the rotation on Line 37, but that's only if the 'keepEuler' flag is added, correct? 

To be more specific about the code question, there seems to be a nested if statement from lines 41 to 66.  I see a block from 41 to 46, and with the indentation it seems that line 47 starts an if/elseif statement inside the if started at line 41.  The if/elseif statement started on line 47 seems to end at line 66, but then there's a transformation on line 67.  I don't see the end to the if started on line 41 then.  

Just trying to figure out if I'm reading the code wrong. (I'm reading the 5.0.3 version)

**Comment by ralfHielscher** [comment]
>
> I see the rotation on Line 37, but that's only if the 'keepEuler' flag is
> added, correct?
>
No, the ~ means not. So this is executed if the the flag is not present.

> To be more specific about the code question, there seems to be a nested if
> statement from lines 41 to 66. I see a block from 41 to 46, and with the
> indentation it seems that line 47 starts an if/elseif statement inside the
> if started at line 41. The if/elseif statement started on line 47 seems to
> end at line 66, but then there's a transformation on line 67. I don't see
> the end to the if started on line 41 then.
>
> The transformation on line 67 is only the shift and no rotation.

Ralf.

**Comment by creuzige** [comment]
Thanks!  And 'keepXY' worked.
