### ISSUE TITLE
The trace of the slip plane is now seen as an arrow

### ISSUE THREAD

**Issue by MGRashed** [mtex-toolbox/mtex#404]
The trace of the slip plane is now seen as an arrow (image below), previously it was just a line.

![53326417-a70bd380-3939-11e9-8bad-7988c92f9aa3](https://user-images.githubusercontent.com/1528712/53491917-a7e46700-3aeb-11e9-9969-790bfa3de193.jpg)

**Comment by kilir** [comment]
Add 'antipodal' to quiver.
Cheers,
Rüdiger

**Comment by MGRashed** [comment]
It worked, thank you.

I see that there are two commands for the trace of slip plane, _cross(sSGrain.n,zvector)_ and _sSGrain.trace_
Which one is the standard (or latest) in MTEX?

**Comment by kilir** [comment]
Have a look mtex/geometry/@slipSystem/trace.m
