### ISSUE TITLE
centerSpecimen doesn't work with fourier odf

### ISSUE THREAD

**Issue by djm87** [mtex-toolbox/mtex#411]
starting with 5.0 centerSpecimen doesn't work with a fourier based ODF. 

%Test code
  CS = crystalSymmetry('622')
  SS = specimenSymmetry('orthorhombic')
  ori = [orientation('euler',135*degree,45*degree,120*degree,CS,SS) ...
         orientation('euler', 60*degree, 54.73*degree, 45*degree,CS,SS) ...
         orientation('euler',70*degree,90*degree,45*degree,CS,SS)...
         orientation('euler',0*degree,0*degree,0*degree,CS,SS)];

  odf = calcFourierODF(SS*ori); %Fourier 
%   odf = unimodalODF(SS*ori); %Radial 

  %we define a rotational displacement
  r2 = rotation('euler', 6*degree,4*degree,0*degree)
  odf = rotate(odf,r2);
  h = [Miller(0,0,1,CS),Miller(0,1,1,CS),Miller(1,1,1,CS)];
  figure;plotPDF(odf,h,'antipodal','complete');

  %and now retrive the rotation back
  [odr,r,v1,v2] = centerSpecimen(odf);
  figure;plotPDF(odr,h,'antipodal')

**Comment by ralfHielscher** [comment]
Thank you for reporting this issue.

Ralf.
