### ISSUE TITLE
 Import EBSD data  5.2.beta3 - still works but ...

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#412]
MTEX 5.2.beta3 (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
 
Warning: loadEBSD is depreciated. Please use instead EBSD.load 
> In loadEBSD (line 3)
  In WizardDataApi/loadData (line 372)
  In pageImportData/localAddData (line 136) 

all the best david

**Comment by ralfHielscher** [comment]
Hi David,

thank you for pointing this out.

Ralf.
