### ISSUE TITLE
Error using strainTensor/calcTaylor (line 57) 'optimoptions' requires Optimization Toolbox.

### ISSUE THREAD

**Issue by isemu** [mtex-toolbox/mtex#413]
Hello,

On the MTEX website it is stated that: MTEX is free and runs in standard Matlab with no toolboxes required.
But I get this error saying that I need the Optimization Toolbox. Is there a by to by-pass the need to call for  the Optimization Toolbox.

Thanks in advance

**Comment by ralfHielscher** [comment]
Indeed, '''calcTaylor''' requires the optimization toolbox. The is no way around it.

Ralf.
