### ISSUE TITLE
Error :Abstract classes cannot be instantiated.  Class 'symmetry' defines abstract methods and/or properties.

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#414]
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
>> startup_mtex
initialize MTEX 5.2.beta3  .... done!
 
MTEX 5.2.beta3 (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
 
>> rho=3.264
rho =
    3.2640
>> cs_Tensor = symmetry('12/m1',[  9.759  8.933  5.256],...
 [  90.0000 105.852  90.0000]*degree,'x||a*','z||c',...
 'mineral','Diopside')
**Abstract classes cannot be instantiated.  Class 'symmetry' defines abstract methods and/or properties.** 
>> M =... 
[[  229.0   78.0    69.8    0.0     9.9     0.0];...
[    78.0  179.0    58.0    0.0     6.1     0.0];...
[    69.8   58.0   242.5    0.0    40.9     0.0];...
[     0.0    0.0     0.0   78.9     0.0     6.6];...
[     9.9    6.1    40.9    0.0    68.1     0.0];...
[     0.0    0.0     0.0    6.6     0.0    78.2]];
>> C = stiffnessTensor(M,cs_Tensor,'density',rho)
**Undefined function or variable 'cs_Tensor'.** 

This problem in every version of mtex I have tested so far, it is also in R2016n, R2018a,R2015b

Abstract classes cannot be instantiated.  Class 'symmetry' defines abstract methods and/or properties.  Same problem ...

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

you have to replace

cs_Tensor = symmetry('12/m1',[ 9.759 8.933 5.256],...
[ 90.0000 105.852 90.0000]degree,'x||a','z||c',...
'mineral','Diopside')

by

cs_Tensor = crystalSymmetry('12/m1',[ 9.759 8.933 5.256],...
[ 90.0000 105.852 90.0000]degree,'x||a','z||c',...
'mineral','Diopside')

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by DavidMainprice** [comment]
Dear Ralf,

Many thanks I missed that in one of my old files !

all the best David
