### ISSUE TITLE
File type cannot be detected

### ISSUE THREAD

**Issue by qzmdtc** [mtex-toolbox/mtex#416]
I have some standard PANalytical xrdml type file but the mtex toolkit cannot detect it. I've used both version 5.1.1 and 4.5.beta.3. Uploaded are the files. Thank you. 

[Polefigure1 ROUGH-ZQ_BTO002.zip](https://github.com/mtex-toolbox/mtex/files/3204038/Polefigure1.ROUGH-ZQ_BTO002.zip)

**Comment by kilir** [comment]
Hi, try the lates development version, works for me (you need this file https://github.com/mtex-toolbox/mtex/blob/develop/interfaces/loadPoleFigure_xrdml.m).
Cheers,
Rüdiger

**Comment by qzmdtc** [comment]
> Hi, try the lates development version, works for me (you need this file https://github.com/mtex-toolbox/mtex/blob/develop/interfaces/loadPoleFigure_xrdml.m).
> Cheers,
> Rüdiger
Thank you very much it worked!! Though how it worked was not due to I changed to the newest development version. What I did was I overwrite the loadPoleFigure_xrdml.m file in the package with the codes in the link you sent. Maybe you can also update that in the next version? Thank you.

**Comment by kilir** [comment]
It will be included in the next release version.
Cheers,
Rüdiger
