### ISSUE TITLE
Errors in Creating a Fibre

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#418]
I'm trying to visualize ODF coverage from a diffraction measurement, so I wanted to plot different fibre textures.  There seems to be an issue assigning a sample symmetry to the fibre texture.

Here's the code I was trying to run:

%% Set Fiber
cs = crystalSymmetry('m-3m');
ss = specimenSymmetry('orthorhombic');
r = xvector;
f = fibre(Miller(1,1,1,cs),vector3d.Z,ss);
psi = bumpKernel(15*degree);
odf = fibreODF(f,psi, cs, ss);

%% ODF plot
figure; plot(odf,'phi2','sections',18,'projection','plain','minmax', 'off',cs,ss);CLim(gcm,[0, 20]);mtexColorbar;

Here's the error message:

Undefined function 'transformationMatrix' for input arguments of type 'specimenSymmetry'.

Error in orientation/transformReferenceFrame (line 28)
M = transformationMatrix(ori.CS,cs1);

Error in  .*  (line 30)
    a = a.transformReferenceFrame(inner2);

Error in fibre/get.r (line 78)
      r = f.o1 .* f.h;

Error in fibre/subsref (line 18)
    [varargout{1:nargout}] = builtin('subsref',f,s);

Error in fibreODF (line 33)
  r = varargin{1}.r;

Error in ODFCoverage (line 15)
odf = fibreODF(f,psi, cs, ss);

Note: If I change the line creating the fibre to 
f = fibre(Miller(1,1,1,cs),vector3d.Z);

I am able to plot the ODF, but it's plotted with triclinic sample symmetry. 

Using Mtex 5.0.3 on Matlab 2019a (mac)

**Comment by kilir** [comment]
Hi Adam,
maybe just a typo, this one should work:
```
f = fibre(Miller(1,1,1,cs),vector3d.Z,cs,ss);
```
Cheers,
Rüdiger

**Comment by creuzige** [comment]
That did resolve the issue. I had thought that the cs in the Miller was sufficient.

Thanks!

Dr. Adam Creuziger
National Institute of Standards and Technology (NIST)
Gaithersburg, MD USA 20899.8553
Office 301-975-6015
adam.creuziger@nist.gov<mailto:adam.creuziger@nist.gov>




On Jun 25, 2019, at 10:57 AM, Rüdiger Kilian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Adam,
maybe just a typo, this one should work:

f = fibre(Miller(1,1,1,cs),vector3d.Z,cs,ss);


Cheers,
Rüdiger
