### ISSUE TITLE
Using text string "Parent" causes error?

### ISSUE THREAD

**Issue by MGRashed** [mtex-toolbox/mtex#420]
I know this is a simple issue, if I use "Parent" as a legend text while doing twinning analysis MTEX returns an error. I believe it is a command so can not be used even as a text string.

I was wondering if there is a way around it, to mark parent grains.

**Comment by filippeof** [comment]
Hi! 
Because 'parent' is used to indicate a figure container for an axis. What about just add a space character after parent?
`'parent '`

**Comment by MGRashed** [comment]
Yes that works, thanks for suggesting the workaround.
