### ISSUE TITLE
Export the Grain ID with the EBSD data set

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#421]
Is there a way when the ebsd data set is exported, that the grain ID can be included?  I realize these come from two different operations (ebsd and grain2d classes), but it would be quite helpful to be able to find what grain each pixel belongs with.

I can see I could brute force it with a for loop and ebsd(ebsd.grainId == #), but that seems little unwieldily. 

For reference, I've attached the small EBSD data set that I am working with, as well as the script (GrainsForIsoDec renamed file type to .txt. from .m) I used to export some of the grain information.  

[GrainsForIsoDec.txt](https://github.com/mtex-toolbox/mtex/files/3468616/GrainsForIsoDec.txt)

[E190725-AAC-001-Area4-Cleaned-80subset_Mtex.txt](https://github.com/mtex-toolbox/mtex/files/3468609/E190725-AAC-001-Area4-Cleaned-80subset_Mtex.txt)

[E190725-AAC-001-Area4-Cleaned-80subset-Neighbors.txt](https://github.com/mtex-toolbox/mtex/files/3468612/E190725-AAC-001-Area4-Cleaned-80subset-Neighbors.txt)

[E190725-AAC-001-Area4-Cleaned-80subset-Grains.txt](https://github.com/mtex-toolbox/mtex/files/3468613/E190725-AAC-001-Area4-Cleaned-80subset-Grains.txt)

**Comment by kilir** [comment]
Hi,
not sure if this is what you are looking for, but EBSD/export() also exports the grainId.
```
mtexdata titanium
[grains, ebsd.grainId]=ebsd.calcGrains
export(ebsd,'out.txt')
```

Cheers,
Rüdiger

**Comment by creuzige** [comment]
Yes, that does what I need.  Thanks!
