### ISSUE TITLE
Warning: The rank of tThe tensor has been guessed to be 2. Please specify the rank explicitely in the future 

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#424]
%% Import Olivine Fo90 Stiffness tensor
% High PT Brillouin measurements were conducted at up to 14GPa at three given temperatures
% of 500 K, 750 K, and 900 K at GSECARS of the APS, ANL, while complimentary high-pressure
%
% Method : Brillouin Scattering
%
% Define density (g/cm3) at 13.3 GPa and 900K
rho= 3.578;
% elastic Cij stiffness tensor (GPa) as matrix M
M =... 
    [[381.0 100.0  104.0     0     0     0];...
    [ 100.0  247.0 112.0     0     0     0];...
    [ 104.0  112.0 279.0     0     0     0];...
    [   0      0      0    76.7    0     0];...
    [   0      0      0      0   86.7    0];...
    [   0      0      0      0     0  92.0]];
% Define Cartesian Tensor crystal symmetry & frame
cs_Tensor = crystalSymmetry('mmm',[4.7646 10.2296 5.9942],[90.00  90.00  90.00]*degree,...
    'x||a','z||c', 'mineral','2008 Olivine Fo90 P=13.3GPa T=900K');
% M as stiffness tensor C with MTEX tensor command
C_olivine = stiffnessTensor(M,cs_Tensor,'density',rho)

Geometric_Mean_Tensor = calcTensor(ODF_Forsterite,C_olivine,'geometricMean')

Warning: The rank of the tensor has been guessed to be 2. Please specify the rank explicitely in the future  I am sure this has been reported before, but not with ODF and geometricMean

All the best Dave

**Comment by kilir** [comment]
Hi David,
I don't get the warning using a current version of Mtex. Also, as far as I can see, 'geometricMean' is not an option for ODF/calcTensor() and it defaults to Voigt.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
The issue has been resolved
