### ISSUE TITLE
Error starting Mtex5.2 error in MATLAB R2019b

### ISSUE THREAD

**Issue by ashimahara** [mtex-toolbox/mtex#426]
Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
initialize MTEX 5.2  ....
********************************************************************************
 
  MTEX: Error running NFFT!
   
  The original error message was:
  Undefined function 'nfsftmex' for input arguments of type 'char'.
 
  Try to compile the binaries or contact author for help!

********************************************************************************
Creating search data base for MTEX documentation.
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB
setup, which should be resolved as soon as possible.  Error
detected was:
MATLAB:doc:CannotBuildSearchDb
The specified directory does not exist.

**Comment by kilir** [comment]
Hi,
if you are running the git version, you need to compile nfft yourself or simply copy the binaries from an existing release version.For compiling them yourself, here are some rough generic instructions: https://github.com/mtex-toolbox/mtex-toolbox.github.io/blob/7bad44bb4e6b241c59594b5c3f3c5ed82b18cdea/files/doc/compilation.html

With respect to the help, your might have to create the folder doc/html/helpsearch-v3

Does that help?

Cheers,
Rüdiger

**Comment by accessT** [comment]
On my private notebook i got the same problem:
Screenshot: i changed folder to MTEX 5.2.3 and then MTEX 5.1.1
<img width="507" alt="426_mtex511to523searchdb" src="https://user-images.githubusercontent.com/57536659/68671453-a1016580-054f-11ea-91fa-e259aa4b3ee5.PNG">
with 5.0.3 and 5.1.1 it has no problems to create db in Matlab 2019b _(with update 1)_

**Comment by ashimahara** [comment]
Hi,

I work around this problem adopting the MTEX from the download option instead the GIT version.

Best Regards.

Alberto Shimahara | Application Engineer
Esta mensagem é para uso exclusivo de seu destinatário e contém informações privilegiadas e confidenciais. Todas as informações aqui contidas são tratadas como confidenciais e não devem ser divulgadas a terceiros sem o prévio consentimento por escrito da OPENCADD. Se você não é o destinatário não deve distribuir, copiar ou arquivar a mensagem. Neste caso, por favor, notifique o remetente da mesma e destrua imediatamente a mensagem.
This message is for the exclusive use of its recipient and contains privileged and confidential information. All information contained herein is treated as confidential and should not be disclosed to third parties without the prior written consent of OPENCADD. If you are not the recipient you should not distribute, copy or archive the message. In this case, please notify the sender of it and immediately destroy the message.

De: accessT <notifications@github.com>
Enviada em: terça-feira, 12 de novembro de 2019 09:26
Para: mtex-toolbox/mtex <mtex@noreply.github.com>
Cc: Alberto Shimahara <alberto.shimahara@opencadd.eng.br>; Author <author@noreply.github.com>
Assunto: Re: [mtex-toolbox/mtex] Error starting Mtex5.2 error in MATLAB R2019b (#426)


On my private notebook i got the same problem:
Screenshot: i changed folder to MTEX 5.2.3 and then MTEX 5.1.1
[426_mtex511to523searchdb]<https://user-images.githubusercontent.com/57536659/68671453-a1016580-054f-11ea-91fa-e259aa4b3ee5.PNG>
with 5.0.3 and 5.1.1 it has no problems to create db in Matlab 2019b (with update 1)

**Comment by kilir** [comment]
Hi,
did you try to add the missing folders (doc/html/helpsearch-v3) mentioned above? That should solve your builddocsearchdb problem.
Rüdiger

**Comment by ashimahara** [comment]
Hi, Rüdger.

Unfortunately i didn’t tried to add the folders.

If this folders are requested, why they are not in the Git?

Best Regards.

Alberto Shimahara | Application Engineer
55 11 3038 3748
55 11 99390 2734
alberto.shimahara@opencadd.eng.br<mailto:alberto.shimahara@opencadd.eng.br>
[cid:image001.png@01D59960.185A2A10]<http://www.opencadd.com.br/>
Esta mensagem é para uso exclusivo de seu destinatário e contém informações privilegiadas e confidenciais. Todas as informações aqui contidas são tratadas como confidenciais e não devem ser divulgadas a terceiros sem o prévio consentimento por escrito da OPENCADD. Se você não é o destinatário não deve distribuir, copiar ou arquivar a mensagem. Neste caso, por favor, notifique o remetente da mesma e destrua imediatamente a mensagem.
This message is for the exclusive use of its recipient and contains privileged and confidential information. All information contained herein is treated as confidential and should not be disclosed to third parties without the prior written consent of OPENCADD. If you are not the recipient you should not distribute, copy or archive the message. In this case, please notify the sender of it and immediately destroy the message.

De: Rüdiger Kilian <notifications@github.com>
Enviada em: terça-feira, 12 de novembro de 2019 12:22
Para: mtex-toolbox/mtex <mtex@noreply.github.com>
Cc: Alberto Shimahara <alberto.shimahara@opencadd.eng.br>; Author <author@noreply.github.com>
Assunto: Re: [mtex-toolbox/mtex] Error starting Mtex5.2 error in MATLAB R2019b (#426)


Hi,
did you try to add the missing folders (doc/html/helpsearch-v3) mentioned above? That should solve your builddocsearchdb problem.
Rüdiger

**Comment by ralfHielscher** [comment]
Usually one includes only source files into Git, i.e., those which are not automatically generated by other files. The html help files and the search index are generated automatically and specific for specific Matlab versions. 

Actually I never got the error "Could not write search database". Even without the folder helpsearch-v3. Could it be that you have no writing permission to the MTEX folder?

Ralf.

**Comment by ashimahara** [comment]
Hi, Ralf.

Problably this discussion will not be closed.

We understand that in the GIT includes only the source code, and the compile process are MATLAB version based.

Why not insert this folder? Because is not related with the compile process.

The normal process to clone from GIT, are maded inside the “My Documents” in most restrictions the normal user have the correct rights.

Best Regards.

Alberto Shimahara | Application Engineer
55 11 3038 3748
55 11 99390 2734
alberto.shimahara@opencadd.eng.br<mailto:alberto.shimahara@opencadd.eng.br>
[cid:image001.png@01D59A07.DC968C00]<http://www.opencadd.com.br/>
Esta mensagem é para uso exclusivo de seu destinatário e contém informações privilegiadas e confidenciais. Todas as informações aqui contidas são tratadas como confidenciais e não devem ser divulgadas a terceiros sem o prévio consentimento por escrito da OPENCADD. Se você não é o destinatário não deve distribuir, copiar ou arquivar a mensagem. Neste caso, por favor, notifique o remetente da mesma e destrua imediatamente a mensagem.
This message is for the exclusive use of its recipient and contains privileged and confidential information. All information contained herein is treated as confidential and should not be disclosed to third parties without the prior written consent of OPENCADD. If you are not the recipient you should not distribute, copy or archive the message. In this case, please notify the sender of it and immediately destroy the message.

De: Ralf Hielscher <notifications@github.com>
Enviada em: terça-feira, 12 de novembro de 2019 16:57
Para: mtex-toolbox/mtex <mtex@noreply.github.com>
Cc: Alberto Shimahara <alberto.shimahara@opencadd.eng.br>; Author <author@noreply.github.com>
Assunto: Re: [mtex-toolbox/mtex] Error starting Mtex5.2 error in MATLAB R2019b (#426)


Usually one includes only source files into Git, i.e., those which are not automatically generated by other files. The html help files and the search index are generated automatically and specific for specific Matlab versions.

Actually I never got the error "Could not write search database". Even without the folder helpsearch-v3. Could it be that you have no writing permission to the MTEX folder?

Ralf.

**Comment by ralfHielscher** [comment]
Can you confirm that adding the folder solves the problem? A second point
is also that the exact name of the folder depends on the Matlab version. On
my system Matlab generates the folder itself and according to the Matlab
documentation this is the correct behavior.

On the other hand we want to make the cloning of MTEX as simple as
possible. So any new information how to do this are helpful for us.

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by kilir** [comment]
Hi,
to add on the phenomenon, on macOS and ArchLinux both with Matlab2019b (but also with 2018b and as far as I remember also with some earlier versions) I need to add both folders to doc/html/helpsearch-v3, otherwise startup errors. Maybe there's somewhere a Matlab/makedoc option to automatically create the folders in your case?
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
I added the path and hope this resolves the issue
