### ISSUE TITLE
Cannot change default kernel halfwidth in PoleFigure/calcODF in MTEX 5.2 

### ISSUE THREAD

**Issue by hakonanes** [mtex-toolbox/mtex#430]
Hi, and thanks for a fantastic texture toolbox!

So, after trying out MTEX 5.2 and estimating ODFs as before using `PoleFigure/calcODF`, I cannot seem to change the default kernel halfwidth of 10 degrees by passing in the `halfwidth` option like so

```matlab
>> odf = calcODF(pfs, 'halfwidth', 5*degree)
  0 |  0.80  0.78  0.90  0.60
  1 |  0.66  0.63  0.69  0.54
  2 |  0.54  0.47  0.56  0.45
  3 |  0.48  0.39  0.54  0.41
  4 |  0.47  0.37  0.53  0.39
  5 |  0.46  0.35  0.53  0.41
  6 |  0.45  0.36  0.53  0.40
 
odf = ODF (show methods, plot)
  crystal symmetry : Al (m-3m)
  specimen symmetry: 1
 
  Radially symmetric portion:
    kernel: de la Vallee Poussin, halfwidth 10°
    center: 4946 orientations, resolution: 5°
    weight: 1
```

This option worked nicely in version 5.2.beta2. I am not that familiar with where this option is picked up in the source code, so I could not track down the changes from 5.2.beta2 to 5.2... Has something changed between these two versions that could introduce this (apparent) bug?

P.S.: The new doc pages are really nice looking!

**Comment by ralfHielscher** [comment]
Hi Hakon,

this is indeed a very good catch of a bug. Thank you very much for reporting it. It will be fixed in the next commit.

Ralf.

**Comment by hakonanes** [comment]
Great to hear, thanks a lot!

**Comment by ralfHielscher** [comment]
Can you check the fix?

**Comment by hakonanes** [comment]
After pulling the latest commit fixing the issue and running `startup_mtex` I get this message on Ubuntu 19.10 with Matlab 2019a and gcc 9.2.1-9ubuntu2:

```matlab
Start up MTEX or AstroEBSD, sir[M/a]? 
initialize MTEX 5.2  ....
********************************************************************************
 
  MTEX: Error running NFFT!
   
  The original error message was:
  Undefined function 'nfsftmex' for input arguments of type 'char'.
 
  Try to compile the binaries or contact author for help!

********************************************************************************
Creating search data base for MTEX documentation.
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error detected was:
MATLAB:doc:CannotBuildSearchDb
The specified directory does not exist. 
```

However, just applying the kernel switch as you did in the commit in the MTEX version 5.2 available from the web page **fixed the issue**!

I see the same error discussed in #426, however, Rüdiger's link to the guide (I assume?) on how to compile the NFFT binaries myself doesn't lead anywhere...

**Comment by hakonanes** [comment]
I see now the info in the `README.md` regarding the relevant directories...
