### ISSUE TITLE
Bug in EBSD.m

### ISSUE THREAD

**Issue by timramirez** [mtex-toolbox/mtex#434]
Hello,

While trying to create my own EBSD data set, I came across a bug in the EBSD.m file in the EBSDanalysis/@EBSD folder. In line 81, the option 'uniCell' is checked instead of 'unitCell'. This can cause errors during manual construction of a variable of the EBSD class. Correcting line 81 fixed the issue for me.

Best,
Tim Ramirez

**Comment by kilir** [comment]
Thank you very much for reporting this. It is corrected in the current version.
Cheers,
Rüdiger
