### ISSUE TITLE
PDF or PoleFigure out of FibreODF with large halfwidth 

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#436]
Hello,

I get some strange behavior by trying to get Pole Figure or PDF values of a fibreODF with large halfwidth – see example below. The pole figure values are 0 for halfwidth > ~74° but the ODF is ok (tested with hodf.eval and plot(hodf)).

>> cs = crystalSymmetry('6/mmm');  
>> hw = 74*degree; hodf = fibreODF(Miller(0,0,1,cs,'hkl'),zvector,'HALFWIDTH',hw);
>> calcPDF(hodf,Miller(0,0,1,cs,'hkl'),vector3d('polar',0,0))
>> ans = 1.2594 
>>
>> hw = 75*degree; hodf = fibreODF(Miller(0,0,1,cs,'hkl'),zvector,'HALFWIDTH',hw);
>> calcPDF(hodf,Miller(0,0,1,cs,'hkl'),vector3d('polar',0,0))
>> ans = 0 

Is there a limitation? 

I'm using Matlab R2017b an MTEX 5.2.beta2.

Thanks.

Arne

**Comment by kilir** [comment]
Hi Arne,
I don't get the 0-values (mtex current, matlab 2019b). For the 74/75 degree hw it's 1.2826
and 1.1422 respectively (but still not your numbers). Can you try the latest version?

Also, for very broad distributions like those, the vonMisesFisherKernel might be more suitable.

Cheers,
Rüdiger

**Comment by ArneBoch** [comment]
Hello Rüdiger,

with the current version 2.4.2 it works fine, so the beta was the problem :-).

Thanks for help.

Arne
