### ISSUE TITLE
Smooth function on hex scans

### ISSUE THREAD

**Issue by xajezade** [mtex-toolbox/mtex#437]
Hi there,

The following script doesn't work in latest version of mtex(MTEX 5.2.4):

>>eb=ebsd.gridify;
>>[grains,eb.grainId,eb.mis2mean] = calcGrains(eb,'threshold',10*degree);
>>ebsm=smooth(eb);
--progress: 0%
--No appropriate method, property, or field 'smoothhex' for class 'splineFilter'.

--Error in EBSDhex/smooth (line 96)
--  ori = filter.smoothhex(ori);

I have tried other filters other than the default (e.g. medianFilter). But it seems that smoothhex function is not defined for any filter for the EBSDs with a hexagonal scan. 

Kindest Regards,
Ali

**Comment by kilir** [comment]
Hi,
thansk for reporting this. It should be just `smooth` instead of `smoothhex` , it'll be fixed in the current version.
Cheers,
Rüdiger
