### ISSUE TITLE
Schmid factor

### ISSUE THREAD

**Issue by zxundust-2** [mtex-toolbox/mtex#438]
Hello,

I just started to learn about the Mtex. There are some problems when i calculate the schmid factor for Magnesium.

``` matlab
% define crystal symmetry
CS = crystalSymmetry('6/mmm', [3.2093 3.2093 5.2103], 'X||a*', 'Y||b', 'Z||c', 'mineral', 'Mg', 'color', 'light blue');

% define basal slip system
sS=slipSystem.basal(CS)

% define a loading direction along c axis on the crystal coordinate
loadingDirection = Miller(0,0,0,1,CS,'uvtw')
```

```
loadingDirection = Miller (show methods, plot)
 size: 1 x 1
 mineral: Mg (6/mmm, X||a*, Y||b, Z||c*)
  U 0
  V 0
  T 0
  W 1
```
```matlab
% compute the schmid factor for the slip system
SF = SchmidFactor(sS,loadingDirection)
```
```
ans =

   1.5308e-16
```
```matlab
% another way to define a stresstensor along the Z axis which is parallel to c axia 
sigma = stressTensor.uniaxial(vector3d.Z)
```
```
sigma = stressTensor (show methods, plot)
  rank: 2 (3 x 3)
 
 0 0 0
 0 0 0
 0 0 1
```
```matlab
% compute the schmid factor for the slip system
sS.SchmidFactor(sigma)
```
```
ans =

   1.2246e-16
```
_______________

why this two ways of calculation are different despite the same slip system and loading directions.

and I do not understand well with the concept on https://mtex-toolbox.github.io/SchmidtFactor.html

and using the command SchmidFactor
```matlab
sS.SchmidFactor(r)
```
```
ans =
    0.1750'
```
Ommiting the tension direction r the command SchmidFactor returns the Schmid factor as a spherical function
```matlab
SF = sS.SchmidFactor

% plot the Schmid factor in dependency of the tension direction
plot(SF)
```
The output for 'sS.SchmidFactor(r)' is a number. But the one for 'SF = sS.SchmidFactor' is a S2FunHarmonic. Dose it mean that the loading direction is not computed this way？

I do not have good background on matlab and would very appreciate if anyone can help.

**Comment by ralfHielscher** [comment]
Both values `1.5308e-16` and `1.2246e-16` are basically 0. The are to small to be distinguished from each other by a computer.

The output of  `SF = sS.SchmidFactor` is the Schmid factor as a function of the loading direction. This can be useful for finding the loading direction with the highest Schmid factor.

Ralf.

**Comment by zxundust-2** [comment]
> Both values 1.5308e-16 and 1.2246e-16 are basically 0. The are to small to be distinguished from each other by a computer.
> The output of  SF = sS.SchmidFactor is the Schmid factor as a function of the loading direction. This can be useful for finding the loading direction with the highest Schmid factor.
> Ralf.

Many thank for the reply.

I have another question. Since the output of SF = sS.SchmidFactor is the Schmid factor as a function of the loading direction, why the S2FunHarmonic figure has only one max point despite of the HCP symmetry. Should it has 6 max points?

Thank you very much

**Comment by ralfHielscher** [comment]
This is because only one slip system is considered and not the
symmetrically equivalent ones.

you can do the latter by

```matlab
SFMax = max(sS.symmetrise.SchmidFactor)
plot(SFMax,'upper')
```

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by zxundust-2** [comment]
Oh, it works, it is fantastic! Thank you, Ralf
