### ISSUE TITLE
using calcPDF for a fiber ODF 

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#439]
Hello,

I got an error using calcPDF for a Fiber ODF, for other ODFs (uniform, unimodal, calculated out of measurements) it works fine.

>> hcs = crystalSymmetry('6/mmm');
>> odf = fibre(Miller(0,0,1,hcs),zvector);
>> calcPDF(odf,Miller(0,0,1,hcs))
Undefined function 'calcPDF' for input arguments of type 'fibre'.

I'm using Matlab R2017b an MTEX 5.2.4.

Thanks for help.

Arne

**Comment by kilir** [comment]
Hi,
a) `odf = fibre(Miller(0,0,1,hcs),zvector);` is not an odf but simply a fibre
and
b) calcPDF for the class fibreComponent requires a direction or a list of directions.
Try:
```
odf = fibreODF(Miller(0,0,1,hcs),zvector);
r = equispacedS2Grid
pdf  = calcPDF(odf,Miller(0,0,1,hcs),r)
```

Does that do it?

Cheers,
Rüdiger

**Comment by ArneBoch** [comment]
Hello Rüdiger,

sorry for that, copy + paste works better sometimes:-). 

I mean:
>> cs = crystalSymmetry('6/mmm');
>> odf = fibreODF(Miller(0,0,1,cs,'hkl'),zvector);
>> calcPDF(odf,Miller(0,0,1,cs,'hkl')) 

but it works for a uniform ODF (or unimodal or a real one coming from a measurement ODF calculated with calcODF(ebsd....)): 
>> odf = uniformODF(cs);
>> calcPDF(odf,Miller(0,0,1,cs,'hkl'))

What is the difference of a fiberODF to the others that calcPDF isn't working. In methods documentation of fiberODF this version is mentioned? 
I use it to do some calulations on model ODFs  coming out of fits to real ones. I had to wrote a work arround for all ODFs having fibreODFs as components.

So it is a question of clarity only - it works well now :-).

Schönen Advent.

Arne

**Comment by kilir** [comment]
I agree that the difference in syntax isn't too a great thing and shall be solved some moment. For now, I just updated the help for fibreComponent/calcPDF to avoid this confusion.
Cheers,
Rüdiger

**Comment by zmichels** [comment]
rot = rotation.map(xvector,yvector)
The class rotation has no Constant property or Static method named 'map’.

**Comment by zmichels** [comment]
As far as I can tell —in may case — none of the “rotation.  …”  notation works.

rot = rotation.matrix(F)
The class rotation has no Constant property or Static method named 'matrix’.

**Comment by ralfHielscher** [comment]
Hi Arne,

indeed `calcPDF(odf,h)` will not return a spherical function for fibreODFs. You can overcome this shortcoming by
```matlab
pdf = calcPDF(FourierODF(odf),h)
```
Ralf.

**Comment by zmichels** [comment]
I’ve had this problem ever since it was introduced for rotation(), but I never reported it because I figured it was a work in progress. But now it shows up in the demos / examples.

**Comment by ralfHielscher** [comment]
Hi Zachary,

are you sure to have the correct MTEX version installed? You may type
```matlab
edit rotation
```
and check that the function at line 163 `r = map(varargin)` the function `map` is defined. As for the matrix the syntax should by

```matlab
rot = roation.byMatrix(M)
```

Ralf.

**Comment by zmichels** [comment]
I reran my 5.2 install and “rotation.map” works now — so I must not have been on the right version. I am not sure how it got back onto a beta. Either way, yes it works!

As for the matrix approach; the “rotation.byMatrix" also works. 

However, the following page suggests the syntax “rotation.matrix”:
https://mtex-toolbox.github.io/rotation.rotation.html <https://mtex-toolbox.github.io/rotation.rotation.html>


Also this:
help rotation
  The class *rotation* allows to work with three dimensional orthogonal
  matrices.
 
  Syntax
    rot = rotation.byEuler(phi1,Phi,phi2)
    rot = rotation.byEuler(alpha,beta,gamma,'ZYZ')
    rot = rotation.axisAngle(v,omega)
    rot = rotation.matrix(A)
    rot = rotation.map(u1,v1)
    rot = rotation.map(u1,v1,u2,v2)
    rot = reflection(b)
    rot = rotation.inversion
    rot = rotation.byRodrigues(v)
    rot = rotation(fibre(u1,v1),'resolution',5*degree)
    rot = rotation(quaternion(a,b,c,d))


Thanks and cheers,
Zach

**Comment by ArneBoch** [comment]
Hello,

thanks for help - I will use the replacement Ralf suggested.

Arne
