### ISSUE TITLE
diameter

### ISSUE THREAD

**Issue by AlexG90** [mtex-toolbox/mtex#44]
Hello,

The 'diameter' function is not working anymore in my code.

-----------------------
Code:
```matlab
grain = calcGrains(ebsd,'angle','unitcell',15*degree);
d=diameter(grain);
```
-----------------------

Error:

Error using get
Conversion to double from grain2d is not possible.

Error in grain2d/diameter (line 9)
I_VG = get(grains,'I_VG');
----------------------

I also tried 'grain.diameter' as we can use 'grain.area' in this new version but nothing works.
Do you have any idea?

MTEX version: 4.0 (it was working on the previous versions)

Thank you,
Alex

**Comment by ralfHielscher** [comment]
Hi Alex,

thank you very much for reporting this bug. I will be fixed in MTEX 4.0.17.

Ralf.
