### ISSUE TITLE
problems with calcAngleDistribution

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#440]
Hello,

I try to do some misorientation calculations and get Errors by using calcAngleDistribution or related functions (calcAxisDistribution, plotAngleDistribution,...) see example below.

>> CS = crystalSymmetry('6/mmm');  
>> odf = uniformODF(CS);
>> [density,omega] = calcAngleDistribution(odf);
Error using all
Dimension argument must be a positive integer scalar within indexing range.

Error in rotation.map (line 35)                               assert(all(delta<1E-3,'all'),...
Error in orientationRegion/cleanUp (line 70)         rot = rotation.map(aNqj,zvector,aNq0,xvector);
Error in orientationRegion (line 36)                        oR = oR.cleanUp;
Error in symmetry/fundamentalRegion (line 78)    oR = orientationRegion([Nq(:).',N0(:).'],cs,cs2,varargin{:});
Error in symmetry/calcAngleDistribution (line 21)  oR = fundamentalRegion(cs,varargin{:});
Error in ODF/calcAngleDistribution (line 40)           [density,omega] = calcAngleDistribution(cs1,cs2);

calcAngleDistribution(CS,CS) gives the same error.

What did I do wrong?

System: Matlab R2017b and MTEX 5.2.4.

Thanks for help.

Arne

**Comment by zmichels** [comment]
I don’t know if this is the root of your problem or not... but I can’t get the “rotation.map” syntax to work, even though it shows up in the function and help documentation that way for a while now. But I can use the older “rotation(‘map’,...)” syntax without problem. Since the first error in your example is related to that, I can’t help but wonder if it’s part of the trouble. 

Does plotAxisDistribution() work for you?

Cheers,
Zach

**Comment by kilir** [comment]
Hi Arne,
the option 'all' for the function all() was introduced with 2018b. I guess you could replace it with `all(delta(:)<1E-3)` if I'm not mistaken. 
Cheers,
Rüdiger

**Comment by kilir** [comment]
Zach,
in case you have trouble using the syntax `rotation.map`, what's the error that comes up?
Cheers,
Rüdiger

**Comment by ArneBoch** [comment]
Hello Rüdiger and Zach,

it looks like that this 'all' flag coming up with R2018b is my problem, need to install a newer Matlab version :-).

The replacement Rüdiger suggested works well for rotation.map(u1,v1,u2,v2) and plotAxisDistribution() works now too but  plotAxisDistribution(mori_vec) doesn't give a density plot but single points for every mori? 

I try to wrote some simple work arround for plotAngleDistribution() and plotAxisDistribution() using calcDensity(mori.axis)!?  

Thanks for help.

Arne

**Comment by kilir** [comment]
Hi,
good to hear. If this is settled, you may close it. With resepct to the desire of contours, you may either calcualte an mdf from your mori_vec or use the option 'contourf' with  plotAxisDistribution() for example.
Cheers,
Rüdiger
