### ISSUE TITLE
Error in @orientation.fibreVolume using weights

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#441]
Hello MTEX Team,

using function @orientations.fibreVolume with 'weights' option gives an error (MTEX 5.2.7). There are a naming and a calculation error. 

The old calculation part looks like this:
>> elseif check_option(varargin,'weight')
>>   weights = get_option(varargin,'weights');
>>   v = mean(weights(angle(ori .\ r,h,varargin{:}) < radius));
>> else

I hope a correct version could look like this:

>> elseif check_option(varargin,'weights')
>>   weights = get_option(varargin,'weights');
>>   v = sum(weights(angle(ori .\ r,h,varargin{:}) < radius)) / sum(weights(:));
>> else

this gives reasonable results for my data.  

Have a nice Christmas time!

Arne

**Comment by ralfHielscher** [comment]
Hi Arne,

thank you very much for providing this bug fix.

Ralf.
