### ISSUE TITLE
grain boundary perimeter and the smoothing issue - suggestion of update in the MTEX documentation

### ISSUE THREAD

**Issue by marcoalopez** [mtex-toolbox/mtex#444]
Hi MTEX developers,

a month ago I published a short outreach article on why grain boundaries should be smoothed when calculating perimeters with MTEX. You can find it here: https://t.co/1vQ3SR8noy?amp=1 Basically, I explain that if the grain boundaries are not smoothed the estimated perimeters do not correspond to those of the particle but those of the box containing it (i.e. the bounding box). In any case, I wonder if it would not be more useful to include this information (in a more simplified or brief way) in the MTEX documentation itself, since this may be relevant for people who intend to characterize the shape of grains. I also provided an MTEX synthetic example that can be used freely.

Best, Marco

**Comment by kilir** [comment]
Hola Marco,
nice article and as you might have guessed, I think to some extend and in some applications this is largely ignored when it comes to measures of grain bouadnry length. Do you think a note of caution, maybe here https://mtex-toolbox.github.io/ShapeParameters.html or here https://mtex-toolbox.github.io/grain2d.perimeter.html should do? If you can spare some time, feel free to add to the documentation where you think it needs.
Thanks and cheers,
Rüdiger

ps: I'd say the bounding box only hold for fully convex areas.

**Comment by marcoalopez** [comment]
Hi @kilir,

sorry for the late response, I was very busy this week.

Ok, when I have some free time I will prepare a very short note of caution and send a PR. Thanks.

Best, Marco

PS: you're right about the thing :)
>I'd say the bounding box only hold for fully convex areas
