### ISSUE TITLE
Bug: volume should be a fraction

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#446]
Hi Ralf,
I guess since `ODF/volume` should return fraction of an odf, there seems to be an issue with Laue groups symmetry.
Example:
```
cs1 = crystalSymmetry('321')
o_ref1 = orientation.byEuler(0,0,0,cs1)
odf1 = unimodalODF(orientation.byEuler(0,0,0,cs1),'halfwidth',15*degree)

cs2 = crystalSymmetry('-3m')
o_ref2 = orientation.byEuler(0,0,0,cs2)
odf2 = unimodalODF(orientation.byEuler(0,0,0,cs2),'halfwidth',15*degree)

volume(odf1,o_ref1,30*degree)
volume(odf2,o_ref2,30*degree)

ans =

    0.8727


ans =

    1.7454

```
This factor of two appears also for uniFormODF, kernel and Fourier odfs but I could not pinpoint the common  issue apart form SO3 space of a proper group being double the one of the corresponding Laue group.

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

for me this bug does not occur neither in MTEX 5.2.8 nor in MTEX develop.

Ralf.

**Comment by kilir** [comment]
Strangely enough,
I can't reproduce it myself eitehr now, so I guess I'm closing it.
Cheers,
Rüdiger
