### ISSUE TITLE
Problem with rotating pole figure about Z-axis

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#45]
I have been testing the differences between pole figures using RP,L1 and L2, see script below.
However rotation about Z does not seem to work, it should change the azimuth of all values.

David
```matlab
%% Defined new orientation
% Define a rotation around the specimen Z-axis about 90 degree
rot = rotation('axis',zvector,'angle',90*degree)
pfs_hkl_rot = rotate(pfs_hkl,rot)
figure
plot(pfs_hkl_rot,'antipodal')
%% Original orientation
figure
plot(pfs_hkl)
%% Compare with rotated pole figures
% RP value of Matthies
e_RP = calcError(pfs_hkl_rot,pfs_uvw,'RP')
% L1 is mean absolute difference abs(d1-d2)
e_L1 = calcError(pfs_hkl_rot,pfs_uvw,'l1')
% L2 is mean squared difference (d1-d2)^2
e_L2 = calcError(pfs_hkl_rot,pfs_uvw,'l2')
```

**Comment by ralfHielscher** [comment]
Hi David,

the problem is not in `rotate(pfs_hkl,rot)` but in `calcError(pfs_hkl_rot,pfs_uvw,'RP')`. This functions assumes that the specimen directions in both pole figures are the same. While it seems quite easy to find a solution for regular grids and rotations with angles which are multiples of the grid size, it's sees very hard to find a general solution.

I'm not so sure what to do.
Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

Thanks for your reply. However my pole figure(s) did not rotate using 

%% Defined new orientation
% Define a rotation around the specimen Z-axis about 90 degree
rot = rotation('axis',zvector,'angle',90*degree)
pfs_hkl_rot = rotate(pfs_hkl,rot)
figure
plot(pfs_hkl_rot,'antipodal’)

BUT they did change structure from 

pfs_hkl = PoleFigure (show methods, plot)
  crystal symmetry : Forsterite (mmm)
  specimen symmetry: 1
 
  h = (100), r = 181 x 361 points
  h = (010), r = 181 x 361 points
  h = (001), r = 181 x 361 points
  h = (111), r = 181 x 361 points

to 

pfs_hkl_rot = PoleFigure (show methods, plot)
  crystal symmetry : Forsterite (mmm)
  specimen symmetry: 1
 
  h = (100), r = 1 x 65341 points
  h = (010), r = 1 x 65341 points
  h = (001), r = 1 x 65341 points
  h = (111), r = 1 x 65341 points

Of course e_RP = calcError(pfs_hkl_rot,pfs_uvw,'RP’) will probably give an error as the pole figures do not have the same grid structure.

I wonder how to control the grid structure in these functions, this is a problem of re-gridding I think.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

is this problem still persistent. For me the pole figures are rotated just fine.

Ralf.

**Comment by DavidMainprice** [comment]
Many thanks Ralf for all the corrections and developments.

all the best David
