### ISSUE TITLE
basicHKL problem

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#450]
Hello MTEX Team,

using function basicHKL (crystallSymmetry) I got a results I'm not sure if it is right.

>> cs = crystalSymmetry('cubic');
>> cs.basicHKL

should give all reasonable Miller h, k, l combinations using numbers -1, 0, 1 for a given crystal symmetry I guess. The example above gives no {1 0 0} combinations.

The probably right result I got by replacing
>> p = Miller(h,k,l,cs);
with
>> p = Miller(h(:),k(:),l(:),cs);    
into the function definition?

I'm using Matlab 2017b and MTEX 5.2.8.

Thanks for help and thanks for MTEX.

Arne

**Comment by ralfHielscher** [comment]
Hi Arne.

thank you for reporting this. Your fix is is correct and will be included into the next release.

All the best,

Ralf.
