### ISSUE TITLE
reading ang files

### ISSUE THREAD

**Issue by efrainhr** [mtex-toolbox/mtex#451]
Hello

I noticed something similar to 
https://github.com/mtex-toolbox/mtex/issues/435

I think it's due to extra info in the header file. My angs have a detailed list of what each column represents (eg NOTES, Column 1: phi1 [radians], etc). If I delete header lines after the line with "SCANID", it seems to work OK.

Anyway to have mtex ignore this header.

I'm using mtex 5.2.8 and matlab2019a

Thanks!

**Comment by ralfHielscher** [comment]
Thank you for reporting this issue. Could you please attach the ang file?

Ralf.

**Comment by efrainhr** [comment]
Ralf

Thanks for the prompt response. I'm attaching a sample file. I renamed it to *.txt so I could upload. If I delete the lines between "# VERSION 7" and "# COLUMN_NOTES: End", MTEX runs fine.

Am I doing something wrong? Also, could you elaborate on the meaning of the "setting N" when using EBSD.load?

Thanks!

[sample.txt](https://github.com/mtex-toolbox/mtex/files/4149976/sample.txt)

**Comment by kilir** [comment]
Hi, there's an extra line in the ang file which is caught when finding phases. Probably a better fix shall be found but your file works for me this way. 

What version of oim (?) are you using and could you say which software/version produced the "old" format?

For the 'setting' , have a look at this thread https://groups.google.com/forum/#!msg/mtexmail/EUBSP4cOw9Y/wXWOYDXTAgAJ

Cheers,
Rüdiger

**Comment by efrainhr** [comment]
Rüdiger

I believe the OIM is version 8 (my colleague gave me the data, as I don't really do characterization). 
As for MTEX, I'm using version 5.2.8 (though I was using 5.0.3 and having the same issues).

I tried running the example I sent, and this is what I get
'''
>> ebsd = EBSD.load('sample.ang',CS,'interface','ang','convertEuler2SpatialReferenceFrame');
Error using loadEBSD_ang (line 129)
EBSD format 'ANG' does not match the data
 file: 'sample.ang'

Error in EBSD.load (line 86)
  ebsd{k} = feval(['loadEBSD_',char(interface)],...
'''

If I delete the lines between "# VERSION 7" and "# COLUMN_NOTES: End" the file loads just fine.
Am I using that function correctly? I should mention, I think loading through the import wizard works on the unedited file.

Thanks!

**Comment by kilir** [comment]
Did you apply the above change to `interfaces/loadEBSD_ang.m` ? (https://github.com/mtex-toolbox/mtex/commit/1154a3420e0774e27c0fbc1cba1f6c4b6b3450f8)

Affterwards it loads your file fine without having to delete any lines from it.

![sample_ebsd](https://user-images.githubusercontent.com/11697557/73692579-e196f800-46d4-11ea-92be-fd85951f8e63.jpg)

Cheers,
Rüdiger

**Comment by efrainhr** [comment]
Rüdiger

Excellent, this fixed it!
Thank you for your quick help!

Thanks!
