### ISSUE TITLE
Cannot download the toolbox "mtex-5.1.1.zip

### ISSUE THREAD

**Issue by huihuizhi** [mtex-toolbox/mtex#452]
Hi, professor Kilian,

Sorry to trouble you! I can't sucessfully download a release version "mtex-5.1.1.zip" from the website https://mtex-toolbox.github.io/download.
I have try many times for obtaining this in recent days, but failed. I guess that there is a link issue for me: no IP address about github-production-release-asset-2e65be.s3.amazonaws.com.

Could you send me this toobox "mtex-5.1.1.zip" through email or other ways?

Thank you so much!

Best wishes to you!

Email : zhininghui@126.com

**Comment by kilir** [comment]
Hi,
no problem here but maybe a temporary issue. 
May I ask why you want to use this old version? It's not only that newer version will have more features, but most importantly, that some bugs are fixed which might  have lead - in the worst cases - to wrong results.
Cheers,
Rüdiger

**Comment by huihuizhi** [comment]
Pro. Kilian,
I have used this version "mtex-5.1.1.zip" to perform some analysis before. I hope to continue to use the same version. But now I cannot obtain it from the above website directly.
Thank you for your so kind help!
Best wishes
Email : zhininghui@126.com

**Comment by kilir** [comment]
Hi,
you can clone the git repo and checkout about the release you like (https://github.com/mtex-toolbox/mtex/releases), d7b0956 would be for 5.1.1.
However, please study carefully bug fixes - not all are for newly introduced bug but might also apply for older issues and verify that the results you get are actually correct.
Cheers,
Rüdiger

**Comment by huihuizhi** [comment]
Pro. Kilian,
When I open MTEX, in Matlab 2018a, some errors alway happen as follows:

MTEX: Error running NFFT!
     The original error message was:
  Undefined function 'nfsftmex' for input arguments of type 'char'.
 
  Try to compile the binaries or contact author for help!

I found a folder named "ntff", such as extern\ntff. And there are two files: .gitignore and readme.md.

What are missing there?

**Comment by kilir** [comment]
Hi,
simply use the relevant binaris from a release version or compile those yourselves. It's mentioned a couple of times in the forum.
E.g. https://groups.google.com/d/msg/mtexmail/CMU2qCsZz4Y/8H4eOOspCAAJ

Other mex files should compile when starting up for the first time.
Hope this works.
Cheers,
Rüdiger

**Comment by kilir** [comment]
So I guess this is seettled.

**Comment by huihuizhi** [comment]
Pro. Kilian,
Sorry to reply you late. Following your suggestions , I did not understand how to simply solve this problem yet.
"MTEX: Error running NFFT!
The original error message was:
Undefined function 'nfsftmex' for input arguments of type 'char'."

I am struggling to deal with it.

Thank you for your so warm help!
Best wishes to you!

**Comment by kilir** [comment]
Hi,
just copy the nfft nfft_openMP folders from a release version adn you should be good to go.
Cheers,
Rüdiger

**Comment by huihuizhi** [comment]
Pro. Kilian,

I can’t get (or download) a release version due to Restricting access to the link at my staying place now. Could you send me a “nfft nfft_openMP folders”? I only can obtain no released version_mtex-5.2.7(8). And I use MATLAB 2018b (64bit) in Microsoft windows 10 system.

Thank you very much!

Best wishes to you!




发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rüdiger Kilian<mailto:notifications@github.com>
发送时间: 2020年2月8日 4:28
收件人: mtex-toolbox/mtex<mailto:mtex@noreply.github.com>
抄送: huihuizhi<mailto:huihui.zhi@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [mtex-toolbox/mtex] Cannot download the toolbox "mtex-5.1.1.zip (#452)


Hi,
just copy the nfft nfft_openMP folders from a release version adn you should be good to go.
Cheers,
Rüdiger

―

**Comment by kilir** [comment]
Hi,
sorry, I have been unclear. Any rather recent release version will do as well for the binaries. You can try the attached ones.

[Compressed file.txz.zip](https://github.com/mtex-toolbox/mtex/files/4174460/Compressed.file.txz.zip)

Rüdiger

**Comment by huihuizhi** [comment]
> Hi,
> sorry, I have been unclear. Any rather recent release version will do as well for the binaries. You can try the attached ones.
> 
> [Compressed file.txz.zip](https://github.com/mtex-toolbox/mtex/files/4174460/Compressed.file.txz.zip)
> 
> Dear Rüdiger
Thank you very much for your help. I solved this issue through downloading ntff functions. 
Now I can successfully run MTEX toolbox.
