### ISSUE TITLE
error of dislocationSystem.hcp

### ISSUE THREAD

**Issue by DingHap** [mtex-toolbox/mtex#454]
Hi Ralf,
When I started mtex, it prompted the following error

startup_mtex
initialize MTEX 5.2.8  ....
********************************************************************************
 
  MTEX: Error running NFFT!
   
  The original error message was:
  Unrecognized method, property, or field 'a' for class 'specimenSymmetry'.
 
  Try to compile the binaries or contact author for help!
Fortunately, it may not affect my normal use of mtex,
But I get errors when I use **'dislocationsystem.hcp'** for calculating GND
at the FCC and BCC, there are no errors

```
 _**dS = dislocationSystem.hcp(ebsd.CS)
Warning: Maybe I should collect here all slipSystems below 
> In slipSystem.hcp (line 134)
  In dislocationSystem.hcp (line 167) 
Output argument "sS" (and maybe others) not assigned during call to "slipSystem.hcp".

Error in dislocationSystem.hcp (line 167)
      dS = dislocationSystem(symmetrise(slipSystem.hcp(cs),'antipodal'));**_

```
I'm using Matlab 2019b and MTEX 5.2.8.

Thanks for help.

**Comment by ralfHielscher** [comment]
Have you tried reinstall MTEX?

Ralf.


********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by DingHap** [comment]
Yes, I have reinstalled MTEX, but I still have the same problem, and I have the same problem with the 5.2.7 version of MTEX

**Comment by ralfHielscher** [comment]
Your error message indicates that there is something wrong with your
installation. Maybe you have other files in your search path that have the
same name as MTEX methods.

Maybe you can do the commands

which specimenSymmetry
which symmetry

to check they are referring to MTEX functions.

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by DingHap** [comment]
After I redownloaded MTEX5.2.8 and reinstalled it, it prompted such a message,
_Warning: Function setappdata has the same name as a MATLAB builtin. We suggest
you rename the function to avoid a potential name conflict. 
initialize MTEX 5.2.8  .... done!
 
MTEX 5.2.8 (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX_
 And after I execute the two commands you suggest, matlab outputs the following results
_>> which specimenSymmetry
C:\Users\Y\Desktop\mtex-5.2.8\geometry\@specimenSymmetry\specimenSymmetry.m  % specimenSymmetry constructor
>> which symmetry
C:\Users\Y\Desktop\mtex-5.2.8\geometry\@symmetry\symmetry.m  % symmetry constructor_

I still get an error when I run _dS = dislocationSystem.hcp(ebsd_gnd.CS)_，But it doesn't happen when you run the _dS = dislocationSystem.fcc(ebsd_gnd.CS)_

_>> dS = dislocationSystem.hcp(ebsd_gnd.CS)
Warning: Maybe I should collect here all slipSystems below 
> In slipSystem.hcp (line 134)
  In dislocationSystem.hcp (line 167) 
Output argument "sS" (and maybe others) not assigned during call to "slipSystem.hcp".

Error in dislocationSystem.hcp (line 167)
      dS = dislocationSystem(symmetrise(slipSystem.hcp(cs),'antipodal'));_

 Thanks very much for your help.

**Comment by kilir** [comment]
Hi,
1) with respect to the error message you get when defining the dislocation system: 
In the class slipSystem, there are a couple of pre-defined slip systems or groups of slip systems for some lattice types. However,for hcp, there's no set of slip systems and you have to define those yourself - or combine some of the pre-defined such as prismatic, pyramidal systems etc or directly define the dislocation systems. I changed the error message a little to make this a bit clearer.

With respect to your nfft error, what Matlab / OS are you using? What's the output of 'ls' from the command line from where you start mtex and what's the content of your folders extern/nfft extern/nfft_openMP?

Cheers,
Rüdiger

**Comment by DingHap** [comment]
I will now start mtex again without any errors.
I can define the slip system for hcp
Thanks very much for your help
