### ISSUE TITLE
BUG: degraded symmetry in ebsd saved as .mat

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#456]
Hi Ralf,
this is a little nasty. EBSd varibales saved in Matlab as .mat (with a pre-symmetry handle mtex version) loose symmetry elements when laoded with the current version.

```
mtexdata titanium
cs = ebsd('t').CS
cs.rot
cs.elements

ans = rotation (show methods, plot)
  size: 1 x 1
 
  Bunge Euler angles in degree
  phi1  Phi phi2 Inv.
     0    0    0    0
 
Error using accumarray
Second input VAL must be a vector with one element for each row in SUBS,
or a scalar.

Error in symmetry/elements (line 22)
mult = accumarray(id,mult,[],@max);
```

This is somewhat annoying since this does not only of course apply to the mtexdata files but probably to 100s of datasets saved as .mat e.g. after being cleaned up using filters which take rather long etc.
Current workaround is to re-define the symmetry after loading, but maybe it's easier somewhere.

Edit: Same goes of course for grain varibales.

Cheers,
Rüdiger

Do we need a 'fixCS' function for grains/ebsd?

```
function ebsd = fixCS(ebsd);
% repair  crystalSymmetry
% for ebsd variables saved with older mtex variables
CSfixed={};
CSlist = ebsd.CSList; 
v=1;
if strcmp(CSlist{1},'notIndexed')
    CSfixed{1}=CSlist{1};
    v=2;
end
for i=v:length(ebsd.CSList)
 
% overcome rounding issues with norm 
abc = round(norm(CSlist{i}.axes)*1e8)/1e8;
% put back together
CSfixed{i} = crystalSymmetry(symmetry.pointGroups(CSlist{i}.id).Inter, ...
              abc,[CSlist{i}.alpha CSlist{i}.beta CSlist{i}.gamma], ...
              CSlist{i}.alignment, 'mineral', CSlist{i}.mineral, ...
              'color', CSlist{i}.color)
end
ebsd.CS=CSfixed;
```

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this is a very good catch. Its extremely surprising how Matlab reads in the old symmetry variables such that it is almost not recognizable that the the definition has been changed.

Your fix looks very good. I will check it a bit.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
https://github.com/mtex-toolbox/mtex/commit/211ba917dc75e0aafda873daf79ab5c36f82774c works for me, for mtexdata as well as for old saved .mat files. Great! And I'm going to close this.
Cheers,
Rüdiger
