### ISSUE TITLE
Installation of MTEX on Mac 10.14 did not install fully; problem w/ CalcDensity

### ISSUE THREAD

**Issue by anthonyrollett** [mtex-toolbox/mtex#459]
Thank you, in advance, to whoever can help with this, Tony Rollett ....
+++++++++++++++
Tried to use CalcDensity which failed as follows:
>> odf = calcDensity(ori)
Unrecognized function or variable 'nfsoftmex'.

Error in unimodalComponent/calcFourier>gcA2fourier (line 65)
plan =
nfsoftmex('init',length(A)-1,length(g),nfsoft_flags,0,4,1000,2*ceil(1.5*(length(A)+1)));
[more output]

At the installation of MTEX, the following warnings showed up:
>> startup_mtex
initialize MTEX 5.2.8  ....
********************************************************************************
 
  MTEX: Error running NFFT!
   
  The original error message was:
  Undefined function 'nfsftmex' for input arguments of type 'char'.
 
  Try to compile the binaries or contact author for help!

********************************************************************************
Warning: missing mex-file S1Grid_find.mexmaci64 
> In check_installation>fast_check_mex (line 104)
  In check_installation>check_mex (line 61)
  In check_installation (line 33)
  In startup_mtex (line 71) 

--------------------------------------------------------------------------------
Checking mex files failed!
> Trying now to recompile mex files.
... compiling S1Grid_find.c
Building with 'Xcode with Clang'.
MEX completed successfully.
[more output, all indicating successful compilation]

**Comment by kilir** [comment]
Hi,
the complaint comes from the binaries which should be located in extern/nfft and extern_openMP. For macOS the files should be nfsoftmex.mexmaci64 and nfsftmex.mexmaci64. 

Could you try the attached ones?

[nfft.zip](https://github.com/mtex-toolbox/mtex/files/4220684/nfft.zip)

Cheers,
Rüdiger

**Comment by anthonyrollett** [comment]
Thank you so much!
 I put the inside the mtex-develop/extern/nfft and /nfft_openMP folders.
I then ran calcDensity – and it worked.
I really appreciate the quick response
Best regards
Tony
……………………..
A.D. (Tony) Rollett
US Steel Professor of Metallurgical Eng. and Materials Sci.
FTMS,FASM,FInstP,FA∑µ
Co-director of the NextManufacturing Center
Carnegie Mellon University
** Attend the next Texture conf.: icotom19.com
5000 Forbes Ave.
Pittsburgh PA 15213
Ph: 412 268 3177 (no voicemail)
Websites: https://anthony.rollett.org/
https://engineering.cmu.edu/next/index.html

**Comment by kilir** [comment]
You're welcome. If you use the development version form github, it won't contain those binaries and it also won't contain a compiled documentation. 
It probably would be a good idea to put up some up to date compiling instructions, especially since under macOS it's a little odd to produce portable binaries.

Cheers and closing this one,
Rüdiger
