### ISSUE TITLE
Fourier coefficients estimation

### ISSUE THREAD

**Issue by ckim130** [mtex-toolbox/mtex#460]
Hello

Thanks for sharing this wonderful toolbox for free!

I am trying to extract Fourier coefficients from EBSD(either Al or Fe) and use them to estimate the effective elastic constants(second and third-order i.e. C11 and C111).

To do this, I need the 2nd and 4th order Fourier coefficients. I figured out how to extract them thanks to the online tutorial.

1. I am having trouble with figuring out what convention is used in mtex (Roe? Bunge? Cylindrical? So far I wasn't able to find a paper on the cylindrical coordinate.)

2. The model I am trying to use is in Roe's notation. If mtex is using another convention, can I get the reference on the relevant papers?

I would appreciate any help!

Thanks

**Comment by daiz89** [comment]
Did you figure it out?
