### ISSUE TITLE
intragranular misorientation analysis

### ISSUE THREAD

**Issue by zxundust-2** [mtex-toolbox/mtex#463]
Hello everyone.

I am working on the intragranular misorientation analysis(IGMA). I try to plot the axis distribution of misorientation between neighbouring pixels within single grain. It is kind of like KAM. KAM concentrate on the angle distribution from all neighbouring pixel and take the maximum one, but the IGMA calculate the misorientation with certain orders, like all adjacent pairs from left to right. 

I found somebody contribute the KAM code to extract adjacent pairs and calculate the misorientation (https://github.com/mtex-toolbox/mtex/blob/9b9e2451c0567412d612fa8026be632140cb1e72/EBSDAnalysis/%40EBSD/KAM.m). Howere, the code can not work well in matlab R2019b and mtex5.1.1, and it is very complicated for the beginners like me to understand. 

Can anyone be so nice to revise the code and give some instructions? Many thanks!

kindly regards,
Xun

**Comment by kilir** [comment]
Hi,
I think this is the same question you had in the forum an I think the forum might be a much better place suited for this question and get an answer while the issues may rather directly relate to mtex functionality, enhancement etc.
Cheers,
Rüdiger
