### ISSUE TITLE
Seismic velocity underestimated in Average tensors/ set outer margin

### ISSUE THREAD

**Issue by filippeof** [mtex-toolbox/mtex#47]
Dear Dr. Ralf
1) Mtex 4.0.16 seems to underestimate aggregate average seismic velocity evaluated by any of the three methods (voigt,reuss,hill). Please, find attached the figure output of mtex4.0.14 and mtex4.0.16 , for voigt method, using the same code (simmilar to mtex examples, but if you need my codes or ebsd file i can send it via e mail)

2) Some of my plots  im mtex 4.x are cutting the titles. Interactively changing outer margin to 40 (mtexmenu>Set outer margin) seems to solve the issue for me. I would like to ask how can i change it by code, something like setMTEXpref('setOuterMargin',40)?

Thanks, 
Filippe

![mtex4 0 14](https://cloud.githubusercontent.com/assets/11142094/7075235/a7d3cfaa-ded6-11e4-9884-f865d7b2393a.jpg)
![mtex4 0 16](https://cloud.githubusercontent.com/assets/11142094/7075237/a7d71c14-ded6-11e4-8f12-9a8fafe0ccdb.jpg)

**Comment by ralfHielscher** [comment]
Hi Filippe,

quick answer to question 2 first:
```matlab
setMTEXpref('outerPlotSpacing',10);
```
should do the trick. See also ```mtex_settings```

For question 1 some scripts and data would be nice.

Ralf.

**Comment by filippeof** [comment]
Thanks for your reply.I send the scripts and files to your e mail.
Filippe

**Comment by ralfHielscher** [comment]
Hi Filippe,

this was a bug in MTEX 4.0.0 - 4.0.14 and had been fixed in MTEX 4.0.15 in ee94934e57709266322fdd46402a60fd23a96c69. If you look at the Voigt and Reuss averages you see that the ones computed by MTEX 4.0.16 makes much more sense.

I'm very sorry about this inconvenience and give my best to avoid those bugs in the future,

Ralf.

**Comment by filippeof** [comment]
You are right. Comparing with similar works on such samples, mtex 4.0.16 seems to give the proper results. Thanks for your answer.
Filippe.
