### ISSUE TITLE
startup.m conflicts with personal startup.m-file

### ISSUE THREAD

**Issue by MicAtWork** [mtex-toolbox/mtex#470]
I have a personal startup.m file that adjust some settings. Now since the installation of MTEX my startup.m-file gets ignored since the MTEX-path is always placed on top in the MATLAB search path.

Maybe the MTEX startup.m-file could look for other startup.m-files further down in the search path and also execute the second top-most file?

**Comment by ralfHielscher** [comment]
You could remove the file ```startup.m``` from the MTEX main directory and call ```startup_mtex.m``` from your ```startup.m``` file.

Ralf.

**Comment by MicAtWork** [comment]
Thanks I didn't think of that...
