### ISSUE TITLE
error of export ebsd data to .ctf

### ISSUE THREAD

**Issue by DingHap** [mtex-toolbox/mtex#479]
Hi Guys,

When I export ebsd data using the following command from MTEX ,and reload the exported data, the following error occurs and the data cannot be used in AZtec crystal.
`ebsd_filled2.export('filled2.ctf')`
`ebsd = EBSD.load([mtexEBSDPath filesep 'filled2.ctf'],'convertEuler2SpatialReferenceFrame') `
Warning: this implementation of uitable is deprecated and no longer supported.
In uitable_deprecated
In uitable (line 38)
In GenericApi/localCreatePage (line 
In GenericApi (line 18)
In generic_wizard (line 20)
In loadEBSD_generic (line 72)
In check_interfaces (line 47)
In EBSD.load (line 72)

In addition，When I execute the following code, I get an error.
`export_ctf(ebsd,'2.ctf','2.cpr')`
 Exporting 'ctf' file 
-> Collecting data
- Microscope acquisition parameters not available
-> Opening file for writing
-> Writing file header
-> Assembling data array
The method, property, or field 'x' of class 'EBSDsquare' is not recognized.
error EBSD/export_ctf (line 170)
if ebsdGrid.x(1,1)< ebsdGrid.x(1,2)

Best,
Hao

**Comment by kilir** [comment]
Hi,
I think this should fix the error for now.
Cheers,
Rüdiger

**Comment by Alireza25101989** [comment]
Hello 
 How can I export to cpr/crc pair format ??
The command " export_ctf(ebsd,'myFile') " is only working to exporting to ctf format but nit cpr/crc. 

Thank you
