### ISSUE TITLE
osc file format are not detected

### ISSUE THREAD

**Issue by Jenny918** [mtex-toolbox/mtex#480]

**Comment by kilir** [comment]
Hi,
can you be a bit more specific? Which file formats version, platform, mtex version etc. In general, using human readable or well documented formats is preferred over others.
Cheers,
Rüdiger

**Comment by Jenny918** [comment]
Hi. thank you very much. i use matlab 2018 and mtex 5.0.3 to Import ebsd data(.osc format). when import ebsd data it keep remainding me that "could not detect file format.please contact one of the maintainers of MTEX and send him a copy of your data files".
yours,
Jenny

**Comment by kilir** [comment]
Hi,
first of all, try to use a more recent mtex version. There are different version of the .osc format, it might be that the one you are using is not supported.
Cheers,
Rüdiger
