### ISSUE TITLE
zAxisDirection preference not working in 5.3?

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#485]
Hi, 

I am working with a colleague's code in which they have specified the z-axis plotting conventional follows:
setMTEXpref('zAxisDirection','intoPlane')

In past versions of mtex, this meant that a vector3D object of:
v = vector3d(0,0,1)

would plot in the lower hemisphere. Similarly, with this convention set, the pre-defined vector3D object 'zvector' would plot in the lower hemisphere.

However, I running mtex v5.3, when I try to set the z-axis plotting convention, the vector3D object always plots in the upper hemisphere. The result is the same whether I set it in my mtex-settings.m or on-the-fly. Oddly though, the ebsd map gets flipped as you would expect, but the pole-figure plotting does not change. Is this a bug? Or, am I doing something wrong even though identical to how I did it for previous versions? Or, was this a purposeful change? It is causing much confusion as we try to logically define stress tensors for some experimental data (because the way we are defining them depends on the map directions and plotting conventions).

Example:

% Load example data
mtexdata forsterite

% set plotting convention to "intoPlane"
setMTEXpref('zAxisDirection','intoPlane');

% plot the ebsd map (this seems to be correctly flipped)
figure,
plot(ebsd)
![mtexForsterite_map_Z_intoPlane](https://user-images.githubusercontent.com/8769619/83037711-baf12a00-a001-11ea-828f-20af4541b4f5.png)

% define a vector3d object for positive z-direction 
v = vector3d(0,0,1);

% plot the vector3d (this looks incorrect)
figure,
plot(v)
![mtexForsterite_001_intoPlane](https://user-images.githubusercontent.com/8769619/83037882-eecc4f80-a001-11ea-969e-68d8d0da330e.png)

% now plot the pre-defined zvector (this also looks incorrect)
figure,
plot(zvector)
![mtexForsterite_Zvec_intoPlane](https://user-images.githubusercontent.com/8769619/83037911-f5f35d80-a001-11ea-8005-1c821a3d56a0.png)

% now switch the plotting convention to "outOfPlane"
setMTEXpref('zAxisDirection','outOfPlane');

% plot the ebsd map (now looks flipped back as expected)
figure,
plot(ebsd)
![mtexForsterite_map_Z_outOfPlane](https://user-images.githubusercontent.com/8769619/83037935-ff7cc580-a001-11ea-96b0-435f908cc7e8.png)

% and again plot the "z vectors" (these look correct)
figure,
plot(v)
![mtexForsterite_001_outOfPlane](https://user-images.githubusercontent.com/8769619/83037955-086d9700-a002-11ea-9a11-c2be382eeb01.png)

figure,
plot(zvector)
![mtexForsterite_Zvec_outOfPlane](https://user-images.githubusercontent.com/8769619/83037988-13282c00-a002-11ea-9025-97bbca56b37c.png)

**Comment by zmichels** [comment]
Also, I should have shown that the y-direction flips as expected (though not z)... which is what I expect the vector to do (it used to for previous versions).

% set plotting convention to "intoPlane"
setMTEXpref('zAxisDirection','intoPlane');


% plot y-direction:
figure,
plot(yvector)
![yvector_for_z_intoPlane](https://user-images.githubusercontent.com/8769619/83039031-44552c00-a003-11ea-8a2c-c7e442b18317.png)


% set plotting convention to "intoPlane"
setMTEXpref('zAxisDirection','outOfPlane');


% plot y-direction:
figure,
plot(yvector)
![yvector_for_z_outOfPlane](https://user-images.githubusercontent.com/8769619/83039054-4a4b0d00-a003-11ea-8393-d4be39c18b22.png)

**Comment by ralfHielscher** [comment]
Hi Zach,

I have checked this for older versions of MTEX, i.e., 4.X and 5.X and found they behave all the same. The logic logic behind this behaviour is that upper / lower always refers to the sphere, i.e., upper hemisphere z>0 and lower hemisphere z<0. 

I understand that  one could define upper / lower also with respect to the projection. I'm not so sure what is better.

Is this a issue for you?

Ralf.

**Comment by zmichels** [comment]
Ralf,

Thanks for the reply. I could have sworn it always flipped in previous versions, but of course I believe you that it didn’t – actually that might explain some previous confusion in collaborations with folks trying to apply rotations. I don't use "intoPlane" myself, because I prefer to think of y-direction upwards on the page, and perhaps I never noticed this before because in that case the zvector polarity is aligned with the hemispheres. However, to me it is awkward that it is defined using 'zAxisDirection' if it has no effect on how the zvector plots, whereas it does affect yvector... and changing the convention for xDirection changes the xvector direction. The main difficulty for me is communicating the effects of different conventions to collaborators long-distance who don’t use mtex often, and in this case it seems unnecessarily inconsistent. Specifically... in the case where we are defining a stressTensor (or vector orientation) which is not perfectly aligned with the z-axis, the convention *does* matter... but if someone plots the z-axis as a reference for defining the directions, they will see a zvector orientation that is completely unaffected by the convention. I recognize that the flipped treatment of the yvector is what controls the different orientations of the plots below, and so perhaps I can just try to communicate that to colleagues. So I can continue to work with this, but it seems to me that it would be most consistent and straightforward for it to have the same effect on all vector coordinates.

Thanks and cheers,
Zach


%% Example with stressTensor:

% set plotting convention to "intoPlane"
setMTEXpref('zAxisDirection','intoPlane');

v = vector3d(0,-1,-1);

% set the stress tensor using the loading direction ('v') defined above
sigma = stressTensor.uniaxial(v);

% plot the stress tensor to confirm it
figure,
plot(sigma,'upper')
hold on
plot(v)
plot(zvector)
![stressTensor_z_intoPlane](https://user-images.githubusercontent.com/8769619/83083169-0ed43100-a04b-11ea-89da-dfbeeb51c246.png)


% [0,0,1]
figure,
plot(vector3d(0,0,1))
![mtexForsterite_001_intoPlane](https://user-images.githubusercontent.com/8769619/83083192-1bf12000-a04b-11ea-82f1-4272788b1301.png)


% switch plotting convention to "outOfPlane"
setMTEXpref('zAxisDirection','outOfPlane');

% plot the stress tensor to confirm it
figure,
plot(sigma,'upper')
hold on
plot(v)
plot(zvector)
![stressTensor_z_outOfPlane](https://user-images.githubusercontent.com/8769619/83083213-2f9c8680-a04b-11ea-874a-2d4d00701308.png)



% [0,0,1]
figure,
plot(vector3d(0,0,1))

![mtexForsterite_001_outOfPlane](https://user-images.githubusercontent.com/8769619/83083243-4216c000-a04b-11ea-9a67-61f2e04386a9.png)
