### ISSUE TITLE
Error using calcMIndex

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#486]
Hi,

calcMIndex worked in previous versions. Now, using v5.3, when I try to use calcMIndex with an ODF, I get an error. 

Example

%% Bug using calcMIndex.m:

% load forsterite dataset
mtexdata forsterite

% compute an ODF
odf = calcDensity(ebsd('f').orientations);

% compute M-index
MI = calcMIndex(odf);

Unrecognized method, property, or field 'axes' for class 'specimenSymmetry'.

Error in symmetry/union (line 7)
  axes = s2.axes;

Error in symmetry/calcAngleDistribution (line 29)
  cs = union(cs,varargin{1});

Error in ODF/calcMIndex (line 37)
[density_uniform,~] = calcAngleDistribution(odf.CS,odf.SS);

**Comment by kilir** [comment]
Hi Zach,
that was fixed in the current version.
https://github.com/mtex-toolbox/mtex/commit/aac48b37b271ca683a1ae50a6ece81484997ff7c
Cheers,
Rüdiger

**Comment by zmichels** [comment]
Hi Rüdiger,

Thank you very much.

Cheers,
Zach
