### ISSUE TITLE
Errors in calcDensity(ori)

### ISSUE THREAD

**Issue by jackson911007** [mtex-toolbox/mtex#488]
Hi all, 
I tried to use MTEX to calculate ODF from my EBSD data(.osc). But it always shows the following errors. I checked my glibc(2.3.0) and the MTEX version (5.3.0). Can anyone help me with this?

Thanks a lot,

>>Command I typed: 
odf = calcDensity(ebsd('Mg').orientations)

>>Errors I got:
Invalid MEX-file '/Users/dw567/Documents/MATLAB/mtex-5.3/extern/nfft/nfsoftmex.mexmaci64':
dlopen(/Users/dw567/Documents/MATLAB/mtex-5.3/extern/nfft/nfsoftmex.mexmaci64, 6): no suitable image
found.  Did find:
	/Users/dw567/Documents/MATLAB/mtex-5.3/extern/nfft/nfsoftmex.mexmaci64: code signature in
        (/Users/dw567/Documents/MATLAB/mtex-5.3/extern/nfft/nfsoftmex.mexmaci64) not valid for use in
        process using Library Validation: library load disallowed by system policy

Error in unimodalComponent/calcFourier>gcA2fourier (line 65)
plan = nfsoftmex('init',length(A)-1,length(g),nfsoft_flags,0,4,1000,2*ceil(1.5*(length(A)+1)));

Error in unimodalComponent/calcFourier (line 29)
f_hat = gcA2fourier(g,c,A);

Error in ODF/calcFourier (line 28)
  hat = calcFourier(odf.components{i},L,varargin{:});

**Comment by jackson911007** [comment]
>>This is my script:
%% Import Script for EBSD Data
%
% This script was automatically created by the import wizard. You should
% run the whoole script or parts of it in order to import your data. There
% is no problem in making any changes to this script.

%% Specify Crystal and Specimen Symmetries

% crystal symmetry
CS = crystalSymmetry('6/mmm', [3.2 3.2 5.2], 'X||a*', 'Y||b', 'Z||c*', 'mineral', 'Mg');

% plotting convention
setMTEXpref('xAxisDirection','north');
setMTEXpref('zAxisDirection','outOfPlane');

%% Specify File Names

% path to files
pname = '/Users/dw567/Desktop';

% which files to be imported
fname = [pname '/map20191107053342077.osc'];

%% Import the Data

% create an EBSD variable containing the data
ebsd = EBSD.load(fname,CS,'interface','osc',...
  'convertEuler2SpatialReferenceFrame');

**Comment by ralfHielscher** [comment]
Please have a look at

https://mtex-toolbox.github.io/installation

Ralf.

**Comment by jackson911007** [comment]
Thanks for the response! Ralf.

**Comment by jackson911007** [comment]
Hi Ralf:

I used curl to download"curl --output mtex.zip https://github.com/mtex-toolbox/mtex/releases/download/mtex-5.3/mtex-5.3.zip". However, I cannot unzip the file on my Mac. I tried different unzip apps such as "The Unarchiver" ,and also changed it to .rar. They all cannot unzip this file on my Mac(it seems weird). Do you have any suggestion?

**Comment by ralfHielscher** [comment]
Have you tried the command

unzip mtex-5.3.zip

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by jackson911007** [comment]
Yes, I did.

I got the following error: (file name is mtex.zip)

>>Terminal:

xxx-iMac curl % unzip mtex.zip
Archive:  mtex.zip
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
atter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of mtex.zip or
        mtex.zip.zip, and cannot find mtex.zip.ZIP, period.

**Comment by kilir** [comment]
Hi,
can you try:
`curl -LJO --output mtex.zip https://github.com/mtex-toolbox/mtex/releases/download/mtex-5.3/mtex-5.3.zip"`
? 
Cheers,
Rüdiger

**Comment by jackson911007** [comment]
It works. I unzipped the file but I still got the same errors when I tried "odf = calcDensity(ebsd('Mg').orientations)"

I just tried to use "parrallels desktop"(window) to run matlab. "odf = calcDensity(ebsd('Mg').orientations)" It works without errors. I guess MTEX might have some compatibility problem with my macOS catalina systems. I will try to operate MTEX on my "parrallels desktop" but please let me know if you have other suggestions

Thanks a lot, Rüdiger and Ralf, 

Dung-Yi, Wu

**Comment by kilir** [comment]
The error is related to macOS not willing to run binaries downloaded from the internet.
You could try
`sudo xattr -r -d com.apple.quarantine /path/to/mtexfolder`
on the downloaded and expanded mtex folder.
Cheers,
Rüdiger

**Comment by jackson911007** [comment]
Appreciate the advice!

best, 

Dung-Yi, Wu
