### ISSUE TITLE
problem loading osc files

### ISSUE THREAD

**Issue by xajezade** [mtex-toolbox/mtex#498]
Hi there,

I am using mtex version 3.5.1 (the latest official version). While my osc file can be detected and be read, it cannot understand phase flags. So, I need to load a cif file to make my scan recognizable. The problem is that if I have non-indexed points, it will be automatically imported as indexed because I cannot distinguish them from other points. 

It is worth to be noted that I don't have any problem using MTEX 5.2.8. 

Kindest Regards,
Ali

**Comment by ralfHielscher** [comment]
Could you please provide a data file that causes this problem?

Ralf.

**Comment by xajezade** [comment]
Hi Ralf,

Here is the link to my dropbox: https://www.dropbox.com/s/3v25n2w0dppa136/375C24H_300C32mms70-1_FromEdge_10.osc?dl=0

Please note that I have used MTEX on my mac system and I have not tried it on other OSs.

thanks,
Ali

**Comment by ralfHielscher** [comment]
Hi Ali,

thank you for reporting this. I hope I could fix it.

Ralf.
