### ISSUE TITLE
Probleme with calcGrains in MTex 4.0.2

### ISSUE THREAD

**Issue by ThomasChauve** [mtex-toolbox/mtex#5]
Hey
It is again me, I hope I don't bother you.

I found something that I thinks is weird but Iam not sure.
I am loading ebsd data without probleme and if a do this 

``` matlab
grains = calcGrains(ebsd('indexed'),'angle',g_angle*degree);
oM = ipdfHSVOrientationMapping(ebsd('Ice-Ih'));
```

or this

``` matlab
[grains,ebsd.grainId, ebsd.mis2mean] = calcGrains(ebsd,'angle',g_angle*degree);
oM = ipdfHSVOrientationMapping(ebsd('Ice-Ih'));
```

I have no probleme but if I do this

``` matlab
[grains,ebsd.grainId, ebsd.mis2mean] = calcGrains(ebsd('indexed'),'angle',g_angle*degree);
oM = ipdfHSVOrientationMapping(ebsd('Ice-Ih'));
```

I've got this error and I don't understand why ?

``` matlab
Index exceeds matrix dimensions.

Error in dynProp/subSet (line 58)
        dp.prop.(fn{i}) = dp.prop.(fn{i})(ind);

Error in EBSD/subSet (line 8)
ebsd = subSet@dynProp(ebsd,ind);

Error in EBSD/subsref (line 13)
  ebsd = subSet(ebsd,ind);

Error in ebsd_CI06_triple_junction (line 42)
oM = ipdfHSVOrientationMapping(ebsd('Ice-Ih')); 
```

I found this weird. I hope this can help.

Thanks
Thomas

**Comment by Sogo5030** [comment]
I followed the guide in #5 but I still got the error:

[grains,ebsd.grainId, ebsd.mis2mean] = calcGrains(ebsd,'angle',1*degree);

I get this error,

Undefined function 'sparse' for input arguments of type 'int32'.

Error in spatialDecomposition (line 44)
I_FD = sparse(I_ED1(I_ED2<=numX),I_ED2(I_ED2<=numX),1,size(F,1),numX);

Error in EBSD/calcGrains (line 70)
[V,F,I_FD] = spatialDecomposition([ebsd.prop.x(:), ebsd.prop.y(:)],ebsd.unitCell,varargin{:});
