### ISSUE TITLE
Question u = h.uvw with h as Miller gives u as double variable not Miller

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#50]
Question u = h.uvw with h as Miller gives u as double variable not Miller
```
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: An100 (-1, X||a*, Z||c)
  h 1
  k 1
  l 1
```
```matlab
u = h.uvw
```
```
u = 0.0238    0.0070    0.0113
```
 How do convert u to Miller?
``` matlab
Miller(u,CS)
```
```
Error using Miller (line 106)
You need at least 3 Miller indice!
% only solution seems to be for an integer result
```
```matlab
round(Miller(u(1),u(2),u(3),CS,'uvw'))
```
```
ans = Miller (show methods, plot)
 size: 1 x 1
 mineral: An100 (-1, X||a*, Z||c)
  u 9
  v 3
  w 4
```
all the best David

**Comment by ralfHielscher** [comment]
Hi David,

I do not really get what you want to do. Expressing h with respect to the direct coordinate system you can do
```matlab
h.dispStyle='uvw'
```
Maybe
```matlab
round(h)
```
if you prefer integer numbers.

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

sorry for the delay in replying. 

A small example

%% MTEX conversion between hkl and uvw
CS = crystalSymmetry('mmm', [4.756 10.207 5.98], 'mineral', 'Forsterite', 'color', 'dark green')
% N.B. converted uvw and hkl not always integer values
h = Miller(1,1,1,CS,'Forsterite','hkl')
% change hkl (h) to uvw  N.B. result hkl is numerical double not Miller
uvw = h.uvw
u = Miller(1,1,1,CS,'Forsterite','uvw')
% change uvw (u) to hkl N.B. result hkl is numerical double not Miller
hkl = u.hkl
% To convert h Miller (hkl) to Miller (uvw) object use dispStyle
h.dispStyle = 'uvw'
% To convert u Miller (uvw) to Miller (hkl) object use dispStyle
u.dispStyle = 'hkl'
% print h is now an object Miller uvw
h
% print u is now an object Miller hkl
u
% round h and u
h_round = round(h)
u_round = round(u)


OUTPUT

CS = crystalSymmetry (show methods, plot)
 
  mineral : Forsterite
  color   : dark green
  symmetry: mmm       
  a, b, c : 4.8, 10, 6
 
 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 1
  k 1
  l 1

uvw =

    0.0442    0.0096    0.0280

 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 1
  v 1
  w 1

hkl =

   22.6195  104.1828   35.7604

 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 0.0442
  v 0.0096
  w  0.028
 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 22.6195
  k 104.183
  l 35.7604
 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 0.0442
  v 0.0096
  w  0.028
 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 22.6195
  k 104.183
  l 35.7604
Error using subsindex
Function 'subsindex' is not defined for values of class 'Miller’.

So here there is an error with round. In fact my suggestion was rather it would be more useful if uvw = h.uvw created a variable that was Miller rather than numerical double, but if for some reason you find that h.dispStyle = ‘uvw’ you find this syntax more elegant we will have to live with this.

all the best David

**Comment by DavidMainprice** [comment]
P.S. dispStyle cannot be found in the documentation with 4.0.17 or the documentation on line


Dear Ralf,

Sorry for the delay in replying. 

A small example

%% MTEX conversion between hkl and uvw
CS = crystalSymmetry('mmm', [4.756 10.207 5.98], 'mineral', 'Forsterite', 'color', 'dark green')
% N.B. converted uvw and hkl not always integer values
h = Miller(1,1,1,CS,'Forsterite','hkl')
% change hkl (h) to uvw  N.B. result hkl is numerical double not Miller
uvw = h.uvw
u = Miller(1,1,1,CS,'Forsterite','uvw')
% change uvw (u) to hkl N.B. result hkl is numerical double not Miller
hkl = u.hkl
% To convert h Miller (hkl) to Miller (uvw) object use dispStyle
h.dispStyle = 'uvw'
% To convert u Miller (uvw) to Miller (hkl) object use dispStyle
u.dispStyle = 'hkl'
% print h is now an object Miller uvw
h
% print u is now an object Miller hkl
u
% round h and u
h_round = round(h)
u_round = round(u)


OUTPUT

CS = crystalSymmetry (show methods, plot)
 
  mineral : Forsterite
  color   : dark green
  symmetry: mmm       
  a, b, c : 4.8, 10, 6
 
 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 1
  k 1
  l 1

uvw =

    0.0442    0.0096    0.0280

 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 1
  v 1
  w 1

hkl =

   22.6195  104.1828   35.7604

 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 0.0442
  v 0.0096
  w  0.028
 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 22.6195
  k 104.183
  l 35.7604
 
h = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  u 0.0442
  v 0.0096
  w  0.028
 
u = Miller (show methods, plot)
 size: 1 x 1
 mineral: Forsterite (mmm)
  h 22.6195
  k 104.183
  l 35.7604
Error using subsindex
Function 'subsindex' is not defined for values of class 'Miller’.

So here there is an error with round. In fact my suggestion was rather it would be more useful if uvw = h.uvw created a variable that was Miller rather than numerical double, but if for some reason you find that h.dispStyle = ‘uvw’ you find this syntax more elegant we will have to live with this.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

the rounding bug I was not able to reproduce. As for ```m.uvw``` I do not want to change this as I use it internally and ```m.u``` is very similar and obviously returns a scalar. Instead I introduced in mtex-4.0.18 the syntax
```matlab
m_uvw = Miller(m_hkl,'uvw')
```
which allows to switch from hkl to uvw. I think this makes it very clear that the output is now Miller.

I hope you like this,

Ralf.

**Comment by DavidMainprice** [comment]
Dear Ralf,

Yes the proposed syntax is more explicit and I like it.

all the best David

**Comment by DavidMainprice** [comment]
My revised teaching script would look like this for MTEX 4.0.18

%% MTEX conversion between hkl and uvw using Miller
CS = crystalSymmetry('mmm', [4.756 10.207 5.98], 'mineral', 'Forsterite', 'color', 'dark green')
% N.B. converted uvw and hkl not always integer values
%
% define (111) integer Miller
h_hkl = Miller(1,1,1,CS,'Forsterite','hkl')
% change h_hkl to [uvw]  N.B. result is non-integer Miller h_uvw
h_uvw = Miller(h_hkl,'uvw')
% change h_uvw to BACK to (hkl)  N.B. result is integer Miller h_hkl2 
% and the same as h_hkl =  (111)
h_hkl2 = Miller(h_uvw,'hkl')
%
% define [111]  integer Miller
u_uvw = Miller(1,1,1,CS,'Forsterite','uvw')
% change u_uvw to (hkl)  N.B. result is non-integer Miller u_hkl
u_hkl = Miller(u_uvw,'hkl')
% change u_hkl BACK to [uvw]  N.B. result integer is Miller u_uvw2 
% and the same as u_uvw =  [111]
u_uvw2 = Miller(u_hkl,'uvw')
%% MTEX conversion between hkl and uvw using dispStyle
%  and *.hkl *.uvw for extacting numerical double values
%
% define (111) integer Miller
h_hkl = Miller(1,1,1,CS,'Forsterite','hkl')
% To convert h_hkl Miller (hkl) to non-integer Miller [uvw] object using dispStyle
h_hkl.dispStyle = 'uvw'
% To convert h_hkl Miller [uvw] BACK to Miller [uvw] object using dispStyle
h_hkl.dispStyle = 'hkl'
% Extract double numerical values from Miller object of hkl or uvw
% N.B. values are integer if originally defined as integer Miller as for hkl
double_hkl = h_hkl.hkl
% N.B. values are non-integer if originally defined as integer Miller as for hkl
double_uvw = h_hkl.uvw
%
% define [111] integer Miller
u_uvw = Miller(1,1,1,CS,'Forsterite','uvw')
% To convert u_uvw Miller [uvw] to non-integer Miller (hkl) object using dispStyle
u_uvw.dispStyle = 'uvw'
% To convert u_uvw Miller [uvw] BACK to Miller [uvw] object using dispStyle
u_uvw.dispStyle = 'hkl'
% Extract double numerical values from Miller object of hkl or uvw
% N.B. values are integer if originally defined as integer Miller as for uvw
double_uvw = u_uvw.uvw
% N.B. values are non-integer if originally defined as integer Miller as for uvw
double_hkl = u_uvw.hkl
