### ISSUE TITLE
Texture rotated during export_vpsc

### ISSUE THREAD

**Issue by ZhangxiJesseFeng** [mtex-toolbox/mtex#505]
Hi,

Please find the attached code (debugReconstructXPC.txt, change .txt to .m) and attached XPC texture data (change .txt to .xpc).

The code will read the xpc data and construct pole figure and ODF. It then outputs the data in VPSC format using export_vpsc. The code was written with MTEX 5.1.1 and I am now running it in 5.3.1. When I run the code, I see that the pole figures plotted up until export_vpsc are all consistent - the poles are all in the same place. However, after I exported into VPSC and imported the data back in, the pole figure is suddenly rotated by 90°. If I uncomment the `setMTEXpref('xAxisDirection','south');` on line 83, the pole figures now match (xAxisDirection was originally set to east on line 31). Does anyone have insight on why export_vpsc seems to rotate the texture in this case?

Thanks!

Jesse

[xpctexture.txt](https://github.com/mtex-toolbox/mtex/files/4938331/xpctexture.txt)
[debugReconstructXPC.txt](https://github.com/mtex-toolbox/mtex/files/4938334/debugReconstructXPC.txt)

**Comment by kilir** [comment]
Hi Jesse,
I can't reproduce any rotation introduced by export_vpsc with your script. Maybe you reset/set your plotting preferences at some moment during something else?
Cheers,
Rüdiger

**Comment by ZhangxiJesseFeng** [comment]
> Hi Jesse,
> I can't reproduce any rotation introduced by export_vpsc with your script. Maybe you reset/set your plotting preferences at some moment during something else?
> Cheers,
> Rüdiger

Hi Rüdiger,

Thanks for replying. I don't know what changed, perhaps because I closed MATLAB and opened again, but I also do not see the issue anymore... That is really strange.

Jesse
