### ISSUE TITLE
Weighting of individual orientations - does this still work in MTEX 4 ?

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#51]
For example working with grains
```matlab
% mean orientations weighted by grain area
%
% odf calculation that works in MTEX3.5.0
odf_by_area = calcODF(o_mean_grains,'kernel',k,'Fourier','weight',g_area)
```
does not seem to take into account the weighting in MTEX4 ?
```
% You can use the orientations within the grains
odf_by_orientations = calcODF(ebsd(grains).orientations,'kernel',k,'Fourier')
```
this would give the same as weighting by area if all positions are indexed in the grains, if there are non-indexed points (holes) in the grains then weighting by area would give slightly different result.

all the best David

**Comment by ralfHielscher** [comment]
Hi David,
```matlab
odf_by_area = calcODF(grains.meanOrientations,'weights',grains.area)
```
still works as desired. The keyword is ```'weights'``` - though documentation was bad. I changed it right now.

Ralf

**Comment by DavidMainprice** [comment]
> Le 17 avr. 2015 à 15:37, Ralf Hielscher <notifications@github.com> a écrit :
> 
> Hi David,
> 
> odf_by_area = calcODF(grains.meanOrientations,'weights',grains.area)
> still works as desired. The keyword is 'weights' - though documentation was bad. I changed it right now.
> 
> Ralf
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mtex-toolbox/mtex/issues/51#issuecomment-93987566>.
> 
Many thanks David
