### ISSUE TITLE
Consistent Miller Indices dispStyle

### ISSUE THREAD

**Issue by ralfHielscher** [mtex-toolbox/mtex#530]
@jhiscocks, please provide some more information what you would like to have changed in Miller/dispStyle

* what are the specific use cases that do not work with the current notation
* how would you like to see this fixed
* have a look at #529 where I started working on this.

Ralf.

**Comment by jhiscocks** [comment]
Hi Ralf, I realised I hadn't explained things clearly so I apologize for that.  If you look at the Miller function documentation

dispStyle - 'hkl', 'uvw', 'HKIL', 'UVTW'

except, when you try to use  'HKIL' it doesn't work correctly.  Enter the following (although it's trivial, the displayed output changes between them).

m1=Miller(1,1,-2,3,cs,'UVTW') 
m2=Miller(1,1,-2,3,cs,'HKIL')

figure;plot(m1,'upper','labeled')
figure;plot(m2,'upper','labeled')

I get an error message after the second one of these, but if you use m2=Miller(1,1,-2,3,cs,'hkil')  it works as expected.  Am I missing something here? 

Jessica

**Comment by ralfHielscher** [comment]
Hi Jessica,

I see the inconsistency. My problem is a little bit that for uvw and UVTW we have in general u != U . That is why we have `u` and `U`. For `HKIL` and `hkl` we have always h=H, k = K and l = L.

But I think you are right, we should make it more strict.

could you please download 

https://github.com/mtex-toolbox/mtex/tree/feature/MillerdispStyle

and check whether this is better for you.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Jessica,

I have reworked the hkl / uvw management in the current beta. Would you like to test it?

Ralf.

**Comment by jhiscocks** [comment]
Hi Ralf, I finally got around to checking this out with version 5.5.2, and the HKIL thing works as I would expect now, so that's fixed.
