### ISSUE TITLE
Using annotate for specific pole figures plots in list

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#54]
For example if you have a list of pole figure 100,010 and 001, but to want to make a specific annotate for each pole figure in the list, how would do this ?

all the best David

**Comment by ralfHielscher** [comment]
The key is the command ```gcm``` which gives you access to all figure properties.
```matlab
mtexFig = gcm
```
In particular, ```mtexFig.children``` contains a list of all single plots in the figure. To annotate something to the second plot do
```matlab
hold on
plot(xvector,'parent',mtexFig.children(2))
hold off
```
Note that this syntax is only allowed for a single plot. To plot different object into different plots you have to use a loop.

Ralf.
