### ISSUE TITLE
Issue with importing EBSD data with .crc extension

### ISSUE THREAD

**Issue by PapStatMechMat** [mtex-toolbox/mtex#557]
Hi,

I get the following error when trying to import EBSD data with a .crc extension:

>> ebsd = EBSD.load(fileName)
Error using check_interfaces (line 53)
Could not detect file format. You may ask for help in the MTEX
forum (https://groups.google.com/forum/#!forum/mtexmail).
Error in EBSD.load (line 72)
  [interface,options] =
  check_interfaces(fname{1},'EBSD',varargin{:}); 

Importing the example .crc files in MTEX5.4 data folder works fine.

Best,
SP

**Comment by lfgmorales** [comment]
Hi


It might be that your *.crc file has a slightly different format to the ones working using import_wizard, Oxford sometimes changes the format here and there. It is normally better to export your data as a *.ctf file (an ASCII file that you can look to see what it contains), that should work nicely with mtex 5.4


cheers



Luiz




Luiz F. G. Morales
ScopeM & Structural Geology and Tectonics Group
ETH Zürich
________________________________

**Comment by ralfHielscher** [comment]
Hi SP,

thank you for reporting this issue. Could you please send the data file, i.e. both the crc and the cpr file.

Ralf.

**Comment by PapStatMechMat** [comment]
Hi Luiz,

Can you import any of the .crc files here? Can you try and let me know?

https://www.dropbox.com/sh/pdcavtcfm01rdul/AACC_VBc2SP90ZLsQUM--JDZa
<https://vmail.ncbj.gov.pl/owa/redir.aspx?C=nVtkEPXr_AID1XQEPT18bf3hOavuBL4gzVa7k40pIfgDQt6HqurYCA..&URL=https%3a%2f%2fwww.dropbox.com%2fsh%2fpdcavtcfm01rdul%2fAACC_VBc2SP90ZLsQUM--JDZa>

Thank you,

Stefanos Papanikolaou

**Comment by PapStatMechMat** [comment]
Hi Ralf,

Can you import any of the .crc files here? Can you try and let me know?

https://www.dropbox.com/sh/pdcavtcfm01rdul/AACC_VBc2SP90ZLsQUM--JDZa
<https://vmail.ncbj.gov.pl/owa/redir.aspx?C=nVtkEPXr_AID1XQEPT18bf3hOavuBL4gzVa7k40pIfgDQt6HqurYCA..&URL=https%3a%2f%2fwww.dropbox.com%2fsh%2fpdcavtcfm01rdul%2fAACC_VBc2SP90ZLsQUM--JDZa>

Thank you,

Stefanos Papanikolaou

**Comment by lfgmorales** [comment]
Dear Stefanos


I cannot open this link you sent


Do you have your *.crc files in the same folder as the *.cpr files? Otherwise they will not work on MTEX


Even better would be to have the *.ctf file, which is a text file you can export from Channel /Aztec



cheers



Luiz


Luiz F. G. Morales
ScopeM & Structural Geology and Tectonics Group
ETH Zürich
________________________________

**Comment by kilir** [comment]
Hi
both sets of .crc/.cpr work for me. Maybe you need to explain a little more what you do.

Cheers,
Rüdiger

**Comment by PapStatMechMat** [comment]
Hi Rüdiger,

Yes, it worked for me as well too, in the end. Thank you for letting me
know.

Sincerely,
Stefanos
