### ISSUE TITLE
When not explicitly set, point size for pole figures varies.

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#563]
**What do you want to do?**
Plot pole figures

**What data do you have?**
Magnesium EBSD data

**What code do you use?**
%ebsd data in variable named ebsd

o=ebsd('Magnesium').orientations
h=[Miller(0,0,1,cs), Miller(1,0,0,cs),Miller(1,1,1,cs),Miller(1,1,0,cs)];
figure;plotPDF(o,h);

**What result do you get**
The point size for the (11-21) pole figure is different than that for the other pole figureds

![untitled](https://user-images.githubusercontent.com/16214025/98055796-53d76d00-1e0c-11eb-9d94-d6851007797a.jpg)

**What result do you expect**
Identical point sizing on all pole figures by default.

**What MTEX version do you use?**
5.4.0

**Comment by kilir** [comment]
Hi,
point size depends as a function of the number of points per plot. If it should be fixed for all plots by default, what would you say should be that size?
Cheers,
Rüdiger

**Comment by jhiscocks** [comment]
This makes a lot of sense - if I was just plotting one orientation I would want points like the larger size.  I think the current state of things is fine, I'll just add a note to the manual that the default point size changes with the number of points to be plotted for each pole figure.  Just out of curiosity, which .m file is this controlled in?

Cheers, J

**Comment by ralfHielscher** [comment]
Its in vector3d/scatter approximately in line 70.

Ralf.
********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************
