### ISSUE TITLE
EBSD data rotated 90 degrees out of plane does not plot

### ISSUE THREAD

**Issue by jhiscocks** [mtex-toolbox/mtex#564]
**What do you want to do?**
Plot an EBSD map that's been rotated 90 degrees out of the XY plane 

**What data do you have?**
Magnesium EBSD data

**What code do you use?**
Please provide minimalist code with code in the following form
rot2=rotation.byAxisAngle(yvector,90*degree)
ebsd_rot2=rotate(ebsd,rot2)
figure;plot(ebsd_rot2('indexed'),ebsd_rot2('indexed').orientations)

**What result do you get**
Distorted map with projections extending from it, or no map.
![untitled](https://user-images.githubusercontent.com/16214025/98057937-833ca880-1e11-11eb-8f79-6e719d1778ad.jpg)

**What result do you expect**
a line, or an error message.

**What MTEX version do you use?**
5.4.0

**Comment by kilir** [comment]
Hi,
for 90 degree, I get a line and for other angles I get the correct distortion with the current mtex development version. Could you try if it works for your file with the 5.5beta5
Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Rotating EBSD data out of the visualization plane is currently not supported.
