### ISSUE TITLE
Defining your own color map in MTEX4

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#59]
In MTEX 3.5 it was relatively easy to define your own color map for pole figure colorbar scales using

``` colormap```.
For example a simple 3-color based on White (RedBlueGreen=111) to Yellow (RBG=110) to Red(RGB=100) called "very red hot metal" is very popular with some students.

In Matlab you can use 
```matlab
% white to yellow to red
r = [1.0 1.0 1.0]
g = [1.0 1.0 0.0]
b = [1.0 0.0 0.0]
map = [r; g; b]
colormap(map)
``````

but this does not work too well with MTEX4 as the colors are not gradual transitions from White to Yellow to Red.

We seem to be missing some documentation in this area.

all the best David

**Comment by ralfHielscher** [comment]
```matlab
mtexColorMap
```
should do the trick

**Comment by DavidMainprice** [comment]
May be I missed the point here ? It does not give a smooth transition in color

all the best David

%%
%**************************************************************************
% Plot Enstatite Pole Figures (PFs)  in Sample co-ordinates (X,Y,Z) 
% Colorbar for each pole figure (default)
%**************************************************************************
figure
setMTEXpref('FontSize',25)
plotPDF(odf_Enstatite,PFs_opx,'antipodal','resolution',5*degree,'contourf');
% white to yellow to red
r = [1.0 1.0 1.0]
g = [1.0 1.0 0.0]
b = [1.0 0.0 0.0]
map = [r; g; b]
mtexColorMap(map)
colorbar
% add labels for X,Y and Z sample directions on PFs
annotate([xvector,yvector,-zvector],'label',{'X','Y','Z'},'backgroundcolor','w','MarkerSize',15,'FontSize',20)
% gray for publications
%colormap(white2blackColorMap)
% file name
saveFigure('/MatLab_Programs/11OA168_PFs_contour_hkls_Enstatite_colorbar_for_each_default.png’)

**Comment by din14970** [comment]
Maybe it's a late reply, but a map can be an array of size nx3, where the columns represent rgb values and rows basically represent bins. If you define 3 colors, that is 3 rows and thus 3 bins. You can generate a more smooth gradient in other ways, for example:
c1=[1:-0.01:0]
c2=zeros(length(c1),1)
c3=[0:0.01:1]
map= [c1', c2', c3']
mtexColorMap(map)
This is a gradient map going from red to blue passing through purple. The way you generate your map is completely up to you.
