### ISSUE TITLE
Problem with calcGrains for indexed pixels only

### ISSUE THREAD

**Issue by ajcross89** [mtex-toolbox/mtex#6]
There is a small bug when getting grain ID's and mis2mean using calcGrains with the ebsd('indexed') option. 

The following command.....

``` matlab
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd('indexed'),'angle',10*degree)
```

Gives.....

```
Index exceeds matrix dimensions.

Error in dynProp/subSet (line 58)
        dp.prop.(fn{i}) = dp.prop.(fn{i})(ind);

Error in EBSD/subSet (line 8)
ebsd = subSet@dynProp(ebsd,ind);

Error in EBSD/plot (line 65)
    color = ebsd.subSet(ind).color;

Error in MTEX4_test (line 60)
plot(ebsd)
```

But there is no problem with using.....

``` matlab
ebsd = ebsd('indexed')
[grains,ebsd.grainId,ebsd.mis2mean] = calcGrains(ebsd,'angle',10*degree)
```

**Comment by Sogo5030** [comment]
I following the guide in #5 but I still got the error:

[grains,ebsd.grainId, ebsd.mis2mean] = calcGrains(ebsd,'angle',1*degree);

I get this error,

Undefined function 'sparse' for input arguments of type 'int32'.

Error in spatialDecomposition (line 44)
I_FD = sparse(I_ED1(I_ED2<=numX),I_ED2(I_ED2<=numX),1,size(F,1),numX);

Error in EBSD/calcGrains (line 70)
[V,F,I_FD] = spatialDecomposition([ebsd.prop.x(:), ebsd.prop.y(:)],ebsd.unitCell,varargin{:});
