### ISSUE TITLE
memory usage in plotODF

### ISSUE THREAD

**Issue by KarstenKunze** [mtex-toolbox/mtex#60]
Hello Ralf,
plotODF consumes temporarily more than 5 GB of memory, as recorded by task manager.
This creates out of memory errors on older systems running XP.

Observed on several examples for trigonal CS (quartz), e.g.
demo pole figures in ..\data\PoleFigure\BearTex\go_2_2.XPa

Just import pole figure data and run 
odf = calcODF(pf)
pause
plotODF(odf)

Are there any options which would reduce memory consumption?
Thanks, kk.

**Comment by ralfHielscher** [comment]
Hi Karsten,

somehow I can not reproduce this. Maybe you can check version 4.0.20.


Anyway, thank you for reporting this. I'l try to find a solution.

Ralf.

**Comment by KarstenKunze** [comment]
Hello Ralf,

same behavior in MATLAB R2014b running MTEX 4.0.20, see screenshot attached (from a Win7 system).

Thanks,

kk.





________________________________
Von: Ralf Hielscher [notifications@github.com]
Gesendet: Montag, 4. Mai 2015 22:09
An: mtex-toolbox/mtex
Cc: Kunze Karsten
Betreff: Re: [mtex] memory usage in plotODF (#60)


Hi Karsten,

somehow I can not reproduce this. Maybe you can check version 4.0.20.

Anyway, thank you for reporting this. I'l try to find a solution.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Karsten,

the estimation of the memory seems to be wrong on windows. I will fix this in the next version. In the meanwhile you can change line 152 in ```mtex_settings.m``` to
```matlab
setMTEXpref('memory',500*1024);
```
and restart mtex. I hope this helps,

Ralf.

**Comment by KarstenKunze** [comment]
Hello Ralf,

thanks a lot for the workaround, seems to help.

Ciao, kk.



________________________________
Von: Ralf Hielscher [notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 07:49
An: mtex-toolbox/mtex
Cc: Kunze Karsten
Betreff: Re: [mtex] memory usage in plotODF (#60)


Hi Karsten,

the estimation of the memory seems to be wrong on windows. I will fix this in the next version. In the meanwhile you can change line 152 in mtex_settings.m to

setMTEXpref('memory',500*1024);

and restart mtex. I hope this helps,

Ralf.
