### ISSUE TITLE
MTEX 5.4.0 and 5.5.0 incompatible with Matlab older than 2019a

### ISSUE THREAD

**Issue by DorianDepriester** [mtex-toolbox/mtex#606]
Its seems that MTEX 5.5.0 is not compatible with versions of MATLAB older than R2019a, because multiple output argument for class constructors has been implemented in R2019a. The timestamped documentions give:

- for [2018b](https://fr.mathworks.com/help/releases/R2018b/matlab/matlab_oop/class-constructor-methods.html#brd2m9e-3): "_The only output argument from a constructor is the object constructed._"
- for [2019a](https://fr.mathworks.com/help/releases/R2019a/matlab/matlab_oop/class-constructor-methods.html#brd2m9e-3): "_The constructor can return multiple arguments, but the first output must be the object created._"

I'm not sure if this can be considered as a bug, but at least this requirement should be stated, for instance in the compatibility matrix given on [MTEX download page](https://mtex-toolbox.github.io/download).

**What do you want to do?**
Install MTEX 5.5.0.

**What code do you use?**
```matlab
mtexdata aachen
grains=calcGrains(ebsd);
```

**Error Message**
```
The constructor for class 'grain2d' must return only one output value.
```
**What MTEX version do you use?**
MTEX 5.5.0

**Comment by ralfHielscher** [comment]
Hi Dorian,

thank you very much for pointing this out. I'l try to workaround this.

Ralf.

**Comment by Alireza25101989** [comment]
> Hi Dorian,
> 
> thank you very much for pointing this out. I'l try to workaround this.
> 
> Ralf.

Dear Dr. Hielscher

I can not run MTEX 5.5.0 even with MATLAB 2020a. 
An error pops-up every time when I install MTEX 5.5.0 

Thank you.
