### ISSUE TITLE
restricting grain boundaries to the fundamental region ?

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#63]
We can create a inter-phase grain boundary set by
```matlab
gB_Opx_Cpx = grains.boundary('Enstatite','Diopside')
```
But the misorientations are not restricted to the fundamental region in ```gB_Opx_Cpx```, where as
can the plot of the axis can be.
```matlab
plotAxisDistribution(gB_Opx_Cpx,'antipodal','contourf','fundamentalRegion')

gB_Opx_Cpx = grains.boundary('Enstatite','Diopside','fundamentalRegion')
```
gives an error.

Is there anyway to apply ```fundamentalRegion``` to ```gB_Opx_Cpx``` ?

all the best David

**Comment by ralfHielscher** [comment]
I updated the previous command.
