### ISSUE TITLE
ImportWizard: Pole figures with superposition 

### ISSUE THREAD

**Issue by KarstenKunze** [mtex-toolbox/mtex#64]
The superposition weights (c) are not correctly imported when entered manually using the import wizards:

a) missing in m-scripts is the line
% structure coefficients
c = {1,[0.52 ,1.23]};

b) the workspace variable pf is possible to display using plot(pf), but 
>> odf = calcODF(pf)
------ MTEX -- PDF to ODF inversion ------------------
Error using cat
Dimensions of matrices being concatenated are not consistent.

Error in Miller/cat (line 26)
m.x = cat(dim,vx{:});

Error in vector3d/horzcat (line 4)
v = cat(2,varargin{:});

Error in PoleFigure/get.h (line 81)
      h = [pf.allH{:}];

Error in PoleFigure/calcODF (line 90)
gh = symmetrise(S3G).' * pf.h; % S3G x SS x CS x h
 
>> pf.h
>> pf.c

ans = 

    [1x2 double]    [1]    [1x2 double]    [1x2 double]    [1]    [1]

**Comment by ralfHielscher** [comment]
I can confirm the first bug. For the second I need more information. Which data are how imported. Maybe you can post the output of 
```
pf.allH
```
Ralf

**Comment by KarstenKunze** [comment]
Hello Ralf,

the attached script runs fine.

The problem occurs when importing the same data into workspace variable pf using the import_wizard :

>> plot(pf) - OK

>> odf = calcODF(pf) - errors as reported

>> pf.c

ans =

    [1x2 double]    [1]

>> pf.allH

ans =

    [2x1 Miller]    [1x1 Miller]



________________________________
Von: Ralf Hielscher [notifications@github.com]
Gesendet: Mittwoch, 6. Mai 2015 05:53
An: mtex-toolbox/mtex
Cc: Kunze Karsten
Betreff: Re: [mtex] ImportWizard: Pole figures with superposition (#64)


I can confirm the first bug. For the second I need more information. Which data are how imported. Maybe you can post the output of

pf.allH


Ralf

—
Reply to this email directly or view it on GitHub<https://github.com/mtex-toolbox/mtex/issues/64#issuecomment-99313159>.

%% Import Script for PoleFigure Data
%
% This script was automatically created by the import wizard. You should
% run the whoole script or parts of it in order to import your data. There
% is no problem in making any changes to this script.

close all
clear all

%% Specify Crystal and Specimen Symmetries

% crystal symmetry
CS = crystalSymmetry('321', [4.916 4.916 5.4054], 'X||a', 'Y||b*', 'Z||c', 'mineral', 'Quartz', 'color', 'light blue');

% specimen symmetry
SS = specimenSymmetry('1');

% plotting convention
setMTEXpref('xAxisDirection','north');
setMTEXpref('zAxisDirection','outOfPlane');

%% Specify File Names

% path to files
pname = '.\';

% which files to be imported
fname = {...
  [pname '\Qtz_100_13_osc_Bgr_Def.xpe'],...
  [pname '\Qtz_011_101_13_osc_Bgr_Def.xpe'],...
  };

%% Specify Miller Indice
h = { ...
  Miller(1, 0,-1, 0,CS),...
  [Miller(1, 0,-1, 1,CS),Miller(0, 1,-1, 1,CS)],...
  };

%% Specifiy Structural Coefficients for Superposed Pole Figures
c = {1,[0.70 ,0.30]}; % from Schmid & Casey (1986)

%% Import the Data

% create a Pole Figure variable containing the data
pf = loadPoleFigure(fname,h,CS,SS,'superposition',c,'interface','beartex');
figure
plot(pf)

%% Compute and plot the ODF:
odf = calcODF(pf)

%% recalculate and plot the pole figures
figure
plotPDF(odf,pf.allH,'superposition',pf.c,'antipodal')

**Comment by KarstenKunze** [comment]
Another observation:

As long as ALL pole figures are either superposed or not, it seems to be fine.

Confusion may come from the situation, where some pole figures are and others are not superposed in the same dataset.





________________________________
Von: Kunze Karsten
Gesendet: Mittwoch, 6. Mai 2015 18:48
An: mtex-toolbox/mtex
Betreff: AW: [mtex] ImportWizard: Pole figures with superposition (#64)




Hello Ralf,

the attached script runs fine.

The problem occurs when importing the same data into workspace variable pf using the import_wizard :

>> plot(pf) - OK

>> odf = calcODF(pf) - errors as reported

>> pf.c

ans =

    [1x2 double]    [1]

>> pf.allH

ans =

    [2x1 Miller]    [1x1 Miller]



________________________________
Von: Ralf Hielscher [notifications@github.com]
Gesendet: Mittwoch, 6. Mai 2015 05:53
An: mtex-toolbox/mtex
Cc: Kunze Karsten
Betreff: Re: [mtex] ImportWizard: Pole figures with superposition (#64)


I can confirm the first bug. For the second I need more information. Which data are how imported. Maybe you can post the output of

pf.allH


Ralf

**Comment by ralfHielscher** [comment]
Hi Karsten,

as a quick workaround you can do
```matlab
pf.allH{1} = pf.allH{1}.'
```
to change [2x1 Miller] to [1x2 Miller]
Ralf.
