### ISSUE TITLE
Contoured pole figure plots

### ISSUE THREAD

**Issue by DavidMainprice** [mtex-toolbox/mtex#69]
In previous versions you could use the cursor get the density value (multiple of uniform distribution) and azimuth and polar angle at that position by clicking the mouse. Now for several versions we only get ```Error in custom data tip sting function```

all the best David

**Comment by ralfHielscher** [comment]
Hi David,

can you tell me which plots are effected. For ODF, PDF and IPDF work fine.

Ralf.
