### ISSUE TITLE
Removing "merged" grains truncated by the map boundaries 

### ISSUE THREAD

**Issue by RicCNR** [mtex-toolbox/mtex#7]
Hi,
thank you very much for your MTEX.
I am determining the grain size from EBSD maps, removing the grains near the edge of map that are truncated by the map boundary. I am working by MEX 3.5.0 with Matlab 11 (because of the present limits of my PC).
About this, I have seen that you developed the very useful function "select_full_grains.m". In my case, before to apply it, I should merge my grains with CSL(3) boundaries in a new grains object. But, after that, the function does not work (while it works very well on the original grain object without merging).
These are the steps (error message included):

``` matlab
grains1 = calcGrains(ebsd,'angle',2*degree)
plotBoundary(grains2,'property',CSL(3),'delta',2*degree,'linecolor','b','linewidth',2)
grains=merge(grains1,CSL(3))
grains_n = select_full_grains(grains)
```

```
Do you want reduice the sample area ? (1 yes, 0 no (default)) : 0
--- Undefined function or variable "pos".-------
----Error in select_full_grains (line 72)
new_grains = findByLocation(grains,pos)-----
```

The resolution is very important for me: could you help me about this my issue, or give some indication where to find the relevant answers?

Thank you very much again 
Best regards 

Riccardo
Researcher at the National Research Council of Italy, Milan

**Comment by ralfHielscher** [comment]
Hi RicCNR,

would you mind if I use your data for documentation in MTEX? If you want to keep you data secret do you have some similar data to demonstrate CSL boundaries?

Thank you,

Ralf.

**Comment by RicCNR** [comment]
Hi Ralf,
thank you for your consideration and sorry for my delay on the answer.
Unfortunately the data that I worked (and that you have seen) are secret data about  a public demonstration or publication, for now at least.
However, I will try to find to you opportune data, similar to that aforesaid (about the same argument), as soon as possible.

Regards

RicCNR





----Messaggio originale----

Da: notifications@github.com

Data: 20/02/2015 17.28

A: "mtex-toolbox/mtex"<mtex@noreply.github.com>

Cc: "RicCNR"<rickyd5@libero.it>

Ogg: Re: [mtex] Removing "merged" grains truncated by the map boundaries  (#7)




Hi RicCNR,


would you mind if I use your data for documentation in MTEX? If you want to keep you data secret do you have some similar data to demonstrate CSL boundaries?


Thank you,


Ralf.
