### ISSUE TITLE
wierd behaviour after installing mtex via git

### ISSUE THREAD

**Issue by bjoerneske** [mtex-toolbox/mtex#705]
wanted to upgrade my mtex with the latest version but got wierd issues.

one is now impossible to get rid off:

`Unknown kind value "ordered" `

gets prompted in the command window when trying to use tabulator completion..

```
clear all
>> startup_mtex
initialize MTEX 5.6.0  .... done!
 
MTEX (develop) (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
 
Unknown kind value "ordered"
>> load cz (error when pressing tab here) 
```
Suspect that a failure in one of the installation attempts messed up something that needs to be cleared from matlab (i am using matlab2017a)

If I uninstall mtex then tab completion works fine again in the command window..

```
MTEX unistalled!
>> load cz and TAB produces
>>load cz_2009_map3.mat
```

**Comment by ralfHielscher** [comment]
Hi Björn,

can you somehow track this down to an MTEX function? load is actually a
Matlab function.

All the best,

Ralf.




********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by bjoerneske** [comment]
i had some problems installing mtex and then this occurred when intalling. The error generally messes up TAB completion in the command window..

**Comment by bjoerneske** [comment]
```
>> startup_mtex
I found another version of MTEX and remove it from the current search path!
Warning: The file 'C:\Users\eskesore\Documents\GitHub\mtex\startup_mtex.m' could not be cleared because it
contains MATLAB code that is currently executing. 
> In startup_mtex>do_install (line 117)
  In startup_mtex (line 33) 
Warning: The file 'C:\Users\eskesore\Documents\GitHub\mtex\startup_mtex.m' could not be cleared because it
contains MATLAB code that is currently executing. 
> In startup_mtex>do_install (line 117)
  In startup_mtex (line 33) 
Warning: The file 'C:\Users\eskesore\Documents\GitHub\mtex\startup_mtex.m' could not be cleared because it
contains MATLAB code that is currently executing. 
> In startup_mtex>do_install (line 117)
  In startup_mtex (line 33) 
initialize MTEX 5.6.0  .... done!
 
MTEX (develop) (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
 
```

**Comment by bjoerneske** [comment]
after updating to matlab 2020b from 2017b no problems: I think actually matlab get messed up during the github problems I had so the best advice if someone has similar issues is to re-install matlab :) So a matlab issue and not a matex issue:

```
>> startup_mtex
initialize MTEX 5.6.0  .... done!
 
MTEX 5.6.0 (show documentation)
  Import pole figure data
  Import EBSD data
  Import ODF data
 
  Uninstall MTEX
 
>> load cz_2009_map3.mat
```
