### ISSUE TITLE
Single orientation pole figures

### ISSUE THREAD

**Issue by KarstenKunze** [mtex-toolbox/mtex#73]
For a single orientation (0,0,0) of a triclinic crystal, the pole figure plots do not coincide for the discrete orientation (blue dots, correct to my opinion) and the odf derived contours (incorrect). Below please find the output of the attached script, using MTEX 4.20. The convention on the crystal coordinate system follows the OIM format using 'Y||b*', 'Z||c'. I have not tested the same issue on any other symmetry settings yet.
Many thanks & regards, 
kk. 
![polefigures_hkl](https://cloud.githubusercontent.com/assets/12185848/8436933/0b98cf5c-1f5c-11e5-9e32-262fd9e80479.jpg)
![polefigures_uvw](https://cloud.githubusercontent.com/assets/12185848/8436934/0b9a6948-1f5c-11e5-8da9-3d8f9e5e0e38.jpg)
```matlab
%% Single orientation with triclinic symmetry
%
close all; clear all; 

% crystal symmetry triclinic (Albite)
cs = crystalSymmetry('1', [8.155 12.821 7.14], [93.965,116.4,89.46]*degree,...
    'Y||b*', 'Z||c', 'mineral', 'Albite', 'color', 'cyan');
ss = specimenSymmetry('1')

% plotting convention
setMTEXpref('xAxisDirection','north');
setMTEXpref('zAxisDirection','outOfPlane');

% basis vectors and plane normals
r_a = Miller(1,0,0,cs,'uvw');
r_b = Miller(0,1,0,cs,'uvw');
r_c = Miller(0,0,1,cs,'uvw');
h_a = Miller(1,0,0,cs);
h_b = Miller(0,1,0,cs);
h_c = Miller(0,0,1,cs);
h = [h_a,h_b,h_c,-h_a,-h_b,-h_c];
r = [r_a,r_b,r_c,-r_a,-r_b,-r_c];

% ODF calculation 
o = orientation('Euler',0*degree,0*degree,0*degree,cs,ss)
odf = calcODF(o,'halfwidth',30*degree)

% plot discrete and contour pole figures
plotPDF(odf,h,'grid','grid_res',90*degree)
hold on
plotPDF(o,h,'Marker','o','MarkerSize',10,'MarkerColor','b')
hold off

figure
plotPDF(odf,r,'grid','grid_res',90*degree)
hold on
plotPDF(o,r,'Marker','o','MarkerSize',10,'MarkerColor','b')
hold off
```

**Comment by ralfHielscher** [comment]
Hi Karsten,

the point is that ```calcODF``` uses sometimes binning for improved performance. Obviously, this should not be used for only few orientations. I have changed the defaults such that for less then 1000 orientations binning is not used. 

In the meantime you can use either
```matlab
odf = calcODF(o,'halfwidth',30*degree,'exact')
```
or
```matlab
odf = unimodalODF(o,'halfwidth',30*degree)
```

Ralf.
