### ISSUE TITLE
Possibility of merging .osc datas

### ISSUE THREAD

**Issue by llcc** [mtex-toolbox/mtex#74]
Hi @ralfHielscher @ppinard 

I have seveal .osc files for some parts of one samples, the observed areas for these .osc files are neighbouring and overlapping. I would like to merge these files using mtex, or import these files to mtex and merging the generated data together. Is this possible?

Thanks for any help!

**Comment by ralfHielscher** [comment]
Yes this is possible. Simply import the ebsd data into different variables and then merge them. The syntax is
``` matlab
ebsd1 = loadEBSD('fname1')
ebsd2 = loadEBSD('fname2')

ebsd = [ebsd1,ebsd2]
```
