### ISSUE TITLE
Normalization by default in calcTaylor

### ISSUE THREAD

**Issue by JustinYCheng** [mtex-toolbox/mtex#750]
## Is your feature request related to a problem? Please describe.
When I use calcTaylor to calculate the Taylor factor, it seems that there is a dependence of the calculated Taylor factor on the magnitude of the strain tensor used for this calculation. For example if I use calcTaylor in this manner:
```
% oriList - a list of orientations that I want to calculate the Taylor factor for
% eps - the strain tensor that I use
% sS - a single slip system that I symmetrise to obtain the set of slip systems that will be used in the computation
% M - my Taylor factors for each orientation
[M,~,~] = calcTaylor(inv(oriList)*eps,sS.symmetrise);
```
So if I define my strain tensor as:
```
eps = strainTensor(diag(2*[-.5 -.5 1]))
```
The value of M (or the Taylor factor) obtained using calcTaylor will be 2 times the value of the factor that I get using:
```
eps = strainTensor(diag([-.5 -.5 1]))
```
## Describe the solution you'd like
I made a discussion asking for advice in the Ask Anything forum, and it looks like normalizing the strain tensor passed to `calcTaylor` gets you correct values of the Taylor factor. I think it'd be common sense to have the normalization occur by default in `calcTaylor` i.e. have the function perform the normalization, instead of having it to do it yourself everytime you want to use `calcTaylor`.

## Propose a Syntax
Before line 35 in `calcTaylor.m`, insert a line:

```matlab
eps = normalize(eps);
```

**Comment by kilir** [comment]
Hi,

`eps/eps.norm`

Cheers,
Rüdiger
