### ISSUE TITLE
kernel density estimator

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#76]
Hi Ralf,
using the function tools/math_tools/kde.m for a one-dimensional data results in an error. Example:
```
a=[randn(100,1)];
kde(a)
Error using  .* 
Matrix dimensions must agree.

Error in kde (line 83)
a_t = a .* exp(-(0:n-1)'.^2 * pi^2 * t_star / 2);
```
However, the kde function at:
https://www.mathworks.com/matlabcentral/fileexchange/14034-kde-data-n-min-max
doesn't do it.

I'm wondering if this behavior is intentional?

All the best,
Rüdiger

update: this is with mtex4.1beta4

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for pointing this out. In mtex-4.1.beta6 I have included the updated function from fileexchange. I still have to check whether I made some changes to it.

Ralf.
