### ISSUE TITLE
Sharp color-coding for mapping a direction

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#80]
Hi Ralf,
is there any easy way to apply a sharp color-coding for the mapping of a direction (vector 3d) in analogy to using a sharp ipf-colorcoding.
So basically instead of:

``` matlab
oMd = ipdfHSVOrientationMapping(ebsd);
oMd.inversePoleFigureDirection = mean(ebsd.orientations) * oMd.whiteCenter;
oMd.colorStretching = 10;
figure
plot(ebsd,oMd.orientation2color(ebsd.orientations)); 
```

I would want to center this beachball around the mean direction `mean(ebsd.orientations.*Miller(0,0,0,1,CS))`

``` matlab
oMSR = ipdfHSVOrientationMapping('1');
oMSR.colorPostRotation = reflection(vector3d(-1,0,-1));
oMSR.colorStretching = 10;
plot(oMSR);set(gcf,'Renderer','zBuffer');
figure
plot(ebsd,oMSR.Miller2color(ebsd.orientations.*Miller(0,0,01,CS)))
```

Is there an easy way to accomplish this?

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

With the present code there is probably no simple solution. I will think about implementing something in this direction.

Ralf.
