### ISSUE TITLE
Calculation of twin orientation of a parent orientation

### ISSUE THREAD

**Issue by LalitKaushik1991** [mtex-toolbox/mtex#807]
can you develop some function which calculates all possible twin orientations of a parent orientation with a given twin mode? 

like FCC material has 12 {111}<112> twin systems, and let's say we want to compute all the twin variants of Copper orientation (90 35 45)

**Comment by kilir** [comment]
I would say that already exists.
1) define your twinning relation such that it is a misoriention
2) symmetrise it
3) apply to your orientation

Cheers,
Rüdiger

**Comment by LalitKaushik1991** [comment]
Dear Rüdiger,

Thanks for suggesting a brilliant way to do that. I tried to calculate twin variants using this approach. I am able to produce desired results.

Here is how I did it for finding twin variants for FCC material

![image](https://user-images.githubusercontent.com/74644807/108954772-a802a780-76b0-11eb-8e6d-3607c6169421.png)



Thanks for creating a powerful tool!!!!
Lalit Kaushik
