### ISSUE TITLE
Bug of rotation

### ISSUE THREAD

**Issue by ryansterne** [mtex-toolbox/mtex#82]
Hi:
I try to define a rotation by a matrix.

The code is:
```matlab
U=[1,1,1;1,1,1;1,1,1]
rotation('matrix',U)
```
Then, I get:
```
ans = rotation (show methods, plot)
  size: 1 x 1
  Bunge Euler angles in degree
  phi1  Phi phi2 Inv.
     0    0    0    0
```
However, this is wrong.

**Comment by ralfHielscher** [comment]
Hi Ryan,

the point is that the matrix you entered
```
1 1 1
1 1 1
1 1 1
```
is not a rotation matrix. Rotation matrices have determinant one. The determinant of your matrix is zero.

Ralf.

**Comment by ryansterne** [comment]
Hi Ralf:
Thank you!
