### ISSUE TITLE
Bug in Miller/scatter

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#832]
Hi Ralf,
I''m not sure why `'noAntipodal'` is used here: https://github.com/mtex-toolbox/mtex/blob/226cce64f2f413165d7d0b1240f65eb7d06e615b/geometry/%40Miller/scatter.m#L34

The following shows an empty plot which I should not be the case, even without adding `'antipodal'` explicitly to plotIPDF or repeating the orientation >100 times:

```
cs = crystalSymmetry('-3m', 'X||a*', 'Y||b', 'Z||c*')
o = orientation.byEuler([158 107 257]*degree,cs)
plotIPDF(o,xvector)
```

Cheers,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

very good you found this. 

Explanation: In combination with `unique` the option `noAntipodal` ensures that antipodal symmetry is not passed to the 
unique command, which in turn would remove it again.

It kind of a weird syntax. 

Ralf.
