### ISSUE TITLE
problems with plotAxisDistribution/plotAngleDistribution

### ISSUE THREAD

**Issue by ArneBoch** [mtex-toolbox/mtex#835]
Hello MTEX Team,

doing some investigations into misorientations and MDFs I have got an error by using plotAngleDistribution and plotAxisDistribution. See issue https://github.com/mtex-toolbox/mtex/issues/440, I try it again with new MTEX version :-). 

Having a hexagonal CS and a uncorrelated or correlated MDF_measured I can plot without problems: 

plotAxisDistribution(MDF_measured); 
plotAngleDistribution(MDF_measured);
plotAxisDistribution(CS);                      
plotAngleDistribution(CS);

but not: 

plotAxisDistribution(calcMDF(uniformODF(cs)));      
plotAngleDistribution(calcMDF(uniformODF(cs)));

It looks like that it not depend on CS, this isn't working too: 

plotAxisDistribution(calcMDF(uniformODF(crystalSymmetry('cubic'))));

I'm using Matlab 2017b and MTEX 5.6.0.

Thanks for help.

Arne

**Comment by kilir** [comment]
Hi,
if you like to define a uniform misorientation density function, simply define it as `uniformODF(cs,cs)` and the following should work nicely:
```
cs = crystalSymmetry('cubic')
mdf_uni = uniformODF(cs,cs)
plotAxisDistribution(mdf_uni);
plotAngleDistribution(mdf_uni);
```

Cheers,
Rüdiger

**Comment by ArneBoch** [comment]
Hello Rüdiger,

thanks for help! Did not know this possibility. I used calcMDF(uniformODF(cs)) because it looks staight forward :-).

Tschüß

Arne
