### ISSUE TITLE
Error using call_extern... cannot plot vector3d

### ISSUE THREAD

**Issue by zmichels** [mtex-toolbox/mtex#84]
Getting this error while trying to plot contour plots of vector3d objects:
```
Error using call_extern (line 158)
Error running external program:
.../MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf
```
My computer is:
MacBook Air (11-inch laptop, Early 2015)
Prcoessor: 2.2 GHz Intel Core i7
OS: Yosemite; 0.10.5 (14F27)
Matlab: r2014b

I just recently updated to mtex 4.1.0, and it seems that is when my trouble began. I have plotted ontours successfully on this same computer with previous versions of mtex. I am able to plot the vector3d points, but I am getting the error when trying to produce a contour plot.
Syntax I am using is:
``` plot(vectors,'contours') ```

**Comment by ralfHielscher** [comment]
Hi zmichels,

I do not think that this issue is connected width mtex-4.1 as the binary causing the error .../MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf has not changed since more then two years. However, you can easily check this by comparing this with an older version of MTEX. They are still all online.

A more likely reason for the bug is that the "old" binary fails to work on you "modern" system. However, MTEX should have checked this at startup. Maybe you can run ```check_mtex```

Ralf.

**Comment by zmichels** [comment]
Looking at older posts on Google code I'm thinking I may need to try to compile the binaries myself.  However, previous versions of mtex worked with regular installation – no problems.
After a reboot, fresh install, and restart of Matlab... I now get this message at initialization:

"
initialize MTEX 4.1.0  ....********************************************************************************
  MTEX binary check failed!

  The original error message was:
  Error using call_extern (line 158)
Error running external program:

.../MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf /private/tmp/odf2pf1571.txt 2>> /private/tmp/output_ZMlocal_Z.log
 
  Check the following options:
  * Compile the binaries yourself.
  * Ask the maintainer for help!
"

**Comment by zmichels** [comment]
>> check_mtex
checking MTEX installation
this might take some time
 
simulating pole figures
 
pf = PoleFigure  
  crystal symmetry : m-3m
  specimen symmetry: 222
 
  h = (100), r = 1 x 206 points
  h = (110), r = 1 x 206 points
  h = (111), r = 1 x 206 points
  h = (211), r = 1 x 206 points
 
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
Error using call_extern (line 158)
Error running external program:

 /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf
 /private/tmp/pf2odf7889.txt 2>> /private/tmp/output_ZMlocal_Z.log

Error in PoleFigure/calcODF (line 139)
[c,alpha] = call_extern('pf2odf',...

Error in check_mtex (line 25)
rec = calcODF(pf) %#ok<NOPRT>

**Comment by zmichels** [comment]
Hi Ralf,


Ok thanks. I’m confused tho why the older versions have worked fine up until now (all I’ve changed recently is to install mtex-4.1). I’m a long time user of mtex, and I would have noticed this problem before.

Thanks for your help,
Zach

>> check_mtex
checking MTEX installation
this might take some time
 
simulating pole figures
 
pf = PoleFigure  
  crystal symmetry : m-3m
  specimen symmetry: 222
 
  h = (100), r = 1 x 206 points
  h = (110), r = 1 x 206 points
  h = (111), r = 1 x 206 points
  h = (211), r = 1 x 206 points
 
------ MTEX -- PDF to ODF inversion ------------------
Call c-routine
Error using call_extern (line 158)
Error running external program:

 /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf
 /private/tmp/pf2odf7889.txt 2>> /private/tmp/output_ZMlocal_Z.log

Error in PoleFigure/calcODF (line 139)
[c,alpha] = call_extern('pf2odf',...

Error in check_mtex (line 25)
rec = calcODF(pf) %#ok<NOPRT>

**Comment by zmichels** [comment]
I just uninstalled and installed mtex-4.0.23

Everything works fine now. 

*Except*, I was really playing with the new smoothing functions/filters and testing the effects of data smoothing with my new code for calculating crystallographic dispersion axes. I don't know what the difference is with 4.1.0 that the installation gets messed up for my system.

Should I be able to just copy the new parts from the EBSDAnalysis folder in 4.1.0 to my working version of 4.0.23? Such that I could keep using the smoothing functions?

Thanks again and cheers.

P.S. MTEX is amazing. Thank you for maintaining such a great toolbox.

**Comment by ralfHielscher** [comment]
Hi Zach,

could you please check the file
```
/Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf
```
actually it should be identical with the file shipped with mtex-4.0.23 (permisions, size). Maybe you can also check the log file
```
 /private/tmp/output_ZMlocal_Z.log
```
I would be very grateful  if you could help figuring out the source of your problem as I do not own a Mac.

Ralf.

**Comment by zmichels** [comment]
File size and permissions are identical. It looks like the files in the 4.1.0 folder though are not being recognized by my system as unix executables.

![screen shot 2015-09-05 at 3 33 08 pm](https://cloud.githubusercontent.com/assets/8769619/9701159/76f2a866-53e3-11e5-8109-62bb15cfd031.png)

**Comment by zmichels** [comment]
As for the log file. I cannot find the log file at that path (/private/tmp/), although I see other files there... nor can I locate a file by the name of output_ZMlocal_Z.log on my computer anywhere. Please let me know how else I can help.

**Comment by zmichels** [comment]
Nevermind... I just replicated the scenario and did it again. Here is the log file contents...

/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2fc: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2fc: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/pf2odf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2pf: Permission denied
/bin/bash: /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/odf2fc: Permission denied

**Comment by ralfHielscher** [comment]
This seems to be the solution of the problem. you can either add the correct permissions by
```bash
cd /Users/Z/Documents/MATLAB/mtex-4.1.0/c/bin/maci64/
chmod a+x *
```
or copy those files from the MTEX-4.023 release. If this succeeds if will ship MTEX-4.1.1 with the updated permissions.

Ralf.

**Comment by zmichels** [comment]
Yup. That fixed it. Thank you very much.

Cheers,
Zach
