### ISSUE TITLE
Perimeter function for GBs...

### ISSUE THREAD

**Issue by DavidMercier** [mtex-toolbox/mtex#85]
Hi Ralf,

I've a short question about the function 'perimeter' in 'EBSDAnalysis/@grainBoundary' folder.

I tried to use it and I get the following error : 
"Undefined function or variable 'g'.
Error in grainBoundary/perimeter (line 29)
peri = full(sparse(g,1,edgeLength,size(gb,1),1));"

Should it be like that ?
"function  peri = perimeter(g, gb,varargin)"
instead of...
"function  peri = perimeter(gb,varargin)"

Thanks a lot for your help.
David

**Comment by ralfHielscher** [comment]
Hi David,

what do you need this function for? There is a function grain2d/perimenter which returns the perimeter of each grain. I though I'm going to remove this function grainBoundary/perimeter.

Ralf.

**Comment by DavidMercier** [comment]
Hi Ralf,

I would like in fact to calculate the total length of a given type of GBs...
And grain2d/perimenter is not the one I need, because for 1 grain, I have several outer GBs  and I want to extract the length of GBs which respect only a given criterion (low misorientation for example)...

Then, I have another question for you...
I can't detect and plot some GBs with MTEX. In 1 given grain, I have sometimes inner GBs segments (kind of lamellas or subgrains inside the grain)... and MTEX see only 1 grain in total, which is correct, but MTEX don't see those segments (low angle GBs)...

Thanks for your help.
David

**Comment by ralfHielscher** [comment]
look at
```matlab
grains.innerBoundary
```

**Comment by DavidMercier** [comment]
It works, thanks... But still many inner GBs are missing. How could I set the calculations/extraction of these special GBs ?
Thanks

David

**Comment by zmichels** [comment]
David,
Have you tried the 'FMC' flag (Fast Multiscale Clustering) in the calcGrains function? 
I use this feature to extract subgrain boundaries. It might help you. Check the documentation for how to add the flag in the function call and specify the clustering parameters.

**Comment by DavidMercier** [comment]
Hi Zachary,

Thanks for the advice. It works perfectly. I played as well with the 'angle' flag and I get what I want...
David
