### ISSUE TITLE
odf/discreteSample

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#86]
Hi Ralf,
I think in line 6 in @ODF/discreteSample.m
there's a little typo, I guess it should read 
``` ori = orientation.id(npoints,odf.CS,odf.SS);```
instead of
```ori = orientation.id(npoint,odf.CS,odf.SS);```.

Another thing is that `oris = discreteSample(odf,50)` returns 
```oris = orientation (show methods, plot)
  size: 50 x 50  
  ...```
 and `oris(:,2:end)` is all zero. Shouldn't it just return oris being 50 x 1 ?

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

thank you for reporting this.

Ralf
