### ISSUE TITLE
default plotting for Miller

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#88]
Hi Ralf,
plotting a Miller defaults for me to outOfPlane reference frame (I guess that is what line 362 in Miller.m does) while a plot for vectors does honor setMTEXpref. E.g.

```
% crystal symmetry
CS = crystalSymmetry('321', [4.91 4.91 5.401], 'X||a', 'Y||b*', 'Z||c');

% plotting convention
setMTEXpref('xAxisDirection','east');
setMTEXpref('zAxisDirection','intoPlane');

h = Miller(1,1,-2,0,CS)
o = orientation('Euler',[10,20,0]*degree,CS)
mtexFig = mtexFigure;
plot(Miller(1,1,-2,0,CS),'parent',mtexFig.nextAxis)
annotate([xvector, yvector],'labeled')
mtexTitle('Miller - defaults to outOfPlane')

plot(o*h,'parent',mtexFig.nextAxis)
annotate([xvector, yvector],'labeled')
mtexTitle(mtexFig.nextAxis,'vector - defaults to setMTEXpref')
mtexFig.drawNow
```
Of course I could set `'zAxisDirection','outOfPlane'` as a plotting option but wouldn't it be more logical if plot(Miller) would behave as defined in setMTEXpref?

All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

this was thought as a feature - not a bug. The origin was that the fundamental sector in MTEX always starts at x and then goes in direction of y. If now x and y are not aligned as usual the fundamental sector looks sometimes misaligned. I think as specimen coordinate system and crystal coordinate system are two different thinks it makes sense to align the differently. Actually, pole plots are now automatically annotated by X and Y while crystal coordinate plots like inverse pole figures, ipf-keys, ... are annotated by Miller indices.

Of course I could also include an additional preference for aligning Miller plots. I'l go asking around whether this is requested.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I almost anticipated this. To me it occurred when using orientations*grid which gives me vectors and comparing those to the original grid - expecting both to be in the same reference frame. But now since I know, for me it's fine to supply `zAxisDirection`.
All the best,
Rüdiger
