### ISSUE TITLE
How to remove triple junctions

### ISSUE THREAD

**Issue by akdasilva** [mtex-toolbox/mtex#90]
Hi,

I am a beginner in Mtex, 

How can I desconsider triple juctions during  calculations using grain boundary length (perimeter)?

Best regards!

**Comment by DavidMercier** [comment]
Hi Alisson,

You should have a look here : 
http://mtex-toolbox.github.io/files/doc/TripelPoints.html

Best regards.
David

**Comment by akdasilva** [comment]
Hi David

Thanks a lot!

Best regards,
Alisson
