### ISSUE TITLE
vector3d/mean

### ISSUE THREAD

**Issue by kilir** [mtex-toolbox/mtex#91]
Hi Ralf,
I'm wondering how to get the mean of vectors with antipodal symmetry.
The following works as expected:

```
>> dirs
 dirs = vector3d (show methods, plot)
 size: 20 x 36
 resolution: 26°
>> dirs.mean
 ans = vector3d (show methods, plot)
 size: 1 x 36
```

However, adding antipodal to the vector, reduces the result to 1x1:

```
>> dirs.antipodal = 1
dirs = vector3d (show methods, plot)
 size: 20 x 36
 antipodal: true
 resolution: 26°

>> dirs.mean
ans = vector3d (show methods, plot)
 size: 1 x 1
          x         y         z
  -0.374602  0.482579 -0.791701
```

It's the same using the function form:

```
>> mean(dirs)
 ans = vector3d (show methods, plot)
 size: 1 x 36
>> mean(dirs,'antipodal')
 ans = vector3d (show methods, plot)
 size: 1 x 1
          x         y         z
  -0.374602  0.482579 -0.791701
```

Is there another way instead of using a loop?
All the best,
Rüdiger

**Comment by ralfHielscher** [comment]
Hi Rüdiger,

I understand that this is not a consistent behavior. Most probably I have to place a loop inside of vector3d/mean since the antipodal mean depends on singular value decomposition and I do not know how to vectorize this.

Ralf.

**Comment by kilir** [comment]
Hi Ralf,
I'm currently using a loop and that's fine. So maybe it's enough to put it in the documentation, although it would be nice to have a consistent behavior. 
After looking up what the "Singulärwertzerlegung" does, I think I can't be of any help.
All the best and thanks for dealing with those details to improve user-friendliness,
Rüdiger

**Comment by ralfHielscher** [comment]
I think this should do the job
