### ISSUE TITLE
export_generic uses depreciated 'get' command

### ISSUE THREAD

**Issue by creuzige** [mtex-toolbox/mtex#94]
I've been updating some of my programs to the new 4.1.1 version, and the export_generic command fails  in the following ways:

>> export(odf1,[pname strcat(bname,'_ODF.txt')],regular,'resolution',5*degree, 'ZXZ,BUNGE');
Undefined function or variable 'regular'.

>> export_generic(odf1,[pname strcat(bname,'_ODF.txt')], 'resolution', 5*degree, 'ZXZ,BUNGE');
Error using get
Cannot find 'get' method for orientation class.

Error in ODF/export_generic (line 51)
  convention = get_flag(get(S3G,'options'),{'ZXZ','ZYZ'},'none');

**Comment by ralfHielscher** [comment]
Thank you for reporting this. It will be fixed in MTEX 4.1.2.

Ralf
