### ISSUE TITLE
Analyzing a large datasets 

### ISSUE THREAD

**Issue by oMuransky** [mtex-toolbox/mtex#976]
Hi Ralf,

When trying to calculate grains in large EBSD map I'm getting a following error - I tried a few things but I don't seem to be able to find solution. Any advice would be great - I can share the data if needed it is stitched from 9 individual EBSD maps and stitching was done in Aztec.  

Thank you,
Ondrej

CODE

 [grains,ebsd.grainId,ebsd.mis2mean] = ...
            calcGrains(ebsd('indexed'),'threshold',[10*degree 2*degree]);

ERROR

Error using matlab.internal.math.qhull
QH7074 qhull warning: more than 16777215 ridges.  ID field overflows and two ridges
may have the same identifier.  Otherwise output ok.
QH7074 qhull warning: more than 16777215 ridges.  ID field overflows and two ridges
may have the same identifier.  Otherwise output ok.
QH7074 qhull warning: more than 16777215 ridges.  ID field overflows and two ridges
may have the same identifier.  Otherwise output ok.
QH7074 qhull warning: more than 16777215 ridges.  ID field overflows and two ridges
may have the same identifier.  Otherwise output ok.
QH6159 qhull input error: more than 16777215 vertices.  ID field overflows and two vertices
may have the same identifier.  Vertices not sorted correctly.

While executing:  | qhull v Q5 Q6 Qs
Options selected for Qhull 2010.1 2010/01/14:
  run-id 1558329480  voronoi  Q5-no-check-outer  Q6-no-concave-merge
  Qsearch-initial-simplex  _pre-merge  _zero-centrum  Pgood  _max-width 1.2e+07
  Error-roundoff 1e-08  _one-merge 7.2e-08  Visible-distance 2.1e-08
  U-coplanar-distance 2.1e-08  Width-outside 4.1e-08  _wide-facet 1.2e-07
Last point added to hull was p8276830.  Last merge was #25420530.

At error exit:

Voronoi diagram by the convex hull of 18638723 points in 3-d:

  Number of Voronoi regions: 16777214
  Total number of nearly incident points: 1861509
  Number of Voronoi vertices: 0
  Number of non-simplicial Voronoi vertices: 14814988

Statistics for:  | qhull v Q5 Q6 Qs

  Number of points processed: 16777215
  Number of hyperplanes created: 58310209
  Number of facets in hull: 18472729
  Number of distance tests for qhull: 1420765134
  Number of distance tests for merging: 90009511
  Number of distance tests for checking: 0
  Number of merged facets: 25420530
  Maximum distance of merged point above facet: 4.5e-08 (0.5x)
  Maximum distance of merged vertex below facet: -3.1e-08 (0.4x)

Error in voronoin (line 107)
[v, c] = matlab.internal.math.qhull(x', 'v ', opt);

Error in spatialDecomposition (line 35)
    [V,D] = voronoin([X;dummyCoordinates],{'Q5','Q6','Qs'}); %,'QbB'

Error in EBSD/calcGrains (line 62)
[V,F,I_FD] = spatialDecomposition([ebsd.prop.x(:), ebsd.prop.y(:)],ebsd.unitCell,varargin{:});

**Comment by ralfHielscher** [comment]
You may try the option `noQHull` to calcGrains.

Ralf.

**Comment by oMuransky** [comment]
Thank you Ralf. I'll try.

**Comment by oMuransky** [comment]
Thank you Ralf doing "noQHull" option helped.

**Comment by Helanism** [comment]
why I try 'noQHull' can not solve it

**Comment by Helanism** [comment]
My data about 30 millions pixels

**Comment by Helanism** [comment]
when I use 'noQHull' options it will calculate for hours, it is abnormal
